- token/src/cli/main.js
- token/src/cli/token-test.js
- token/src/client/token.js
- token/src/client/util/send-and-confirm-transaction.js
- token/src/program/src/error.rs
- token/src/program/src/state.rs
Allow Token owners to mint new tokens.  If no owner is supplied during the creation of the token than that token's supply is fixed.
fixes: #13
> Add MintTo instruction

- do.sh
- `do.sh` checks for specific directories when it attempts to build all the programs.  Make it more generic to try to build any project that contains a `Cargo.toml` file in its root.
- Add support for generating docs
(Also my shell didn't like the form of the test syntax)
> Make do.sh more generic

- ci/token.sh
- token/js/package.json
Web3.js used to be the only way to pull the bpf-sdk, and build a program. Now that we have generic scripting for that in this repo, we can remove the overloading from package.json and the duplicate build from token CI
> Remove bpf-sdk handling from token package.json

- token/src/instruction.rs
The `SetOwner` instruction also supports setting a new owner of a token account.
> Fix SetOwner documentation

- token-swap/js/cli/token-swap-test.js
- token-swap/src/lib.rs
- token/inc/token.h
- token/js/cli/main.js
- token/js/cli/token-test.js
- token/js/client/token.js
- token/src/error.rs
- token/src/instruction.rs
- token/src/state.rs
> Token type renaming

- memo/Cargo.toml
Cargo.toml changes to enable `cargo publish`
@mvines @jackcmay While the program itself hasn't changed, do you think I should go all the way and change the program id and republish to the clusters, since this is a version number change?
> Version solana-sdk-bpf-test and spl-memo for crates.io

- token-swap/inc/token-swap.h
- token-swap/js/cli/token-swap-test.js
- token-swap/js/client/token-swap.js
- token-swap/src/lib.rs
- token/.gitignore
- token/inc/token.h
- token/js/cli/main.js
- token/js/cli/token-test.js
- token/js/client/token.js
- token/js/client/util/store.js
- token/src/error.rs
- token/src/instruction.rs
- token/src/state.rs
Problem:
The Token program currently supports unlimited delegates associated with a single token account.
Doing so:
- Overly complicates both the interface and implementation of the token program
- Requires each delegate to be its own token account, adding unnecessary steps to the process
- Any instruction that that does delegation must include both the delegate account and the associated source account.  This is especially painful for programs like token-swap where it operates on a number of delegated accounts at the same time
Proposed solution:
Switch the token program to supporting one delegate per token account.
(Removes ~1000 lines of implementation and test code 🎉 )
> Single delegate support

- token/inc/token.h
- token/js/cli/token-test.js
- token/js/client/token.js
- token/src/instruction.rs
- token/src/state.rs
Requiring signers to initialize mint states means these states cannot be initialized with an account obtained with `create_from_seed`.
Removing the requirement that accounts being initialized be signed and added documentation alerting the user that these operations should be done atomically.
> Remove initialize signers

- .travis.yml
- ci/memo.sh
- ci/token-swap.sh
- ci/token.sh
- token-swap/js/cli/main.js
- token/js/cli/main.js
> Fix automation

- token/inc/token.h
- token/js/cli/token-test.js
- token/js/client/token.js
- token/src/instruction.rs
- token/src/state.rs
Split the `Approve` instruction into two to avoid the complexity of an optional account
> Add revoke instruction

- token-swap/js/cli/main.js
- token/inc/token.h
- token/js/cli/main.js
- token/src/instruction.rs
- token/src/state.rs
Unnamed fields are confusing to document and not conducive to auto-generation by procedural macros
> Use variant fields

- token-swap/inc/token-swap.h
- token-swap/js/cli/token-swap-test.js
- token-swap/js/client/token-swap.js
- token-swap/src/lib.rs
- token/inc/token.h
- token/js/cli/token-test.js
- token/js/client/token.js
- token/src/instruction.rs
- token/src/state.rs
- Tracking total supply may be misinterpreted and lead to confusion If accounts are removed due to rent delinquency.
- Removing supply reduces a required key in the `Burn` instruction
> Remove supply from Token

- token-swap/src/lib.rs
- token/cbindgen.toml
- token/inc/token.h
- token/js/client/token.js
- token/src/error.rs
- token/src/instruction.rs
- token/src/state.rs
The changes in this PR reduce the size of the token program:
- Split the `State` enum into individual structures so as not to incur largest variant size of all variants
- Generalize `State` unpack
- Remove `State` serialize and instead operate directly on `&mut`
- Enforce that only initialized accounts are used across the board
Reduces:
- BPF instructions for each `TokenInstruction` by an average of 30%, all instructions saw reductions
- Stripped BPF shared object file size from 186 to 86 kB
- Reduces the Mint data size from 128 to 40 bytes
- Reduces the Account data size from 128 to 120 bytes
Fixes: #86
> Whittle down the token program across the board

- token/inc/token.h
- token/js/cli/main.js
- token/js/cli/token-test.js
- token/js/client/token.js
- token/src/error.rs
- token/src/instruction.rs
- token/src/lib.rs
- token/src/native_mint.rs
- token/src/state.rs
Add support to the Token program to support a "Native Mint" which wraps SOL
Picking up from here: https://github.com/solana-labs/solana-program-library/pull/67
> Add support for native token

- .mergify.yml
Automerge isn't working, because it attempts a rebase commit. "Rebase merges are not allowed on this repository."
> Mergify squash commits

- token/src/error.rs
- token/src/state.rs
Also a couple `cargo fmt` fixes
> Disable CloseAccount for non-native token accounts

- do.sh
> Move targetDir inside perform_action

- do.sh
Shared object dumping was outdated and not tested against recent changes, fix it.
> Fix `./do.sh dump ...`

- README.md
- docs/src/token.md
- token/README.md
- token/js/README.md
- token/js/package.json
First cut of the token docs, please chime in if there are additional topics you'd like to see.
Fixes: #132
> Add token docs

- token/src/instruction.rs
When testing a downstream parser for Token instructions, Approve accounts kept appearing in the wrong order. Looks like delegate and source were flopped.
> TokenInstruction::Approve: source account must be writable

- token/src/instruction.rs
- Spell out destination
- `authority` is used when either owner or delegate may exercise an action. In this case, only `owner` is authorized.
> Consistency nits

- do.sh
`do.sh build all` assumes that all crates contain a program, which will not be the case when https://github.com/solana-labs/solana-program-library/pull/188 lands
> `do.sh build all` now skips non-program crates

- do.sh
Fixes current CI failure on #188
> Enable do.sh clippy/test for non-program crates

- token/build.rs
- token/inc/token.h
Autogenerated C enum variants may conflict with other programs, tag them with the enum name.
> Add tag to C enum variants

- .travis/install-program-deps.sh
- ci/client/Cargo.lock
- ci/client/Cargo.toml
- memo/Cargo.lock
- memo/Cargo.toml
- token-swap/Cargo.lock
- token-swap/Cargo.toml
- token-swap/js/cli/token-swap-test.js
- token-swap/js/package-lock.json
- token-swap/js/package.json
- token-swap/src/processor.rs
- token/Cargo.lock
- token/Cargo.toml
- token/inc/token.h
- token/js/package.json
Fixing solana-sdk at 1.2.13 breaks crates.io publishing from the monorepo, `cargo publish` does not permit multiple version fo solana-sdk to exist.  Instead allow the version of solana-sdk to float upwards to match the monorepo's current version
> Relax solana-sdk version requirement

- token/inc/token.h
- token/src/native_mint.rs
9 is a magic number for wrapped SOL tokens, const it
> token: Add native_mint::DECIMALS

- token/src/processor.rs
Add support to the token program to transfer tokens to yourself which is useful sometimes when testing.  
Fixes: #207
> Add support for self transfers

- ci/token.sh
- token/program/inc/token.h
- token/program/src/instruction.rs
cbindgen does not produce deterministic header files, remove ci check for now
Tracking via: https://github.com/solana-labs/solana-program-library/issues/262
> cbindgen does not produce deterministic header files

- Cargo.lock
- Cargo.toml
- ci/token-swap.sh
- docs/src/token.md
- token-swap/js/package.json
- token-swap/program/src/instruction.rs
- token-swap/program/src/processor.rs
- token/cli/Cargo.toml
- token/cli/src/main.rs
- token/js/package-lock.json
- token/js/package.json
- token/program/Cargo.toml
- token/program/src/instruction.rs
> Adapt spl-token cli to Solana 1.3.2

- ci/script.sh
- token/program/build.rs
- token/program/inc/token.h
- token/program/src/instruction.rs
Exclude `Token_DECIMALS` and extra white space to work around weird cbindgen non-determinism
Fixes #262
> Restore generated token.h check

- token-swap/js/cli/token-swap-test.js
- token-swap/js/package-lock.json
- token-swap/js/package.json
- token/js/cli/token-test.js
- token/js/package-lock.json
- token/js/package.json
The latest versions of web3.js default to the new loader but the new loader is not supported on any networks yet.
Change the js tests to use the deprecated loader.  Once the networks are updated then the token and token-swap programs must pull in the latest solana-sdk and remove these changes to switch to the new loader
> Use deprecated bpf loader

- token/program2/src/option.rs
No way to covert between rust Option and COption.
Also, packing of COptions is hard to read in the context of token Instruction::pack and Instruction::unpack, so separate into helpers.
Fixes #300 
Also: https://github.com/solana-labs/solana-program-library/pull/297#discussion_r475993617
> Add COption helpers

- token/js/client/token.js
- token/program/src/error.rs
- token/program/src/processor.rs
- token/program2/src/error.rs
- token/program2/src/processor.rs
When doing a transfer or mint amount may overflow, check and return error instead
> Fix overflow when amounts are u64::MAX

- token/program2/inc/token2.h
- token/program2/src/error.rs
- token/program2/src/instruction.rs
- token/program2/src/processor.rs
- token/program2/src/state.rs
An authority may want the ability to "freeze" specific accounts.
Add a new authority to the Mint and a new initialized state variant to Account. The authority is able to toggle that variant for an associated account. Setting the variant to "frozen" disables any changes from being made to the account, ie transfer in or out, approve, revoke, set-authority, burn.
Fixes #229
> Add capability to freeze token Accounts

- token/program2/inc/token2.h
- token/program2/src/error.rs
- token/program2/src/instruction.rs
- token/program2/src/processor.rs
- token/program2/src/state.rs
There are cases when the SOL required for rent at the creation of an SPL token account will be subsidized by a 3rd party, opening the door for a financial attack where users request token accounts from the subsidizer only to immediately close them in order to drain SOL from the subsidizer.
Our previous solution to this attack was to disable CloseAccount for non-native accounts, locking that SOL forever.
This PR re-enables CloseAccount for non-native accounts, and adds an Account::close_authority, enabling a 3rd party as above to reclaim their SOL when an account has 0 token balance.
Also adds a couple clarifying comments to the mint section of process_set_authority
Closes #302 
Reverts #127
> token: Add close_authority and re-enable CloseAccount for non-native Accounts

- token/program2/inc/token2.h
- token/program2/src/instruction.rs
- token/program2/src/processor.rs
InitializeMint is more complicated than it needs to be; all the same functionality is available by chaining other methods.
Namely, an InitializeMint instruction that mints a fixed supply to an account becomes:
- InitializeMint with mint_authority
- Use mint_authority to MintTo account
- Use mint_authority to set mint authority to None
Fixes #308
> token: Simplify initialize_mint

- token-swap/program/src/processor.rs
- token/cli/src/main.rs
- token/program/inc/token.h
- token/program/src/instruction.rs
- token/program/src/processor.rs
- token/program/src/state.rs
Reinstate the `supply` field to the `Mint` state, and adjust on MintTo and Burn instructions. Reinstate passing the mint account into Burn instructions.
Also cleaned up a couple account ordered lists in docs
Fixes #328
> Reinstate Mint supply

- token/program/inc/token.h
- token/program/src/error.rs
- token/program/src/instruction.rs
- token/program/src/processor.rs
Tokens can be created with invalid mints. These token accounts are useless because without a valid mint, they can never hold a token balance.
- Add check for Mint validity in process_initialize_account
Fixes #303
> token: Check mint on InitializeAccount

- ci/script.sh
- token/program/inc/token.h
- token/program/src/error.rs
- token/program/src/instruction.rs
- token/program/src/native_mint.rs
- token/program/src/processor.rs
TODO:
Depends-on: https://github.com/solana-labs/solana-program-library/pull/342
<s>Depends-on: https://github.com/solana-labs/solana-program-library/issues/315</s>
Fixes: https://github.com/solana-labs/solana-program-library/issues/289
> Add Transfer2/Approve2/MintTo2/Burn2 instructions for improved hardware wallet support

- docs/src/token.md
- token/program/src/error.rs
- token/program/src/instruction.rs
* Update native mint public key in the docs
* Fix `revoke` instruction constructor; account state was readonly, but needs to be writable
* Allow more parallelization in multisig transactions; signers weren't readonly
* Fix the AlreadyInUse error display message
> Token nits

- token/program/src/pack.rs
- token/program/src/processor.rs
- token/program/src/state.rs
Tests were using the same mechanism to allocate account sizes as the token was using to check them, this covered up that fact that pack was not enforcing the account sizes correctly.
For correct count sizes and add tests
> Fix account size comparisons

- token/js/client/token.js
Now that account data is packed, we don't need to add extra padding to the account data
> Remove extra account padding

- ci/script.sh
- token/js/cli/token-test.js
Fixes: https://github.com/solana-labs/solana-program-library/issues/332
Fixes: https://github.com/solana-labs/solana-program-library/issues/370
- Now that spl-token is deployed in the wild, we need to make sure that the JS bindings are always tested against it to prevent incompatible changes
- solana-sdk v1.3.6 requires bpf loader 2
- Allow running token-js tests against token keg
- Use bpf loader 2 for program loading from source
> Fix token-js CI tests

- token/cli/src/main.rs
Token CLI still issues old format instructions
Update to `Transfer2`, `MintTo2` and `Burn2`
Fixes: #364
> Token CLI: Use Token2 instructions

- docs/src/token.md
Document that the supply for the native mint is always 0.
Also a couple small fixups
Fixes #377
> Fix up spl-token docs

- Cargo.lock
- ci/script.sh
- docs/src/token.md
- memo/program/Cargo.toml
- token-swap/js/package.json
- token-swap/program/Cargo.toml
- token-swap/program/src/processor.rs
- token/cli/Cargo.toml
- token/js/cli/token-test.js
- token/js/package.json
- token/perf-monitor/Cargo.lock
- token/perf-monitor/Cargo.toml
- token/program/Cargo.toml
- token/program/src/native_mint.rs
- utils/test-client/Cargo.toml
I need to link Ledger app tests against SDK 1.3.8 _and the SPL Token program.  So Token needs to upgrade, too!
> Build Token on SDK 1.3.8

- token/js/cli/main.js
- token/js/cli/token-test.js
- token/js/client/token.js
- token/js/package.json
New token2 functionality isn't currently available via the JS library. The decimal-asserting instructions are particularly relevant for wallet integrations with Ledger support.
cc @t-nelson
> Flesh out @solana/spl-token with token2 instructions

- ci/script.sh
- token-swap/js/cli/token-swap-test.js
- token-swap/js/client/token-swap.js
- token-swap/js/client/util/send-and-confirm-transaction.js
- token-swap/program/src/instruction.rs
- token-swap/program/src/processor.rs
- token-swap/program/src/state.rs
- token/js/cli/token-test.js
- token/js/client/token.js
- token/js/client/util/send-and-confirm-transaction.js
- token/js/package-lock.json
- token/js/package.json
This is two separate problems to some extent, but it all came up while trying to run the JS test suite on token-swap.  Let me know if you prefer to split this up.
* Fix the swap instruction and add a test for A -> B and B -> A swapping
* Update JS and Rust libs to new versions, and correctly use the new version of the web3 SDK, using Jack's PR on hello world for inspiration: https://github.com/solana-labs/example-helloworld/commit/0510fcc777a3a4cbbd37e54d09aa806feb128457
* Re-enable token-swap in CI
> token-swap: Swap instruction fix and update libs for CI

- token/js/cli/token-test.js
- token/js/client/token.js
- token/js/module.d.ts
- token/js/module.flow.js
Add support for wrapped native token account generation in the Token JS client.
Usage:
```
const native = await Token.createWrappedNativeAccount(
connection,
programId,
owner.publicKey,
payer,
lamportsToWrap,
);
const accountInfo = await token.getAccountInfo(native);
assert(accountInfo.isNative);
// check that the new account has wrapped native tokens.
assert(accountInfo.amount.toNumber() === lamportsToWrap);
```
Token.createAccount function performs the systemProgram account creation and token account initialisation steps in one transaction, without first passing lamports to the created account. So the balance is 0 (rent notwithstanding) when initializeAccount is called. This means that, in the native token case, the SOL cannot be wrapped
This function allows you to transfer lamports on …
> Wrapped SOL support

- Cargo.lock
- token-swap/js/client/token-swap.js
- token-swap/program/Cargo.toml
- token-swap/program/src/entrypoint.rs
- token-swap/program/src/error.rs
- token-swap/program/src/instruction.rs
- token-swap/program/src/processor.rs
- token-swap/program/src/state.rs
* SwapInfo and SwapInstruction are more memory-efficient, following the
example from SPL Token
* Remove unnecessary helper structs to make instructions clearer
* Error -> SwapError
* Update JS tests to reflect the change
> Pack instructions and state more efficiently

- token/cli/src/main.rs
Spelling "type CommmandResult = …" -> "type CommandResult = …"
fixes #429
> Fix spelling

- token/program-v3/src/processor.rs
#411 for /program-v3
In the transfer instruction, if the source account owns itself the instruction panics trying to double mutably borrow.
Add test and re-arrange to avoid duplicate borrow
These changes are incomplete: more duplicate key tests should be added and more instructions will probably have to be updated. To follow in separate PRs
Also, since I was in there:
Fixes #427
> Allow source account to be its own owner in Transfer and Transfer2

- token/program-v3/src/processor.rs
Also: Allow source to be freeze_authority in FreezeAccount/ThawAccount
As in the transfer instruction (cc #433 ), if the source owner or close authority is the Account itself, a CloseAccount instruction panics trying to double mutably borrow. Similarly, a FreezeAccount or ThawAccount instruction will panic if source is the freeze_authority.
Add tests and re-order process_close_account and process_toggle_freeze_account to fix
> Allow source to be owner/close_authority in CloseAccount

- token/program-v3/src/processor.rs
As in the transfer instruction (cc #433 ), if the source owner is either the Account itself or the Mint, a Burn or Burn2 instruction panics trying to double mutably borrow.
Add tests and re-order process_burn to fix
> Allow source or mint to be account owner or delegate in Burn and Burn2

- token/program-v3/src/processor.rs
As in the transfer instruction (cc #433 ), if the mint authority is either the Mint itself or the destination Account, a MintTo or MintTo2 instruction panics trying to double mutably borrow.
Add tests and re-order process_mint_to to fix
> Allow destination or mint to be mint_authority in MintTo and MintTo2

- token/program-v3/src/processor.rs
As in the transfer instruction (cc #433 ), if the previously set authority of an Account or Mint is itself, a SetAuthority instruction panics trying to double mutably borrow.
Add tests and re-order process_set_authority to allow self-authorities
> Allow Account or Mint to be its own authority in SetAuthority

- token/program-v3/src/processor.rs
As in the transfer instruction (cc #433 ), if the source account of an approve or revoke instruction owns itself, the instruction panics trying to double mutably borrow.
Add tests and re-order process_approve and process_revoke to allow source-owner
> Allow source account to be its own owner in Approve, Approve2, and Revoke

- ci/script.sh
Now that all of the token-swap and web3 fixes have landed, we can finally re-enable the token-swap JS tests in CI.
Fixes #305
> Re-enable token-swap ci

- token/program-v3/src/pack.rs
- token/program-v3/src/processor.rs
The methods `Pack::unpack_mut` and `Pack::unpack_unchecked_mut` provide a bit of a footgun; if an account is included in the account list multiple times, it is easy to cause a panic by attempting to mutably borrow one named account while it is already held via another name using an unpack_mut method.
A more straightforward pattern is to unpack the account and release the mutable borrow, and then repack after any changes are made.
Since #433 , #434 , #435 , #436 , #437 , and #438 , there are no program uses of `unpack_mut` and only a couple, easily rewritten uses of `unpack_unchecked_mut`. No reason to retain these methods just for tests. This PR rewrites these uses and removes `unpack_mut` and `unpack_unchecked_mut` to remove the footgun from spl-token and provide a better example for …
> Remove Pack mutable unpack methods

- token/perf-monitor/Cargo.lock
- token/perf-monitor/tests/assert_instruction_count.rs
- token/program-v3/src/error.rs
- token/program-v3/src/pack.rs
- token/program-v3/src/processor.rs
Pack traits depend on `TokenError`.  These changes remove the Token dependency in prep for making `Pack` more widely available.
> Remove pack's dependency on TokenError

- docs/src/token.md
A quickie to unblock Dom, describing how to configure `spl-token` CLI default cluster and keypair.
Main docs need some cleanup, then we can just link there.
> Docs: Describe how to configure spl-token-cli

- docs/src/token.md
- token/program-v3/src/processor.rs
- token/program/src/instruction.rs
- token/program/src/processor.rs
Multisignature validation is compromised if a single valid signer signs m times.  Fix that by requiring a 1x1 pairing of m signers to m multisignture keys
Fixes https://github.com/solana-labs/solana-program-library/issues/477
> Fix multisign check

- token-swap/program/src/processor.rs
- token/program/src/processor.rs
While relevant failure cases vary from instruction to instruction, there are some that are consistent across many. It makes code easier to understand and test if these consistent failure cases are checked in the same order across instructions.
Here is the general order implemented:
1. Frozen
2. Account type is wrong in some way (native vs. non-native, authority type not applicable)
3. Insufficient funds
4. Mint mismatch
5. Decimal mismatch
6. Delegated checks
Fixes #500
> Standardize failure case ordering

- token/cli/src/main.rs
Several spl-token-cli arguments appear in the `--help`, but don't seem to work. For one, clap returns `arg wasn't expected, or isn't valid in this context`, due to missing `global` tag. For another, fee_payer and owner are actually never parsed or used.
This pr adds the global tag and uses fee_payer and owner when provided. It also simplifies the parsing of the json_rpc_url arg slightly.
Fixes #499 
cc @t-nelson
> Enable spl-token-cli args

- docs/src/token.md
Point to the CLI docs to inform readers on how to generate a keypair if they don't have one
Fixes #428
> Add doc info about generating keypair

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/main.rs
- Add ability to initialize mint with freeze authority (set to same as mint authority for now; SetAuthority work as part of #502 will allow greater control)
- Add freeze and thaw subcommands to cli app
- Add "frozen" marker to accounts output, when relevant
Fixes #365 
Toward #502
> Add freeze and thaw functionality to spl-token cli

- token-swap/js/client/token-swap.js
- token-swap/js/module.d.ts
- token-swap/js/module.flow.js
- token/js/client/token.js
- token/js/module.d.ts
- token/js/module.flow.js
Expose Layouts and instruction creation functions to allow more flexible use of the Token and TokenSwap clients.
This PR does two things:
- expose the Mint, Account and TokenSwap layouts, so that you can TransactionInstructions to create system program accounts for each of them. The alternative is using the client functions, which send a transaction immediately and therefore require passing an account (with secret key).
- expose a static function to create a TransactionInstruction that initialises the token swap, again to avoid having to pass an account..
> Expose layouts and instruction creation function

- ci/script.sh
- token-swap/js/client/layout.js
- token-swap/js/client/token-swap.js
- token-swap/js/client/util/store.js
- token-swap/js/module.d.ts
- token-swap/js/module.flow.js
- token-swap/js/package-lock.json
- token-swap/js/package.json
- token/js/client/layout.js
- token/js/client/token.js
- token/js/client/util/store.js
- token/js/module.d.ts
- token/js/package-lock.json
- token/js/package.json
* `npm run lint` now checks that code is properly formatted, instead of
running the formatter
* Add extra commands to run the linting, include ts definitions file
* Update flow-bin, fix type errors that came up
> Fix lint check in CI

- token/cli/src/main.rs
CreateAccount+InitializeMint and CreateAccount+InitializeAccount transactions are both being signed by an extra Signer; the owner doesn't need to sign Initialize instructions. Due to `unique_signers`, this wasn't an issue when the owner and fee-payer were always the same. However, now that the `--owner` and `--fee-payer` args work to identify separate Signers, the extra Signer panics the app.
Remove unnecessary owner signer
> Owner doesn't need to sign spl-token initialize transactions

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/main.rs
`spl-token-cli` has no way to look up an SPL Token account's mint directly
Add an `account-info` subcommand
There's some dupe here that will be dropped once https://github.com/solana-labs/solana/pull/12466 ships and we can implement `OutputFormat` in `spl-token-cli`
fixes #467
> spl-token-cli: Add 'account-info' subcommand

- token/cli/src/main.rs
This pr:
- renames the `assign` subcommand to `authorize`
- enables setting all types of authority on Mints and Accounts
- adds the capability to set authority to None (via the `--disable` arg)
Towards #502 
Examples:
```
$ spl-token authorize 4fYNw3dojWmQ4dXtSGE9epjRGy9pFSx62YypT7avPYvA mint new-mint-authority.json
Updating 4fYNw3dojWmQ4dXtSGE9epjRGy9pFSx62YypT7avPYvA
Current mint authority: CYRJWqiSjLitBAcRxPvWpgX3s5TvmN2SuRY3eEYypFvT
New mint authority: 7aHDubg5FBYj1SgmyBgU3ZJdtfuqYCQsJQK2pTR5JUqrv
```
```
$ spl-token authorize BnfYisgpGNkFfPz9eFX4UaXQ2W28CXK6r7rmnzfdrqEM owner new-owner.json --owner old-owner.json
Updating BnfYisgpGNkFfPz9eFX4UaXQ2W28CXK6r7rmnzfdrqEM
Current owner: CYRJWqiSjLitBAcRxPvWpgX3s5TvmN2SuRY3eEYypFvT
New owner: 7aHDubg5FBYj1SgmyBgU3ZJdtfuqYCQsJQK2pTR5JUqrv …
```
> Flesh out SetAuthority capabilities

- bpf-sdk-install.sh
- token-swap/js/client/util/send-and-confirm-transaction.js
- token-swap/js/package-lock.json
- token-swap/js/package.json
- token/js/client/util/send-and-confirm-transaction.js
- token/js/package-lock.json
- token/js/package.json
Also, update `sendAndConfirmTransaction` to use `preflightCommitment` of `recent`. For the token tests, on my machine, this setup took roughly 18.5 seconds, and with `skipPreflight: true` it was about 21.5 seconds.
The main question: should the commitments move to `singleGossip`?
cc @jstarry for awareness -- thanks for the announcement!
> Upgrade web3 to 0.78.0 and sdk to 1.3.13

- token/js/cli/token-test.js
The token js tests (`npm run start`) timeout against devnet and testnet because they request airdrops larger than the caps in place. This isn't a permanent fix against very low caps or non-existent faucets in the future, but might as well facilitate these tests for now.
> token js: Reduce airdrop amounts

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/main.rs
- token/perf-monitor/Cargo.lock
- token/perf-monitor/Cargo.toml
- token/perf-monitor/tests/assert_instruction_count.rs
- token/program/Cargo.toml
`spl-token-cli` mostly uses keypair/pubkey args directly, limiting their expression to file paths and base58 pubkeys
* Switch all args to signer-based utils
* BONUS! Consolidate transaction construction and signing
This is blocked by needing changes at the tip of v1.3.  Last commit will need replaced after the next release
> spl-token-cli: Use signer arg utils throughout

- token-swap/program/src/error.rs
- token-swap/program/src/processor.rs
- token-swap/program/src/state.rs
**Problem**
Token-swap is using an ad-hoc version of Pack which doesn't exactly follow the traits.
**Solution**
Use the sdk version of Pack and update other bits as needed.
Fixes #492
> token-swap: Use sdk version of Pack

- token-swap/js/cli/token-swap-test.js
- token-swap/js/client/token-swap.js
- token-swap/js/module.d.ts
- token-swap/js/module.flow.js
- token-swap/program/src/error.rs
- token-swap/program/src/instruction.rs
- token-swap/program/src/processor.rs
**Problem**
When performing swap, withdraw, or deposit, there's a chance that we'll receive much less than expected due to slippage.
**Solution**
Add minimum / maximum amount parameters for all commands, along with updates to JS bindings.
Fixes #87 and #88
> token-swap: Add slippage to swap / withdraw / deposit

- bpf-sdk-install.sh
- memo/program/Cargo.toml
- token-swap/js/cli/token-swap-test.js
- token-swap/program/Cargo.toml
- token-swap/program/src/curve.rs
- token/js/package.json
- token/program-v3/Cargo.toml
**Problem**
In our implementation of fee calculation, we assess the fee entirely on the output token, but Uniswap and Balancer assess on the input. The overall effect on the pool value is the same, but when we withdraw from the pool, the gains from fees are slightly unbalanced.
**Solution**
Update the swap fee calculation to line up with uniswap.  Also, update the SDK version everywhere.
Fixes #341
> token-swap: Assess swap fee on input token

- memo/program/Cargo.toml
- themis/client_bn/Cargo.toml
- themis/client_ristretto/Cargo.toml
- themis/program_bn/Cargo.toml
- themis/program_ristretto/Cargo.toml
- token-swap/program/Cargo.toml
- token/program-v3/Cargo.toml
- token/program/Cargo.toml
The feature `skip-no-mangle` is used a macro that is defined in the sdk but used in programs.  This means to enable this feature the programs must define it, not the sdk.  Currently, all the programs define this feature but they also require it in the sdk which is not necessary.
These changes remove the `skip-no-mangle` feature dependency on the sdk.
> solana sdk does not need skip-no-mangle

- memo/program/Cargo.toml
- themis/client_bn/Cargo.toml
- themis/client_ristretto/Cargo.toml
- themis/program_bn/Cargo.toml
- themis/program_ristretto/Cargo.toml
- token-swap/program/Cargo.toml
- token/program-v3/Cargo.toml
- token/program/Cargo.toml
Programs now use other features to decide if the program's entrypoint should be pulled in or not.  Remove it entirely.
> Remove skip-no-mangle entirely

- token-swap/program/src/curve.rs
- token-swap/program/src/processor.rs
**Problem**
Pointed out by @dankelleher -- if working with very small amounts of pool tokens, we can get in situations where we deposit / withdraw / swap 0 tokens, which is a big problem!
**Solution**
Return `None` from the calculations if 0 is invalid, triggering `CalculationFailure`.  The other approach is to add checks wherever these functions are used, but I thought it would be clearer for `None` to mean that the calculation has no good result.
> token-swap: Add checks for 0 token output and tests

- token/js/client/token.js
- token/js/module.d.ts
- token/js/module.flow.js
Standardise datatypes of amount parameters to accept u64s across the board in the token program JS client.
> Standardise amount datatypes in token client

- Cargo.lock
- themis/client_ristretto/Cargo.toml
- themis/client_ristretto/examples/tps.rs
- themis/client_ristretto/src/lib.rs
- themis/client_ristretto/tests/assert_instruction_count.rs
- themis/client_ristretto/tests/e2e.rs
- themis/program_ristretto/Cargo.toml
- themis/program_ristretto/src/instruction.rs
- themis/program_ristretto/src/state.rs
CalculateAggregate and SubmitProofDecryption operations exceed the BPF instruction limit
Use the new `ristretto_mul` and Sha256 builtins to stay below the BPF instruction limit.
All operations will now stay below the limit in the forthcoming 1.4 testnet:
```
BPF instructions executed
InitializePolicies(2): 3,354 (80000)
InitializeUserAccount: 19,746 (22000)
CalculateAggregate:    87,220 (200000)
SubmitProofDecryption: 105,372 (200000)
```
> Use ristretto_mul builtin to stay below BPF instruction limit

- token-swap/program/src/instruction.rs
As @joncinque already mentioned, this will only become relevant for cross-program invocations.
> Set correct read/write permissions on token-swap instruction calls

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
After a discussion with @jackcmay we decided to:
- Use different seeds to generate deposit and withdraw authorities (added "deposit" and "withdraw" prefixes)
- Rename nonce used for program address generation to 'bump seed'
> Changes to stake pool program address generation

- token/program-v3/src/processor.rs
- token/program/src/processor.rs
Transfer will succeed if the source and destination accounts have the same address, regardless of whether it is a valid token account.
This is probably wrong but transactions in the wild have been observed to do this so this behavior is now part of the token ABI
> Add additional transfer test coverage

- token/js/module.d.ts
- token/js/module.flow.js
Add Token class properties to spl-token library module declaration files so downstream users can access them without having to bypass type checking
> Add Token class properties to spl-token library module declaration files

- token-swap/program/src/error.rs
- token-swap/program/src/processor.rs
- Swap pool mints can have a freeze authority which can be used to freeze liquidity provider's pool tokens to lock in liquidity
- Swap pool liquidity token accounts can have a close authority. If the token accounts reach zero tokens, they can be closed and deleted and replaced with new accounts which aren't restricted by the normal initialization instruction.
- Prohibit token accounts from having a close authority
- Prohibit mint accounts from having a freeze authority
> Check for close and freeze authorities in token-swap

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
Fixed several issues we found while working on CLI and unit tests:
- Read-only interface accounts added as read-only
- Fixed mint authority on deposit
- Fixed stake pool state deserializing
> Stake pool interface fixes

- Cargo.lock
- token-swap/program/src/processor.rs
No validation check to prevent swap info token accounts being used as user inputs
- Prevent pool accounts from being used as swap inputs, deposit inputs, and withdraw outputs
> Prevent swap accounts being used as user accounts

- token/program-v3/src/instruction.rs
- token/program/src/instruction.rs
There is no `CreateInstruction` System instruction, should be referring to `CreateAccount`
> Refer to CreateAccount

- Cargo.lock
- ci/script.sh
- token-swap/js/cli/token-swap-test.js
- token-swap/js/client/token-swap.js
- token-swap/js/module.d.ts
- token-swap/js/module.flow.js
- token-swap/program/Cargo.toml
- token-swap/program/src/constraints.rs
- token-swap/program/src/curve.rs
- token-swap/program/src/error.rs
- token-swap/program/src/instruction.rs
- token-swap/program/src/lib.rs
- token-swap/program/src/processor.rs
- token-swap/program/src/state.rs
In the dex situation, the token swap program may have multiple frontends interacting with it, but the program creator would like to be the default destination for trading fees, along with enforcing certain fees on its exchange.  This provides a little framework for setting and enforcing these constants, enabled using the "production" feature.
Currently, only the owner key is configured through an environment variable.  I wanted to statically create a Pubkey based on &'static str using a const function, but the only const function for creating is from an array, so I'm not sure if we can go the full way to creating a Pubkey at this point.  We could eventually also include the fee parameters as env variables, but the conversion &'static str -> u64 wasn't clear either.
Additionally, there's …
> Token-swap: Add "production mode" hard-coded fee constraints

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/main.rs
`spl-token` has no support for the program's multisig features
Add subcommands to create and view multisig accounts
Plumb ability to specify multisig owners through supporting subcommands
> token-cli: Add multisig support

- Cargo.lock
- shared-memory/program/Cargo.toml
- token/perf-monitor/Cargo.toml
Currently we're getting failures on the `cargo test` and `clippy` parts of the CI because of mismatched versions of solana_rbpf.  It seems like the solana sdk dependencies need to upgrade to solana_rbpf v 0.2.0 before we can upgrade the dependencies here.
> Revert solana_rbpf to 0.1.32 to fix CI

- Cargo.lock
- associated-token-account/program/Cargo.toml
- associated-token-account/program/src/entrypoint.rs
- memo/program/Cargo.toml
- memo/program/src/lib.rs
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- stake-pool/program/src/lib.rs
- themis/client_ristretto/Cargo.toml
- themis/program_ristretto/Cargo.toml
- themis/program_ristretto/src/lib.rs
- token-lending/program/Cargo.toml
- token-lending/program/src/lib.rs
- token-swap/program/Cargo.toml
- token-swap/program/src/lib.rs
- token/cli/Cargo.toml
- token/perf-monitor/Cargo.toml
- token/program-v3/Cargo.toml
- token/program-v3/src/lib.rs
- token/program/Cargo.toml
- token/program/src/lib.rs
- utils/test-client/Cargo.toml
Downstream clients are using `no-entrypoint`, no need to make them change when upgrading to a newer crate
> Back to no-entrypoint feature name

- Cargo.lock
- associated-token-account/program/program-id.md
- associated-token-account/program/src/lib.rs
- token/cli/Cargo.toml
- token/cli/src/main.rs
The following commands feature additional behaviour:
* `spl-token create-account <token>` without an explicit account will now create the associated token account
* `spl-token transfer` now accepts the user wallet address as the recipient, which will transfer to their associated token account.   The `--fund-recipient` flag may also be specified to fund their associated token account
Also adds a new `spl-token gc` command.  This will consolidate token balances into the associated token account, and then close the ancillary token accounts.  Frozen accounts and accounts with another close authority are skipped.
> Add associated-token-account support to spl-token-cli

- Cargo.lock
- associated-token-account/program/Cargo.toml
- token-swap/program/Cargo.toml
- token/cli/Cargo.toml
- token/program/Cargo.toml
The latest spl-token crate is based on the solana-program crate in v1.4, and cannot easily be integrated with a downstream program based on the solana-sdk 1.3 crate.   Bump the major version to clearly indicate the new dependencies
> Bump spl-token to v3.0.0

- Cargo.lock
- token-swap/program/src/curve/calculator.rs
- token-swap/program/src/processor.rs
If a swap has a trading fee and a zero owner fee, when calculating the owner
fee to pool token conversion, the simulated trading fee will be non-zero
because we floor the trading fee to 1 token.  If the input to trading
fee calculation is 0, then we will try to do `0 - 1` on an unsigned int,
which causes an underflow error.  The fix is to simply return a 0 fee
for a 0 input.
> token-swap: Fix zero fee calculation

- token-swap/js/client/token-swap.js
- token/js/client/token.js
`fromBuffer` expects the return type to be `u64` or `Numberu64` but returns `BN` instead. This causes errors downstream if a user tries to call `toBuffer`, which only exists on `u64`.
> Fix u64.fromBuffer return type to u64

- Cargo.lock
- stake-pool/program/Cargo.toml
- stake-pool/program/src/entrypoint.rs
- stake-pool/program/src/stake.rs
- stake-pool/program/tests/functional.rs
- token/program/Cargo.toml
stake pool unit tests can only cover the local logic, since it isn't possible to extract the stake program processor like we can with spl_token.  This adds the capability to run tests against the real stake program processor using ProgramTest.
> stake-pool: Add end-to-end testing using ProgramTest

- Cargo.toml
- feature-proposal/program/Cargo.toml
- feature-proposal/program/Xargo.toml
- feature-proposal/program/program-id.md
- feature-proposal/program/run-tests.sh
- feature-proposal/program/src/borsh_utils.rs
- feature-proposal/program/src/entrypoint.rs
- feature-proposal/program/src/instruction.rs
- feature-proposal/program/src/lib.rs
- feature-proposal/program/src/processor.rs
- feature-proposal/program/src/state.rs
- feature-proposal/program/tests/functional.rs
The Feature Proposal program will allow for Solana runtime features to be activated based on community vote.  The feature proposer is responsible for:
* Submitting the code for the feature itself into the Solana code base, and gating the feature by a feature id
* Once all validators have updated to a version of the software with the new feature, submitting a transaction to initiate the on-chain voting.
* Distributing the SPL Tokens that will be used to vote for the feature using `solana-tokens` (fyi @CriesofCarrots)
* Informing the community that a vote is active, and sharing the SPL Token activation address that used to denote "yes".
Community members then use `spl-token transfer` to vote for the feature activation (or another SPL Token-enabled wallet of their choosing).
Finally the …
> Feature Proposal program

- token/cli/src/main.rs
SPL Token cli uses max commitment for balance checks. This is annoying and unexpected, since everything else defaults to singleGossip commitment.
Fixes #837
> spl-token-cli: Use config commitment for balance checks

- Cargo.lock
- associated-token-account/program/src/entrypoint.rs
- examples/rust/cross-program-invocation/src/entrypoint.rs
- examples/rust/custom-heap/src/entrypoint.rs
- examples/rust/logging/src/entrypoint.rs
- examples/rust/sysvar/src/entrypoint.rs
- examples/rust/transfer-lamports/src/entrypoint.rs
BPF cfg check has been moved into the `entrypoint` macro where it belongs, remove the unnecessary checks in the programs.
> Remove entrypoint bpf cfg check

- token-swap/js/cli/main.js
- token-swap/js/cli/token-swap-test.js
This is WIP, but it can showcase how to reduce the number of separate roundtrips required to do many things at once.  It may be worth porting all of the token-swap tests to look like this to speed them considerably.
> Add JS test for creating accounts and swapping in one transaction

- token/cli/src/main.rs
No need to output the mint on every line when the user already provided it as input
> Clean up `spl-token accounts <MINT>` output

- token/cli/src/main.rs
Much cleanup.  This PR is blocked until https://github.com/solana-labs/solana/pull/13638 ships
> spl-token-cli: Use RpcClient::new_with_commitment()

- Cargo.lock
- Cargo.toml
- docs/sidebars.js
- docs/src/feature-proposal.md
- feature-proposal/cli/Cargo.toml
- feature-proposal/cli/src/main.rs
- feature-proposal/program/Cargo.toml
- feature-proposal/program/src/instruction.rs
- feature-proposal/program/src/lib.rs
- feature-proposal/program/src/processor.rs
- feature-proposal/program/tests/functional.rs
```
$ spl-feature-proposal --help
spl-feature-proposal-cli 1.0.0
SPL Feature Proposal Command-line Utility
USAGE:
spl-feature-proposal [FLAGS] [OPTIONS] <SUBCOMMAND>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
-v, --verbose    Show additional information
OPTIONS:
-C, --config <PATH>        Configuration file to use [default: /Users/mvines/.config/solana/cli/config.yml]
--url <URL>            JSON RPC URL for the cluster [default: value from configuration file]
--keypair <KEYPAIR>    Filepath or URL to a keypair [default: client keypair]
SUBCOMMANDS:
address    Display address information for the feature proposal
help       Prints this message or the help of the given subcommand(s)
propose    Initiate a feature proposal
tally      Tally the …
```
> Add spl-feature-proposal-cli and documentation

- Cargo.lock
- stake-pool/program/src/processor.rs
Here we add a bunch of negative tests (where we expect errors to happen) to the stake pool smart contract.
This change set was waiting for its turn before interface to stake account program was added for test purposes, so it does not incorporate those changes.
> Added negative tests for stake pool

- feature-proposal/cli/Cargo.toml
- feature-proposal/cli/src/main.rs
Once https://github.com/solana-labs/solana/pull/13815 lands, `solana-tokens` will expect spl-token distribution CSVs to use raw amounts (no decimal).
Update `feature-proposal` CSV-generation code accordingly.
> spl-feature-proposal: output raw spl-token amounts in csv

- Cargo.lock
- token-swap/program/src/curve/base.rs
- token-swap/program/src/curve/calculator.rs
- token-swap/program/src/curve/constant_product.rs
- token-swap/program/src/curve/stable.rs
- token-swap/program/src/processor.rs
In order to do proper conversions between pool tokens and trading tokens (A/B), we need the full amounts of token A and B in the swap, so this adds an interface to be used by the new curves.
> token-swap: Add pool token conversion interface

- token-swap/program/src/curve/base.rs
- token-swap/program/src/curve/constant_price.rs
- token-swap/program/src/processor.rs
The constant price is a flat line, where the amount of token A required to buy 1 token B is fixed on init.  This makes the value function for the pool very simple:
`value = token_a_amount + token_b_amount * token_b_price`, so single deposit calculations are done with respect to that number.
~~Note that this depends on #934 , so the only substantial changes are in `constant_price.rs` and some more tests in `processor.rs`.~~
The PR has been rebased for easier reading.
> token-swap: Constant price curve

- Cargo.lock
- token-swap/program/Cargo.toml
- token-swap/program/src/curve/calculator.rs
- token-swap/program/src/curve/math.rs
- token-swap/program/src/curve/offset.rs
In order to restrict the potential problem surface of the new math functions, we expose only a `sqrt` function from `PreciseNumber` and add a property test to be sure that the calculation works as expected.
This implements the recommended test: "To claim that the function f approximates sqrt with a relative error of at most epsilon, then your property-based test should assert that (f(x)*(1-epsilon))^2 < x < (f(x)*(1+epsilon))^2 for all x in the range of inputs that f is documented as accepting."
> token-swap: Refactor math into sqrt function and add proptest

- token-swap/program/src/curve/math.rs
The Rust version used to build BPF is a bit older, so it requires a full name for `u128::MAX`.
> token-swap: Fix bpf build, need to fully reference u128::MAX

- Cargo.lock
- token-swap/js/cli/main.js
- token-swap/js/cli/token-swap-test.js
- token-swap/js/client/token-swap.js
- token-swap/js/module.d.ts
- token-swap/js/module.flow.js
- token-swap/program/fuzz/src/instructions.rs
- token-swap/program/fuzz/src/native_token_swap.rs
- token-swap/program/src/instruction.rs
- token-swap/program/src/processor.rs
In order to properly support the new curves, we need the ability to deposit or withdraw just one side of the token swap.  This uses the interface added in #934.
Since the math part is covered in other PRs, this focuses on the interface into processor.rs, and the tests closely mirror the logic to test the normal `withdraw` and `deposit` instructions.
> token-swap: Add instructions to deposit / withdraw one token

- token-swap/program/src/curve/calculator.rs
- token-swap/program/src/curve/constant_price.rs
- token-swap/program/src/curve/constant_product.rs
- token-swap/program/src/curve/offset.rs
In order to provide more confidence for the new curve math, this adds proptests for each curve to make sure that a one-sided deposit is actually equivalent to a swap and deposit.  For almost all curves and deposit directions, with the exception of B -> A constant price curves with huge prices (which highlights truncation issues), we can guarantee an epsilon of less than 0.5% for one-sided deposit vs swap + deposit.
This also provides more information about what the cases in which a swap or deposit is expected to succeed.
> token-swap: Add proptests for single token conversion

- .gitignore
- token-swap/program/src/curve/calculator.rs
- token-swap/program/src/curve/constant_price.rs
- token-swap/program/src/curve/constant_product.rs
- token-swap/program/src/curve/math.rs
- token-swap/program/src/curve/offset.rs
This set of proptests checks that a swap never takes value out of the liquidity pools, and re-uses the successful swap conditions developed for #950.
In order to check that value has not been lost, this also adds a simple `total_value` function to the calculator, which defaults to the constant product invariant.  The offset and constant price curves have different ways of figuring out the total value.
Note that the total value result is meant to be unique to each curve type, and not to be used for comparing against other curves.
Also, I tried implementing this for `StableCurve`, but the tests failed.  It seems we need to do some more work to properly support it first.
> token-swap: Add proptests for decreasing curve value

- token-swap/js/cli/token-swap-test.js
- token-swap/program/fuzz/src/instructions.rs
- token-swap/program/src/curve/calculator.rs
- token-swap/program/src/curve/constant_price.rs
- token-swap/program/src/curve/constant_product.rs
- token-swap/program/src/curve/math.rs
- token-swap/program/src/curve/offset.rs
- token-swap/program/src/curve/stable.rs
- token-swap/program/src/processor.rs
This adds an extra check in the instruction fuzzer, where we calculate the total value of pool tokens before and after the instructions.  Their relative value should never decrease, ie. `A_total_start / P_total_start <= A_total_end / P_total_end` should always hold.  This also showed that the deposit math was incorrect, and we should *not* be adding the amount coming in on a deposit.  See https://balancer.finance/whitepaper/#all-asset-deposit-withdrawal for the applicable formula.
> token-swap: Add fuzz check for pool token value

- Cargo.lock
- token-swap/program/src/curve/calculator.rs
- token-swap/program/src/curve/constant_price.rs
- token-swap/program/src/curve/constant_product.rs
- token-swap/program/src/curve/offset.rs
This adds a specific proptest to make sure that no deposit drains value from the pool.  While creating these tests, I noticed that the constant price curve was not performing its conversions totally correctly.  The true normalized value for an additive curve (one in which the value is derived as `x * token_a + y * token_b`) needs to have a division by 2 at the end, similar to how the constant product curve normalized value needs to be `sqrt`'ed.
> token-swap: Add proptest for deposit draining

- token-swap/program/fuzz/src/instructions.rs
- token-swap/program/fuzz/src/native_token_swap.rs
- token-swap/program/src/instruction.rs
- token-swap/program/src/processor.rs
Add the new deposit and withdraw single token type instructions to the fuzzer.  While working on this, I noticed that the functions to create instructions in the program never got updated to the new names, so I included that in these changes.  Since this isn't a very big change and only for testing, I hope it's ok to lump them in together.
> token-swap: Add new instructions to fuzzing

- ci/fuzz.sh
Adds some logic to print the output of fuzz failures to reproduce the error locally.
> Print fuzz file content on failure for local repro

- token-lending/program/Cargo.toml
- token-lending/program/src/dex_market.rs
- token-lending/program/src/error.rs
- token-lending/program/src/lib.rs
- token-lending/program/src/processor.rs
- token-lending/program/tests/borrow.rs
- token-lending/program/tests/helpers/mod.rs
- token-lending/program/tests/liquidate.rs
- token-lending/program/tests/repay.rs
- Fix the scales used during trade simulation
- Reuse order book state in liquidate to save instructions
- Verify that correct side of order book is used
> lending: Optimize liquidate and clean up dex market handling

- token-lending/js/client/index.ts
- token-lending/program/src/dex_market.rs
- token-lending/program/src/processor.rs
- token-lending/program/src/state.rs
- token-lending/program/tests/genesis_accounts.rs
- token-lending/program/tests/helpers/mod.rs
- token-lending/program/tests/init_lending_market.rs
We haven't been able to discuss the best path for versioning structs just yet, but this is a simple alternative of just adding a version at the start of the struct and padding to be potentially used later.
Once `version` was added to `Obligation`, the build failed because of stack size violations in `process_borrow`, so I refactored the borrow amount calculation into a function on `TradeSimulator`.  I didn't see an obvious place to move the calculation -- I thought about putting it in `state.rs`, but then you pull in the TradeSimulator into state, which didn't seem like the right solution.  We can also implement it on `BorrowAmountType`.
Let me know what you think!
> lending: Add version and padding to state structs

- token-swap/program/src/processor.rs
This changes the order of CPIs into the token program to always transfer towards the user at the end of instructions.
cc @jstarry
> swap: Move transfers into user account to the end of instructions

- ci/fuzz.sh
If there's a fuzz failure, the contents of the file are printed using `cat`, which isn't useful for binary files.  Instead, use `od -t x1` to get a hex output that's easy to use with `xxd -r` to reconstruct the binary file.  That way we can reliably reproduce the fuzz failure locally.  There are now more instructions included in the script as well.
> fuzz: Dump error file as hex instead of using cat

- token-swap/program/fuzz/src/instructions.rs
- token-swap/program/fuzz/src/native_token.rs
- token-swap/program/fuzz/src/native_token_swap.rs
There are sporadic crashes on the nightly fuzzing because of the new "withdraw single token type" instruction.  In the fuzzing environment, the curve has a withdraw fee, which means we must provide a minimum of 2 pool tokens to the withdraw instruction, 1 for the fee, and 1 to withdraw token A / B.  There are checks in the other instructions to avoid getting down to 1 pool token, but "withdraw single token type" doesn't allow us to specify exactly how many pool tokens to withdraw, meaning that we can eventually have a situation where we have 1 pool token, causing a crash on the end calculation.  To get around that, this introduces a change to transfer all pool tokens to the fee account before the final withdrawal.  The fee account is not charged a withdrawal fee, so this makes the end …
> swap: Avoid fuzz 1 token withdrawal errors by using fee account

- token-lending/js/client/index.ts
- token-lending/program/src/processor.rs
- token-lending/program/src/state.rs
- token-lending/program/tests/borrow.rs
- token-lending/program/tests/deposit.rs
- token-lending/program/tests/helpers/mod.rs
- token-lending/program/tests/liquidate.rs
- token-lending/program/tests/repay.rs
- token-lending/program/tests/withdraw.rs
Finding the bump seed for a derived address can take a variable number of iterations which each cost 1500 compute units leading to varied compute costs for lending instructions.
- Store bump seed in lending market state to avoid having to recompute it
- Lower compute unit clamps in tests
> lending: Store bump_seed in lending market to cut compute cost

- token-lending/program/src/error.rs
- token-lending/program/src/processor.rs
- token-lending/program/src/state.rs
- token-lending/program/tests/helpers/mod.rs
- token-lending/program/tests/liquidate.rs
- token-lending/program/tests/repay.rs
Obligation interest calculation is overcomplicated and untested
- Simplify obligation interest calculation
- Add tests for obligation repayment
> lending: Fix obligation interest accrual

- docs/src/token.md
To improve transfer interoperability between wallets supporting the SPL Token transfer, the sender's wallet is now **required** to fund the recipient's SPL token account if it doesn't already exist.   
Previously this was just a recommendation, however this causes interoperability problems between wallets that choose to not follow the recommendation.
> Refine SPL Token wallet integration guide

- token-lending/program/src/math/decimal.rs
- token-lending/program/src/processor.rs
- token-lending/program/src/state/obligation.rs
- token-lending/program/src/state/reserve.rs
- token-lending/program/tests/repay.rs
Difficult to test obligation repay math due to it being inline in the processor instruction handling
Factor out repay math into obligation method and add proptests. Caught a few issues:
- Obligation token repay percent should always strictly less than withdraw percent because we don't want a split obligation to be able to take advantage of rounding error to receive more collateral than they are allotted.
- Borrowers could take advantage of rounding error to pay less liquidity for more withdrawn collateral leading to lost interest returns for the pool. Changes were made to round up liquidity payments and round down collateral withdrawals.
> lending: Refactor and test obligation repays

- token-lending/program/src/instruction.rs
- token-lending/program/src/processor.rs
- token-lending/program/src/state/obligation.rs
- token-lending/program/tests/borrow.rs
- token-lending/program/tests/genesis_accounts.rs
- token-lending/program/tests/helpers/mod.rs
- token-lending/program/tests/init_obligation.rs
- token-lending/program/tests/repay.rs
The borrow instruction is too overloaded and consumes a lot of compute units which causes problems with composability
- New init obligation instruction
- Borrow now always expects initialized obligation accounts
- Interest is not accrued for the deposit reserve to save compute cost
> lending: Add InitObligation instruction

- token-lending/program/src/error.rs
- token-lending/program/src/instruction.rs
- token-lending/program/src/processor.rs
- token-lending/program/tests/accrue_interest.rs
- token-lending/program/tests/borrow.rs
- token-lending/program/tests/deposit.rs
- token-lending/program/tests/helpers/mod.rs
- token-lending/program/tests/init_obligation.rs
- token-lending/program/tests/liquidate.rs
- token-lending/program/tests/repay.rs
- token-lending/program/tests/withdraw.rs
Most lending instructions require up-to-date knowledge about the current reserve borrow rate which requires compounding the interest over the elapsed slots since the last successful instruction. In the worst case (1 year of interest), this adds about 30k compute units per reserve which severely limits the lending protocol's composability
- Create new "Accrue Interest" instruction that can be passed a list of reserves to compound interest for
- Remove interest accrual from borrow, repay, liquidate, etc and replace with an assertion that the reserve was last updated in the current slot
> lending: Split interest accrual into new instruction

- token-lending/program/src/dex_market.rs
- token-lending/program/src/error.rs
- token-lending/program/src/processor.rs
- token-lending/program/src/state/mod.rs
- token-lending/program/src/state/obligation.rs
- token-lending/program/src/state/reserve.rs
- token-lending/program/tests/helpers/mod.rs
- token-lending/program/tests/liquidate.rs
- Code for borrow and liquidate was not tested and not very suitable for rigorous prop testing
- A few configuration parameters were not validated correctly
- Rounding was not done in the correct direction in a few places
- Remove trade simulator orders cache
- Split bonus payout into separate instruction for higher transparency
- Return an error if liquidation will result in 0 received collateral
- Ensure LTV ratio is non-zero
- Enforce that liquidation threshold is higher than LTV
- Ensure math is rounded with ceiling / floor when appropriate:
- Liquidations should never round to more than the close factor
- Liquidation should never receive more collateral than the precise exchange rate
- Bonus amount should never be higher than the bonus rate
Liquidation processing has changed quite a …
> lending: Fixes and tests for borrow and liquidate

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/initialize.rs
- stake-pool/program/tests/set_owner.rs
- stake-pool/program/tests/set_staking_authority.rs
- stake-pool/program/tests/update_list_balance.rs
- stake-pool/program/tests/update_pool_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_create.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
All negative outcomes covered except for the cases where it is needed to change account data (or just the system clock) for proper testing.
> Stake pool: test coverage for most of the program errors

- token/program/src/processor.rs
SPL Token self-transfers are special-cased such that they always succeed despite bypassing many checks.  This could mislead other programs or apps which make assumptions based on the success of a transfer.
~Since most of the benefits of the special-case were to avoid deserializing accounts and those deserializations are necessary to perform the checks we'd like to reinstate, simply remove the special-case and treat self-transfers as normal transfers~
So that only works if you delete too many tests :sweat_smile: 
Problem being that even though the account refs are the same, we deser into separate buffers, so the token `amount` manipulations don't cancel each other out and the add-store overwrites the subtract-store.  Instead, move the self-transfer special case to just before the `amount` …
> token: Fully check self-transfers

- .github/workflows/pull-request.yml
Base CI target cache key on Rust version
> ci: Base `target` cache key on env.RUST_STABLE (version)

- ci/rust-version.sh
- token-swap/program/program-id.md
- token-swap/program/src/lib.rs
Since token swap has finally been released to a stable address, it's time to add it to the repo for other people to build against.
> Update rust stable to 1.49 (and add token swap program id)

- .github/workflows/pull-request.yml
PRs that do not change the dependency hash run into this error on CI build:
`error[E0460]: found possibly newer version of crate `std` which `solana_program` depends on`
https://github.com/solana-labs/solana-program-library/pull/1157/checks?check_run_id=1829061379
Use a big hammer for now, and remove `target` from the cache
> Remove target from cache

- patch.crates-io.sh
- update-solana-dependencies.sh
We are working on upgrading tokio upstream at solana: https://github.com/solana-labs/solana/pull/15013
Currently, this breaks the downstream-projects CI build, because of conflicts between the solana and SPL tokio versions.
This PR updates the SPL patching script to keep tokio in sync with `solana-program-test`. This will fix solana CI, but also make developing SPL against a local solana monorepo easier.
> Keep tokio consistent with solana-program-test

- docs/src/token-swap.md
Now that the token swap program is out in the wild, it's really time for some documentation.
The idea is to follow the docs at [token](https://github.com/solana-labs/solana-program-library/blob/master/docs/src/token.md), specifically focusing on:
* How the accounts are created and used.  Devs (myself included) have initial struggles understanding the many accounts required by Solana programs, so the idea is to also provide background information about accounts
* Curves present.  If people want to implement their own curve, they should know that it's possible and what's already in the program.
> docs: Flesh out token swap README

- token/program/inc/token.h
- utils/cgen/src/main.rs
I really just wanted to pick up the `InitializeAccount2` instruction enum variant, but it looks like this hasn't been done in a while...
I've tried to split the diff into related changes to ease review.  They're mostly cosmetic and comments changes.  Outliers being `COption` and `Pubkey` being moved to the `solana-program` crate (https://github.com/solana-labs/solana-program-library/commit/4d8fe2d6be4425183b03fac2436fcb04ab9bba25) and the addition of `InitializeAccount2` (https://github.com/solana-labs/solana-program-library/commit/aa81dbd7dc65c6ea99f3cee4d56705ab7adb55a3)
> token: Bump C bindings

- .github/dependabot.yml
While the `cbindgen` crate version is pinned in `Cargo.toml`, dependabot happily bumps it as new releases come out.  Since these updates don't regenerate the C bindings, cosmetic changes silently creep in.
Add `cbindgen` to dependabot ignore
> Pin cbindgen harder

- docs/src/token.md
Fixes two small typos in docs/src/token.md.
> Fix two small typos in docs

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/update_list_balance.rs
A validator stake account only has 1 lamport, which means that it will
gain very few rewards per epoch.  Its credits_observed is not
be reset each epoch, which makes it practically impossible to merge
into.  Get around this by instantiating them with more stake.
> stake-pool: Validator stake account initialized with 1 SOL

- stake-pool/cli/src/main.rs
When running `spl-stake-pool update` on an empty stake pool with no validator accounts, the command does no work, when it actually needs to update the last epoch on the stake pool.  This adds an additional check for when to do no work.
> stake-pool-cli: Fix update command for empty stake pool list

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
The update command in the stake pool CLI was passing the validator vote
account instead of the associated stake account from the pool, causing
it to fail.  Additionally, add more verbose logging, and a dry-run mode
to get simulate transaction information, useful for debugging CLI
failures.
> stake-pool-cli: Fix update command, add verbosity

- associated-token-account/program/src/lib.rs
- associated-token-account/program/src/processor.rs
- ci/js-test-token.sh
- token/js/cli/main.js
- token/js/cli/store/index.js
- token/js/cli/token-test.js
- token/js/client/token.js
- token/js/module.d.ts
- token/js/module.flow.js
- token/js/package.json
- token/js/test/token.test.js
- There is no easy way of accessing associated tokens from JS land
- Support them
- Also, make testing more robust including `./program`'s NFC modifications.
> Support associated token for JS (Also, make the program testable)

- docs/src/token-swap.md
- token-swap/README.md
People have a hard time discovering the production parameters of token-swap, specifically who is supposed to be the fee owner address.
Include that info in the README along with more info about testing.  This is the documentation side of #1367
> token-swap: Document owner address in README

- memo/program/tests/functional.rs
The memo test randomly fails on CI with two different errors.
Not pretty, but expand to check for both possible errors returned.  At least it will unblock CI!
> memo: Expand error type to make test less flaky

- token-lending/program/src/instruction.rs
- token-lending/program/src/processor.rs
- token-lending/program/tests/set_lending_market_owner.rs
No way to migrate an existing lending market to a new owner. In this case, I would like to move the owner authority to a multisig contract
> lending: Add SetLendingMarketOwner instruction

- token/cli/src/main.rs
- Special-cases `accounts` subcommand to allow `--owner` to accept a Pubkey string
Fixes #1429
> Allow pubkey owner for accounts subcommand

- libraries/math/tests/instruction_count.rs
The new rust toolchain in solana 1.6.0 causes some the compute unit consumed by some of the math ops to increase.  Bump the limits.
> math: Bump max BPF compute units

- token/cli/src/main.rs
Several changes to remove footguns and make failure debugging easier for `spl-token authorize` commands.
- Check target account type (mint vs. account) and return clear error message if authorize is attempting to change an incompatible authority type
- Print the real current authority to make it easier to detect if `--owner` is incorrect authority for operation
- Refuse to change the owner or close authority if the account is an ATA of the `--owner`; hidden `--force` arg overrides
Fixes #791 
Fixes #1431
> Token cli: Improve authorize command

- shared-memory/program/tests/shared-memory.rs
shared-memory/program/tests/shared-memory.rs needs to use AccountSharedData instead of Account to work with Solana v1.6/v1.7
> Adapt to AccountSharedData

- memo/program/tests/functional.rs
`test_memo_compute_limits()` attempts to hit 200,000- and 200,000+ exactly.  But newer toolchains aren't guaranteed to produce the exact same amount of compute units.  Relax the limits to turn https://github.com/solana-labs/solana/pull/15886 green
> Adjust test_memo_compute_limits to account for toolchain differences

- token-lending/program/tests/deposit.rs
- token-lending/program/tests/deposit_obligation_collateral.rs
- token-lending/program/tests/genesis_accounts.rs
- token-lending/program/tests/init_obligation.rs
- token-lending/program/tests/init_reserve.rs
- token-lending/program/tests/liquidate.rs
- token-lending/program/tests/repay.rs
- token-lending/program/tests/withdraw.rs
- token-lending/program/tests/withdraw_obligation_collateral.rs
Lending doesn't fit into the compute budget when built against the master branch.  There may be a regression on master and have no easy way to bisect because https://github.com/solana-labs/solana/pull/15886 is still red.
Some of these increases will need to be revisited
> lending: Relax some `set_bpf_compute_max_units` to unblock testing against the solana master branch

- Cargo.lock
- binary-oracle-pair/program/Cargo.toml
Binary-oracle-pair program was merged after https://github.com/solana-labs/solana-program-library/pull/1456, and didn't get those changes. As a result, the program is breaking solana CI downstream-projects build on v1.5
cc @joncinque
> Binary-oracle: Remove explicit tokio

- Cargo.lock
- libraries/math/src/checked_ceil_div.rs
- libraries/math/src/lib.rs
- stake-pool/cli/src/main.rs
- stake-pool/program/Cargo.toml
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- token-swap/program/src/curve/constant_price.rs
- token-swap/program/src/curve/constant_product.rs
- token-swap/program/src/curve/mod.rs
When a stake account is totally removed from a stake pool by the
manager, there's a chance that the operation would not take enough of
the manager's pool tokens by 1 due to truncation.
Do a ceiling division instead, and refactor ceiling division into the
math library.
> stake-pool: Use checked_ceil_div for withdraw calc

- token/cli/src/main.rs
The ATA model is designed such that users only need to know their main wallet address (system account). But in order to perform a transfer using the spl-token cli, they must determine their actual token account address.
Update `spl-token transfer <MINT_ADDRESS> <QUANTITY> <RECIPIENT>`, with optional `--from` param for sending from auxiliary token accounts
Toward #1479
> Transfer from ATA by default

- token/cli/src/main.rs
`spl-token wrap` spins up an auxiliary account on each use, which deviates from the general standard of one ATA per main wallet address per mint.
Use ATA by default instead. Additional wrapped SOL accounts are still possible via the `--aux` parameter.
> spl-token-cli: use ATA by default in wrap/unwrap commands

- .github/workflows/pull-request-docs.yml
- .github/workflows/pull-request.yml
CI runs on this repo are pretty long, and lengthening as more programs are added. No reason to wait all that time to just update the SPL docs.
> CI: skip build/test suite when changes only affect docs

- token-swap/proposals/ProactiveMarketMaking.md
`P_{margin}=iRP` didn't make sense, as P isn't defined, and i is already defined as the price (from the oracle).
the referenced doc contains `P_{margin}=iR`, so I assume this is a typo.
> fixed formula to match referenced doc [1] + formatting

- README.md
when building for the first time:
```
error: failed to run custom build command for `hidapi v1.2.5`
Caused by:
process didn't exit successfully: `solana-program-library/target/debug/build/hidapi-81175f45ee69e1c2/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=LIBUDEV_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=LIBUDEV_STATIC
cargo:rerun-if-env-changed=LIBUDEV_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_PATH …
```
> adding a dep i needed when building on Ubuntu 20.10

- token/js/client/util/send-and-confirm-transaction.js
Currently, sendTransaction via spl-token is confirmed with `recent`, even if the connection's confirmation is `confirmed` for example.
This means any token transaction async executions could return too early, causing very hard-to-debug issues:
The following harmless-looking code doesn't work _for some time_:
```javascript
try {
await this.createAssociatedTokenAccountInternal(     <=  this submits tx and it's confirmed with recent internally
owner,
associatedAddress,
);
} catch (err) {
// ignore all errors; for now there is no API compatible way to
// selectively ignore the expected instruction error if the
// associated account is existing already.
}
// Now this should always succeed
return await this.getAccountInfo(associatedAddress); <= this is fetched with confirmed internally; could …
```
> Remove unconditional hidden commitment override for sanity

- token/cli/src/main.rs
Various spl-token cli subcommands require account addresses be passed in. This is inconsistent with the general emphasis on ATA, and the standard of one ATA per main wallet address per mint.
This PR updates close, balance, and account-info to expect a mint address and use the ATA by default. Closing or querying a specific account is still available using the `--address` parameter.
Also adds an `Aux` tag to account infos of non-ATAs
> spl-token-cli: support ATA in close, balance, and account-info

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/stake.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_create.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
This makes create-validator-stake-account a bit nicer:
* requires owner permission, assigns stake / withdraw authority to the owner
* automatically delegates the stake
Extra updates:
* removes unnecessary accounts as parameters (stake program and system program)
* removes all of the tests that check for a non-delegated validator account (not sure what those were really testing to be honest)
Note that the update to not count the rent-exempt reserve will be done during the `remove-validator` rework for #1501 
Fixes #1276 Fixes #1419
> stake-pool: Rework create validator stake account

- stake-pool/program/tests/initialize.rs
Stake pool tests fail when the `ProgramError` mappings are fixed because they check for the current but wrong error.  Instead, loosen the test to allow for both the current and wrong error as well as the correct error.
> Allow for fixed error mappings

- token/cli/src/main.rs
Resolution of `spl-token`'s `--owner` was getting a bit out of hand
Simplify it
> spl-token-cli: Simplify owner resolution

- token/cli/src/main.rs
Passing `--multisig-signer` args in different orders results in different transaction messages and consequently, signatures
Sort them
> spl-token-cli: Sort multisigners

- token/cli/src/main.rs
`spl-token-cli` panics if `--nonce ...` is specified without `--nonce-authority`
Fallback to the CLI config wallet
> spl-token-cli: Use CLI config wallet for nonce authority fallback

- memo/program/src/lib.rs
Memo's old program ID is still handy to have around
Add it back under `mod v1`
> spl-memo: Add back v1 program ID as `spl_memo::v1::id()`

- stake-pool/cli/src/client.rs
- stake-pool/cli/src/main.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/withdraw.rs
`spl-stake-pool list -v` then displays information about each actual stake account.
Oh yeah, rename a bunch of variables too.  I guess I'm not quite done scent marking this part of the code base yet...
> Reimplement `spl-stake-pool list` command to use the StakePool/ValidatorList as the primary source of information

- ci/solana-version.sh
- libraries/math/src/approximations.rs
- libraries/math/tests/instruction_count.rs
Fixes #1232 
Using a binary-based algorithm for sqrt calculation and a better guess, we can reduce the amount of BPF instructions by a good amount, especially for large `u128`s.  Thanks for the tip!
> math: Improve sqrt using bit-wise operations

- stake-pool/cli/src/main.rs
`stake-pool-cli update` will not work as is with a stake pool containing hundreds of validators.  Break up the `UpdateValidatorListBalance` instructions across multiple transactions so it will
> stake-pool-cli: Break up the UpdateValidatorListBalance instructions over multiple transactions

- stake-pool/program/src/error.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/initialize.rs
The stake pool init does not check the supply on the pool token mint, so someone could mint a bunch of tokens to themselves, then reuse that mint for a stake pool.
Add a supply check and test
> stake-pool: Ensure zero pool token supply on init

- Cargo.lock
- token-swap/program/Cargo.toml
The token swap 2.0.0 crates were published against Solana SDK 1.5, so this version will be built against 1.6.
> token-swap: Bump crate version to 2.1.0 for release

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
This can get the discussion going about the interface for the new rebalancing instructions.  I may be missing some sysvars or builtin programs, which will come out in implementation and testing.
Some open questions:
* PDA derivation for transient stake accounts: I'm not wedded to the solution of just using the stake account, and just opted for the simplest thing
* Accounting gets more complicated.  In order to properly keep track of the amount of stake under management, we need to also update the balances in transient accounts.  This proposes sending in pairs of accounts (canonical and transient) during `UpdateValidatorListBalance`.
* This adds a funder for transient stake accounts, but if we make sure that all movements are for `stake_account_rent_exemption + 1` lamport, then we can have …
> stake-pool: Add rebalancing instruction interface

- token/cli/src/main.rs
A few of `spl-token` CLI's subcommands are still querying RPC in sign-only mode, which breaks offline signing.
Add `sign_only` gates around RPC calls, with sane defaults in else-clauses where they exist and new CLI args where they don't
Bonus: Fix transfers to ATAs of multisig accounts
Review suggestion: `?w=1`
> Fix `spl-token` CLI offline signing support

- docs/src/stake-pool.md
- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
- stake-pool/program/tests/update_validator_list_balance.rs
Fixes #1521 
Instead of minting pool tokens on deposit to the manager, we mint them every epoch as a percentage of rewards perceived.  If there were no rewards or the pool lost value due to slashing, no fee is minted.  
From the associated issue:
> Problem
>
> Taking all of the fee upfront on deposit is a simple model, but unnecessarily punishes users who deposit for a short time. Also, it's totally different from the main staking program's reward model if assessing the commission every epoch.
>
> Solution
>
> Adopt a model similar to regular staking, and have the stake pool fee paid out as pool tokens minted every epoch during "update pool balance". Also, update the documentation to reflect this change.
> stake-pool: Assess fee as a percentage of rewards

- docs/src/token.md
`spl-token transfer` docs are outdated
> docs: specify mint in `spl-token transfer` examples

- Cargo.lock
- shared-memory/program/Cargo.toml
- shared-memory/program/tests/shared-memory.rs
Switch shared-memory program tests to program test to avoid using the rbpf interfaces directly
> Switch shared-mem tests to programtest

- libraries/math/src/instruction.rs
- libraries/math/src/processor.rs
- libraries/math/tests/instruction_count.rs
Due to inlining, it was hard to tell how many instructions the float operations were taking.  Move the float and integer operations out into their own function.
New operation comparison (instructions)
u64 multiply - 8
f32 multiply - 176
f32 divide - 219
> Fix float measurements

- stake-pool/cli/src/main.rs
- stake-pool/program/src/error.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/stake_program.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
Adding and removing validators from the pool involves pool tokens, which mixes the staker and manager roles.  The staker should not have to handle any pool tokens to do their work.
* Remove pool tokens from add to pool and remove validator from pool
* Set a required minimum for validator stake accounts (1 SOL + rent exemption)
* Make sure that on add validator / remove validator / withdraw we are respecting that limit
* Update book-keeping to not count the minimum amount
Fixes #1501
> stake-pool: Rework add / remove validator to not use pool tokens

- docs/src/stake-pool.md
- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/initialize.rs
- stake-pool/program/tests/set_fee.rs
The manager has no option to update the fee assessed by the stake pool.
Align things with the native vote program, and allow the manager to update the fee!  This does not allow the fee to be changed if the pool hasn't been updated in the current epoch.
While adding the documentation for the new set fee command, I noticed a bit of the documentation was out of date, and rearranged that for the new manager / staker split.
I'll take care of the confirmation step for #1418 in another PR.
> stake-pool: Set fee

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/stake_program.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_create.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
Transient stakes need to merged into their associated validator stake account or reserve stake.
Add merging logic!  Also:
* use Borsh to deserialize stakes, which allows us to merge up to 12 stakes per `Update` instruction
* add an index parameter for processing many at once, eliminating the brute force logic
* add a `no_merge` parameter, which allows to just update without performing merges.  Useful in case a merge just isn't working
* check for the transient stake while removing a validator from the pool
* fixup accounting
Fixes #1499 Fixes #1567
> stake-pool: Add merging transient stakes in update

- stake-pool/program/tests/update_validator_list_balance.rs
Unbreak downstream build in monorepo: https://buildkite.com/solana-labs/solana/builds/44668#69c5a87e-cb27-4123-908c-b60f4892b91d
Real fix will come in the monorepo so we don't have to warp so far.
> hotfix: ignore stake-pool tests that break with tip of 1.6

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_remove.rs
The current lower limit on increase-validator-stake only covers rent exemption, but that transient stake will not be mergeable once it's active if it's too small.
Increase the limit!  There was a huge annoyance on the testing framework due to low staked amounts, so this also adds a huge stake account that speeds up activation and deactivation.
> stake-pool: Increase lower limit for increase-validator-stake

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/initialize.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
Some stake pools need to be private, and not allow outside depositors.
Enhance the existing deposit authority in the stake pool be configurable
on initialization, and then require its signature on deposit.
The existing deposit authority is a program address, making deposits
permissionless. This allows a pool creator to set their own deposit_authority on
initialization. In a great turn of events, almost everything else works
the same way!
Here's the current workflow for deposit, where the user calls
stake_program::authorize and stake_pool::deposit in the same
transaction:
* stake_program::authorize assigns staker and withdraw authority to the
stake pool deposit authority
* stake_pool::deposit
- uses the deposit authority to assign authority on the deposited
stake account to the stake pool …
> stake-pool: Add depositor key on init, required on deposit

- docs/src/token.md
`spl.solana.com/token` may be a user's entrypoint to solana; if they are following the token examples target devnet or testnet, they may not know how to get some SOL to execute the commands successfully.
Fixes https://github.com/solana-labs/solana/issues/16837
> Add airdrop help to token docs

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
When removing a validator from the pool, the validator stake account must have the minimum lamports in the account, and no transient stake is allowed either.  This effectively makes it impossible to remove a validator from the stake pool.  Here's the situation:
* the staker wants to remove validator X from the pool, it currently has 10 SOL
* the staker decreases a validator's stake by 9 SOL, leaving it with the minimum of 1 SOL
* the stake pool creates the transient stake account and deactivates it
* staker tries to remove the validator account, but it's not possible because there's a transient stake
* staker waits one epoch, updates the pool, the transient stake is merged, thinks they're good to go
* staker tries to remove validator X, but the operation fails because the stake account …
> stake-pool: Add ability to remove a validator that has deactivating transient stake

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
The stake pool expects pool tokens to be delegated to the withdraw
authority before performing a withdrawal. If a user delegates too many
tokens to the withdraw authority, anyone else can take the rest of their
tokens by doing their own withdrawal.
Delegate pool tokens to an ephemeral keypair and sign with that.
Fixes #1483
> stake-pool: Add user transfer authority on withdraw

- token-swap/program/src/constraints.rs
- token-swap/program/src/error.rs
- token-swap/program/src/processor.rs
When withdrawing, the slippage check is done before `min`ing the token a
and b amounts, which makes it possible to ignore the desired slippage,
and lose out on a lot more than expected.
This has an additional knock-on effect. When burning all of the pool
tokens, it becomes impossible to ever use it again.
* Check for slippage after getting the actual amount that would be
traded
* Re-initialize the pool token amount on the next deposit if all pool
tokens were burned
Fixes #1629
> token-swap: Fix slippage on withdraw tokens

- Cargo.lock
- stake-pool/cli/Cargo.toml
- stake-pool/cli/src/main.rs
While going back through the docs, I ended up doing a lot of stake
pool CLI items, and also adding support for new program features:
* Deposit / withdraw command: Use associated token account by default
* Create command: Allow passing the stake pool and mint keypair (useful
for testing)
* Create command: Split the transaction for pool creation (required to get under the
transaction size limit)
* Add / remove validator command: take a validator vote account rather than stake
account, which makes integration from outside tools a lot simpler
* Update command: add a `--force` flag to force the update
* Update command: add a `--no-merge` flag to not merge while updating
(useful to allow the pool to work, even if the transient stake
accounts are unmergeable)
* Withdraw: Add `--use-reserve` flag …
> stake-pool-cli: Support new features

- Cargo.lock
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
It's time to release the stake pool crates! But they need versions on the SPL dependencies, so add those versions, and update the stake pool cli version to 0.1.0, which was probably just copied from the token cli.
> stake-pool: Update versions for crate deployment

- examples/c/src/cross-program-invocation/cross-program-invocation.c
Correctly check if deriving the PDA with the given seed was successful.
Don't pass the system program pubkey to the allocate instruction: the first account passed must be the one to be allocated.
> Fix cross-program-invocation C example

- .github/workflows/pull-request-docs.yml
If a PR has docs changes in additional to other code changes, Mergify may merge it before the full CI suite completes.
> Ensure only docs files are modified when triggering all-checks success

- stake-pool/program/tests/update_validator_list_balance.rs
#1622 disabled some tests that worked on 1.6.2, but failed on 1.6.6 when running the monorepo's downstream CI job due to limited warp slots possible in program-test.  1.6.7 added a fix in program-test to add a big bootstrap stake so that we don't need to warp quite so much.
Now that 1.6.7 is out, we can re-enable the tests and warp less!
> stake-pool: Re-enable tests, avoid warping so much

- docs/src/token.md
As the cli prompt indicates the argument should be the token address
```bash
$ spl-token account-info
error: The following required arguments were not provided:
<TOKEN_ADDRESS>
USAGE:
spl-token account-info <TOKEN_ADDRESS> --config <PATH>
```
In this case `7KqpRwzkkeweW5jQoETyLzhvs9rcCj9dVQ1MnzudirsM` is the associated token address and `559u4Tdr9umKwft3yHMsnAxohhzkFnUBPAFtibwuZD9z` is the token's address. 
Therefore the argument has been replaced to use the token rather than the associated account
> swap associated token account addr for token addr

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/initialize.rs
- stake-pool/program/tests/set_manager.rs
- stake-pool/program/tests/set_staker.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_create.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
The functions to create instructions on the stake pool are a little cumbersome, since they often require also passing in the correct validator / transient stake account.
Create a set of functions that take the stake pool and validator vote account address for easier use by clients.  These all came up while implementing the stake-o-matic with stake pools, so I imagine they'll be useful for other integrations.
> stake-pool: Add helper instruction creators for stake pool integration

- token-swap/program/src/processor.rs
- token/js/cli/main.js
- token/program/src/instruction.rs
- token/program/src/lib.rs
- token/program/src/processor.rs
This PR adds a `check_program_account` function to the spl-token crate which checks that the correct spl-token program id is in use. Programs which did not perform this check manually were liable to a privilege escalation attack if those programs used `invoke_signed` on spl-token program bindings.
> Fix potential vulnerabilities in programs using spl-token CPIs by adding program id checks

- token/program/src/processor.rs
Resolves #1739.
Please close if it's actually intentional.
> Fix #1739: ThawAccount incorrectly logged as FreezeAccount in token program

- Cargo.lock
- stake-pool/program/src/state.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
Per discussion with @ruuda, the current calculation method gives the pool owner too many tokens.  Since the new lamports are already part of the pool, and we're minting a part of it, it's not the same as a normal deposit / withdrawal calculation where all of the tokens are new.
The old calculation simply did:
```
fee_in_pool_tokens = fee_in_sol * pre_pool_token_supply / pre_epoch_lamports
```
But those pool tokens are worth more than `(post_epoch_lamports - pre_epoch_lamports) * fee_numerator / fee_denominator`.  The correct equation should be:
```
fee_in_pool_tokens / (fee_in_pool_tokens + pre_pool_token_supply) = fee_in_sol / post_epoch_lamports
```
which simplifies to:
```
fee_in_pool_tokens = fee_in_sol * pool_token_supply / (post_epoch_lamports - fee_in_sol)
```
Fix the calculation, …
> stake-pool: Fix fee calculation

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
We're going to have more than one stake pool program, and some of the instruction constructors don't allow you to set a program id.
Add `program_id` as a parameter on all constructors.
cc @ruuda let me know how this looks
> stake-pool: Add program_id to all instruction ctors

- stake-pool/cli/src/main.rs
- stake-pool/program/src/error.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/set_fee.rs
- stake-pool/program/tests/set_preferred.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
Stake pools can be arbitraged by depositing to one validator and withdrawing from another.
Cover a lot of potential attack vectors, and allow the stake pool staker to restrict deposits and withdrawals to specific validators.  If the preferred deposit validator is set, all deposits must go through it.  If a preferred withdrawer is set, all withdrawals must go through it if it has *any* stake at all.  If it's empty, then normal rules apply.
cc @aeyakovenko
> stake-pool: Add preferred deposit / withdraw validator accounts

- token/js/client/token.js
- token/js/test/token.test.js
`getAssociatedTokenAddress` will throw an error If I want to create an ada for a pda.
I don't think it should be blocked here and in fact I can sign the owner by program.
> bugfix: fix getAssociatedTokenAddress can't used by pda

- token-lending/program/src/error.rs
- token-lending/program/src/instruction.rs
- token-lending/program/src/processor.rs
- token-lending/program/src/state/reserve.rs
- token-lending/program/tests/borrow_obligation_liquidity.rs
- token-lending/program/tests/flash_loan.rs
- token-lending/program/tests/helpers/mod.rs
This PR
- Makes the reserve account writable and persists the borrow and repay so the flash loan receiver program has a consistent view of the state.
- Reorganizes the accounts expected by the FlashLoan instruction so that the writable accounts come first, the reserve accounts come in order, and the flash loan receiver program ID and variadic accounts come last.
- Renames some things for consistency with the other instructions.
- Improves related tests.
> lending: Flash Loan fixes

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
Update stake pool balance isn't properly checking for the correct reserve stake.
Add the check
Fixes #1861
> stake-pool: Add reserve stake check on update pool balance

- token/cli/src/config.rs
- token/cli/src/main.rs
Fixes: https://github.com/solana-labs/solana-program-library/issues/548
Fixes: https://github.com/solana-labs/solana-program-library/issues/1856
The `--owner` argument is not needed for every subcommand and in some cases `--owner` does not need to be a signer, but this is not explicit in the current code.
- Removed `owner` as a global argument and re-added it to the subcommands where it's needed. Each subcommand can now specify if it needs `owner` to be a keypair or just an address.
- Added named authority arguments for several subcommands (`mint` now accepts `--mint-authority` for example)
- Kept `--owner` as an alias to the new named authority arguments for backwards compatibility
- Added convenience methods for falling back gracefully to `owner` or the default cli signer when authority …
> spl-token-cli: Remove global owner argument

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
It's possible for a very malicious pool staker to constantly increase /
decrease the stake on validators, making it impossible for people to get
their SOL out.
Split the accounting to know how much of the stake is active and how
much is transient and allow users to withdraw from transient accounts,
but only if there's no more active stake.
> stake-pool: Add ability to withdraw from transient stakes

- governance/program/src/instruction.rs
- governance/program/src/lib.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_add_signatory.rs
- governance/program/src/processor/process_cancel_proposal.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_create_account_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/processor/process_deposit_governing_tokens.rs
- governance/program/src/processor/process_execute_instruction.rs
- governance/program/src/processor/process_finalize_vote.rs
- governance/program/src/processor/process_insert_instruction.rs
- governance/program/src/processor/process_relinquish_vote.rs
- governance/program/src/processor/process_remove_instruction.rs
- governance/program/src/processor/process_remove_signatory.rs
- governance/program/src/processor/process_set_governance_delegate.rs
- governance/program/src/processor/process_sign_off_proposal.rs
- governance/program/src/processor/process_withdraw_governing_tokens.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/proposal_instruction.rs
- governance/program/src/state/realm.rs
- governance/program/src/state/signatory_record.rs
- governance/program/src/state/token_owner_record.rs
- governance/program/src/state/vote_record.rs
- governance/program/tests/process_deposit_governing_tokens.rs
- governance/program/tests/process_set_governance_delegate.rs
- governance/program/tests/process_withdraw_governing_tokens.rs
- governance/program/tests/program_test/mod.rs
Remove static program_id to support runtime clones of the program
> Governance: use runtime program_id

- stake-pool/program/src/error.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/initialize.rs
It's possible to pass a mint with a freeze authority to a stake pool.
Don't allow it.
> stake-pool: Fail initializing if mint has a freeze authority

- stake-pool/program/src/processor.rs
The runtime was updated in 1.7 to not allow 0-lamport account creation, creating an issue reported at https://github.com/solana-labs/solana-program-library/pull/1617#issuecomment-864482976
Stake pools still leans on 0-lamport account creation for transient stake accounts.
Don't do `create_account` with 0 lamports when working with transient stake accounts, and instead separate out allocate + assign.
cc @keemy
> stake-pool: Split transient stake account creation

- .github/workflows/pull-request-token.yml
- .mergify.yml
- token/js/cli/token-test.js
Trying again for #1965
Automerge may be broken due to the split of GitHub Actions workflows -- once all_github_action_checks passes on the main pull-request.yml workflow, it may merge before finishing the program specific workflow.
This may not work, so the idea is to add more status-checks to mergify *along with* the normal all_github_actions check, and just change some whitespace to trigger it. If automerge waits for everything, then we're all good! If not, back to the drawing board.
> CI: Add status-failure and status-pending check to be sure that all steps are run

- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/proposal_instruction.rs
- governance/program/src/tools/account.rs
- governance/program/src/tools/mod.rs
- governance/program/src/tools/pack.rs
- governance/program/src/tools/spl_token.rs
- governance/program/tests/process_create_mint_governance.rs
- governance/program/tests/process_execute_instruction.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
- `CreateMintGovernance` - It works in similar way to `CreateProgramGovernance` by allowing to create a concrete `Governance` account of `MintGovernance` type.  
In addition to creating the concrete account type the instruction verifies the current mint authority signed the transaction and optionally transfers the authority to the newly created `Governance` account PDA.
The account PDA is unique and can only be created using `CreateMintGovernance` instruction ensuring only the current mint authority can create it.
> Governance: Create mint governance

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/update_validator_list_balance.rs
In order to make full use of all lamports in a stake pool, we need to withdraw the rent-exemption lamports from an active stake account after a merge.  Also, fix a bug during the update, where we weren't re-deserializing the validator stake account after the merge.
Do the accounting better!  There's also a little CLI update to also take in a reserve keypair if desired.
> stake-pool: Fixup accounting on increase transient account

- governance/README.md
- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/governance.rs
- governance/program/src/tools/spl_token.rs
- governance/program/tests/process_create_token_governance.rs
- governance/program/tests/process_execute_instruction.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
- `CreateTokenGovernance` - It works in similar way to `CreateMintGovernance` by allowing to create a concrete `Governance` account of `TokenGovernance` type.  
In addition to creating the concrete account type the instruction verifies the current token account owner signed the transaction and optionally transfers the owner to the newly created `Governance` account PDA.
The account PDA is unique and can only be created using `CreateTokenGovernance` instruction ensuring only the current token owner can create it.
> Governance: Create token governance

- governance/program/src/instruction.rs
- governance/program/src/processor/process_cancel_proposal.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/processor/process_execute_instruction.rs
- governance/program/src/processor/process_finalize_vote.rs
- governance/program/src/processor/process_insert_instruction.rs
- governance/program/src/processor/process_sign_off_proposal.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/proposal_instruction.rs
- governance/program/tests/process_cancel_proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_create_proposal.rs
- governance/program/tests/process_deposit_governing_tokens.rs
- governance/program/tests/process_execute_instruction.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/process_sign_off_proposal.rs
- governance/program/tests/program_test/mod.rs
Change all `Proposal` lifetime timestamps and configurable time periods (`voting_time`, `instruction_hold_up_time`) from slots to UnixTimestamp to make them human friendly
> Governance: Change timestamps and time periods to UnixTimestamp

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/lib.rs
When testing locally with 32-slot epochs, on bigger pools, it would take longer than an epoch to just update.
Split up the updating instructions to process all of them at the same time, and also reduce the number of accounts updated at once to avoid using up the whole compute budget.  This allows us to work with stake pools of roughly 200 validators.
> stake-pool-cli: Add small optimizations for updating faster

- docs/src/token.md
Improve the formatting of the examples in token.md.   Because many of the examples in the doc use multiline input, this change uses the 'console' key word in the markup to help distinguish input from output.   In cases where multiline input and output exists, we omit 'console' and the '$' symbol for the input, but include 'console' in the output.   This makes the coloring consistent and the text easier to read.
For the nonce multisign example, i pretty much rewrote the instructions because for whatever reason several steps were left out making the introduction really hard to understand.
> Fix a variety of token.md doc inconsistencies; improve multi-sign nonce example

- token/cli/src/main.rs
`clap::Arg::value_name` accumulates help message value names
```
--owner <OWNER_KEYPAIR> <SENDER_TOKEN_OWNER_KEYPAIR>
Specify the owner of the sending token account. This may be a keypair file, the ASK keyword. Defaults to the
client keypair.
```
Add a helper variant for the owner arg that takes the value name explicitly
> token-cli: Dedupe 'transfer' help message --owner value name

- Cargo.lock
- governance/program/Cargo.toml
- governance/program/src/error.rs
- governance/program/src/processor/process_create_account_governance.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/processor/process_create_realm.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/processor/process_deposit_governing_tokens.rs
- governance/program/src/processor/process_execute_instruction.rs
- governance/program/src/processor/process_insert_instruction.rs
- governance/program/src/processor/process_sign_off_proposal.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/proposal_instruction.rs
- governance/program/src/state/realm.rs
- governance/program/src/state/signatory_record.rs
- governance/program/src/state/token_owner_record.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_create_account_governance.rs
- governance/program/tests/process_execute_instruction.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/process_sign_off_proposal.rs
- governance/program/tests/process_withdraw_governing_tokens.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
The PR contains a set of changes which aim to future proof `Governance` program accounts for future versions
1. `VoteThresholdPercentageType` - vote threshold percentage type to support quorum based votes in future versions.
2. `VoteWeightSource` - vote weight source to support account snapshot based voter weights in future versions. With snapshots it'll be possible to vote without depositing governing tokens. 
3. `InstructionExecutionStatus` - status to support failed instructions in future versions and prevent Proposals permanently staying in `Succeeded` or `Executing` state.
4. `InstructionExecutionFlags` - execution flags to support ordered and transactional instructions in future versions.
5. `proposal_cool_off_time`- time period to allow proposal cancellation after voting. 
3. Move …
> Governance: future proofing for v2

- stake-pool/cli/src/main.rs
- stake-pool/program/src/big_vec.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/initialize.rs
- stake-pool/program/tests/set_preferred.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
Stake pools can't support more than 200 validators at the moment because of memory and compute budget limitations during serialization and deserialization.
Update the on-chain serde to support up to 4k validators!  Since the instructions that involve iterating through the whole pool can't do too much else, this also introduces a new `CleanupRemovedValidatorEntries` instruction, which just cleans up any validator that's marked `ReadyForRemoval`.  There's no requirement to perform this except when validator entries are ready to be removed, and it's permissionless.  Likely, the stake pool staker will call this whenever needed to free up space in their validator list.
Additionally, there's some unsafe Rust used for very specific reasons:
* casting [u8] slices to ValidatorStakeInfo entries …
> stake-pool: Optimizations for 4k validators

- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_set_governance_config.rs
- governance/program/src/state/governance.rs
- governance/program/tests/process_create_account_governance.rs
- governance/program/tests/process_execute_instruction.rs
- governance/program/tests/process_insert_instruction.rs
- governance/program/tests/process_remove_instruction.rs
- governance/program/tests/process_set_governance_config.rs
- governance/program/tests/program_test/mod.rs
- governance/program/tests/program_test/tools.rs
- `SetGovernanceConfig` - Instruction allows to update `GovernanceConfig`. The instruction must be signed by `Governance` PDA and hence can only be executed as an instruction of a `Proposal` for the `Governance` the `Proposal` belongs to. It allows self governance and tweaking of the `GovernanceConfig` parameters for a given community. For example it can be used to adjust vote threshold which makes sense for the given community engagement.
> Governance: SetGovernanceConfig instruction

- stake-pool/program/src/processor.rs
The downstream build fails on stake pools with the error: "Program failed to complete: Access violation in stack frame 1 at address 0x200001f50 of size 8 by instruction #13025"
https://buildkite.com/solana-labs/solana/builds/49577#463986f1-6a44-4af0-bf07-ecdf147564c0 for an example build.
Not too sure what's going on with the compiler, but since that instruction had to do with `u64` adds around the update validator balance part, I changed the `checked_add` to `saturating_add`, which seems to keep the memory in-line and avoid the problem during the downstream build.
> stake-pool: Convert `checked_add` to `saturating_add` to fix downstream build

- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_create_account_governance.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/processor/process_relinquish_vote.rs
- governance/program/src/processor/process_set_governance_config.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_create_account_governance.rs
- governance/program/tests/process_create_program_governance.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/process_insert_instruction.rs
- governance/program/tests/process_set_governance_config.rs
- governance/program/tests/program_test/mod.rs
This is a maintenance change to improve program quality without any feature changes.
While implementing `SetGovernanceConfig` instruction I realised it was too difficult. I had to add code and tests for attack vectors which shouldn't have even existed. The reason for that was `GovernanceConfig` struct which was being changed but at the same time had immutable data on it: `realm` and `governed_account`. This change moves these fields from `GovernanceConfig` to direct `Governance` account fields and hence protects their immutability without any extra code.
> Governance: Move realm and goverend_account from config to direct field

- stake-pool/program/src/processor.rs
While doing some stake-o-matic testing, there's a step to withdraw and split any extra stake, and there was a missing check in the stake pool program for the delegation amount, along with the lamports amount.
Add a check during add / remove validator to make sure that the delegated amount is the exact desired amount.
> stake-pool: Add check for delegation stake in add / remove

- stake-pool/program/tests/huge_pool.rs
Stake-pool's `huge_test` includes the test `update` that attempts to process a very large transaction that fails the new compute budget tx-wide limit.  The test's transaction is not a practical use case and was done because it was easy to throw all the instructions into one transaction.  Break the test's transaction into multiple.
> Breakup stake-pool update test transactions

- token-lending/program/tests/init_lending_market.rs
- token/js/package-lock.json
- token/js/package.json
The token js CI is tripping up on flow, due to issues in upstream projects.
Use `flow check-contents` to restrict the checks to just token.
And also, bump the compute budget on failing lending test.
> token-js: Use `flow check-contents` to not trip on others' issues

- token/program/src/processor.rs
On `set_authority` for a token (holding) account, the delegate is persisted.
Clear that delegate!
Fixes #2078
> token: Drop delegate on ownership transfer

- token-lending/program/tests/borrow_obligation_liquidity.rs
- token-lending/program/tests/deposit_reserve_liquidity.rs
- token-lending/program/tests/liquidate_obligation.rs
- token-lending/program/tests/obligation_end_to_end.rs
- token-lending/program/tests/redeem_reserve_collateral.rs
- token-lending/program/tests/refresh_obligation.rs
- token-lending/program/tests/refresh_reserve.rs
- token-lending/program/tests/repay_obligation_liquidity.rs
- token-lending/program/tests/withdraw_obligation_collateral.rs
The Solana compute cap is being applied transaction-wide instead of per instruction.  Bump the test's compute caps to compensate
> Bump token-lending test caps

- libraries/math/src/approximations.rs
- stake-pool/program/src/stake_program.rs
- token-swap/program/src/curve/calculator.rs
- token-swap/program/src/curve/constant_price.rs
- token-swap/program/src/curve/constant_product.rs
- token-swap/program/src/curve/stable.rs
This patch series allows `cargo doc` to run without emitting any warnings. It changes bare URLs to "autolinks", surrounded by angle brackets, and it changes some "account references" lists to put their bracketed requirements (sign/write) in code spans (as with other such lists in this repo) so they won't be interpreted as markdown links.
> Eliminate doc warnings

- stake-pool/cli/src/main.rs
We had some user feedback, issues with identifying information about the pool, including accounts used / required, and the pool fee account.
* Add more output for `list` command, `-v` gives more info
* Default to the manager's associated token account when creating a pool
New output for list:
```
Stake Pool: tppRnkEWouTxXoLVXDPMJ6V5rTYWYaQ7qWsJ3E6YfkA
Pool Token Mint: tpmg27ULGHUnCFVaDhiTrPErCh7kg9JGcN2jVTkhpcN
Fee: none
Reserve Account: tprLWb21rTvUTX7CSTNgfxz2jgwooNayoN1ken2F7H4    Available Balance: ◎22000.000000000
Vote Account: AYHQTpjHsCEaSboz2vL5tUKiP8t4a2khgLp3TASXVvP8      Balance: ◎0.000000000   Last Update Epoch: 210
Total Pool Stake: ◎22000.000000000
Total Pool Tokens: 22000
Current Number of Validators: 1
Max Number of Validators: 4000
```
New output for list -v:
```
Stake …
```
> stake-pool-cli: Integrate user feedback

- token/cli/src/config.rs
- token/cli/src/main.rs
- token/js/cli/token-test.js
- token/js/client/token.js
- token/js/module.flow.js
- token/js/test/token.test.js
- token/program/src/error.rs
- token/program/src/instruction.rs
- token/program/src/processor.rs
Fixes #2077 
If you `system_instruction::transfer` lamports into a wrapped SOL token account, the wrapped SOL account will not register its new balance.
Add `SyncNative` instruction to update the account's `amount` based on the underlying account's lamports.
cc @armaniferrante
> token: Add SyncNative instruction (program, CLI, JS)

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/update_validator_list_balance.rs
People can burn pool tokens on their own, but the pool doesn't take those into account when figuring the fair value of pool tokens.
During the update phase, also update the pool token supply.
> stake-pool: Update pool token supply on update, in case of burns

- Cargo.lock
- governance/program/Cargo.toml
- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_execute_instruction.rs
- governance/program/src/processor/process_flag_instruction_error.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/proposal_instruction.rs
- governance/program/tests/process_flag_instruction_error.rs
- governance/program/tests/program_test/mod.rs
- `FlagInstructionError` - instruction allows proposal owner (or delegate) to manually flag `ProposalInstruction` and its parent `Proposal` with execution error status. It's required to prevent ghost proposals which could stay indefinitely in `Succeeded` or `Executing` state when one of their instructions couldn't be executed. 
The flagged error status is information only and doesn't prevent the instruction to be attempted to be executed again when the error condition changes, for example missing governance authority is granted.
Ideally we shouldn't need this instruction but currently there is no way to catch errors from CPI calls and the `Governance` program has no way to know an instruction failed and flag it automatically. If such an option is implemented at some point in the future …
> Governance:  FlagInstructionError instruction

- Cargo.lock
- governance/program/Cargo.toml
- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/realm.rs
- governance/program/src/state/token_owner_record.rs
- governance/program/tests/process_create_proposal.rs
- governance/program/tests/program_test/mod.rs
- This change introduces `min_council_tokens_to_create_proposal` and `min_community_tokens_to_create_proposal` instead of a single `min_tokens_to_create_proposal` threshold to make it possible to use different thresholds for council and community tokens. A single threshold `min_tokens_to_create_proposal` is not sufficient for scenarios when the `Council` and `Community` mints supplies are significantly different (the most common case) and have different decimal places.
- This change also makes it possible for community token holders to create proposals voted on by the council and council token holders can now create proposals voted on by the community. 
This restriction existed in previous versions but it was a side effect of the implementation and not by design.
> Governance: Use separate thresholds to create proposals for council and community tokens

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/config.rs
- token/cli/src/main.rs
- token/cli/src/output.rs
- token/cli/src/sort.rs
As more apps integrate SPL tokens alongside SOL, there is demand for `spl-token-cli` json support that parallels `solana-cli`. This PR adds that functionality.
There is one existing weirdness around `spl-token gc`, since that method may submit multiple transactions. Currently, `spl-token gc --output json` prints multiple json Signature objects (or Signer objects, if `--sign-only`), instead of one nice json array of those objects. Implementing this properly requires an upstream change in the form of `solana_cli_output::return_signers_with_config()` that returns `CliSignOnlyData` instead of strings (or a bunch of duplication). That will follow after the upstream work is implemented. In the meantime, this changeset should meet current needs.
Closes #2128
cc @ryoqun
> token-cli: support json output

- docs/src/stake-pool.md
The stake pool docs are pretty out of date, and caused some confusion to users, so let's clarify them!
* add set-preferred-validator instruction
* update all output to how it looks
* remove all mentions of the word "derivative"
* explain practically how to add a validator to the stake pool
* explain why funds are safe in the system
@c3pko could you take a look at this? All comments are very welcome
> stake-pool: Update docs with new instructions and output

- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/program_test/mod.rs
Capture  `vote_threshold_percentage` on voted on proposal to correctly display historical vote results.
`vote_threshold_percentage` can be changed over time through governance and hence we have to store the value used to resolve proposal vote.
> Governance: Capture vote_threshold_percentage on voted on proposal

- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/program_test/mod.rs
Use Option for storing `vote_threshold_percentage` on proposal instead of None enum value. 
The change is necessary because 
- There is no native `None` value for `VoteThresholdPercentage` enum
- It broke backward compatibility with existing test `Governances`
> Governance: Use option for proposal VoteThresholdPercentage

- Cargo.lock
- governance/program/Cargo.toml
- governance/program/src/instruction.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_create_realm.rs
- governance/program/src/processor/process_finalize_vote.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/realm.rs
- governance/program/src/state/token_owner_record.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_create_proposal.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/program_test/mod.rs
Introduce `RealmConfig` to capture realm level configuration and make it possible to change it through governance in future versions. The `RealmConfig` contains:
-  `council_mint` - council mint was moved to the config to make it possible to change it
-   `community_mint_max_vote_weight_source` - defines how the max vote weight is calculated for community tokens
- `custodian` - none security critical authority with realm maintenance powers 
A following PR would implement `SetRealmConfig` instruction which would be used to change `RealmConfig`. It would have to be signed by realm authority and could be voted on through proposals
> Governance: Realm config

- stake-pool/cli/src/main.rs
Fixes #2158
The help message for decrease-validator-stake is wrong, since it accepts SOL, not lamports.
Fix it!
> stake-pool-cli: Fixup help message for decrease-validator-stake

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/withdraw.rs
If a stake pool has a withdraw fee, even the fee account will be assessed a fee, making it very annoying for the manager to get SOL out of the pool.
Don't assess the withdrawal fee for the fee account.
cc @jon-chuang what do you think?
> stake-pool: Don't assess withdrawal fee from fee account

- token-lending/js/src/instructions/depositObligationCollateral.ts
- token-lending/program/src/instruction.rs
- token-lending/program/src/processor.rs
The `DepositObligationCollateral` instruction has a derived lending market authority that isn't needed for validation or for token transfers. This removes the account from the instruction and JS client.
> lending: remove unnecessary PDA

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/deposit_sol.rs
- stake-pool/program/tests/set_deposit_authority.rs
- stake-pool/program/tests/set_deposit_fee.rs
- stake-pool/program/tests/set_fee.rs
- stake-pool/program/tests/set_referral_fee.rs
- stake-pool/program/tests/set_withdrawal_fee.rs
A few cleanup bits from the great work done in #2141
Program:
* fix checking sol deposit auth <-- this one's important
* add 0 pool token check for user, so that they don't deposit into the pool and get nothing back!
* avoid using `+` in favor of `saturating_add` for one check in particular (which may even be optimized away by the compiler)
* remove unused instruction creators
CLI:
* unify `set-sol-deposit-authority` and `set-stake-deposit-authority` into `set-deposit-authority`
* unify `set-sol-referral-fee`and `set-stake-referral-fee` into `set-referral-fee`
cc @jon-chuang @billythedummy
> stake-pool: Address a few points post-liquid staking

- Anchor.toml
As requested by @SebastianBor.
Adds an Anchor.toml so that the governance program can be built and verified via the Anchor CLI. Both the write-buffer and the program can be verified.
Usage:
* [Install](https://project-serum.github.io/anchor/getting-started/installation.html#install-anchor) anchor-cli v0.13.2 or later.
* Build: `anchor build -p spl_governance --verifiable` in the root workspace directory.
* Deploy: `solana program write-buffer target/verifiable/spl_governance.so`
* Verify: `anchor verify -p spl_governance <program-id>`
> Add Anchor.toml for source verification

- token/program/src/instruction.rs
- token/program/src/lib.rs
- token/program/src/processor.rs
Providing the Rent sysvar when creating Token accounts is now unnecessary, and is a detriment when composing new programs over SPL Token account initialization as it requires the new program to also unnecessarily require the Rent sysvar as an account.
Add new variants of the initialization instructions that do not require the Rent sysvar.
> token: Add InitializeMint2/InitializeMultisig2/InitializeAccount3 instructions

- token/js/module.flow.js
This PR intention is to add the `createTransferCheckedInstruction` static method from the Token class in the flow-typed definitions for users still using it.
> chore(token): add createTransferCheckedInstruction to flow-typed

- stake-pool/program/src/error.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/set_preferred.rs
closes #2262
- denies setting validator to validators with status `ReadyForRemoval`
- add test for this in `set_preferred`
@jon-chuang
> fix stake-pool: preferred validator can be set to validator not part of the pool

- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/withdraw.rs
Fixes: https://github.com/solana-labs/solana-program-library/issues/2261 https://github.com/solana-labs/solana-program-library/issues/2264
> stake-pool: skip manager fee if invalid account, check new manager fee owned by `spl_token`

- stake-pool/program/src/instruction.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
If a stake pool wants to set up a non `spl_token_program::id` pool, they can do so, but their users will not be minting SPL tokens, (unless via a complex scheme where the alternative token program mints spl tokens in exchange for its tokens):
```rust
// on initialize:
if pool_mint_info.owner != token_program_info.key {
return Err(ProgramError::IncorrectProgramId);
}
```
In my mind, there is nothing strictly wrong with exposing the extra flexibility of a parametrised token program. It is a little redundant though.
If still wanting to make it hard coded, I don't think this is an urgent issue per se. The current logic works, and is probably correct, and tearing it out could introduce errors, for little benefit.
The purpose of this PR is to use a fully non hard-coded token program id
Fixes: …
> Use stake pool's declared token ID rather than hard-coded

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/set_preferred.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_remove.rs
If the stake pool gives over the validator stake account to the staker,
they may keep it and make it impossible to re-add that validator in the
future.
Split the whole amount into a new stake account on removal.
> stake-pool: Split from validator stake account during removal

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/bench.rs
- token/cli/src/config.rs
- token/cli/src/main.rs
- token/cli/src/rpc_client_utils.rs
Add a `spl-token bench` subcommand with some basic token benchmarking facilities.
```
SUBCOMMANDS:
close-accounts     Close multiple token accounts used for benchmarking
create-accounts    Create multiple token accounts for benchmarking
deposit-into       Deposit tokens into multiple accounts
withdraw-from      Withdraw tokens from multiple accounts
```
> spl-token-cli: Add bench subcommand

- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/increase.rs
It's expensive to commit 1 SOL + rent exemption for each validator to add to the pool, creating a high barrier for potential pool operators.
Even in the worst case of a poorly performing validator with a 1% commission, ~0.001 SOL will earn rewards, so let's bring this number down to 0.001 SOL!
> stake-pool: Reduce minimum stake per validator to 0.001 SOL

- ci/rust-version.sh
The monorepo master is at Rust version 1.54 and nightly 2021-08-02, so let's match that.  Note that the monorepo v1.7 is still on 1.52.1, but since solana-program-library is already at 1.53, we're best off matching master.
Bump the version in CI.
> Bump Rust to match monorepo (1.54 and 2021-08-02 nightly)

- Cargo.lock
- stake-pool/cli/Cargo.toml
- stake-pool/cli/src/main.rs
The added `sol_depositor` flag was never added as a flag in the command line parsing, causing sol deposits to fail for a private pool.
Simplify the flags and combine `sol-depositor` with `depositor`. Also remove unneeded signature from sol deposit function.
> stake-pool-cli: Fix sol deposit for private pool

- governance/test-sdk/Cargo.toml
The `cargo-test-bpf` binary looks for the presence of a `cdylib` crate type to determine whether to run tests with the SBF toolchain (https://github.com/solana-labs/solana/blob/7aa5f6b8332516347282d0e36ceb8ae020c02ddb/sdk/cargo-test-bpf/src/main.rs#L192). Crates which are not BPF programs could therefore be built for BPF which doesn't support some dependency crates.
- Removed crate-type from the governance test crate
> Remove cdylib crate type attribute from non programs

- stake-pool/cli/src/main.rs
for the `remove-validator` subcommand, `instructions` vec was being overwritten to a single element vec containing the stake pool instruction. If a new stake account needs to be created, it will throw:
```
thread 'main' panicked at 'Transaction::sign failed with error KeypairPubkeyMismatch', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-sdk-1.7.7/src/transaction.rs:258:13
```
since the new stake account's keypair is in signers but the create stake account instruction is not in instructions
> stake-pool: cli fix remove-vsa bug

- docs/src/token-swap.md
Outdated docs still referred to JS files that have been removed or replaced already.
> (docs) Fix broken links

- examples/c/src/logging/logging.c
Accounts are serialized into random memory
Fixes issue brought up here: https://github.com/solana-labs/solana-program-library/pull/823
> fix logging example

- stake-pool/cli/src/main.rs
@joncinque 
if the active stake balance is lower than MIN_STAKE_BALANCE, then we get an "attempt to subtract with overflow" exception
````
spl-stake-pool withdraw-stake --verbose --vote-account F7LN71sYZGLB6WpDmNT6LP25z7a3HezLStDM1y1JJfdf 5mJ3EhrQ1ZBwDW7AFodQaEzBSw1wG89mvTpAnc81bngK 0.01 --config /Users/alexanderray/Documents/Development/mfactory/customers/solana/projects/stake-pool/playground/config-with-delegator-wallet.yaml
Signature: 5PMzHKbZAHTMTZFHS1dRjLpbHhsnMh3Bxg3RuRBf8fMqK9QGNB12ANWEJR6FrVTV1DQ3nyyfNaZuxbxKvwi5Jqk9
Signature: 2s33p7hRyA2ta34iEngcxGoGJtrL5oiGaHmBR2CP81yCNczDEg7gZweeQZpYBsrdN3HYRQksyse1KF7LwoWMzHP3
thread 'main' panicked at 'attempt to subtract with overflow', stake-pool/cli/src/main.rs:1191:44
````
> - fix "attempt to subtract with overflow" issue

- Cargo.lock
- stake-pool/cli/Cargo.toml
- stake-pool/cli/src/main.rs
There's a new minimum balance for stake pool accounts, but the CLI used its own hard-coded value, so it was out of step with the program, causing strange failures.
Corporate software engineering 101: Hardcode values in one place only!
> stake-pool-cli: Update minimum balance to be correct

- stake-pool/program/tests/vsa_remove.rs
`Unkown` is not how you spell `Unknown`, but a stake pool test relies on that misspelling, making it impossible to update the spelling in the monorepo.
use a `matches!` check in the test instead
> stake-pool: Use `matches!` to allow for fix in underlying error

- associated-token-account/program/src/processor.rs
The latest ATA release, v1.0.3, is not affected.  Introduced by #2325
> ATA: Avoid hard coding spl_token id

- stake-pool/cli/Cargo.toml
- stake-pool/cli/src/main.rs
During the renaming of "deposit authority" to "funding authority", one of the CLI flags was missed, using an incorrect name, causing the CLI command to always revert the relevant authority to the default value.
Use the right flag name, and change the authority variable name to be consistent.
> stake-pool-cli: Fix funding authority flag name

- docs/src/stake-pool.md
- stake-pool/cli/src/main.rs
There are some weird usability issues in the stake pool CLI:
* the withdraw authority for the stake deposited into the pool is specified using the `--staker` flag, which explicitly says it's for the stake pool staker.  that stinks.
* the recipient for the sol on `withdraw-sol` has a default, which also stinks
* Add a `--withdraw-authority` flag on `deposit-stake`, defaulting to the default signer
* Make the SOL recipient required as the second argument (after the stake pool), following how `solana transfer` does things
> stake-pool-cli: Improve deposit and withdraw UX

- docs/src/stake-pool.md
- stake-pool/cli/README.md
- stake-pool/cli/scripts/deposit-withdraw.sh
- stake-pool/cli/scripts/setup-local.sh
- stake-pool/cli/scripts/setup-stake-pool.sh
- stake-pool/cli/src/main.rs
People want private pools, but don't know how to create them.
Add a section in the docs about how to create a private pool, and also update `setup-stake-pool.sh` to allow a pool creator to easily see all of the available fields and customize them in one place.
> stake-pool-cli: Add more docs around scripts

- token/cli/src/main.rs
Empty associated accounts will only be closed in case the new flag del_associated_accounts is set. Otherwise behaviour is as before.
This can be used tto reclaim SOL that was sent to the associated accounts e.g. for rent exemption
Useage:
spl-token gc --del_associated_accounts
> Allow GC to close empty associated accounts

- libraries/math/tests/instruction_count.rs
This increase is caused by upgrade of compiler builtins
> Increase compute max units for sqrt_u128_max test

- token/js/cli/main.js
- token/js/cli/token-test.js
There's no JS test disabling a mint authority in the token program, so it might not seem possible.
Add a test, as a start.
> token-js: Add test for disabling mint authority

- stake-pool/cli/src/main.rs
We're showing the stake pool address instead of the validator vote account address in the "details" part of the `list` output.
Show the validator vote account address.
> stake-pool-cli: Fix vote account address in details

- governance/chat/program/tests/program_test/mod.rs
- governance/program/tests/program_test/mod.rs
- governance/test-sdk/src/lib.rs
`solana_sdk::process_instruction` is getting refactored in `solana_program_runtime` in https://github.com/solana-labs/solana/pull/21180, but the governance program explicitly uses parts of `solana_sdk::process_instruction`
Redo the testing bits to remove the dependency, with no change to functionality.
cc @SebastianBor @Lichtso
> governance: Remove dependency on ProcessInstructionWithContext

- patch.crates-io.sh
To fix broken "downstream-projects" CI step in the mono repo after #2576 was merged.
> Adds "solana-version" to "patch.crates-io.sh"

- README.md
Commands I had to run to get `./coverage.sh` to complete on Intel MacOS
> (Docs) Update Coverage instructions with MacOS commands

- Cargo.lock
After removing the themis directory, lots of Cargo.lock elements got blasted as well.
Update Cargo.lock based on Rust 1.54.0. We'll have to follow the monorepo and update the Rust version on this soon.
> Update Cargo.lock post themis removal

- stake-pool/cli/src/main.rs
People want to deposit from ledgers, but the stake pool cli input parsers are too restrictive.
Relax the input parsers from `is_keypair_or_ask_keyword` to `is_valid_signer` for the important signers.
> stake-pool-cli: Update input parser to work with ledgers

- token-lending/program/src/processor.rs
- token-lending/program/src/pyth.rs
Pyth's [best practices guide](https://docs.pyth.network/consumers/best-practices) encourages checking the price's status to make sure it's valid.
> lending: validate pyth price trading status

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/initialize.rs
- stake-pool/py/stake_pool/actions.py
- stake-pool/py/stake_pool/instructions.py
- stake-pool/py/tests/conftest.py
- stake-pool/py/tests/test_deposit_withdraw_stake.py
If a pool creator puts too many lamports in the reserve account on creation, those are essentially lost.  This behavior is unclear.
Credit the additional reserve lamports as pool tokens on init.
Big thanks to @soteria-bc / Soteria for reporting this issue!
> stake-pool: Mint extra reserve lamports as pool tokens on init

- token/program-2022/src/extension.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/processor.rs
- token/program-2022/src/state.rs
- token/program-2022/tests/action.rs
- token/program-2022/tests/assert_instruction_count.rs
It isn't possible to assess fees on token transfers.
Add new account types for Mints / Accounts with transfer fees, along with an over-type to handle any type, see `UberMint` for more info.
Add instructions for initializing mints with transfer fees, setting fees, transferring tokens, and transferring withheld tokens.
> token-2022: Add transfer fee types and instructions

- stake-pool/cli/src/main.rs
- stake-pool/cli/src/output.rs
Next epoch's fees aren't displayed through the CLI, even in verbose mode, and the next stake withdrawal fee is improperly mapped.  This was discovered by the JPool team while modifying fees, thanks @AlexanderRay !
Fix the mapping, and print out next epoch's fees too.
> stake-pool-cli: Add next fees in verbose mode, fix mapping

- libraries/math/tests/instruction_count.rs
BPF syscalls base costs are being updated, nudge these tests up to match
> Bump instruction count limit

- docs/src/stake-pool/overview.md
It's not clear that epoch fees in stake pools are charged on top of normal validator commissions.
Make it clearer with an example.
> stake-pool-docs: Clarify that epoch fee is on top of commissions

- token/program/tests/assert_instruction_count.rs
bpf-tools v1.21 changed implementation of memory operations, which results in larger instruction numbers for the same operations. This PR adjusts the compute limits in tests affected by the changes in bpf-tools.
> Increase compute max units due to changes in handling of memory ops

- governance/test-sdk/src/lib.rs
- name-service/program/tests/functional.rs
- record/program/tests/functional.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/deposit_sol.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/initialize.rs
- stake-pool/program/tests/set_funding_authority.rs
- stake-pool/program/tests/set_manager.rs
- stake-pool/program/tests/set_staker.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
Soon, `BanksClient` will only return `BanksClientError`, but many tests in SPL rely on `TransportError` being returned.
Be sneaky, and add a currently unnecessary `into()` conversion, which will be necessary when the return type changes.  This way, we never break downstream builds.
> Update tests to prepare for `BanksClientError`

- coverage.sh
Hi,
I have grcov in version 0.8.4 and current version check causes problem here when running coverage.sh
This change fixes version check for me, but in the future this check should be redesigned.
Best regards,
Michal
> fix grcov dependency checking

- Cargo.lock
- governance/program/Cargo.toml
- governance/program/src/addins/voter_weight.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_create_token_owner_record.rs
- governance/program/src/processor/process_set_realm_config.rs
- governance/program/src/processor/process_update_program_metadata.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/mod.rs
- governance/program/src/state/program_metadata.rs
- governance/program/tests/process_update_program_metadata.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
`spl-governance` is deployed using multiple instances and `governnace-ui` needs a to know what version of the program it communicates with in case the api is different between versions. 
`ProgramMetadata` account was introduced to store the given instance version. The version is stored using `UpdatePorgramMetadata` instruction which dumps the program's crate version into the account and also outputs into the logs to make it possible to query the version using Tx simulation
> Governance: Program metadata

- Cargo.lock
- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_create_native_treasury.rs
- governance/program/src/processor/process_execute_instruction.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/mod.rs
- governance/program/src/state/native_treasury.rs
- governance/program/tests/process_create_native_treasury.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
- governance/test-sdk/src/cookies.rs
- governance/test-sdk/src/lib.rs
- governance/tools/src/account.rs
At present `spl-governance` supports only `spl-token ` based treasury accounts and it's not possible to have a native SOL treasury. Only `wSOL` is supported which is both confusing and inconvenient for users.
Its also not possible to pay for execution of proposal instructions using DAO treasury and personal wallets a currently used. 
Create a `NativeTreasury` account which is a PDA without any data and make it possible to associate it with `Governance` accounts. This way any proposal instruction executed for the governance can use the funds from the associated SOL treasury account or in the simple case the instruction can be just a native SOL transfer.
> Governance: Native Treasuries

- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/extension.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/pod.rs
- token/program-2022/src/state.rs
Extensions need to be read / written in a way that's simple for the program processor and clients.
Implement a `Pack`-like interface for the TLV entries using bytemuck and Pod types for extensions.
> token: Extension state packing

- update-solana-dependencies.sh
Bump deps to 1.10.0 and tweak `update-solana-dependencies.sh` to work on osx.
> Fix update-solana-dependencies.sh to work on osx

- .github/workflows/pull-request.yml
- ci/do-audit.sh
We should know if SPL is using insecure crates.
Just like in the monorepo's https://github.com/solana-labs/solana/blob/master/ci/do-audit.sh, run `cargo audit` on every pull request.  Thankfully, SPL has a smaller number of dependencies, which makes it easier to manage.  The `ignore`s here are all from the monorepo, except for the `memmap` one, which comes from `honggfuzz`, only used in testing.
Inspired by #2703 -- @silas-x, what do you think of this?  I had a hard time finding info about some of the extra flags used for `cargo audit` in your PR, so if there's anything that you think is missing in this, please let me know!
> CI: Add cargo audit, just like in the monorepo

- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
Merging the zk-token program into SPL Token will require a token extension that does all the things:
* additional account/mint data
* additional token instructions
* extension instruction processor
This PR attempts to carve out this path, using a simple "Todo" instruction.  Once accepted, follow-up patches will bring in the full zk-token program into this framework
cc: https://github.com/solana-labs/spl-zk-token/issues/91
> Add Confidential Transfer Extension boilerplate

- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/transfer_fee.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
Every extension documents its account type, so Mint/Account prefixes aren't really necessary. (Also, I can envision an extension that may have the same data structure for both Mint and Account implementations.)
This PR removes Mint and Account prefixes from TransferFee extensions.
`MintCloseAuthority` is kept as-is, since token Accounts already have close-authorities in their base state.
> Strip extension account-type prefixes

- stake-pool/program/tests/helpers/mod.rs
Rent-exempt requirement for accounts is coming down the pipe: solana-labs/solana#22292
The stake-pool helper `create_vote` creates a validator identity account that is rent-paying for no particular reason.
> Fix up helper to create rent-exempt accounts

- associated-token-account/program/tests/process_create_associated_token_account.rs
- name-service/program/tests/functional.rs
Rent-exempt requirement for accounts is coming down the pipe: https://github.com/solana-labs/solana/pull/22292
Several tests in this repository create rent-paying accounts. Since these account balances appear to be arbitrary, this PR fixes those tests up to use rent-exempt amounts.
@mvines , any concerns here? I didn't see any fundamental reason for these rent-paying accounts.
There are also some stake-pool tests that are failing. Will be addressed in a separate PR.
> Fixup tests to use rent-exempt accounts

- token/cli/src/bench.rs
Blocked on https://github.com/solana-labs/solana/pull/19733 shipping in the next v1.7 release
> spl-token-cli bench: Display RPC transport stats

- docs/src/stake-pool.md
- docs/src/stake-pool/fees.md
- docs/src/stake-pool/overview.md
- docs/src/stake-pool/quickstart.md
- stake-pool/cli/src/main.rs
People can shoot themselves in the foot by creating pools with no fees.
Only allow creating a pool with zero fees given a `--yolo` flag, and add some best practices around fees.
@bennofs can you take a look specifically at the "Best Practices" section in the Fees page?  I only added absolute minimums there, so we may want to more forcefully suggest higher numbers.  Or you may have calculated some totally different values!
> stake-pool-cli: Add best practices for fees, prevent zero fees

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/tools
Rewrite of the zk-token program as token 2022 extension.
TODO: Only a couple instructions have been implemented so far, to test out the new extension framework.  PRing this early to share what the code of a reasonably complex extension currently looks like
cc: https://github.com/solana-labs/spl-zk-token/issues/91
> Confidential transfer extension

- docs/src/name-service.md
- farms/README.md
Fixed a small typo that refers to a user as a "his" vs. "their" which is used everywhere else in the repo
> fix small typo

- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/mint_close_authority.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/transfer_fee.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/pod.rs
- token/program-2022/src/processor.rs
Since the token program does not know anything about the buffers passed in before they're initialized, we can run into all sorts of strange situations, mainly arising from initializing mixed types, ie initializing a mint extension on a buffer that actually contains an account extension already.
Add more checks on initializing extensions and unpacking the buffer to make sure that it's correct.  This introduces a mapping from ExtensionType -> AccountType, which was not possible before with just the trait.
In later work, we'll also need to introduce a mapping ExtensionType -> ExtensionType for mint type to account type.
Note that this will mainly save us if we ever allow for account extensions to be initialized on their own.
> token: Add checks for mixed type initialization

- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/processor.rs
Token accounts with confidential transfers enabled may not be closed until their confidential side is also closed.  Plumb this hook into the normal `CloseAccount` instruction to motivate more discussion around the current extension API
> Allow the confidential transfer extension to block `CloseAccount`

- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/extension/transfer_fee/mod.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
It's cleaner to refactor all extension-related instructions into their own separate module.
Move all of the transfer fee instructions and processor into new modules.
My main questions here:
* does `TransferCheckedWithFee` belong in the transfer fee module or in the top-level?  I went with putting it in the module
* the instruction packing / unpacking was already done manually, so I opted to not do it with `Pod`s
The rest is boiler-plate, no logic changes
> token: Refactor transfer fee instructions + processor

- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/processor.rs
- token/program-2022/src/tools
This brings over the bulk of the zk-token program.  The removal of the omnibus account and the separate zk-token PDA accounts nicely simplified parts of the original code. 
Follow up PRs will include:
* Resolving the TODO around account reallocation in the `ConfigureAccount` instruction
* Bringing over the zk-token unit tests, and likely fixing bugs as a result
cc: #https://github.com/solana-labs/spl-zk-token/issues/91
> Port the remainder of the zk-token program to the ConfidentialTransfer extension

- Cargo.lock
- associated-token-account/program/Cargo.toml
- associated-token-account/program/tests/process_create_associated_token_account.rs
Very soon we'll want to update the ATA program to create extension-enabled accounts.
Update spl-token dependency to spl-token-2022 to pull in necessary apis, like InitializeAccount and upcoming GetAccountDataSize.
> Use spl-token-2022 in ATA program

- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
The ATA program is going to need to know the minimum length of new accounts based on required extensions. This PR plumbs in the GetAccountDataSize instruction for ATA to CPI.
Couple notes:
- `get_account_extensions()` doesn't do any duplicate checking of either input Mint extensions or output Account extensions at the moment. We don't intend to support extensions that can exist in a Mint as duplicate, and currently none of the Mint extensions on the horizon have overlapping Account extension requirements, so I chose to make this helper as simple as possible. But we can update later if either of those predicates turns out to be false.
- the test for `process_get_account_data_size` is not complete, but I think the extension cases will be easier to write once InitializeMint is implemented
> Add GetAccountDataSize implementation

- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/initialize_mint.rs
- token/program-2022/tests/program_test.rs
- token/rust/Cargo.toml
- token/rust/src/lib.rs
- token/rust/src/token.rs
- token/rust/tests/program-test.rs
We want to use the rust client to simplify the 2022 tests.
Use it!  A few notes:
* while adding extension support, it borked on the base case of no extensions, so I fixed that up
* the `no-entrypoint` feature took me about an hour of debugging trying to figure out why the program was doing nothing
> token-2022: Basic integration with rust client

- token/program-2022/src/extension/mod.rs
- token/program-2022/src/processor.rs
InitializeAccount variations should initialize extensions required by the mint.
This PR adds that support.
Base and native mint cases are covered by existing test suite. The extended-mint cases still need testing, but I wanted to PR this now because: (a) that testing will be a lot easier when InitializeMint implementations for extensions are done; and (b) I wanted to see what you think of `StateWithExtensionsMut::init_extension_from_type()` and the error-type change in `StateWithExtensionsMut::unpack_uninitialized()` now. Thoughts?
> token-2022: Support extensions in InitializeAccount variations

- governance/program/tests/process_create_realm.rs
- governance/test-sdk/src/lib.rs
- governance/tools/src/account.rs
Any `PDA` account can be created by sending `lamports` to it and then it can't be initialised by program using `create_account` instruction any longer. 
Use `allocate/assign` to initialise PDA when it already exists
> Governance: Account creation workaround for existing PDA

- token/program-2022/tests/assert_instruction_count.rs
The monorepo downstream job is failing because of compute unit usage, most likely due to the new logic added to token-2022.
Bump out the instruction counts.
> token: Bump compute units in tests

- governance/program/tests/process_create_realm.rs
PDA needs rent exempt number of `lamports` to be be created
> Governance: fix test_create_realm_for_existing_pda

- token/program-2022/tests/assert_instruction_count.rs
BPF toolchain was bumped again in 1.9.3. Tip of 1.9 wants the more CUs for downstream builds
> Bump token-2022 test CUs again for tip of 1.9

- token/program-2022/src/error.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/initialize_mint.rs
- token/program-2022/tests/program_test.rs
- token/rust/src/token.rs
- token/rust/tests/program-test.rs
People want to initialize mints with extensions
Add that ability.  A few notes from this PR:
* introduces `StateWithExtensionsOwned`, used in testing and client situations, where the TLV data is owned instead of borrowed.  There's some copy-pasta because vec uses `split_off` and slice uses `split_at`
* can initialize a mint close authority
* initialize mint supports extensions
* `ExtensionInitializationParams` for cleaner init!
Edit: Reduced the scope of this to just initialization and tests. The actual support for the mint close authority will come in a separate PR
> token: Add extension support in mint init

- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/mint_close_authority.rs
- token/rust/src/token.rs
Builds on #2744 , only need to look at 4904516a82545afb7900b5c5b741e5834ab87ef8
The mint close authority must be properly supported in `set_authority` and `close_account`.
Add the support.
Also, update `validate_owner` to accept the data length from the outside, since there were still double-borrow issues.  Now, we pull out the data length right at the beginning, and use that later to see if the authority account is a multisig.  Thankfully, if the authority is a multisig, then it *can't* be used for anything else in processing logic, meaning all double-borrows are avoided.
> token-2022: Add mint close authority support everywhere

- token-lending/cli/src/main.rs
#2759 but for the token-lending cli
`get_fee_for_message` fails because the message is not signed, so there's no blockhash in the message yet.
####Solution
Sign the messages before getting the fee
> token-lending-cli: Sign before checking fee for message

- token/program/src/processor.rs
- token/program/tests/assert_instruction_count.rs
Closing accounts still leaves some readable / usable data that can be reused in the same transaction.
Explicitly zeroize all of the data in the account when closing accounts.
Note: this is exactly what was previously reviewed.
> token: Zeroize data on account close

- token/program-2022/src/lib.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/assert_instruction_count.rs
This the token-2022 version of #2763 
Closing accounts doesn't null out all the data.
Zero out all data on account close.
Differences with the non-2022 version:
* Reuse `check_program_account` instead of the other owner check
* `cmp_pubkeys` refactored into lib.rs
* `sol_memset` on close sets the entire `data.len()` to 0, and not `Account:::LEN`
> token-2022: Zeroize account data on close

- Cargo.lock
- associated-token-account/program/Cargo.toml
- associated-token-account/program/src/lib.rs
- associated-token-account/program/src/processor.rs
- associated-token-account/program/tests/process_create_associated_token_account.rs
- associated-token-account/program/tests/program_test.rs
- stake-pool/cli/src/main.rs
- stateless-asks/program/Cargo.toml
- token/cli/src/main.rs
- token/rust/Cargo.toml
- token/rust/src/token.rs
We jumped the gun a little bit with ATA by linking it to spl-token-2022, and we'll need a version of the crate linked to token 3.3.0.
Bump the version and update the program to use `initialize_account3`.  As soon as this is merged, I'll publish the crate and revert the Cargo.toml change.
> associated-token-account: Bump dependent token version to 3.3

- Cargo.lock
- associated-token-account/program/Cargo.toml
- token/rust/Cargo.toml
Now that associated-token-account v1.0.4 is out, we can point the crate back to spl-token-2022.
> associated-token-account: Revert to using spl-token-2022

- token/program-2022/tests/assert_instruction_count.rs
The monorepo downstream job is failing because of compute unit usage in `close_account` test: https://buildkite.com/solana-labs/solana/builds/63871#bb2e1442-b5cb-422f-bcd3-2fe6e67a6819
Bump limit
> token-2022: bump compute limit for close test

- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/confidential_transfer/mod.rs
Unblocks initialization of extensions with default values (#2746 ) by implementing Default for the confidential-transfer extensions
> Bump zk-token-sdk and impl Default for confidential-transfer extensions

- Cargo.lock
- token/program-2022/Cargo.toml
Bumping to newly published crate that specifies solana-program and solana-sdk dependencies as caret requirements, instead of exact.
> Bump solana-zk-token-sdk again

- token/program-2022/src/extension/mod.rs
As discussed in this thread https://github.com/solana-labs/solana-program-library/pull/2743#discussion_r785221520, this PR explores overwriting any existing data for an ExtensionType when `init_extension()` is called, using `Type::default()`. This enables future extensions to be initialized with non-zero default data.
@joncinque wdyt?
~~This is still marked as draft because of the `default()` implementation. I think ideally Extension becomes `trait Extension: Pod + Default`, but the ConfidentialTransfer state structs will need to have Default impl first. At a glance, it looks to me like it would be okay to add a `Self::zeroed()` default to each of those structs, but need to confirm with @samkim-crypto~~
(edit) Default implemented upstream, so it is now `trait Extension: Pod + Default` 🎉
> token-2022: overwrite with init_extension using default state

- token/program-2022/src/processor.rs
https://github.com/solana-labs/solana/pull/22647 / https://github.com/solana-labs/solana/pull/22652 need to change the type signature of SyscallStubs `sol_set_return_data()`. Comment out this implementation and ignore test for now; to be restored when bumping solana crate versions to v1.9.6
> Comment SyscallStubs sol_set_return_data and ignore test for now

- stake-pool/cli/src/main.rs
- token-lending/cli/src/main.rs
To use the new `get_fee_for_message` APIs, the CLIs were wrongly signing the message, and then checking the fee, which means that signatures could remain unused, making @t-nelson 's skin crawl.
No crawling skin! Use `Message::new_with_blockhash`, check the fee, and then sign the transaction with that.
> stake-pool-cli / token-lending-cli: Sign after balance check

- ci/do-audit.sh
Data race in `Iter` and `IterMut` in thread_local 1.1.3 upstream dependencies 
Date: 2022-01-23
https://rustsec.org/advisories/RUSTSEC-2022-0006
Solution: Upgrade to >=1.1.4
Ingored untill fixed in solana sdk
> Temp. ignore thread_local 1.1.3 security warning

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/instruction.rs
- token/program-2022/tests/initialize_mint.rs
- token/program-2022/tests/mint_close_authority.rs
- token/program-2022/tests/transfer_fee.rs
- token/rust/src/token.rs
Started writing some tests using extension ix builders. It's really tedious to have to remember which instructions and which fields take a Pubkey by reference vs not. Also, users shouldn't have to know about COptions at all.
Rewrite ix builders to use `&Pubkey` and `Option` consistently and handle conversions/deref under the hood
> token-2022: make extension instruction builders consistent with vanilla token

- token/program-2022/src/processor.rs
- token/program-2022/tests/initialize_account.rs
Now that InitializeMint with extensions is supported, can flesh out TODOs:
- test_get_account_data_size unit test with extended mint
- ProgramTest tests for InitializeAccounts
More tests via rust client to come after ATA support is complete in #2738
Needs rebase on #2782
> token-2022: add more tests

- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_set_realm_authority.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/legacy.rs
- governance/program/src/state/realm.rs
- governance/program/tests/process_set_realm_authority.rs
When  a `realm` is created its `realm_authority` is initially set to some wallet (usually the realm's creator). 
After governances are added to the `realm` then one of them is elected as the `realm_authority` 
The purpose of this change it to prevent footgun scenario where the authority could be set to none existing or wrong account
> Governance: Realm authority validation

- governance/program/src/processor/process_cast_vote.rs
- governance/program/tests/process_cast_vote.rs
Check the proposal owner when vote is tipped by the owner
> Governance: Check tipped proposal owner

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/initialize_account.rs
- token/program-2022/tests/initialize_mint.rs
- token/rust/src/token.rs
Passing in the token program-id instead of hard-coding it will facilitate supporting multiple token program ids -- for usages like a staging program -- in the future.
> token-2022: plumb program_id through instruction builders

- associated-token-account/program/src/instruction.rs
- associated-token-account/program/src/lib.rs
- associated-token-account/program/tests/process_create_associated_token_account.rs
- stake-pool/cli/Cargo.toml
- stake-pool/cli/src/main.rs
- token/cli/Cargo.toml
- token/cli/src/bench.rs
- token/cli/src/config.rs
- token/cli/src/main.rs
- token/cli/src/sort.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/tests/program_test.rs
- token/rust/Cargo.toml
- token/rust/src/token.rs
- token/rust/tests/program-test.rs
It's desirable to optionally request a different SPL Token program id to `spl-token-cli`. 
Freebie: `spl-token-client` also now requires a program id as input
> spl-token-cli: Add global `--program-id` argument

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/tools/spl_token.rs
- governance/program/tests/process_create_mint_governance.rs
- governance/program/tests/process_create_token_governance.rs
- governance/program/tests/program_test/mod.rs
- governance/test-sdk/src/lib.rs
When mint or token account is transferred to governance then all authorities should be transferred at that time
Mint `freeze_authority`  and token account `close_authority` are transferred in addition to `mint` and `owner` authorities when governance is created
> Governance: Transfer freeze and close authorities 

- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/transfer_fee.rs
The transfer fee config authorities cannot be configured after initialization
Implement SetAuthority for these types
To come later: additional test cases to check that updated withdraw_withheld_authority can withdraw and old cannot; will be much easier to code when the rust token client supports extended Accounts (via ATA) and TransferCheckedWithFee
> token-2022: implement SetAuthority for TransferFeeConfig and WithheldWithdraw

- token/program-2022/src/error.rs
- token/program-2022/src/extension/transfer_fee/mod.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/transfer_fee.rs
It's possible to set a transfer fee above 10k basis points, which means that you assess more than all of the amount transferred.  Discovered this one while testing transfer fees.
Enforce a maximum transfer fee of 10,000 basis points.
> token-2022: Enforce maximum transfer fee of 10k bps

- token/program-2022/src/error.rs
- token/program-2022/src/extension/transfer_fee/mod.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/mint_close_authority.rs
- token/program-2022/tests/transfer.rs
- token/program-2022/tests/transfer_fee.rs
- token/rust/src/token.rs
- token/rust/tests/program-test.rs
Transfer fees need to get assessed during transfers.
Assess those fees!  The commits on this were done purposely:
* commit 1 just reorders the normal transfer logic using `StateWithExtensionsMut`, no logic changes
* commit 2 adds some simple `TokenClient`-based tests, mostly boiler-plate
* commit 3 implements the transfer fees
* commit 4 adds more tests
> token-2022: Assess transfer fees

- token/program-2022/src/extension/default_account_state/instruction.rs
- token/program-2022/src/extension/default_account_state/mod.rs
- token/program-2022/src/extension/default_account_state/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
- token/program-2022/src/state.rs
- token/program-2022/tests/default_account_state.rs
- token/program-2022/tests/program_test.rs
- token/rust/src/token.rs
This PR adds a Mint-targeted extension that allows mints to define the default AccountState for new Accounts. This provides a convenient way for mint operators to establish a whitelist of accounts/users by having all new Accounts default to AccountState::Frozen, and manually thawing approved accounts.
I made the assumption that Mints with Some freeze_authority should be able to update the default Account state of new Accounts after mint initialization, allowing a Mint to stop the whitelist approach in the future.
Currently, there is nothing to prevent a Mint operator from unsetting their freeze authority while the DefaultAccountState is set to Frozen, meaning all new accounts will be frozen and un-thawable. It could be desirable to do this, thus limiting the number of active Accounts for …
> token-2022: add DefaultAccountState mint extension

- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/instruction.rs
`Slice::split_at(n)` panics on slices shorter than `n`. We're using split_at several places in TokenInstruction unpacking, which means that spl_token can panic on malformed instructions. The BPF loader catches and unwinds these panics, but it seems pretty "meh" to depend on that, instead of handling failures gracefully. It also makes debugging -- with ProgramTest and in the wild -- a bit harder than it needs to be.
This PR also adds constants to make slice indexing a little more self-documenting.
> token-2022: remove split_at usages

- stake-pool/cli/src/main.rs
Associated-token-account v1.0.5 isn't out yet, but the stake pool CLI is already using the new instruction, causing issues for people working from master.
Revert the change, and use the old instruction creator.
> stake-pool-cli: Use old ATA creation instruction

- token/program-2022/src/extension/mod.rs
The TLV handling in the extension module uses a lot of direct indexes and `split` methods. These can panic on index out of range when the provided account data is too small.
This PR tries to protect against these panics in as lightweight and compute-minimal way as possible.
> token-2022: fix panics due to small buffers

- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_set_realm_authority.rs
- governance/program/src/state/realm.rs
- governance/program/tests/process_set_realm_authority.rs
- governance/program/tests/process_set_realm_config.rs
- governance/program/tests/program_test/mod.rs
Make it possible to set realm authority to non governance accounts.
It's required for scenarios where an external program takes ownership of the realm and controls all interactions
`SetRealmAuthorityAction` was introduced to make it possible to specify the intent (`SetChecked`, `SetUnchecked`, `Remove`) of the `SetRealmAuthority` instruction
> Governance: Make realm authority check optional

- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/tests/use_proposals_with_multiple_options.rs
Make it possible to define how many wining options for a proposal can be executed. 
This PR only added the required fields to `VoteType` and leaves the implementation for `V3`
> Governance: Add max_executable_options to VoteType

- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/tests/transfer_fee.rs
- token/rust/src/token.rs
In order to allow for account closures when transfer fees are held, we need a permissionless instruction to harvest withheld fees from accounts and into the mint.
Add the capability.
> token-2022: Add harvest from accounts to mint

- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/process_sign_off_proposal.rs
- governance/program/tests/process_sign_off_proposal.rs
- governance/program/tests/program_test/mod.rs
Make it possible for a proposal owner to sign off the proposal themself
Adding signatories to a proposal is optional and entirely at the discretion of the proposal owner
This PR simplifies the proposal creation workflow when an owner can directly sing off a proposal without creating signatory record for themself.
> Governance: Proposals signed off by owner

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/program_test/mod.rs
This allows two new tipping styles in addition to the previous "Strict" mode:
- Early: Where a yes majority above the yes vote threshold will
complete the vote, even if below 50% of total possible votes.
- Disabled: Where votes never complete early.
- `VoteWeightSource` was removed because it become irrelevant with `voter-weight-addin` and spot taken for `VoteTiping` option 
@SebastianBor
> spl-governance: Add VoteTipping option

- governance/addin-api/src/voter_weight.rs
- governance/program/src/error.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/processor/process_relinquish_vote.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/vote_record.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/program_test/mod.rs
- governance/program/tests/use_proposals_with_multiple_options.rs
Add fields to `Proposal` account as placeholders to be implemented in future versions
- `start_voting_at` - Allows to optionally specify a future start time for voting when a proposal doesn't automatically enters `Voting` state after being signed off 
- `veto_vote_weight` - `Veto` votes for either community or council members to veto each other vote
- `abstain_vote_weight` - `Abstain` vote to support explicit indifference to a proposal and/or earlier vote tipping  
- `max_voting_time`- Make it possible to extend the voting time specified in the parent `Governance` 
Add options to `VoterWeightAction`
- `SignOffProposal` - action for `VoterWeightRecord` to support gated proposal signing
> Governance: future proof v2 Proposal account

- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/process_add_signatory.rs
- governance/program/src/processor/process_cancel_proposal.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_create_governance.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/processor/process_create_realm.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/processor/process_deposit_governing_tokens.rs
- governance/program/src/processor/process_execute_transaction.rs
- governance/program/src/processor/process_finalize_vote.rs
- governance/program/src/processor/process_flag_transaction_error.rs
- governance/program/src/processor/process_set_governance_config.rs
- governance/program/src/processor/process_set_realm_config.rs
- governance/program/src/processor/process_sign_off_proposal.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/realm.rs
- governance/program/tests/process_cancel_proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_create_governance.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/process_sign_off_proposal.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
- governance/tools/src/error.rs
Track the number of proposals in voting state at the `Realm` and `Governance` level to make it impossible to change `RealmConfig` and `GovernanceConfig`  while there are proposals in voting state for them. 
It's also helps with UI performance to have the number of proposals in voting state at these level already calculated.
The check to prevent config changes are not enabled in the PR because they can work as the defence of last resort against governance attacks until we have `Veto` vote implemented.
> Governance: Track proposals in Voting state for realms and governances

- governance/program/src/processor/process_cancel_proposal.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_finalize_vote.rs
- governance/program/src/processor/process_set_governance_config.rs
- governance/program/src/processor/process_set_realm_config.rs
After upgrading to `v2` existing realms won't have `voting_proposal_count` and hence transition to completed state would result in underflow
Use `saturating_sub` instead of `checked_sub`
> Governance: Use saturating sub to decrease voting proposal count

- governance/program/src/instruction.rs
- governance/program/src/processor/process_create_proposal.rs
- governance/program/src/processor/process_insert_transaction.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/proposal_transaction.rs
- governance/program/tests/program_test/mod.rs
- governance/program/tests/use_proposals_with_multiple_options.rs
- Limit proposal options to 10 to avoid exceeding computation limit
- Increase `Proposal` reserved space to 64 bytes. Even though the runtime would support changing account size in the future version it'll still be very difficult for Governance accounts if other programs read the accounts.
> Governance: Limit proposal options to 10

- stake-pool/cli/src/output.rs
Two of the fields in the CLI output for stake pools are mismatched, making things very confusing.
Use the correct fields when building the CLI output for a stake pool.
> stake-pool-cli: Fix mismatched output fields

- token/program-2022/src/processor.rs
- token/program-2022/tests/freeze.rs
- token/rust/src/token.rs
Freeze / thaw still use `Account::unpack` and `Mint::unpack`, making them incompatible with extensions.
Use `StateWithExtensions{,Mut}` and add a very basic program-test for it.
> token-2022: Add freeze / thaw through StateWithExtensions

- token/program-2022/src/processor.rs
It's ok to allocated more account data than what's needed by the required extensions, as maybe the user wants to mix in some optional extensions as well
> token-2022: Permit new token accounts to be overallocated

- associated-token-account/program/src/tools/account.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
When the user wants to allocate a token account with optional extensions, there's no convenient method to figure the size required for those extensions.  This is in contrast to mandatory extensions, where `GetAccountDataSize` can be used to compute the size.
Extend `GetAccountDataSize` to allow the caller to pass in a list of additional `ExtensionTypes` they intend to initialize on the account.
Context: this'll be used by the ATA program to add an extension in a future PR to ATA accounts to prevent ownership transfers (cc: #2640)
> token-2022: GetAccountDataSize instruction now accepts user-provided extension types

- token/program-2022/tests/transfer_fee.rs
The `withdraw_wthheld_from_mint` test has already shown itself to be flaky.  Since the transaction looks exactly the same in some cases, `BanksClient` will return the result from the previous transaction, causing a false negative.
Always use a new account during the test, so that every transaction is unique.
> token-2022: Fix flaky test

- associated-token-account/program/src/processor.rs
- associated-token-account/program/src/tools/account.rs
- associated-token-account/program/tests/process_create_associated_token_account.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/immutable_owner.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
ATA will now set the ImmutableOwner extension on new accounts it creates.
Fixes #2640
> Add ImmutableOwner extension to block ATA owner authority changes

- token/program-2022/src/extension/mod.rs
Several issues with initial `realloc_needed()` api:
- Does not properly handle accounts with only the base state originally initialized
- Diff returned does not include the space needed for ExtensionType and Length
- Does not check whether the new ExtensionType is already initialized (which does not require reallocation)
> token-2022: fixup realloc_needed

- token/program-2022/src/extension/mod.rs
`get_extension_types()` returns early if the ImmutableOwner extension is present
> token-2022: fix handling for extensions with no data

- token/program-2022/src/extension/mod.rs
If a token extension uses `realloc()` to make space for itself on a base-state-only Account or Mint, it needs to be able to unpack the state. `unpack_uninitialized()` doesn't work, because the base-state is already set. `unpack()` doesn't work because the AccountType isn't already set.
This PR adds a new method, `unpack_after_realloc()` that acts like `unpack`, but permits unset AccountType ... and indeed initializes the AccountType under the hood.
> token-2022: add StateWithExtensionsMut::unpack_after_realloc

- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/tests/transfer_fee.rs
- token/rust/src/token.rs
Harvesting tokens + withdrawing from the mint is great, but it's also useful to withdraw directly from the accounts to avoid taking a write lock on the mint too much.
Implement `withdraw_withheld_tokens_from_accounts`!
> token-2022: Add withdraw withheld tokens from accounts

- Anchor.toml
- Cargo.lock
- governance/addin-api/Cargo.toml
- governance/addin-mock/program/Cargo.toml
- governance/chat/program/Cargo.toml
- governance/program/Cargo.toml
- governance/program/src/state/realm.rs
- governance/test-sdk/Cargo.toml
- governance/tools/Cargo.toml
`get_realm_data_for_authority` didn't use `V1` compatible deserialisation for `Realm` and `SetRealmAuthority` instruction didn't work for realms upgraded from `V1`
- Use `V1` backward compatible deserialisation `get_realm_data`
- Bump crate versions for `V2` release
> Governance: Fix Realm deserialisation and bump create versions for V2

- token/program-2022/tests/transfer_fee.rs
Doing the same transaction twice can make program-test hang, and `harvest_withheld_tokens` does that.
Don't do that.
> token-2022: De-flake test

- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
Delegates cannot revoke themselves.  Currently, a delegate can only reset the delegate by transferring out the entire delegated amount, which is not great UX.
Let delegates also revoke.
Fixes #2747
> token-2022: Add delegate self-revoke

- token/program-2022/src/error.rs
- token/program-2022/src/extension/transfer_fee/mod.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/transfer_fee.rs
It's possible to close a token account that still has withheld fees.
Prevent closing an account with withheld fees.
> token-2022: Fail to close account with withheld fees

- token/program-2022/src/processor.rs
- token/program-2022/tests/delegate.rs
- token/rust/src/token.rs
Builds directly on #2869
`approve` / `revoke` don't work with extensions
Add the support, and some tests
> token-2022: Add approve / revoke support with extensions

- associated-token-account/program/src/processor.rs
- associated-token-account/program/src/tools/account.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/reallocate.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/reallocate.rs
- token/rust/src/token.rs
Some extensions are opt-in for token account owners at any time after the account has been initialized. In these cases, the owner needs the ability to reallocate their token account data to be large enough to hold the new extension. Previous approaches attempted to do this in the initialization logic of the specific extension, but borrows on the token account were messy, and it was inefficient to include additional reallocation-specific accounts (payer and system-program) on every initialization.
This PR adds a separate Reallocate instruction to handle the data resize and rent-exempt-reserve funding for a provided set of extensions.
First and last commits can be ignored for the purposes of discussion
> token-2022: Add Reallocate instruction

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/default_account_state/instruction.rs
- token/program-2022/src/extension/memo_transfer/instruction.rs
- token/program-2022/src/extension/memo_transfer/mod.rs
- token/program-2022/src/extension/memo_transfer/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/pod.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/memo_transfer.rs
- token/rust/src/token.rs
Some users would like to require all transfers into particular accounts be accompanied by a memo.
This PR implements a MemoTransfer extension, which stores a byte indicating whether memo-transfers are or are not required. The extension can be initialized on any existing token Account, assuming the account has space for the extension. Callers should call Reallocate to make space, if the account is too small.
Currently, there is only a placeholder where the memo-requirement would be in `_process_transfer()`, pending the syscall that will expose previous sibling instructions to be checked for the memo. Bumping the solana crates and using the syscall will be done in a subsequent PR.
Needs:
Closes #2729
> token-2022: Add MemoTransfer extension

- stake-pool/py/stake/state.py
- stake-pool/py/tests/conftest.py
- stake-pool/py/tests/test_deposit_withdraw_stake.py
Fixes #2865
Python stake pool tests are flaky because of epoch rollovers.
Wait until the next epoch at the start of each test, in the hope that it makes things more stable.
There's also some debugging stuff that could be helpful later, specifically with deserializing stakes.
> stake-pool-py: Add more waits to solidify tests

- token/program-2022/tests/reallocate.rs
- token/rust/src/token.rs
The realloc test can be flaky due to the no-op repeated transaction.
Force-refresh the blockhash in the test.  The implementation is stolen from `program-test`'s extension to `BanksClient` of `get_new_latest_blockhash`.
> token-2022: Force refresh blockhash on no-op transaction

- token/program-2022/src/extension/mod.rs
The extension helper `set_account_type::<Account>()` can set the AccountType incorrectly if the base is initialized as a Mint. See #2875
Check Account initialization with a quick memcmp of one byte when S::ACCOUNT_TYPE == AccountType::Account
@joncinque , I considered adding a method to `trait BaseState`, something like:
```
fn is_initialized_raw(input: &[u8]) -> Result<bool, ProgramError>;
```
that would perform the contents of is_initialized_account for Account, and similar for Mint, even though the Mint check is not strictly necessary. Think I ought to?
> token-2022: fixup set_account_type to confirm AccountType

- Anchor.toml
- Cargo.lock
- governance/chat/program/Cargo.toml
- governance/program/Cargo.toml
- governance/program/src/state/proposal_transaction.rs
`max_size` is not calculated correctly for `ProposalTransaction` with multiple instructions and serialisation fails
- Fix  `max_size` calculation and add serialisation test with multiple instructions 
- Bump version to 2.2.3
> Governance: Use correct max size for multiple instruction transaction

- Cargo.lock
- associated-token-account/program/Cargo.toml
- associated-token-account/program/src/error.rs
- associated-token-account/program/src/instruction.rs
- associated-token-account/program/src/lib.rs
- associated-token-account/program/src/processor.rs
- associated-token-account/program/tests/create_idempotent.rs
- associated-token-account/program/tests/create_if_non_existent.rs
- associated-token-account/program/tests/process_create_associated_token_account.rs
Fixes #2295
Lots of ATA transactions fail because they all try to create the account.
Add a `CreateIfNonExistent` instruction. I'm up for any better names!
> associated-token-account: Add "CreateIdempotent" instruction

- token/program-2022-test/tests/initialize_mint.rs
- token/program-2022-test/tests/program_test.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/native_mint.rs
- token/program-2022/src/processor.rs
- token/rust/src/token.rs
The native mint for SPL token was [forged by special case](https://github.com/solana-labs/solana/blob/a7598b6d78808aeab52923a4cc4137017538b9df/runtime/src/bank.rs#L6454-L6493).  For token-2022, add an idempotent instruction to create the native mint instead. This means token-2022's WSOL mint doesn't get a vanity address, something we'll all need to find a way to live with.
> token-2022: Add CreateNativeMint instruction

- Cargo.lock
- token/rust/Cargo.toml
- token/rust/src/token.rs
There is no ergonomic way to add a memo to a token transaction in the rust token client
Add `with_memo()` method to stash a memo on the Token object, which will be included with the next Transaction built by `process_ixs`
> Add rust token client support for memo

- associated-token-account/program/src/processor.rs
- associated-token-account/program/tests/create_idempotent.rs
- associated-token-account/program/tests/process_create_associated_token_account.rs
The `CreateIdempotent` instruction gives a false positive on valid non-associated token accounts.
Move the address derivation check higher to be covered by `CreateIdempotent`.
Thanks @ryoqun for noticing this!
> associated-token-account: Fail create idempotent for non-ata

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/vsa_add.rs
Creating an account only uses `create_account`, which can be inflexible.
Also have the option to `transfer + allocate + assign` if any lamports are in the target account.
> stake-pool: Option to use transfer + allocate + assign for PDA

- Anchor.toml
- Cargo.lock
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
For the new stake pool release, bump everything to 0.6.4, and also add the stake pool to `Anchor.toml` to easily do verifiable builds and publish the source to the Anchor registry.
> stake-pool: Bump version for release, add to Anchor

- token/js/README.md
Just found the broken link and it looks like I found the correct path. :)
> Fix Broken Link to Token Program TypeScript Docs

- token/client/src/token.rs
- token/program-2022-test/tests/sync_native.rs
- token/program-2022/src/processor.rs
Extensions aren't supported in `SyncNative`, so native accounts created with `ImmutableOwner`, as done with ATA, fail to sync.  This PR assumes that we want native mint accounts to support extensions, which for `ImmutableOwner`, makes sense to me.  We'll have to write a carve-out for the native mint in confidential transfers though.
Use `StateWithExtensionsMut` in `process_sync_native`.
> token-2022: Support extensions in `SyncNative`

- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
- token/program/Cargo.toml
- token/program/src/instruction.rs
- token/program/src/lib.rs
- token/program/src/processor.rs
The extensions model  in spl-token-2022 gets us most of the way to being able to support interest-bearing tokens: https://github.com/solana-labs/solana/pull/15927
In addition to actual iToken extension definitions, we need on-chain methods to convert between raw token amounts (the number stored in the account) and ui token amount strings. The ui_amount currently only includes the decimal place, but would include the effects of interest for iTokens.
The PR implements those instructions for both token programs, so that RPC handling can be consistent.
> Add token Amount/UiAmount conversion Instructions

- Cargo.lock
- token/program-2022-test/Cargo.toml
- token/program-2022-test/build.rs
Running the program-2022-test suite uses the most recently built spl_token_2022.so, leading to potentially tedious debugging, if you've made changes to the program, but haven't explicitly rebuilt it.
Add custom build.rs to program-2022-test that runs `cargo build-bpf --manifest-path <path/to/program-2022>` if any of the program files have been modified.
@joncinque , can you give this a try and see what you think? Particularly, how do you like the logging in the 2nd commit? I thought it felt weird to not have the .so info and etc, but it is a bit yelly, since the warning was the only way I could figure out how to expose the output. I'm torn about whether to keep or drop that commit.
Incidentally, that logging will appear on every `cargo test-bpf` in program-2022-test, the same way that it …
> Custom build.rs for program-2022-test

- token-swap/program/src/instruction.rs
Hi!
A small typo in solana-program-library/token-swap/program/src/instruction.rs.
> Fix a typo in instruction.rs

- token-swap/program/src/curve/stable.rs
When calculating the new destination amount, the constant product curve takes the ceiling during division, but the stable curve doesn't.
Make the calculation consistent between curves.
> token-swap: Ceiling stable curve division

- token/program/src/instruction.rs
I broke @solana/spl-token by adding new `TokenInstruction`s and not handling them in /js
https://github.com/solana-labs/solana-program-library/pull/2949#issuecomment-1050260443
Add a comment to help ensure instruction sets stay in sync.
@joncinque , wdyt?
> token: Add comment to help keep instruction sets in sync

- Cargo.lock
- token/program-2022-test/Cargo.toml
- token/program-2022-test/tests/memo_transfer.rs
- token/program-2022/Cargo.toml
- token/program-2022/src/error.rs
- token/program-2022/src/processor.rs
Once v1.9.6 is released and incorporated into SPL, this will wrap-up the memo extension, using the `get_processed_sibling_instruction` syscall to flesh out the Transfer `if memo_required(&dest_account)` case.
@joncinque , wdyt about what I've done in the rust client here, adding Option<memo> to all the transfer methods? I liked that better than adding `_with_memo` versions of all of them, but open to other approaches. Also, probably it should take the memo as a String instead of bytes...?
> token-2022: complete memo extension functionality

- token/js/package.json
- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/index.ts
- token/js/src/extensions/mintCloseAuthority.ts
- token/js/src/instructions/index.ts
- token/js/src/instructions/initializeMintCloseAuthority.ts
- token/js/test/e2e-2022/closeMint.test.ts
- token/js/test/unit/decode.test.ts
We need to add JS bindings for the extensions, including `MintCloseAuthority`.
Add the support!
This commit can be used as a template for adding all other extensions, since it shows the instruction + state + tests to add.
The one missing part is how an `action` should be defined.  This part is a bit tricky because we want extensions to be composable with each other.  Typically, there's an action like `createMint` to easily `await`, but we can't have a specific function for each combination of extensions, ie `createMintWithMintCloseAuthorityAndTransferFee`.
Most likely, we should go with some builder model to add extensions before calling `createMint`, but we can save that for another set of PRs.
> token-js: Support MintCloseAuthority

- token/program-2022/src/extension/confidential_transfer/instruction.rs
Changing doc styles in the confidential transfer extension instructions for consistency with the rest of the token-2022 docs.
> token-2022: update doc style for confidential extension instructions

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/transfer_fee/instruction.rs
The `WithdrawWithheld` ix docs use some language that doesn't make a lot of sense to describe a potential multisig `withdraw_withheld_authority`. Fix it up!
(Needs rebase on https://github.com/solana-labs/solana-program-library/pull/2961)
> Fixup TransferFee instruction docs

- patch.crates-io.sh
- update-solana-dependencies.sh
https://github.com/solana-labs/solana-program-library/commit/4c3a3d2d5218571638a7f803ae111b523bafb57a broke v1.9 monorepo downstream build tests as there's no `zk-token-sdk` there
add an arg to skip patching `solana-zk-token-sdk`. we'll pass it from v1.9 downstream builds script
> patch-crates: optionally patch zk-token-sdk

- Cargo.lock
- token/program-2022/src/state.rs
- token/program/Cargo.toml
- token/program/src/state.rs
In certain applications, there is a need to quickly unpacking some subfields of the account without unpacking the whole account to take actions such as creating secondary indexes. The code implemented here was adapted from solana-runtime.
> Support unpacking token accounts fields partially

- ci/rust-version.sh
- name-service/program/src/state.rs
CI token job keeps failing on `use of unstable library feature 'saturating_div'`.
Bump rust versions to match monorepo (`saturating_div` was stabilized in rust v1.58)
> Bump rust versions

- ci/fuzz.sh
- ci/rust-version.sh
Since upgrading to 1.59.0, the fuzz build doesn't work anymore, with an error just like https://github.com/rust-fuzz/honggfuzz-rs/issues/61
Apply a workaround to use the old LLVM pass manager, which requires Rust nightly.
> fuzz: Fix fuzz build

- .github/workflows/pull-request-binary-oracle-pair.yml
- .github/workflows/pull-request-examples.yml
- .github/workflows/pull-request-feature-proposal.yml
- .github/workflows/pull-request-governance.yml
- .github/workflows/pull-request-libraries.yml
- .github/workflows/pull-request-memo.yml
- .github/workflows/pull-request-name-service.yml
- .github/workflows/pull-request-record.yml
- .github/workflows/pull-request-shared-memory.yml
- .github/workflows/pull-request-stake-pool.yml
- .github/workflows/pull-request-token-lending.yml
- .github/workflows/pull-request-token-swap.yml
- .github/workflows/pull-request-token.yml
I [bumped the rust version](https://github.com/solana-labs/solana-program-library/pull/2978), and didn't realize I had broken the token-swap fuzz CI because the program-specific CI jobs didn't run.
This PR updates the CI rules to run all the CI jobs on all rust- or solana-version bumps
> Run full CI on version updates

- token/client/src/token.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/src/processor.rs
- token/program/src/processor.rs
We seem to be about 50/50 on whether to spell out "destination". But when we don't, my brain invariably gets hung up on what a "dest" is.
Spell it out. There are a small handful of `dest`s remaining, due to upstream struct fields in zk-token-sdk, which I'd rather not meddle with.
No functional changes.
> token: spell out "destination"

- Anchor.toml
Verifiable builds and publishing source code doesn't work currently, since not all required programs are included in the Anchor workspace.
Add required programs to publish token and token-2022.
While we're at it, upgrade the solana version to 1.9.9.
> anchor: Updates for token-2022

- update-solana-dependencies.sh
The `solana_version` in `Anchor.toml` isn't updated with the rest of the dependencies during `update-solana-dependencies.sh`, which leads to awkward updates later on bundled up with other changes.
Also update `solana_version` during `update-solana-dependencies.sh`
> scripts: Update solana_version in Anchor.toml with dependencies

- token/twoxtx.patch
One type in rpc.rs changed upstream, breaking the patch.
> Update twoxtx patch

- token/program-2022-test/tests/confidential_transfer.rs
Test is failing due to upstream changes in solana-zk-token-sdk
Ignore it for now
Also see failed attempt to avoid patching solana-zk-token-sdk: https://github.com/solana-labs/solana-program-library/pull/2998
> Ignore failing ConfidentialTransfer test

- Cargo.lock
- token/program-2022-test/Cargo.toml
- token/program-2022-test/tests/burn.rs
- token/program-2022/src/processor.rs
- token/program-2022/src/state.rs
- token/program/src/processor.rs
- token/program/src/state.rs
The Incinerator and the System Program both own tons of token accounts due to incorrect burning procedures, wasting validator disk space.
If a token account is owned by one of those addresses, bypass owner/signer checks for burn and close. This allows anyone to burn those token accounts, as well as close them. The rent SOL must be burned, so close will fail if the incinerator is not passed in as the recipient.
> token-2022: Allow anyone to burn/close an Account owned by the system program or the incinerator

- token/js/package.json
- token/js/yarn.lock
Updating the token-js package to the newest web3.js causes an issue when resolving buffer-layout-utils.  We need the newest version in order to land #2990
Update package.json and yarn.lock for the change.
> token-js: Update @solana/web3.js dependency

- Cargo.lock
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Upgrading to zk-token-sdk `1.10.1-pre1`. Just updating the variable names in this PR. Will update range proof in a subsequent PR.
> Bump zk token sdk

- token/js/package.json
- token/js/src/state/account.ts
impl of `getMultipleAccounts` allows to request **multiple token accounts in a single RPC call** compared to `getAccount` which can only get 1 account per RPC call
> add getMultipleAccounts for Token

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/memo_transfer/instruction.rs
- token/program-2022/src/extension/memo_transfer/processor.rs
- token/program-2022/src/instruction.rs
There are a lot of copies of instruction encoding / decoding in the extensions.
Unify most of them!  A few notes:
* the default account extension can't easily follow this model because the data passed in is `AccountState`, and not `Pod`, so I excluded it from this
* this changes the confidential token instruction to use `num_enum` instead of `num_traits`, which has a bit more in terms of type and size safety
> token-2022: Refactor extension instruction encoding / decoding

- token/program-2022-test/tests/delegate.rs
This test flaked on me once, and I noticed it does the same transaction twice, which can cause that flakey failure that we see sometimes.
Change the doubled transaction to be slightly different.
> token-2022: Fix (rarely) flakey test by changing tx

- Cargo.lock
- governance/addin-api/Cargo.toml
- governance/addin-api/src/max_voter_weight.rs
- governance/addin-api/src/voter_weight.rs
- governance/addin-mock/program/Cargo.toml
- governance/chat/program/Cargo.toml
- governance/program/Cargo.toml
`MaxVoterWeightRecord` and `VoterWeightRecord` are defined in `spl-governance-addin-api` but they are owned by the addin programs. In order to make them easier to use in `Anchor` based programs their discriminators were updated to match the ones automatically generated by `Anchor`.
For backward compatibility with existing addins the legacy discriminator are also considered as valid ones.
> Governance: Update addin accounts discriminators to Anchor compatible

- .github/workflows/pull-request-token-lending.yml
- .github/workflows/pull-request-token-swap.yml
#3046 failed CI on token-lending JS because it's using Node 12 whereas `@solana/spl-token` requires version 14.
Bump the CI environment to use Node 14 where it was using 12 before.
> ci: Bump Node from v12 to v14 for spl-token downstream users

- token/js/yarn.lock
The token js build is broken because of duplicated `@solana/web3.js` dependencies -- see this CI failure: https://github.com/solana-labs/solana-program-library/runs/5741779486?check_suite_focus=true
Remove the duped version, and have 1.36 service for both 1.36 and 1.32
> token-js: Fix build due to duplicated web3.js

- governance/README.md
> Fix small typo in /governance README.md (Mutlisig -> Multisig)

- Cargo.lock
Downstream builds are failing because of mixed versions of `bytemuck_derive`.
Update the dependency to 1.1
> deps: Update bytemuck_derive to 1.1

- token-lending/README.md
The current example of requesting an airdrop of 10 sol three times results in failed transactions due to the current airdrop limit of 2 sol per request and 24 sol per account per day. This PR updates the example to work within those constraints.
> updated airdrop request values

- stake-pool/cli/src/output.rs
**Problem:**
'list -v' command prints 'Stake accounts' header twice.
It looks as follows:
Stake Deposit Referral Fee: 50% of Stake Deposit Fee
SOL Deposit Referral Fee: 50% of SOL Deposit Fee
Stake Accounts
--------------
Stake Accounts
--------------
Reserve Account: GYEzowUBH3XeLjke9z38To1HP8T88K1MGaCq7GJYSso7	Available Balance: ◎0.062412670
**Solution:**
Remove duplicate output of 'Stake Accounts' header
> Remove duplciate output of 'Stake Accounts' header

- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/Cargo.toml
The zk-token-sdk is upgraded to 1.10.8. The confidential transfer test that was ignored previously ([#3000](https://github.com/solana-labs/solana-program-library/issues/3000)) should now work.
> token-2022: fix confidential transfer tests

- token/program-2022/src/instruction.rs
- token/program/src/instruction.rs
While doing the work to parse token-2022 and token-v3 instructions, it became clear that we're not totally sure about the compatibility between token-2022 and token-v3.
Since token-2022 is meant to be a superset of token-v3, be sure that all of the instruction creators make the same exact instructions.  This way, when testing instruction parsing on the validator, we can be sure that we only need to support the token-2022 variants.
This actually uncovered a bug!
> token-2022: Add compatibility test for instructions

- token/program-2022-test/tests/mint_close_authority.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
Mints with the `mint_close_authority` extension active expect `SetAuthority` instructions to use the `AuthorityType::CloseAccount` variant. This works, but means that it is not possible to tell if an account being modified is an Account or a Mint by inspecting the instruction. (eg. https://github.com/solana-labs/solana/pull/24537#discussion_r857848860)
This PR adds an `AuthorityType::CloseMint` variant to disambiguate. This is essentially just a cosmetic change, but follows the theme of `TransferChecked` etc exposing context within each instruction.
> Add AuthorityType variant to use for mint close-authority adjustment

- token/program-2022/src/extension/confidential_transfer/processor.rs
We need to build spl-token-2022 without default features to deploy to current public clusters. The new `ConfidentialTransferInstruction::TransferWithFee` instruction doesn't include this feature-wrapping.
cc @samkim-crypto
> Add feature-wrapping for new ConfidentialTransferInstruction::TransferWithFee

- token/program-2022-test/tests/transfer_fee.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
Transfer fees are currently set one epoch ahead, in order to avoid a malicious transfer-fee-configurer from imposing a massive fee out of nowhere, potentially making the token unusable.
This still has an issue however, since a truly malicious configurer can simply set the fee right before the end of the epoch, essentially achieving the same rug pull.
Set the epoch fee two epochs forward, giving a minimum of 1 epoch for people to react to the change.
> token-2022: Set transfer fee two epochs ahead

- token-lending/program/src/processor.rs
- token-lending/program/src/state/obligation.rs
`max_withdraw_value` is incorrectly calculated because it uses `allowed_borrow_value` which represents the average LTV, not the LTV of the actual asset to withdraw.
Correctly calculate the max withdraw value using the LTV of the applicable asset.
> token-lending: Fix maximum withdrawal value calculation

- token-lending/program/Cargo.toml
`token-lending` doesn't specify a version for its `spl-token` dependency, making it impossible to publish.
Add a version.
> token-lending: Add version to spl-token dependency

- Cargo.lock
- token/client/Cargo.toml
- token/client/src/client.rs
- token/client/src/token.rs
- token/client/tests/program-test.rs
- token/program-2022-test/Cargo.toml
It's not that easy to use spl-token-client with an RpcClient (to point at a test-validator or live cluster RPC).
Changes:
- (First commit is purely cosmetic, and can be ignored in review)
- Use the nonblocking RpcClient instead of the blocking one (we're already async here)
- Arc-wrap the RpcClient in `ProgramRpcClient` so that it's easier to use for multiple calls without `will not live long enough` compile errors
- Change RpcClient `send` impl method from `send_transaction` to `send_and_confirm_transaction` - I think this is the most controversial of the changes. This approach seems the most straightforward to me, but we could instead require the caller to do any confirming they need/want. If so, we probably need to rework some things in client/src/token.rs. For instance, …
> Token client improvements

- token/program-2022-test/tests/confidential_transfer.rs
Previously, the confidential token tests only verified decryptable balances in the confidential token extended accounts. This PR extends the tests so that using decryption, they check that pending and available balances are also behaving correctly.
> token-2022: check pending and available balance on confidential token tests

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
There were some inconsistencies regarding the variable names of regular pubkey and ElGamal pubkey. After this PR:
- If a variable does not have the `pubkey` suffix, then it is a regular pubkey
- If a variable has the `encryption_pubkey` suffix, then it is an ElGamal pubkey
> Rename encryption pubkey

- Cargo.lock
- token-lending/cli/Cargo.toml
- token-lending/program/Cargo.toml
We need to release spl-token-lending-cli 0.2.0.
Bump all versions, and set them where needed for the crate to be properly deployed.
> token-lending: Bump / set / pin versions for 0.2.0 crates

- token/js/package.json
- token/js/src/state/mint.ts
- token/js/test/unit/index.test.ts
- token/js/yarn.lock
> token-js: Add sync version of getAssociatedTokenAddress

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
Adding standard tests for the confidential transfer extension `WithdrawWithheldTokensFromMint` instruction in token-2022.
> token-2022: add tests for confidential transfer withdraw withheld tokens from mint

- docs/src/token.mdx
If decimals for the mint are set to "9", then to mint 100 tokens, you'd need to enter 100000000000
unless I am mistaken?
> Confusion with decimals

- token/js/package.json
This patch moves the `start-server-and-test` dependencies to devDependencies which should shave off a few deps when using this library :)
> token-js: move start-server-and-test dep to devDependencies

- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Currently, a self-transfer with fees using the confidential extension incurs a fee. This PR modifies the confidential transfer processor logic so that fee amount is not deducted for self-transfers.
I initially thought that this would require an involved update to the zk-token-sdk due to the way fee amount is encrypted in the transfer amount. It turned out that this could be fixed rather simply without any updates to the sdk.
> Fix confidential self transfer with fees

- token/program-2022/Cargo.toml
- token/program-2022/src/extension/memo_transfer/mod.rs
- token/program-2022/src/extension/reallocate.rs
The reallocate and sibling instruction features were enabled on mainnet on epochs 310 and 311, respectively.  But token-2022 still has features for their usage.
Remove the features to prep for the next release.
> token-2022: Remove `reallocate` and `sibling-instruction` features

- Anchor.toml
- governance/program/src/error.rs
- governance/program/src/processor/process_relinquish_vote.rs
- governance/program/tests/process_relinquish_vote.rs
Once voting time ends and `Proposal` vote is not tipped then it enters implicit `Finalising` state and must be manually transitioned to `Succeeded` or `Defeated` state. In that interim state relinquishing `VoteRecords` should be disallowed because it creates an inconsistent state, especially when the chain clock diverges. 
In order to prevent inconsistent state between `Proposal` and `VoteRecords` throw error when relinquishing votes in `Finalising` state
> Governance: Do not allow relinquishing votes in Finalising state

- name-service/js/package.json
- name-service/js/yarn.lock
The dependencies for `@solana/name-service-js` are out of sync with what's in the repo.  There seems to be a newer release not reflected which contains unnecessary dependencies: https://www.npmjs.com/package/@solana/spl-name-service/v/0.1.3
Bump the minor version to release a new package without these unneeded dependencies.
Fixes #3146
> name-service-js: Bump version and sort out dependencies for release

- token-lending/README.md
`solana airdrop` request is capped at 2 now, exceeding the cap will lead to failed transactions.
This is an updated PR from #3221.
> feat: fix `solana airdrop` amount

- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/default_account_state/processor.rs
- token/program-2022/src/extension/interest_bearing_mint/processor.rs
- token/program-2022/src/extension/memo_transfer/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/src/processor.rs
The `confidential_transfer::ConfigureAccount`, should fail if run on an already configured account as stated in the [description](https://github.com/solana-labs/solana-program-library/blob/master/token/program-2022/src/extension/confidential_transfer/instruction.rs#L62-L63). However, this is currently not enforced in the processor logic, allowing users to overwrite the account state.
This PR adds a check in the `ConfigureAccount` processor logic to prevent accounts from being configured again.
Thank you @joncinque for the catch!
> token-2022: prevent an already configured confidential account to be configured again

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/processor.rs
Decrypting ElGamal ciphertexts that encrypt large numbers (> 2^32) is computationally very expensive. When a confidential transfer extended account receives incoming transfers of large amounts that are accumulated into the `pending_balance` ciphertext, then it may become very expensive for users to decrypt and recover the exact amount of tokens that is held as `pending_balance`. 
To cope with this, a confidential transfer instruction is structured such that the transfer amount (a 64-bit number) is encrypted as two ciphertexts: a `lo` ciphertext that encrypts the low 32-bits of the transfer amount and a `hi` ciphertext that encrypts the high 32-bits. Since each of the `lo` and `hi` ciphertexts encrypt 32-bit numbers, they can be efficiently decrypted. Then to recover an amount that is held …
> token-2022: limit incoming transfers for confidential transfer extension

- Cargo.lock
- docs/src/token-swap.md
- token-swap/README.md
- token-swap/js/package-lock.json
- token-swap/js/package.json
- token-swap/js/src/index.ts
- token-swap/program/Cargo.toml
- token-swap/program/program-id.md
- token-swap/program/src/lib.rs
People still use token-swap v2 on all networks, but it's unmaintained.
Prepare and release token-swap v3, meant for education and testing on devnet and testnet.  There will never be a mainnet release of this program, to avoid cannibalizing other ecosystem projects.
> token-swap: Prepare v3.0.0 release for testnet and devnet

- Cargo.lock
- associated-token-account/program/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
It's time to release a new token-2022, but the version is still at 0.3.0
Bump it to 0.4.0 everywhere to tag the next release.
> token-2022: Bump version for next release

- governance/program/src/error.rs
- governance/program/tests/process_execute_transaction.rs
- governance/program/tests/process_flag_transaction_error.rs
- governance/program/tests/process_set_governance_config.rs
- governance/program/tests/program_test/mod.rs
- governance/program/tests/use_proposals_with_multiple_options.rs
Create a test to assert a flash loan attack is not possible 
Within the same transaction, an attacker can flash loan a large amount of governance tokens, deposit them, create a proposal on a mint governance, insert a transaction to mint themself infinite tokens, vote and tip the proposal to 
success, execute the transaction, and finally repay the flashloan with a profit
> Governance: Add test to assert flash loan attack is not possible

- ci/install-build-deps.sh
- ci/rust-version.sh
I think `ci/install-build-deps.sh` was migrated from travis and not everything need to install when we use Github Actions.
I use a lint commit to trigger these affected actions and all of them passed.
`fuzz-nightly.yml` is also an affected action but I haven't a better way to trigger it so I ran it in my fork project.
> chore: update ci install dep script

- memo/ts/package.json
- name-service/js/package.json
- stake-pool/js/package.json
- token-lending/js/package.json
- token-swap/js/package.json
- token/js/package.json
- token/js/src/instructions/initializeAccount3.ts
If `eslint` fails during CI, CI still passes. That's no good.
Add `--max-warnings 0` to fail eslint properly.
> CI: Add `--max-warnings 0` to eslint to abort on errors

- token/js/src/extensions/defaultAccountState/actions.ts
- token/js/src/extensions/defaultAccountState/index.ts
- token/js/src/extensions/defaultAccountState/instructions.ts
- token/js/src/extensions/defaultAccountState/state.ts
- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/index.ts
- token/js/test/e2e-2022/defaultAccountState.test.ts
Token-2022 allows for a default account state (initialized or frozen) on all new accounts, but the JS bindings don't exist for it.
Add the bindings and tests.
Fixes #2958
> token-js: Add default account state support

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Add tests for the confidential `WithdrawWithheldTokensFromAccounts` now that syscalls have been updated.
> token-2022: add tests for withdraw of confidential withheld tokens from accounts

- token/program-2022-test/tests/confidential_transfer.rs
Add tests that encrypted transfer amounts are properly added to destination confidential accounts. This was previously labled as a todo before syscalls were updated.
> token-2022: check destination accounts on confidential token tests

- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/index.ts
- token/js/src/extensions/interestBearingMint/actions.ts
- token/js/src/extensions/interestBearingMint/index.ts
- token/js/src/extensions/interestBearingMint/instructions.ts
- token/js/src/extensions/interestBearingMint/state.ts
- token/js/src/instructions/types.ts
- token/js/test/e2e-2022/interestBearingMint.test.ts
@joncinque WIP to resolve https://github.com/solana-labs/solana-program-library/issues/3263
Lmk what you think. I'm also having trouble running e2e tests, so this hasn't been validated. I'm getting an error with:
Is there some set up I have to do?
> Support interest bearing mint in token-js

- token/cli/src/main.rs
- token/cli/tests/config.rs
The test using `assert_cmd` is done as a unit test, which causes an error when running, saying that the binary doesn't exist.
This is a known issue with `assert_cmd`, and the tests are supposed to be in a separate `tests` directory, so just move the test.
> token-cli: Move cmd test into a separate file

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
Currently, the ElGamal and authenticated encryption keys are taken as input to token client instruction functions. This PR modifies the instruction functions so that the encryptions keys are deterministically derived from the owner and token account addresses. This should abstract out the encryption keys altogether and simplify the confidential transfer rust interface in the cli.
> Derive elgamal key in token client

- Cargo.lock
Audit is currently failing in CI.
Same as https://github.com/solana-labs/solana/pull/26410, we need to bump openssl.
> CI: Bump openssl for audit

- .github/workflows/pull-request-token.yml
- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/serialization.rs
- token/program-2022/tests/serialization.rs
We would like to serialize TokenInstruction to json in order to have easier indexing, already implemented it for Metaplex token. This is still a draft I worked on with Lawrence Wu. 
* Add ser/deser traits to structs that are used when serde TokenInstruction
* Use serde_as package to serialize Pubkey as string rather than bytes
* Since COption doesn't implement serde, add manual serde 
* Tested roundtrip with some and none values
cc: @joncinque @CriesofCarrots @lwus
> Add serde feature - token-2022

- Cargo.lock
- token/program-2022/Cargo.toml
Problem
It's time to release a new token-2022, but the version is still at 0.4.0
Solution
Bump it to 0.4.1 everywhere to tag the next release.
---
p.s. open that Cargo.lock file to be sure :)
/cc @joncinque
> token-2022: Bump version for 0.4.1 release

- docs/src/associated-token-account.md
Based on @CriesofCarrots comment. Made a new PR, because I couldn't change #3330 anymore. 
Used full out spelling of the word `AToken` to resolve confusion.
> Used full out spelling to resolve confusion - related to #3330

- governance/program/src/processor/process_deposit_governing_tokens.rs
- governance/program/src/state/realm.rs
- governance/program/tests/use_realm_with_voter_weight_addin.rs
Now that token deposits can be used as inputs to vote plugins, remove the constraint that prevents token deposits when a vote plugin is used.
> Enable token deposits with voting plugin

- examples/rust/transfer-lamports/tests/functional.rs
https://github.com/solana-labs/solana/pull/26606
prevents crediting a rent paying account if the account stays rent
paying. As a result, test_lamport_transfer fails.
The commit updates destination account lamports so that after transfer
it is no longer rent paying.
> patches test_lamport_transfer

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- Added client functions to fetch and decrypt specific confidential token account state information
- Updated confidential token client functions so that it takes in confidential token account state as input for offline signing of transactions
> Adjust confidential token rust client for offline signing

- token/cli/src/main.rs
Fixes: #887
Tacked on a sync-native instruction if the destination is a wrapped account.
> token-cli: Fix unexpected behavior when closing a wrapped SOL account with another wrapped SOL account as recipient

- ci/cargo-build-test.sh
- token/cli/build.rs
The token-cli `build.rs` helpfully builds dependent BPF programs required for tests (token, token-2022, and associated-token-account). It's currently behind a check for the `DEBUG` environment variable, which means that it only runs on debug builds.  This is fine for the most part, but `cargo build` and even `cargo publish` do debug builds before the publish, which means that we currently can't publish the token-cli crate.
Add a new environment variable for building the dependent programs.
I'm not very happy with this solution, but there are literally no special environment variables set during `cargo test` which are available to `build.rs`, to tell us if we're in a testing environment.
Other options are to eliminate the file entirely or add crate feature to build the programs.  The crate …
> token-cli: Make BPF program builds in build.rs dependent on env var

- token/program-2022/src/error.rs
- token/program-2022/src/processor.rs
Following on the excellent work in #3357 , we should refactor the errors in token-2022 as well to follow the new pattern in token.
No functional changes, just move the implementation of `PrintProgramError` into `error.rs`.
> token-2022: Refactor PrintProgramError impl to error file

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/bench.rs
- token/cli/src/config.rs
- token/cli/src/main.rs
We need to move the token cli to async in order to use the rust token-client with token-2022 extensions.
Move it all to async!  No functional changes here, but some of the tests were slightly rewritten to more easily slot in token-2022 later.
Note: the async TpuClient will only come in with 1.11, so `spl-token bench` is still blocking.
> token-cli: Move everything to async

- token/cli/src/bench.rs
- token/cli/src/config.rs
- token/cli/src/main.rs
This is a reimagining of #3307 with separated commits to better understand the different pieces.
In order to more easily integrate with token-2022, the entire CLI needs to figure out the program id dynamically.
These changes were strongly coupled to https://github.com/solana-labs/solana-program-library/pull/3071, so I tried to decouple them as much as possible. The idea is that there aren't any functional changes, just figuring out the correct `program_id` based on the mentioned mint or token account, rather than using `config.program_id`. That'll help with the token-2022 support work.
> token-cli: Figure out program_id dynamically

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/bench.rs
- token/cli/src/config.rs
- token/cli/src/main.rs
- token/cli/src/sort.rs
The token CLI only works with `Tokenkeg...` and not `Tokenz...`.
Support both of them at once!  Most of the changes here involve deserializing accounts with extensions, and passing in the program id correctly.
> token-cli: Add compatibility for token-2022

- docs/sidebars.js
When adding the new token docs, some of the filenames were changed, but not in the sidebars, causing a build error.
Fix the links, and in the future, consider doing a docs build in CI for PRs on docs. I thought this was happening already, but maybe we need to add one more step.
> docs: Fix links

- docs/build.sh
The docs CI build is failing on a push to master, since it's expecting the VERCEL_TOKEN, which isn't there.
Only try to publish docs if the VERCEL_TOKEN is set.
> ci: Harden docs publish to only run with a vercel token

- docs/sidebars.js
- docs/src/confidential-token.md
- docs/src/confidential-token/deep-dive/encryption.md
- docs/src/confidential-token/deep-dive/overview.md
- docs/src/confidential-token/deep-dive/zkps.md
- docs/src/confidential-token/quickstart.md
Starting the process of translating some of the confidential extension paper to the SPL doc section. This PR includes the protocol overview. Other sections soon to come in a separate PR.
> Confidential transfer overview doc

- stake-pool/py/requirements.txt
- stake-pool/py/tests/conftest.py
- stake-pool/py/tests/test_a_time_sensitive.py
The upgrade to 1.10.33 causes the python tests to hang due to https://github.com/solana-labs/solana/pull/26851.
Wait a little bit longer so that stake accounts are not created in epoch 0.  While debugging this on a newer version of Python, I had to upgrade some dependencies
> stake-pool-py: Fix tests for Solana 1.10.33

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/main.rs
The token cli tests have become flaky, as an outcome of running so many test validators in parallel.
Run the tests in two big batches using `serial_test::parallel`.  If needed, we can instead do it in three batches.  This seemed like an easy solution, but does require setting a new `parallel` for each test added, which could be annoying.  Alternatives are welcome!
> token-cli: Run tests in batches

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/config.rs
- token/cli/src/main.rs
We want to integrate token-2022 extensions into the token-cli, and a lot of the work is already done in the token-client.
Add a `program_client` field to the token cli config, which can be used when using token-2022 extensions or instructions.
This uses `config.program_client` just to get rent exemptions, which was an easy way to show that the new field exists and can be used.
> token-cli: Add token-client dependency for token-2022 support

- token-lending/program/src/instruction.rs
- token-lending/program/src/processor.rs
- token-lending/program/src/state/reserve.rs
- token-lending/program/tests/helpers/mod.rs
- token-lending/program/tests/modify_reserve_config.rs
**Issue**: Addresses [issue #1000](https://github.com/solana-labs/solana-program-library/issues/1000)
Reserve configuration values (LTV ratio, liquidation params, APY curve params, etc.) can not be adjusted after the reserve is initialized.
**Summary of changes**:
-  Created an instruction variant `ModifyReserveConfig`, with unpack and pack implementations
- In the processor, created `process_modify_reserve_config` to handle the instruction
- Wrote tests in `modify_reserve_config.rs` to test that the reserve config can be changed and only by the correct lending market owner
**Approach - Steps**:
1. Created `ModifyReserveConfig` instruction variant, with pack & unpack implementations, and created a function to create the instruction. The instruction requires 3 accounts: Reserve …
> lending: Add instruction for changing reserve configuration after initialization

- token/cli/src/main.rs
The token-cli tests are still flaky.
Run fewer of them at once.  This approach takes longer, but let's hope it's kinder to CI machines.
> token-cli: Run fewer tests at once

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
The instruction data that is needed for `Transfer` and `TransferWithFee` is the same since the additional expected fee amount in `TransferWithFee` is encrypted and included in the proof verification instruction.
Currently, we have two separate structs for these two instructions. This pr merges these two data structs.
> token-2022: merge instruction data for confidential Transfer and TransferWithFee

- token/program/src/instruction.rs
#3416 added some guard rails, but we already have an elegant way of doing this in token-2022.
This PR refactors those checks to match, and makes the unpack unit test exhaustive.
> Refactor unpack and make test more robust

- .github/workflows/pull-request-token.yml
- token/twoxtx-setup.sh
The token CI is failing on the twoxtx step, because spl is still using Rust 1.59.0, but the monorepo is at 1.60.0, and depends on features stabilized in 1.60.0
Split out the twoxtx build step, and use the correct version of Rust there.
> ci: Separate twoxtx build step, match Rust version

- Cargo.lock
- token/program-2022/src/instruction.rs
- token/program/Cargo.toml
- token/program/src/instruction.rs
Token instruction unpacking shouldn't fail.
Add a proptest to give more coverage of test cases.  This generates a vector of random bytes and tries to unpack it as an instruction.  Note that this just generates a random 1024 tests every time `cargo test` is invoked.
The next step should be a top-level fuzz, similar to how token-swap is fuzzed.  #3420 will cover that
> token[-2022]: Add proptest for unpacking

- .github/workflows/pull-request-token.yml
- ci/cargo-build-test.sh
- token/cli/src/main.rs
The token-cli tests keep failing CI.
Serialize all the tests.  This takes a lot longer, so also split off the tests into a separate CI step.
> token-cli: Split out CI into separate step, run tests in serial

- token/program-2022-test/tests/close_account.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
- token/program/src/instruction.rs
- token/program/src/processor.rs
- token/program/tests/close_account.rs
Closing token accounts sets data to 0, but it's still possible to re-use closed accounts by initializing again in the same transaction.
Completely close the account by reassigning it back to the system program and reallocating the account to 0, as if it were totally new.
> token: Reassign and reallocate accounts on close

- token/cli/src/main.rs
fixes a regression introduced in #3166. prior to that, the config argument would default to the value of `solana_cli_config::CONFIG_FILE`, and loading the config would fall back to a default if it failed. changing the to an error protected against a missing file provided by `--config`, but also errored in the default case if they lacked the default file
this change distinguishes the three cases, erroring if the user provided a bad `--config` option, but falling back to defaults if they didnt
> token-cli: don't error when missing default config

- Cargo.lock
- associated-token-account/program/Cargo.toml
- binary-oracle-pair/program/Cargo.toml
- feature-proposal/program/Cargo.toml
- governance/addin-mock/program/Cargo.toml
- governance/chat/program/Cargo.toml
- governance/program/Cargo.toml
- governance/test-sdk/Cargo.toml
- governance/tools/Cargo.toml
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- stateless-asks/program/Cargo.toml
- token-lending/cli/Cargo.toml
- token-lending/flash_loan_receiver/Cargo.toml
- token-lending/program/Cargo.toml
- token-swap/program/Cargo.toml
- token-swap/program/fuzz/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/program/Cargo.toml
In preparation for the crate release of spl-token and spl-associated-token-account, we need to bump the versions.
Bump those versions!
> token/ata: Bump versions to 3.4.0 and 1.1.0, respectively

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- binary-oracle-pair/program/Cargo.toml
- feature-proposal/program/Cargo.toml
- governance/addin-mock/program/Cargo.toml
- governance/chat/program/Cargo.toml
- governance/program/Cargo.toml
- governance/test-sdk/Cargo.toml
- governance/tools/Cargo.toml
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- stateless-asks/program/Cargo.toml
- token-lending/cli/Cargo.toml
- token-lending/flash_loan_receiver/Cargo.toml
- token-lending/program/Cargo.toml
- token-swap/program/Cargo.toml
- token-swap/program/fuzz/Cargo.toml
- token/cli/Cargo.toml
- token/program-2022/Cargo.toml
- token/program/Cargo.toml
In preparation for the crate release of spl-token and spl-associated-token-account, we need to bump the versions.
Bump!
> Bump token to v3.5.0 and ata to v1.1.1

- Cargo.lock
- docs/src/token-2022/onchain.md
- token-swap/program/Cargo.toml
- token-swap/program/src/processor.rs
Token-2022 is out on all networks, but it's not clear how to integrate it in on-chain programs.
Add some docs with a concrete example using token-swap.  This only covers the simplest migration towards supporting both token and token-2022, but not both in the same instruction. That'll happen in a separate PR.
@jacobcreech no need to look at the program changes, but any comments on the doc are extremely appreciated :smile: 
This PR will be merged without squash so that we can link all of the commits in the doc aftewards.
> token-swap: Support two token programs at once

- examples/c/src/cross-program-invocation/cross-program-invocation.c
Explaining enum values and linking the source (Issue #2243 ):
System program instruction source: https://github.com/solana-labs/solana/blob/master/sdk/program/src/system_instruction.rs
Enum Values:
0: CreateAccount
1: Assign
2: Transfer
3: CreateAccountWithSeed
4: AdvanceNonceAccount
5: WithdrawNonceAccount
6: InitializeNonceAccount
7: AuthorizeNonceAccount
8: Allocate
9: AllocateWithSeed
10: AssignWithSeed
11: TransferWithSeed
12: UpgradeNonceAccount
> Issue 2243 comments and source for system program instruction

- token/js/src/instructions/index.ts
- token/js/src/instructions/reallocate.ts
- token/js/test/e2e-2022/reallocate.test.ts
- token/js/test/unit/index.test.ts
`Reallocate` is an available instruction in token-2022 to add more space to token accounts, but the JS bindings don't use it yet.
Implement the reallocate instruction and add a test.
Fixes #2956
> token-js: Add reallocate instruction implementation

- Cargo.lock
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
We have new instructions in the stake pool program to create / update pool token metadata, but the program hasn't been released anywhere.
First step: tag a new release so we can build a program from it!
> stake-pool: Bump versions to 0.7.0

- ci/do-audit.sh
There's a security advisory out for rocksdb, and audit is failing.
Ignore RUSTSEC-2022-0046 until we update to the newest Solana 1.11 crates.
> ci: Add rocksdb to ignore audit (for now)

- .github/workflows/pull-request-token.yml
Since the new rocksdb lib is incompatible with Rust 1.59.0, we can't properly build the programs while `build-bpf` is on an older version of Rust.
Not the best option, but just disable the job until we have Rust 1.60 available everywhere.
> ci: Disable twoxtx for now

- ci/read-cargo-variable.sh
- ci/rust-version.sh
- rust-toolchain.toml
It's not clear what version of rust to use when testing / running SPL stuff.
Specify the channel in `rust-toolchain.toml`, and use that in `ci/rust-version.sh`. This doesn't resolve the issue of knowing which version of nightly to use, but at least building / fmt is covered.
> toolchain: Pin repo to 1.59.0 using rust-toolchain.toml

- docs/src/token-2022/onchain.md
- token-swap/js/src/index.ts
- token-swap/js/test/token-swap-test.ts
- token-swap/program/fuzz/src/native_token_swap.rs
- token-swap/program/src/instruction.rs
- token-swap/program/src/processor.rs
Token-2022 is out, but people may not know how to support both Token and Token-2022 within the same program.  For example, how do you swap Token tokens for Token-2022 tokens?
Provide another guide with step by step instructions, using the token-swap program as a testing ground.  This is part 2 of 3, so we're almost there!
> token-swap: Support pools with mixed token and token-2022 mints

- token/cli/src/config.rs
- token/cli/src/main.rs
- token/client/src/client.rs
In order to make offline signing work with `TokenClient`, we need to avoid going out to the network, the token client will by default try to send off transactions.
Implement a no-op / offline client type that can be substituted in if `--sign-only` is specified.
> token-cli: Add no-op client

- token/js/examples/transferFee.ts
- token/js/package.json
- token/js/src/state/account.ts
- token/js/src/state/mint.ts
- token/js/src/state/multisig.ts
- token/js/yarn.lock
The new unpack functions haven't been published to npm yet. This gets their argument order consistent with other lib functions, and updates to the latest spl-memo before releasing.
> token/js - make unpack functions consistent

- token/program-2022/src/processor.rs
- token/program/src/processor.rs
During the upgrade to `cargo build-sbf` / `test-sbf` in #3492, we had to use the `--arch` flag since some parts of the code still rely on it.
Make token consistent with the rest of the codebase, and use `target_os = "solana"` instead of `target_arch = "bpf"`
> token[-2022]: Change `target_arch` to `target_os`

- token/cli/src/main.rs
- token/client/src/client.rs
- token/client/src/token.rs
- token/client/tests/program-test.rs
- token/program-2022-test/tests/program_test.rs
- token/program-2022-test/tests/sync_native.rs
- token/program-2022-test/tests/transfer_fee.rs
draft because:
* ~i had a small question about the memo handling~
* ~i need to rebase again when #3449 lands~
* ~i need to reverse merge out the close authority stubs~
* ~we need a new solana monorepo version to bring in the `Signers` impl (so this actually wont build at all for you as-is)~
but (other than that!!) this is basically done
this pr implements a full flow for `command_create_token` to go through the token client, including support for nonce mode offline signing. this is prerequisite work to #3403
> Refactor command_create_token to use token client

- stake-pool/js/src/instructions.ts
- stake-pool/py/stake_pool/instructions.py
the python and ts client stake pool instructions have some incorrect docstrings
> fix incorrect docstrings in stake pool client instruction libraries

- governance/program/src/instruction.rs
- governance/program/src/processor/process_revoke_governing_tokens.rs
- governance/program/tests/process_revoke_governing_tokens.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
Use `governing_token_mint_authority` instead of `realm_authority` to authorise `Membership` tokens revocation.
The `mint_authority` can mint the `Membership` tokens and hence has ultimate power over the governance tokens because it could dilute any existing governance structure by minting more tokens. It makes then more sense to use the same authority to authorise revocation (burn) of those tokens instead of the `realm_authority` which doesn't have to be the same.
> Governance: Use mint authority to revoke membership tokens

- governance/program/src/state/proposal.rs
- governance/program/tests/process_cast_vote.rs
When vote tipping is disabled the vote should not end early even if `max_voter_weight` worth of `vote_weight` have been cast.
> Governance: Do not tip on max vote weight when tipping Disabled

- stake-pool/cli/scripts/withdraw.sh
- stake-pool/cli/src/main.rs
- stake-pool/js/src/index.ts
- stake-pool/js/src/layouts.ts
- stake-pool/js/test/instructions.test.ts
- stake-pool/js/test/layouts.test.ts
- stake-pool/js/test/mocks.ts
This PR adds :-
1). Merge the stake account if stake receiver is initialized.
2). Mock tests for the js and withdraw with stake receiver in the cli scripts.
Instead of changing the stake pool program the withdraw functionality is extended in tools. The stake pool program always performs split with a new stake account and if the ```stake_receiver``` is initialized , the withdrawn stakes are merged with the ```stake_receiver```
closes #1421
> Extends withdraw functionality in stake pool

- feature-proposal/cli/src/main.rs
- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_create_governance.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/processor/process_revoke_governing_tokens.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_revoke_governing_tokens.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
Make it possible to have different `vote_tipping` settings for `Community` and `Council`.
It allows to create a governance structure where both `Community` and `Council` can control the same assets but with different voting rules. For example a governance to control program upgrades could use the following settings:
- `Community` `vote_tipping` set to `Disabled`  meaning its vote can't end early and always must last the configured amount to time.
- `Council` `vote_tipping` set to `Early` meaning it has power to create and execute fast forward emergency proposals to upgrade security vulnerabilities. 
- `council_vote_tipping` was added to `GovernanceConfig` struct. It used reserved space making the change backward compatible with previous versions and the binary account layout.
> Governance: Add council_vote_tipping

- governance/program/src/error.rs
- governance/program/src/state/token_owner_record.rs
- governance/program/tests/process_create_governance.rs
- governance/program/tests/process_create_proposal.rs
Make it possible to explicitly disable voter weight thresholds to create governances and proposals. 
The purpose of this change is to have strong guaranteed to prevent governance or proposal creation by given governance population. 
Ideally `Option<u64>` should be used to indicate the optionality of the value but In order to preserve backward compatibility with existing realms the value of `u64::MAX` was used to denote Disabled thresholds.
> Governance: Explicit disabled weight thresholds

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/processor/process_create_governance.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/realm.rs
- governance/program/tests/program_test/mod.rs
- governance/program/tests/use_veto_vote.rs
Enable `Community Veto` vote to make it possible for the `Community` to veto `Council` proposals.
For existing accounts `Community Veto` is disabled as a more conservative setting which grants more governance power  to `Council`. It also consistent with setup where `Community` vote was implicitly disabled.
- `reserved` space from `Governance` account was used to make the change backward compatible.
> Governance: Community Veto Vote

- token/cli/src/main.rs
- token/client/src/token.rs
- token/client/tests/program-test.rs
- token/program-2022-test/tests/burn.rs
- token/program-2022-test/tests/default_account_state.rs
- token/program-2022-test/tests/interest_bearing_mint.rs
- token/program-2022-test/tests/mint_close_authority.rs
- token/program-2022-test/tests/transfer_fee.rs
* ~add `--enable-close` flag to `create-token` that sets up a close authority~
* ~implement `close-mint` to close a mint that has a close authority~
* ~support `close-mint` in `authorize` to change a mint close authority~
~this needs to be rebased after #3469 lands~
~this is now based on the quite erroneously named `close-mint` branch so a rebase to master is trivial~
this is based on master
closes #3403
> token-cli: support `MintCloseAuthority`

- token/cli/src/bench.rs
- token/cli/src/main.rs
i allowed unchecked transfer to be deprecated because the purpose of using it is to make a deprecated thing available (although i do wonder whether anyone actually needs this). everything else is straightforward
closes #3497
> token-cli: remove #[allow(deprecated)] from toplevel

- Cargo.lock
- token/cli/Cargo.toml
release has already been made and lives in the `token-cli-v2.0.17-branch` branch
> bump token-cli to 2.0.17

- Cargo.lock
There's a security vulernability in lz4 v1.9.3, and we need to update to 1.9.4 to unblock CI.
Bump the version
> ci: Bump lz4 for audit fix

- ci/fuzz.sh
- ci/rust-version.sh
- stake-pool/program/src/state.rs
SPL was upgraded  to Rust 1.60, but nightly is still on 2022-02-24.
Bring them in line with the monorepo, and upgrade rust nightly to 2022-04-01.  There was only one additional nit to fix.
> ci: Update rust-nightly to 2022-04-01

- memo/js/.eslintrc
- memo/js/package-lock.json
- memo/js/package.json
- token/js/.eslintrc
- token/js/package-lock.json
- token/js/package.json
This adds a lint rule to enforce correct use of .js file extensions.
See https://github.com/solana-labs/eslint-plugin-require-extensions and https://github.com/solana-labs/wallet-adapter/issues/546 for context.
> Token JS, Memo JS: add eslint-plugin-require-extensions

- token/cli/src/main.rs
> token-cli: Removed usage of Account::LEN as a verificaton for token account

- token/program-2022-test/tests/confidential_transfer.rs
The confidential tests currently don't compile because they're still using the old generic parameters for `Token` as `Token<T, Keypair>` rather than `Token<T>`.
Very simple, just get rid of the removed generic param.
> token-2022-test: Use updated generic types for Token client in confidentials

- token/program-2022/src/extension/transfer_fee/mod.rs
While working on #3523 for token swap, the program needed to figure out how much to send in order to get a particular output.  This seems like it could be generally useful.
Add the inverse fee calculation.  Getting this to work with the ceiling calculation in the normal transfer fee was tricky, but the proptest works with really good precision, one part in 10^15, which seems pretty darn good!
Also, happy to bikeshed a better name for this.
> token-2022: Add inverse fee calculation

- token-swap/js/package-lock.json
- token-swap/js/package.json
#3364 fixed the references to esm files in package.json, but this fix is not available on npm.
Bump the version to 0.2.1 for a new release.
> token-swap-js: Bump version for release

- stake-pool/cli/src/main.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
- stake-pool/py/stake_pool/constants.py
Currently, the stake pool program hardcodes a minimum delegation amount of 0.001 SOL in the program, but the stake program will soon enforce a higher minimum delegation amount.
Use the maximum of the previous value (0.001 SOL) and the value reported by the stake program's `get_minimum_delegation` instruction.
> stake-pool: Use stake program minimum delegation

- .github/workflows/pull-request-token.yml
- token/twoxtx-setup.sh
- token/twoxtx.patch
This is another attempt at #3465 -- we disabled the twoxtx CI job because of incompatible rust versions, but we can actually pick up the correct version if we just use cargo-test-sbf from the twoxtx solana repo.
Just use that!
Fixes https://github.com/solana-labs/solana-program-library/issues/3461
> ci: Re-enable twotx job

- token/cli/src/bench.rs
- token/cli/src/config.rs
- token/cli/src/main.rs
- token/client/src/token.rs
- token/client/tests/program-test.rs
- token/program-2022-test/tests/burn.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/delegate.rs
- token/program-2022-test/tests/freeze.rs
- token/program-2022-test/tests/memo_transfer.rs
- token/program-2022-test/tests/mint_close_authority.rs
- token/program-2022-test/tests/transfer.rs
- token/program-2022-test/tests/transfer_fee.rs
part of #3482. i started with `mint_to`, will also do `burn` and `transfer` since we discussed unifying the client interface of those to take `decimals: Option<u8>` and get rid of checked/unchecked variants
i dunno if im gonna do all the cli stuff but this will provide a blueprint at least as for what the changes need to look like. in short:
* the `S` on a client method type signature changes from `Signer` to `Signers`
* `authority` param changes from `&S` to `&Pubkey`
* methods take an additional param `signing_keypairs: &S`
* `get_multisig_signers` is called up top to gather pubkeys to mark as signers on token instructions
* return types change to `TokenResult<T::Output>` if not already, to enable returning signatures or (possibly partially) signed transactions
* cli flow changes, …
> run more cli stuff through client

- Cargo.lock
- ci/fuzz.sh
- ci/install-program-deps.sh
- token-swap/program/fuzz/Cargo.toml
CI is failing at the moment on the fuzzing step because of a failure to install honggfuzz.  The installation step pulls in a newer version of `"arbitrary"` which requires a higher version of Rust.
Use Rust 1.63 for the fuzzing step.  Also, honggfuzz had a new release, which means that we don't need to use nightly anymore.
> fuzz: Update honggfuzz and rust version required

- docs/src/token-2022/onchain.md
- token-swap/js/src/index.ts
- token-swap/js/test/token-swap-test.ts
- token-swap/program/fuzz/src/instructions.rs
- token-swap/program/fuzz/src/native_token_swap.rs
- token-swap/program/src/instruction.rs
- token-swap/program/src/processor.rs
If people follow the on-chain program migration docs, they may get stuck if their program uses `transfer` instead of `transfer_checked` everywhere.
Provide docs and example for how to migrate to `transfer_checked`, using token-swap example once again.
There will be one more doc after this, for using specific extensions, and after that we'll be good from the on-chain side, I hope.
> token-swap: Migrate to `transfer_checked`

- docs/src/token-2022/extensions.mdx
The `confirmTransaction` method was recently overloaded and the old method signature was deprecated. 
**New docs should use the new overload.**
Note: I'm not positive that my shorthand usage is best practice, feedback welcome.
> Token 2022 Docs: use new overload of confirm tx

- account-compression/programs/account-compression/src/state/concurrent_merkle_tree_header.rs
The `account_type` member of `ConcurrentMerkleTreeHeader` is currently an `#[repr(u32)]` enum, but borsh only uses one byte to serialize or deserialize an enum tag, which leads to issues with `try_from_slice` calls that get passed slices computed based on applying `size_of` to `ConcurrentMerkleTreeHeader`. This commit replaces the underlying type of `account_type` with an `u64` to also eliminate any padding; if that's not required or helpful we can use a narrower type and potentially move the field to be last.
> Fix `ConcurrentMerkleTreeHeader` (de)serialization

- docs/src/token-2022/onchain.md
- token-swap/program/src/processor.rs
On-chain programs that use Token-2022 could see some surprising behavior if mints have extensions.  Two situations in particular:
* if a mint has transfer fees, then token-swap slippage calculations are wrong
* if the pool token mint has a close authority, it's possible to brick a pool
Cover these situations, and also add some docs for it.  This builds on #3491 and #3524
> token-swap: Add transfer fee and mint close authority support

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Currently, confidential transfers are still possible even if the mint is a `NonTransferable`. This pr adds a check for `NonTransferable` in the confidential transfer processor.
> confidential-extension: forbid confidential transfer if nontransferable mint

- token/program-2022/src/extension/transfer_fee/mod.rs
An attempt at simplifying transfer fee calculation.
- Simplified fee calculation using ceiled division `ceil[ a / b ]` as `(a + b - 1) / b`.
- Added `calculate_post_fee_amount` and `calculate_pre_fee_amount`.
It seems like for most applications, computing (1) the net transfer amount from the gross amount or (2) the gross amount from the net amount is very useful.
@joncinque What do you think? The updated `calculate_inverse_fee` breaks a couple of the edge case tests, but it seems to maintain the precision. It also seems like `calculate_post_fee_amount` and `calculate_pre_fee_amount` can be used directly for the swap program.
> token-2022: add calculate post and pre fee amounts

- token/cli/src/config.rs
- token/cli/src/main.rs
first step is to normalize what our args are named (details in commit message, for the sake of our futute descendents) and then its pretty easy to handle this inside config creation
closes #3532
> token-cli: infer program_id when possible

- token/cli/src/main.rs
- token/client/src/token.rs
- token/program-2022-test/tests/memo_transfer.rs
this also fixes a bug where cli memos implicitly signed with `fee_payer` rather than `default_signer`
closes #3538
> token-client: memo now explicitly declares signers

- libraries/concurrent-merkle-tree/src/concurrent_merkle_tree.rs
- libraries/concurrent-merkle-tree/tests/tests.rs
Address Halborn feedback on documentation & public function visibility
> Concurrent Merkle Tree: Improve Docs

- token/client/src/token.rs
- token/client/tests/program-test.rs
- token/program-2022-test/tests/burn.rs
- token/program-2022-test/tests/close_account.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/default_account_state.rs
- token/program-2022-test/tests/delegate.rs
- token/program-2022-test/tests/freeze.rs
- token/program-2022-test/tests/memo_transfer.rs
- token/program-2022-test/tests/mint_close_authority.rs
- token/program-2022-test/tests/reallocate.rs
- token/program-2022-test/tests/sync_native.rs
- token/program-2022-test/tests/transfer.rs
- token/program-2022-test/tests/transfer_fee.rs
The token client's `create_associated_account` and `create_auxiliary_account` functions return the pubkey of the created account, which is nifty in tests, but not usable in CLIs where we want a transaction signature.
I came across this issue while writing a CLI for the token-upgrade program. One of the commands just creates a token account, but I wasn't able to display the transaction info because of the previous return type.
Change the output of the the create account functions to `T::Output`, and fixup all tests that use it.
> token-client: Change create_account to return T::Output

- Cargo.lock
- token/client/Cargo.toml
- token/client/src/lib.rs
- token/client/src/output.rs
- update-solana-dependencies.sh
While working on #3593, I wanted to print the result from the token client, but the Debug printer for `Signature` gives `Signature(signature_in_base_58)`, which is not great.
Implement `fmt::Display` on `RpcClientResponse`, and add a feature for output that can be disable if needed.
> token-client: Add fmt::Display implementation to RpcClientResponse

- token/js/src/actions/createMint.ts
- token/js/src/instructions/associatedTokenAccount.ts
- token/js/src/instructions/decode.ts
- token/js/src/instructions/initializeMint2.ts
- token/js/test/unit/index.test.ts
Implemented the `InitializeMint2` instruction and updated the `createAssociatedTokenAccount` instruction builder to not use rent anymore. In addition, I defaulted the createMint instruction to use the new `InitializeMint2` handler. Not sure if there's a good reason not to do that? Would love to hear any reasons if they do exist.
> Update token-js with rent-less instructions

- Cargo.lock
As evidenced by https://github.com/solana-labs/solana/pull/27745 and the CI failure in https://github.com/solana-labs/solana-program-library/pull/3600, we need to update `axum-core`.
Update `axum-core` and its dependencies as needed.
> audit: Update axum-core and its deps aggressively

- stake-pool/cli/src/main.rs
currently, `set-manager` cannot be used to change the stake pool manager to a hardware wallet, due to the use of `keypair_of`, which does not support a hardware wallet path. We instead use `get_signer` to get the signer, which allows hardware wallets to sign the transaction
> add stake pool support support for hardware wallets in set-manager

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Currently, the deposit source and withdraw destination accounts for the confidential extension instructions can differ from the base account for the extension, which can act as an alternate way to transfer tokens (issue [#3519](https://github.com/solana-labs/solana-program-library/issues/3519)). 
Summary:
- limit the deposit source and withdraw destination accounts to base accounts only
- limit deposit amounts to a 48-bit number
> confidential-extension: Restrict deposit source and withdraw dest to base accounts

- token/client/src/token.rs
- token/program-2022-test/tests/non_transferable.rs
- Extended `ExtensionInitializationParams` for the non-transferable extension so that non-transferable extension can be easily initialized
- Tweaked `create_auxiliary_token_account_with_extension_space` in token client so that immutable owner accounts can be easily initialized
- Added basic tests for the non-transferable extension. Tests for the non-transferable confidential extension will be added in a separate PR.
> token-2022: Add support for non transferable and immutable ownership in token client

- Cargo.lock
- token-upgrade/cli/Cargo.toml
- token-upgrade/cli/src/main.rs
The token upgrade CLI is using `solana-validator` for its tests, but that brings in a lot of extra dependencies. It should just be `solana-test-validator`.
Make that change.
> token-upgrade-cli: Use test-validator instead of validator

- farms/docs/fund.md
- farms/docs/governance.md
- farms/docs/quick_start.md
- farms/farm-sdk/build.rs
- farms/vaults/Cargo.toml
The farms docs say to use `build-sbf`, but farms still use older crates that aren't compatible with `build-sbf`.
Update the docs to say `build-bpf` everywhere, and remove all traces of `sbf`.
> farms: Update docs to build-bpf instead of build-sbf

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/process_create_realm.rs
- governance/program/src/processor/process_set_realm_config.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/realm.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_create_realm.rs
- governance/program/tests/program_test/args.rs
- governance/program/tests/program_test/mod.rs
Implement `Absolute` option for `community_mint_max_voter_weight_source` to support static values not related to the governance token supply
> Governance: Implement Absolute max voter weight source

- ci/install-build-deps.sh
- governance/program/tests/program_test/mod.rs
Splits the unrealistically large transaction, which has 88 instructions and can not be send over the network, generated by `with_governed_program()` into many.
This change is necessary because [this PR](https://github.com/solana-labs/solana/pull/27938) will limit the number of instructions per transaction explicitly.
> Refactor `test_create_program_governance`

- libraries/concurrent-merkle-tree/src/concurrent_merkle_tree.rs
- libraries/concurrent-merkle-tree/src/error.rs
- libraries/concurrent-merkle-tree/tests/tests.rs
Needed for closing on-chain trees
> CMT: add method to check if Concurrent Merkle Tree is empty

- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Confidential transfers without memo do not fail even if the destination accounts are extended to require fees. This PR fixes this so that confidential extension can work with the memo extension.
> token-2022: integrate memo into confidential extension

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/processor/process_create_governance.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/tests/program_test/mod.rs
Move `reserved` space to `GovernanceConfig` to make it easier to use it in backward compatible way for future `config` changes.
> Governance: Move reserved space to GovernanceConfig

- token/cli/src/config.rs
looks like this branch of the if statement got dropped on the floor in a rebase because me and the outside contributor were working on the code at the same time. without it, `config.yml` is never loaded
closes #3630
> token-cli: load config if exists without -C

- Cargo.lock
- account-compression/Cargo.lock
- account-compression/programs/account-compression/Cargo.toml
- account-compression/programs/noop/Cargo.toml
- account-compression/sdk/idl/spl_account_compression.json
- libraries/concurrent-merkle-tree/Cargo.toml
- Update program ids for `spl-noop`, `spl-account-compression`
- Add instruction to remove empty tree for `spl-account-compression`
- Update `concurrent-merkle-tree` library to support checking empty tree condition
> Account Compression: 0.1.1 release

- token/cli/README.md
It's unclear how to run the token-cli tests.
Add instructions to the README.
> token-cli: Add directions for building and running tests

- token/cli/src/config.rs
- token/cli/src/main.rs
- token/cli/src/output.rs
- token/cli/src/sort.rs
* ~fetch for all programs by default~
* ~display program an account belongs to~
* ~display delegate/close authority~
* ~filter by delegate/close authority~
* ~output nothing but token account addresses~
first two are for better token22 ergonomics, latter three are for conveniently viewing and revoking unwanted permissions
closes #3602
> improve `spl-token accounts`

- token-upgrade/cli/src/main.rs
- token-upgrade/program/tests/functional.rs
- token/cli/src/main.rs
- token/client/src/token.rs
- token/client/tests/program-test.rs
- token/program-2022-test/tests/burn.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/delegate.rs
- token/program-2022-test/tests/memo_transfer.rs
- token/program-2022-test/tests/mint_close_authority.rs
- token/program-2022-test/tests/non_transferable.rs
- token/program-2022-test/tests/program_test.rs
- token/program-2022-test/tests/transfer.rs
- token/program-2022-test/tests/transfer_fee.rs
this properly belongs on the object. as always, this interface change excludes the confidential functions, which can be stabilized when confidential transfers go in the cli
~rebase on master when #3482 lands~
closes #3648
> remove decimals parameter from token client methods

- token/cli/src/config.rs
unless im extremely stupid (entirely possible) this is literally all we need to do. authority is always pushed onto the vec in the relevant match arm of `process_command`, totally irrespective of anything to do with `fee_payer`. that means the `fee_payer` push is completely pointless because fees are always paid by `payer` on `Token`
closes #3509
> token-cli: dont push fee_payer to bulk_signers

- account-compression/programs/account-compression/src/events/changelog_event.rs
- account-compression/programs/account-compression/src/events/mod.rs
Needed by Metaplex.
* https://github.com/metaplex-foundation/metaplex-program-library/pull/801
* https://github.com/metaplex-foundation/blockbuster/pull/9
* https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/pull/10
> Adding new() function for ChangeLogEvent and expose ChangeLogEventV1

- account-compression/Cargo.lock
- account-compression/programs/account-compression/Cargo.toml
- account-compression/programs/noop/Cargo.toml
- account-compression/programs/noop/README.md
- account-compression/sdk/idl/spl_account_compression.json
- expose ChangeLogEventV1 in crate
- update SPL Noop README
> Account Compression: Rust Release v0.1.3

- account-compression/sdk/README.md
- account-compression/sdk/package.json
- account-compression/sdk/src/accounts/ConcurrentMerkleTreeAccount.ts
- account-compression/sdk/src/utils/index.ts
- account-compression/sdk/tests/accountCompression.test.ts
- account-compression/sdk/tests/utils.ts
- account-compression/sdk/yarn.lock
- Expose all maxDepth, maxBufferSize pairs
- Add canopyDepth getter to `ConcurrentMerkleTreeAccount`
- Fix issue that required `@metaplex-foundation/beet*` to be installed separately
- Update README.md
> Account Compression: JS SDK release 0.1.1

- .github/workflows/pull-request-instruction-padding.yml
- Cargo.lock
- Cargo.toml
- instruction-padding/program/Cargo.toml
- instruction-padding/program/README.md
- instruction-padding/program/src/entrypoint.rs
- instruction-padding/program/src/instruction.rs
- instruction-padding/program/src/lib.rs
- instruction-padding/program/src/processor.rs
- instruction-padding/program/tests/noop.rs
- instruction-padding/program/tests/system.rs
For testing the effect of larger transaction sizes on the network, it's useful to have a program that just accepts large transactions and either no-ops or CPIs into some other program.
This can be integrated into bench-tps to see the effect with huge numbers of transactions, as done in https://github.com/solana-labs/solana/pull/27495
Start with the program, build / publish it, then add the bench-tps parts from https://github.com/solana-labs/solana/pull/27495
> instruction-pad: Add a new program for padding instructions

- managed-token/program/Cargo.toml
The SPL build currently gives this warning every time:
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/jon/src/solana/solana-program-library/managed-token/program/Cargo.toml
workspace: /home/jon/src/solana/solana-program-library/Cargo.toml
```
Remove the ignored `profile.release` configuration in managed-token.
> managed-token: Remove ignored profile.release

- Cargo.lock
- account-compression/Cargo.lock
- account-compression/programs/account-compression/Cargo.toml
- account-compression/programs/account-compression/src/error.rs
- account-compression/programs/account-compression/src/lib.rs
- account-compression/programs/account-compression/src/state/concurrent_merkle_tree_header.rs
- account-compression/sdk/idl/spl_account_compression.json
- account-compression/sdk/package.json
- account-compression/sdk/src/generated/errors/index.ts
- account-compression/sdk/tests/accountCompression.test.ts
- account-compression/sdk/tests/utils.ts
- libraries/concurrent-merkle-tree/Cargo.toml
- libraries/concurrent-merkle-tree/src/concurrent_merkle_tree.rs
- libraries/concurrent-merkle-tree/src/error.rs
- libraries/concurrent-merkle-tree/tests/tests.rs
Add checks to prevent `leaf_index` accesses beyond `rightmost_proof.index`
> Account Compression: Add CMT checks for out of bounds leaf indices and initialization

- governance/program/src/processor/process_relinquish_vote.rs
- governance/program/src/processor/process_remove_signatory.rs
- governance/program/src/processor/process_remove_transaction.rs
- governance/program/tests/process_relinquish_vote.rs
- governance/tools/src/account.rs
In order to support `ChangeVote` instruction semantics it must be possible to call `RelinquishVote` and `CastVote` in a single transaction. 
`dispose_account` was changed to reallocate account data to 0 and assign it back to `SystemProgram`. This change allows to reallocate `VoteRecord` account in `CastVote` within a single transaction after it was previously disposed by `RelinquishVote`
> Governance: Vote change in a single transaction

- token/twoxtx.patch
The twoxtx step is failing due to an outdated patch, see https://github.com/solana-labs/solana-program-library/actions/runs/3316735829/jobs/5478868796 for an example.
Update the patch!
> ci: Update twotx.patch to apply properly

- token/cli/src/config.rs
- token/cli/src/main.rs
The `spl-token` uses the argument `-C` to specify the cli config file, if the argument isn't provided a default config file is created, using  the default signer `~/.config/solana/id.json`.
This behavior is inconsistent with the main `solana` cli, where in case the cli config file isn't explicitly passed, the cli will use the default cli config file at `~/.config/solana/cli/config.yml`
These changes consolidate the default cli config file loading behavior between the `spl-token` and  `solana`.
If the file is not explicitly specified with `-C`, the default cli config at `~/.config/solana/cli/config.yml` if it exists.
Main [solana cli for reference](https://github.com/solana-labs/solana/blob/master/cli/src/clap_app.rs#L17)
> `spl-token` cli - use default config file

- Cargo.lock
- ci/do-audit.sh
- feature-proposal/cli/Cargo.toml
We've had to ignore a few RUSTSEC advisories over the years, but we've since upgraded for the most part!
Remove ignores that aren't needed, and upgrade chrono to 0.4.22 in the feature-proposal CLI to get rid of one more.
Fixes #3459
> ci: Reduce audit ignores

- token/program-2022/src/extension/mod.rs
If the length of an extension is greater than `u16::MAX`, then `init_extension` could cause a panic due to `unwrap`. It seems like we can let the error from `try_from` propagate out to the external caller in this case.
Addresses issue #3698.
> [token-2022] Let error from large extensions propagate out when initing an extension

- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
The fee withdrawal functions in token-2022 don't have explicit owner checks on some accounts. Although these are not exploitable, it could allow an instruction to get a little further in processing than expected.
Add a couple of ownership checks.  Note that the linked issue mentions the reallocate instruction, but doing it there is completely unnecessary since the runtime would break first.
Fixes #3696
> token-2022: Add unnecessary owner checks for more clarity

- token/program-2022/src/instruction.rs
`decode_instruction_data` is a bit unclear, since it expects the full input, including the first byte for the instruction type. This can be confusing to users.
Since this is already used in the monorepo, it'll be too much of a headache to change this. Let's just comment the unclear behavior.
Fixes #3699
> token-2022: Clarify `decode_instruction_data`

- Cargo.lock
- token/client/src/token.rs
- token/program-2022-test/Cargo.toml
- token/program-2022-test/build.rs
- token/program-2022-test/tests/cpi_guard.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/cpi_guard/instruction.rs
- token/program-2022/src/extension/cpi_guard/mod.rs
- token/program-2022/src/extension/cpi_guard/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
to save you the pain of actually reading any of this:
```
hana@laptop:cli$ git show master
commit e69c7706fb5b1c651b086853d5cb1d688958083a (upstream/master, upstream/HEAD, master)
Author: J <jakob.povsic@gmail.com>
Date:   Wed Oct 26 05:41:37 2022 +0800
`spl-token` cli - use default config file (#3738)
* add missing load from CONFIG_FILE default path
diff --git a/token/cli/src/config.rs b/token/cli/src/config.rs
index ef6ee30f..b6cfff1c 100644
--- a/token/cli/src/config.rs
+++ b/token/cli/src/config.rs
@@ -112,6 +112,8 @@ impl<'a> Config<'a> {
eprintln!("error: Could not find config file `{}`", config_file);
exit(1);
})
+        } else if let Some(config_file) = &*solana_cli_config::CONFIG_FILE {
+            solana_cli_config::Config::load(config_file).unwrap_or_default()
} else { …
```
> revert CpiGuard reversion

- token/program-2022/src/error.rs
- token/program-2022/src/extension/mod.rs
When searching for an extension in the TLV data, if we get to an uninitialized spot, we keep going, but when initializing we stop there.  This means that we're searching too far, and completely unnecessarily.
Stop the search earlier, since nothing is ever written after the `Uninitialized` spot.
Fixes  #3701
> token-2022: Error sooner when searching for an extension in TLV data

- token/program-2022/src/processor.rs
During `unpack_uninitialized`, there's a check to make sure that the base is not initialized https://github.com/solana-labs/solana-program-library/blob/12c11f6f9c42be5d232403335f46d3a3a82da46d/token/program-2022/src/extension/mod.rs#L388-L390, but we check it anyway during mint initialization.
Remove the redundant check.
> token-2022: Remove redundant mint initialization check [ZELLIC-4.3]

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
The confidential extension `Transfer` and `TransferWithFee` instructions are identical except for the zk proof instruction that should accompany it in the same transaction.
Remove the `TransferWithFee` instruction. The instruction processor can already distinguish whether to process a transfer instruction with respect to fee by checking if the mint is extended for fees.
Fixes #3704
> [token-2022] Remove transfer with fee instruction

- token/program-2022/src/extension/confidential_transfer/processor.rs
The ElGamal pubkeys that are associated with a token account and the proof data in an `EmptyAccount` instruction are not checked for consistency, which could lead to a deflationary bug.
Add the consistency check.
> [token-2022] Add pubkey consistency check on account and proof data [ZELLIC-3.3]

- token/program-2022/src/extension/confidential_transfer/processor.rs
The ElGamal pubkeys that are associated with a token account and the proof data in a `Withdraw` instruction are not checked for consistency, which could lead to an inflationary bug.
Add the consistency check.
> [token-2022] Add pubkey consistency check on account and proof data for withdraw [ZELLIC 3.2]

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
The withdraw withheld authority can decrypt withheld fee amounts associated with accounts, which could reveal information about transfer amounts. However, this is not fully described in the confidential extension docs.
Update the docs to mention that a withdraw withheld authority can decrypt withheld amounts associated with accounts. This should be added to the confidential extension docs in spl.solana.com in a separate PR.
> [token-2022] Add doc regarding the ability of withdraw withheld authority [ZELLIC-3.4]

- .github/workflows/pull-request-docs.yml
[GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
replace `::set-output` with `>> $GITHUB_OUTPUT`
> chore: replace '::set-output' with '>> $GITHUB_OUTPUT'

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/interest_bearing_mint/mod.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/processor.rs
- token/program-2022/src/state.rs
- token/program/src/instruction.rs
- token/program/src/lib.rs
- token/program/src/processor.rs
- token/program/src/state.rs
I made a typo, as pointed out at https://github.com/solana-labs/solana-program-library/pull/3762#discussion_r1005944946
This isn't ready for CI yet, but I've been using `cargo spellcheck` https://github.com/drahnr/cargo-spellcheck to check for other errors with a pretty small additional dictionary and checking rules. Here are the results of fixing the token program and program-2022 crates.
> token: Fix some spelling mistakes

- token/js/package-lock.json
- token/js/package.json
The `CreateIdempotent` ATA instruction binding was added a few weeks ago, but there's no new release of `spl-token` that includes it.
Bump the version to release.
> token-js: Bump version to 0.3.6 for release

- token/program-2022-test/Cargo.toml
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/confidential_transfer/processor.rs
Temporarily disable confidential transfer tests that require syscalls to make breaking updates to the zk-token-sdk.
> Disable confidential transfer tests

- token/program-2022/src/extension/cpi_guard/processor.rs
- token/program-2022/src/extension/memo_transfer/processor.rs
I was reading #3756 to understand what the new extension does, and stumbled on a typo.
I also noticed an opportunity to DRY the processor code, and then realized I introduced the verbose pattern myself in RequiredMemoTransfers. Wdyt about this tidying?
> Fix CpiGuard typo, but actually DRY processor methods

- token/cli/src/main.rs
The non-transferable mint extension exists, but isn't usable in the CLI
Add the ability to create a non-transferable token mint
> token-cli: Add non-transferable mint creation

- token/cli/src/main.rs
The default account state extension exists, but isn't supported in the CLI.
Add support for the extension through a flag during `create-token` called `default-frozen-accounts` and a new command `update-default-account-state`.
I don't feel strongly about the flag names, so happy to bikeshed.  We could make it `--default-account-state initialized` or `--default-account-state frozen` as an alternative to be totally flexible during mint initialization, but that seemed more confusing, since people might feel compelled to use `--default-account-state initialized` as a "sensible default", when really they don't want the extension at all.
Fixes #3404
> token-cli: Support DefaultAccountState extension

- token/cli/src/main.rs
The default account state extension isn't working because the `default-account-state` flag doesn't say to take a value.
Specify `takes_value`
> token-cli: Specify that `default-account-state` takes a value

- token/cli/src/main.rs
- token/client/src/token.rs
The transfer fee extension has existed in token-2022 for awhile, but it's not usable in the CLI yet.
It looks like a doozy, but each commit goes in order to implement each of the points in #3408.
Note: this one is *not* urgent, just needed to be done, so I started on it, and kept going. Let me know if you prefer that I break it up.
Fixes #3408
> token-cli: Support transfer fee extension

- token/cli/src/main.rs
`command_close` didnt work with non-wsol recipients between june and whenever i converted the function to use the token client, this covers that regression
> token-cli: test close account

- associated-token-account/program-test/tests/extended_mint.rs
- token-swap/program/src/processor.rs
- token/cli/src/main.rs
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/cpi_guard.rs
- token/program-2022-test/tests/default_account_state.rs
- token/program-2022-test/tests/initialize_account.rs
- token/program-2022-test/tests/initialize_mint.rs
- token/program-2022-test/tests/interest_bearing_mint.rs
- token/program-2022-test/tests/memo_transfer.rs
- token/program-2022-test/tests/mint_close_authority.rs
- token/program-2022-test/tests/permanent_delegate.rs
- token/program-2022-test/tests/transfer_fee.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/cpi_guard/mod.rs
- token/program-2022/src/extension/memo_transfer/mod.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/permanent_delegate.rs
- token/program-2022/src/extension/reallocate.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
NFT projects want to implement a Harberger Tax on the tokens, which requires the ability for an external authority to take over the tokens if needed.  A few other projects have expressed the desire for something similar, so it's time to add it in finally.
Add the ability for mints to specify a "permanent delegate" during initialization, that can always transfer or burn tokens, similar to a normal delegate, but with an unlimited amount, and that can't be revoked.
Also, adds a warning during account initialization that the tokens can be seized, which will probably be useful for people hit by the Harberger Tax.
cc @aeyakovenko 
Fixes #2762 Fixes #2823
> token-2022: Add PermanentDelegate extension

- .github/workflows/pull-request-token.yml
The two-tx build is failing due to unsupported language features, following the bump to rust 1.65 on the monorepo. See https://github.com/solana-labs/solana-program-library/actions/runs/3446859167/jobs/5752258103 for an example
Bump the version to 1.65 for the twotx build
> ci: Bump rust stable version for twotx build

- token/cli/src/main.rs
went ahead and did my suggestion in the issue, since i think its right. also cleaned up a few owner-related things to hopefully reduce ambiguity
closes #3684
> token-cli: add `--recipient-owner` to mint

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/processor.rs
For some applications, a user may wish to receive token payments only confidentially. However, there is currently no mechanism that allows this functionality in the token-2022 program.
- Add a new `allow_non_confidential_credits` field in the confidential account extension
- Update the `process_transfer` such that if `allow_non_confidential_credits` is `false`, then the transfer fails
- Add the `EnableConfidentialCredits` and `DisableConfidentialCredits` instructions that updates the `allow_non_confidential_credits` field
Closes #3631
> [token-2022] Enable confidential payments only feature

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/process_cancel_proposal.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_create_governance.rs
- governance/program/src/processor/process_create_mint_governance.rs
- governance/program/src/processor/process_create_program_governance.rs
- governance/program/src/processor/process_create_token_governance.rs
- governance/program/src/processor/process_finalize_vote.rs
- governance/program/src/processor/process_sign_off_proposal.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/legacy.rs
- governance/program/src/state/proposal.rs
- governance/program/tests/process_cancel_proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/process_sign_off_proposal.rs
- governance/program/tests/program_test/mod.rs
- governance/program/tests/use_veto_vote.rs
Remove stats only field `voting_proposal_count` from `Governance` account to make room for more `RealmConfig` values without breaking binary layout compatibility with previous versions.
> Governance: Remove stats only fields to make room for more Config values

- stake-pool/program/src/state.rs
`calc_lamports_for_withdraw` does a ceiling calculation, which can overestimate the amount to return.
Remove the truncation, add some tests.
> stake-pool: Truncate on withdrawal calculation
