- stake-pool/program/src/processor.rs
`decrease_validator_stake` does not check that transient account meets minimum delegation requirement
From a security POV this is irrelevant since the stake program will abort the transaction. But the program already checks for the minimum rent exempt amount, so it feels weird to check for that but not for the minimum delegation.
Increase the check to include the minimum delegation.
> stake-pool: Add lamports check for transient stake account on decrease

- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
There's no test that `cleanup_removed_validators` does not run out of compute budget if removing all validators from max size pool.
Add a test for it! For posterity, it uses ~176k compute units.
> stake-pool: Add test for removing all validators from huge pool

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- token-swap/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
as described in other issues, im going to start the (somewhat complicated) release process, which in total will look like:
* bump token22. cargo release
* change monorepo version of token22 to match
* bump versions of token cli, token client, and token upgrade cli. cargo release 
this is just for the first bullet. please lmk if theres any changes you want to get into token22 before this
part of #3776
> token-2022: bump version to 0.5

- Cargo.lock
- stake-pool/program/Cargo.toml
#3714 was merged right after #3831, but still references token-2022 version 0.4, causing the build to break.
Bump stake pool to use token-2022 version 0.5
> stake-pool: Bump token-2022 to 0.5

- token/cli/src/output.rs
from the downstream projects stage ("hey, thats us!!") of monorepo ci for https://github.com/solana-labs/solana/pull/28932:
```
error[E0004]: non-exhaustive patterns: `&CpiGuard(_)` and `&PermanentDelegate(_)` not covered
--
  | --> token/cli/src/output.rs:536:11
  | \|
  | 536 \|     match ui_extension {
  | \|           ^^^^^^^^^^^^ patterns `&CpiGuard(_)` and `&PermanentDelegate(_)` not covered
  | \|
  | ::: /var/lib/buildkite-agent/builds/ci8/solana-labs/solana/account-decoder/src/parse_token_extension.rs:24:5
  | \|
  | 24  \|     CpiGuard(UiCpiGuard),
  | \|     -------- not covered
  | 25  \|     PermanentDelegate(UiPermanentDelegate),
  | \|     ----------------- not covered
  | \|
  | = help: ensure that all possible cases are being handled, possibly by adding wildcards or more …
```
> token-cli: temp add wildcard to account output

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/error.rs
- governance/program/src/processor/process_cast_vote.rs
- governance/program/src/processor/process_relinquish_vote.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/realm_config.rs
- governance/program/tests/process_cancel_proposal.rs
- governance/program/tests/process_cast_vote.rs
- governance/program/tests/process_finalize_vote.rs
- governance/program/tests/process_relinquish_vote.rs
- governance/program/tests/process_set_realm_config.rs
- governance/program/tests/program_test/mod.rs
- governance/program/tests/use_proposals_with_multiple_options.rs
- governance/program/tests/use_veto_vote.rs
Introduce voting cool of time to add an extra time when `Community` and/or `Council` can disapprove or veto proposals.
- All existing Governances with `max_voting_time`  > `10h` default to `1h` cool of time. The setting can be further adjusted or removed via config change proposal. 
- Cool of time doesn't apply when a vote ends early with `Early` or `Strict` tipping rules.
> Governance: voting_cool_off_time

- token/twoxtx.patch
As reported on Stack Exchange and select users, the 2x-tx build isn't working.  See https://solana.stackexchange.com/questions/4449/solana-build-error-after-twoxtx-setup-sh-patch-with-2x-transaction-size for more info about the error.
Fix the const assert checks in the patch.
cc @askibin
> ci: Fix 2xtx build

- stake-pool/program/tests/withdraw.rs
There are still new failures in the stake pool tests. The most recent one https://github.com/solana-labs/solana-program-library/actions/runs/3576868159/jobs/6015187724 is likely due to running the same transaction signature twice.
Make the transaction different to force a new signature.
> stake-pool: Make transaction signatures unique in withdraw test

- Cargo.lock
- associated-token-account/program/Cargo.toml
- stake-pool/cli/Cargo.toml
In preparation for a new ATA release, we need to bump the version. ✅
> Bump ATA to v1.1.2

- token/program-2022/src/extension/confidential_transfer/processor.rs
In the confidential extension, the proof instruction for a confidential transfer instruction contains an expected `new_source_ciphertext` field that represents the new source account's new spendable balance. The zero-knowledge proof is checked with respect to this field, guaranteeing that the source account's new spendable balance is solvent. However, the token-2022 processor does not verify whether this ciphertext is computed correctly with respect to the original source account's spendable balance.
Check that the ciphertext in the proof data is consistent with the original source account data in the instruction processor.
> [token-2022] Check expected new source ciphertext in processing confidential transfer [ZELLIC 3.1]

- stake-pool/program/src/big_vec.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/withdraw.rs
- stake-pool/program/tests/withdraw_edge_cases.rs
As the value of stake pool tokens increase, it could become impossible to reduce a stake account to its minimum value due to rounding.
This is a very tricky problem, but to give at least some cushion, round up to the lamports-per-pool-token value.
While working on this, I refactored the `BigVec` search to go through a closure rather than a function pointer, and it reduced compute unit consumption so much that the max pool size has increased by 50%!
> stake-pool: Add tolerance for stake accounts at minimum

- account-compression/Cargo.lock
- account-compression/programs/account-compression/Cargo.toml
- account-compression/programs/account-compression/src/state/concurrent_merkle_tree_header.rs
- account-compression/programs/account-compression/src/state/mod.rs
Indexing CMT is made difficult without additional types.
Consider when needing to ensure we have not missed a tree while indexing. We will need an account data source.
* Geyser
* RPC Via GPA
If we get the raw account data and deserialize it into a `ConcurrentMerkleTreeHeader` we will not be able to introspect the data version or event the account type.
This pr exposes new types and bumps the version. Please consider this contribution as it could be a blocker to the additional layer of merkle tree backfilling needed for Metaplex Read API.
I also add a `get_creation_slot` on the Main header struct as a convenience feature as I'm relatively sure that information will be present in all data versions.
> Expose more types from CMT

- Cargo.lock
- token/program-2022-test/Cargo.toml
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
The pending balance in a confidential extension account is divided into lo and hi components. However, the encrypted fee that is associated with transfer with fee proof data was not divided into lo and hi components. The single encrypted fee was simply added on to the lo pending balance.
When the fee amount is below 2^16, this is fine. However, for larger fee amounts, this could potentially result in a negative pending balance.
This PR fixes this issue by dividing the encrypted fee in the proof data into lo and hi components.
Fixes issue #3705
> [token-2022] Divide encrypted fee into lo and hi (TOB-STK-11)

- binary-option/program/src/error.rs
- binary-option/program/src/processor.rs
- binary-option/program/src/state.rs
This PR fixed three integer overflows that have been confirmed. If there're any other actions I need to take, please let me know. Thanks!
> binary-option: Fixed three integer overflows

- Cargo.lock
With the update of the repo to 1.4.10 in #3872, we also need to keep `Cargo.lock` in sync with the updated dependencies.
Update Cargo.lock
> ci: Update Cargo.lock with 1.4.10 crate resolution

- Cargo.lock
- feature-proposal/program/Cargo.toml
- governance/test-sdk/src/lib.rs
- name-service/program/tests/functional.rs
- token/program-2022-test/tests/initialize_account.rs
- token/program-2022-test/tests/initialize_mint.rs
- token/program-2022-test/tests/memo_transfer.rs
- token/program/tests/close_account.rs
When making the banks client error more expressive, we had to add a bunch of `useless_conversion` allows in the code to keep the downstream projects build intact in #2657
Now that the change is rolled out, we can remove all of the `#[allow(...)]`s
> clippy: Remove `useless_conversion`

- Cargo.lock
SPL is still on uint version 0.9.1, but 0.9.5 exists.
Update the dep!
> deps: Update uint to 0.9.5

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
some random things i noted when reviewing the program as a whole. the comment changes are obvious enough. the change from `!=` to `>` is to cope with the possibility that `MINIMUM_DELEGATION_SOL` rises to put a poorly resourced validator below it, which otherwise would require the pool to stake _more_ to it to be able to remove it
> stake-pool: allow removing validator below minimum

- Cargo.lock
The bump of `uint` to version 0.9.5 in #3901 broke the build, roughly *doubling* the number of compute units for math, which broke some tests.
Revert the upgrade
> deps: Revert uint

- stake-pool/program/tests/huge_pool.rs
The new rust compiler and standard library generate slightly increased number of SBF instructions, which triggers failure of the stake-pool/program/tests/huge_pool.rs test due to running over the compute budget limit. I would like to decrease the maximum size of the pool to make the test pass when compiled by the new toolchain.
> Decrease MAX_POOL_SIZE in huge_pool test to make it work with rust 1.65

- docs/sidebars.js
There's a fees page for stake pools, but it's not exposed on the sidebar.
Add the fees page
> docs: Add stake pool fees page to the sidebar

- stake-pool/js/package-lock.json
- stake-pool/js/package.json
- stake-pool/js/rollup.config.js
- stake-pool/js/tsconfig.json
stake-pool-js links its browser CJS output to an ESM build. This is likely to cause issues for a browser build that expects CJS. This PR adds an additional CJS build for browser output, and simplifies the Rollup config a little.
> fix: stake-pool-js: add browser CJS build

- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Summary of changes:
- Refactor `check_source_confidential_account` function into `valid_as_source` method 
- Refactor `check_destination_confidential_account` function into `valid_as_dest` method
- Organize pending balance counter increment into `increment_pending_balance_credit_counter` method
- Skip ciphertext arithmetic on `Deposit` and `Withdraw` if the amount is zero (issue #3560)
- Rename `previous_instruction` to `zkp_instruction` and other minor variable renaming for consistency
- Add comments on potentially confusing parts of the code
> [confidential-extension] Refactor and add comments for readability

- docs/src/token-2022/extensions.mdx
The token-2022 extension docs say "CLI support coming soon" everywhere, but the CLI supports everything now.
Add usage examples for the CLI to the docs.
> docs: Add token-2022 extension usage examples in CLI

- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/interestBearingMint/actions.ts
- token/js/src/extensions/interestBearingMint/state.ts
consider this a suggestion to accept or reject. this is the only variant on the `ExtensionType` enum that doesnt match the name used in token22. because the js enum is supposed to correspond 1:1 with the program enum (to the extent that the order must match too, because the js enum values are compared to the type tags stored in `tlv_data` onchain) i feel they should be identical
admittedly the name is worse. as an alternative maybe we should rename `InterestBearingConfig` instead. but either way the js should be subservient to the rust imo
> token-js: rename ExtensionType.InterestBearingMint

- token/client/src/token.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Currently, the ElGamal public key that is needed to instantiate a confidential extension account is included in both the Token-2022 `ConfigureAccount` instruction and the corresponding zk proof instruction. This is in-line with the other instructions like `Transfer` and `Withdraw` where the public key is encoded in both the token instruction and zkp instruction. However, unlike these two instructions, the `ConfigureAccount` is not susceptible to front-running attack and therefore, this redundant inclusion of the public key is not needed. 
As an optimization, remove the public key from the `ConfigureAccount` instruction and use the public key from the zkp instruction for processing.
> [confidential-extension] Remove ElGamal pubkey from confidential transfer `ConfigureAccount` data

- token/program-2022/src/extension/transfer_fee/mod.rs
Fixing a small typo in the description of the ceiling division function in transfer fee. `floor[ dividend + (divisor - 1) / divisor ]` should be `floor[ (dividend + divisor - 1) / divisor]`.
In the process, changing `dividend` to `numerator` and `divisor` to `denominator` to be consistent with the rest of the fee calculation functions.
> token-2022: Fix parenthesis typo in fee calculation doc

- token/program-2022/src/extension/transfer_fee/mod.rs
The docs for the `ceil_div` function was updated so that `dividend` was updated to `numerator` and `divisor` was updated to `denominator`, but the actual variable names were not updated. This PR updates the variable names.
> token-2022: fix `ceil_div` variable name

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Currently, the `InitializeMint` instruction allows the initiator to submit the entire `ConfidentialTransferMint` state, allowing it to instantiate `withheld_amount` to any ciphertext. This allows the initiator to potentially create new tokens confidentially without affecting the mint.
The `UpdateMint` instruction allows the authority to change the `withdraw_withheld_authority_encryption_pubkey` and `withheld_amount`. As in `InitializeMint`, the authority could potentially overwrite the withheld amount and create or burn tokens privately without being detected.
This PR restricts the two instructions above. For `InitializeMint`, the initial `withheld_amount` is always set to be the zeroed ciphertext. For `UpdateMint`, modify it so that it does not affect …
> [confidential-extension] Restrict `InitializeMint` and `UpdateMint` instructions

- governance/program/src/error.rs
An small update to add comments of error numbers to error definitions for Governance. It happens to me to get an error and it's easier to find the number when mentioned directly in source code.
> Governance: adding error labels

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/pod.rs
Summary of changes:
- Add `OptionalNonZeroEncryptionPubkey` struct
- Use `OptionalNonZeroPubkey` and `OptionalNonZeroEncryptionPubkey` for the optional pubkey fields in the confidential extension mint
Closes issue #3941
> [confidential-extension] Use `OptionalNonZeroPubkey` and `OptionalNonZeroEncryptionPubkey` for confidential extension

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/increase.rs
As brought up during the single validator manager proposal #3881, there's an annoying "attack" vector where a person puts in the minimum stake delegation at the start of an epoch and immediately increases stake on the validator, preventing later SOL deposits from being activated.
There's nothing technically stopping two activating stakes from merging, so introduce a new instruction on the stake pool program which allows for a second increase in an epoch.
The normal instruction splits into the transient account and then activates it, so this instruction:
* splits into an ephemeral stake account
* if the transient account exists: merges the ephemeral stake account into the transient stake account\
* if the transient account doesn't exist: splits from ephemeral into transient, so pools can …
> stake-pool: Add "IncreaseAdditionalValidatorStake" instruction

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/helpers/mod.rs
It's possible to do multiple increases in a stake pool with #3924, but this is also possible with decreases!
There's nothing technically stopping two deactivating stakes from merging, so introduce a new instruction on the stake pool program which allows for more decreases in an epoch.
The normal instruction splits into the transient account and then deactivates it, so this instruction:
* splits into an ephemeral stake account
* if the transient account exists: merges the ephemeral stake account into the transient stake account
* if the transient account doesn't exist: splits from ephemeral into transient, so pools can transition to always using this new instruction
The implementation is extremely similar to #3924, and this instruction is less important, so be sure to check this out …
> stake-pool: Add `DecreaseAdditionalValidatorStake` instruction

- docs/src/stake-pool.md
Neodyme re-audited the stake pool program and published the report, but it isn't available for people to find.
Add it to the docs. At the same time, update the audit links to use the security-audits repo rather than `solana.com`
> docs: Add second stake pool audit by Neodyme

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/redelegate.rs
- stake-pool/program/tests/withdraw.rs
- stake-pool/program/tests/withdraw_edge_cases.rs
https://github.com/solana-labs/solana/pull/26294 added the ability to redelegate stake in one go, without waiting for cooldowns and warmups, allowing delegators to move stake much more easily.
While normal delegators will certainly make good use of it, stake pools will truly benefit from it, allowing managers to maintain high performance on their pool.
Add the ability to redelegate on stake pools!
The implementation aims to keep this simple, reusing the transient stake accounts used for normally rebalancing pool.  The instruction processor roughly does:
* split from source account into transient
* redelegate from transient account into ephemeral account -- this account is only used for the duration of the transaction, and uses a PDA to avoid the additional signature cost on a normal …
> stake-pool: Support stake redelegation

- token/twoxtx-setup.sh
this should hopefully mean we dont need to update the file all the time. i was starting on an experiement to have the ci script merge from a special twotx branch into monorepo master, and get rid of the patch file, and discovered you can actually have git fall back on the merge algorithm when a patch file fails to apply
> twotx: allow git to merge the twotx ci patch

- ci/do-audit.sh
There was a security vulnerability issued on tokio 1.14.  https://github.com/solana-labs/solana/pull/29585 added an exception for this advisory.
Do the same thing in SPL, and add the exception.
> ci: Add exception for tokio in audit job

- Cargo.lock
- Cargo.toml
- examples/rust/transfer-tokens/Cargo.toml
- examples/rust/transfer-tokens/src/entrypoint.rs
- examples/rust/transfer-tokens/src/lib.rs
- examples/rust/transfer-tokens/src/processor.rs
- examples/rust/transfer-tokens/tests/functional.rs
There's no program-test example that uses spl-token, and I want to demo one.
Add a simple example "giver" program that simply transfers tokens from a PDA-owned account.
Fixes  #829
> example: Token transfer with PDA

- examples/rust/transfer-tokens/src/processor.rs
- examples/rust/transfer-tokens/tests/functional.rs
The token transfer example is great, but the test hardcodes a bunch of accounts and uses ProgramTest's `set_account` to set them up. This isn't indicative of how to really create token accounts, since you typically need to send transactions to the network.
Improve the test by actually sending transactions.
> examples: Use txs instead of set_account in token test

- account-compression/Cargo.lock
- account-compression/programs/account-compression/src/canopy.rs
- account-compression/programs/account-compression/src/lib.rs
- account-compression/programs/account-compression/src/macros.rs
- account-compression/programs/account-compression/src/state/concurrent_merkle_tree_header.rs
- account-compression/programs/account-compression/src/zero_copy.rs
- account-compression/sdk/tests/accountCompression.test.ts
Right now this instruction fails when the canopy is not fully initialized, because the `merkleTree` account is passed as read only.
I changed this instruction to be read-only so now the instruction works as intended
> Account Compression: Change VerifyLeaf to avoid modifying canopy

- governance/program/src/instruction.rs
- governance/program/src/processor/process_revoke_governing_tokens.rs
- governance/program/src/state/realm_config.rs
- governance/program/tests/process_revoke_governing_tokens.rs
- governance/program/tests/program_test/cookies.rs
- governance/program/tests/program_test/mod.rs
Make it possible for the owner of governing `Membership` token to voluntarily revoke its own memebership
> Governance: Allow token owner to revoke their own membership

- stake-pool/program/tests/withdraw_edge_cases.rs
#3980 is failing on `success_with_small_preferred_withdraw` while adding a new validator, maybe due to a reused blockhash.
Refresh the blockhash more in the test
> stake-pool: Refresh blockhash more on failing test

- stake-pool/program/tests/withdraw_with_fee.rs
After the most recent test fix, the merge into master had some errors in the `withdraw_with_fee` tests during CI, e.g. https://github.com/solana-labs/solana-program-library/actions/runs/3951739033/jobs/6765965952
Yet again, refresh the blockhash more often.
> stake-pool: Refresh blockhash more in another test

- stake-pool/program/tests/withdraw.rs
We're still getting a failure on `fail_with_not_enough_tokens` in CI https://github.com/solana-labs/solana-program-library/actions/runs/3961304648/jobs/6786565676
Refresh that blockhash a bit earlier, and hope this will finally be stable.
> stake-pool: Refresh blockhash earlier in flakey test

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/redelegate.rs
During increase additional, decrease additional, and redelegate, the stake pool program relies on the stake program to check that the merge is correct.
During the epoch in which a validator is added, however, its stake will be "activating", so if you "increase" and then "decrease additional", the decreased stake will actually be *added* back in since the additional stake is deactivated and then merged into an activating stake, which is valid.
Don't lean on the runtime, and just do the check explicitly.
> stake-pool: Check transient stake state explicitly during increase / decrease / redelegate

- stake-pool/program/src/processor.rs
- stake-pool/program/tests/vsa_remove.rs
Deactivating a validator requires reducing its active stake to the minimum delegation first. However, the funds all go back to the reserve anyway, so there's no reason to gate the removal to some lamport amount.
Remove the lamport check.
Fixes #3994
> stake-pool: Remove lamport minimum for validator removal by staker

- stake-pool/program/src/processor.rs
With #3987, we added a check to make sure that the existing transient stake was "going in the right direction", ie. that it's activating during "increase additional" and "redelegate", and that it's deactivating during "decrease additional". The existing check is oversimplified, and only checks that it's activating OR active / deactivating OR inactive.
Make the check a bit more strict, to make sure that it's activating *in that epoch*. This is a pedantic change, since it's typically impossible to "increase additional" / "redelegate" with transient stakes that are active or inactive, unless there's an explicit ask to *not* merge transient accounts while updating. Either way, the runtime would catch that.
> stake-pool: Make activating / deactivating check stricter

- stake-pool/program/src/instruction.rs
There are some gotchas in the `redelegate` behavior, first in the amount that is actually moved to the destination validator, and another in an implicit check that is not called out.
Document both of these explicitly.
> stake-pool: Document redelegate behavior better

- stake-pool/cli/src/main.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/withdraw.rs
There's some `unwrap`s in the stake pool program, which can cause issues.
Remove a couple of them.  When trying to remove the ones from `active_lamports_greater_than` and `transient_lamports_greater_than`, it increased compute usage so much that the max pool size went down to 2500, so it's not worth removing all of them.
> stake-pool: Remove some unwraps

- .github/workflows/pull-request-token.yml
The twoxtx build is currently failing because the monorepo has deprecated `Pubkey::new`, SPL still uses it, and CI builds all tests with `-D warnings`.
There's no release of 1.14 with the `Pubkey::try_from` implementation on `&[u8]` just yet, so we can't fix this correctly until that's ready.  Keep it simple for now and just build the token-2022 tests directly, without `-D warnings`.
#4006 will keep track of the later work
> ci: Update twoxtx build to ignore warnings

- stake-pool/program/src/error.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/deposit_sol.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/withdraw.rs
- stake-pool/program/tests/withdraw_sol.rs
When depositing and withdrawing from stake pools, it's impossible for a user to guarantee how much they'll receive.
Add `*WithSlippage` variants to all deposit and withdraw instructions, which guarantee a minimum output, similar to an AMM.
> stake-pool: Add slippage to all deposit and withdraw ixs

- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
When using `Pubkey`s as `&[u8]`s, the stake pool program does `Pubkey::to_bytes()`, which creates a copy of the data into a new array. This is inefficient copying of existing data, and `as_ref()` has been shown to reduce compute usage in the past.
Switch to using `as_ref()` rather than `to_bytes()` everywhere. While I was at it, I tweaked the `huge_pool` test value to the current maximum, which is 3300 validators with 200k compute units. This PR has no impact on the max pool size supported, but at least it reduces compute units a little bit for other instructions.
> stake-pool: Use `Pubkey::as_ref()` instead of `to_bytes()`

- stake-pool/program/tests/huge_pool.rs
The monorepo downstream build is failing due to the bumped up huge pool number, see https://buildkite.com/solana-labs/solana/builds/89326
Bump it back down to 3k, where it was before
> stake-pool: Revert huge pool number to 3k

- stake-pool/program/src/processor.rs
Ensure rent-exempt calculations are performed on actual data size instead of theoretical data size. E.g.
in AddValidatorToPool, rent exempt calculation on the reserve_pool is performed on the default
account size:
```
let space = std::mem::size_of::<stake::state::StakeState>();
let stake_minimum_delegation = stake::tools::get_minimum_delegation()?;
let required_lamports = minimum_delegation(stake_minimum_delegation)
.saturating_add(rent.minimum_balance(space));
```
If it was possible to create a Stake account larger than the default (200 bytes), this computation would
be inaccurate and the stake account may be able to be closed here.
Note: the stake program validates the account size during initialization and during split the remaining
lamports must be either greater than the minimum …
> stake-pool: Specify the space used for new stake accounts (OS-SSP-SUG-00)

- token/twoxtx.patch
web3.js was removed from the monorepo, and the 2xTx patch file makes a change to the web3.js transaction size constants, so it fails to apply.
Remove the web3.js diff
> ci: Update twoxtx patch file

- account-compression/sdk/package.json
This package is missing from the distributed version of `@solana/spl-account-compression`
Will require cutting a new release of this SDK and ensuring that this package makes it to the destination!
found this when installing this library and noticing errors around missing packages
> Moving `typescript-collections` to `dependencies`

- account-compression/sdk/package.json
New minor version with `typescript-collections` as dependency. This was an error of omission on my part when I added the `merkle-tree` file into the main export path.
> Account Compression: Bump TS SDK Version

- stake-pool/program/tests/helpers/mod.rs
- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/nonTransferable.ts
- token/js/test/e2e-2022/nonTransferableMint.test.ts
- token/program-2022-test/tests/non_transferable.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/non_transferable.rs
- token/program-2022/src/processor.rs
The non-transferable token status is only stored on the mint, so during an unchecked transfer of non-transferable tokens, the instruction processor doesn't know to restrict the transfer.
Add a bit to non-transferable token accounts to show that they shouldn't be transferred, even during unchecked transfers.
> token-2022: Fix non-transferable extension for unchecked transfers

- token/cli/src/main.rs
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
In token-2022, there is currently an inconsistency in the way authorities associated with extensions are updated. In the confidential transfer (CT) extension, the instruction `ConfidentialTransferInstruction::UpdateMint` must be used to update the mint authority. However, in the rest of token-2022, `TokenInstruction::SetAuthority` instruction is used to update the authorities. 
- Extend the `AuthorityType` to include `AuthorityType::ConfidentialTransfer` and update the `SetAuthority` instruction to support confidential transfer authority
- Limit the `ConfidentialTransferInstruction::UpdateMint` to only update the mint parameters, not the authority.
In addition to fixing the inconsistency, separating the ability to (1) update the CT mint authority and (2), update the rest of the CT mint …
> [token-2022, confidential-extension] Add confidential transfer authority type

- token/cli/src/config.rs
- token/cli/src/main.rs
- token/client/src/token.rs
As reported by a user, the multisig signer functionality is currently not working, since it's including the multisig address itself as a signer for the transaction.
Don't include the owner as a signer if we're in a multisig situation. The main changes are the replacements of `!bulk_signers.contains(&authority_signer)` with `config.multisigner_pubkeys.is_empty()` and then always filtering out the authority in the token client. I think that's correct, but please correct me if I'm wrong!
> token-cli: Remove multisig owner as signer

- governance/program/src/error.rs
- governance/program/src/state/proposal.rs
Recreated PR (https://github.com/solana-labs/solana-program-library/pull/3879) for having an API method to check the final state of the proposal. Expected to be called from outside (from other contract).
> Governance: assertion for proposal final state

- governance/program/src/error.rs
A small update of comments on `error.rs` to label missing errors with numbers.
> Governance: add comment labels for error.rs

- Cargo.lock
Just like https://github.com/solana-labs/solana/pull/30173, there's a [vuln](https://rustsec.org/advisories/RUSTSEC-2023-0007) in the openssl-src dependency
Update to 111.25 where it's used.
> ci: Update openssl crate per RUST-SEC advisory

- stake-pool/program/tests/withdraw_edge_cases.rs
CI still randomly fails on the stake pool tests, ie https://github.com/solana-labs/solana-program-library/actions/runs/4123712790/jobs/7122054405
Refresh the blockhash more often during tests.
> stake-pool: Refresh blockhash more often to please CI

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- stake-pool/program/Cargo.toml
- token-swap/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
We've had a few changes to token-2022 since 0.5.0, including confidential transfer instruction changes, a fix to non-transferable tokens, and a CLI fix.
The CLI fix is the main driver for this, since it would be good to get a release out with the fix.
Bump token-cli, token-client, and token-2022 for a new release. Let me know if you have any additional bits you want to sneak in before cutting!
> token-2022: Bump program, cli, and client for release

- .github/workflows/pull-request-name-service.yml
- ci/js-test-name-service.sh
- name-service/js/package.json
- name-service/js/test/e2e/index.test.ts
- name-service/js/test/unit/index.test.ts
- name-service/js/yarn.lock
> name-service-js: add tests

- README.md
- SECURITY.md
- account-compression/README.md
- binary-option/README.md
- binary-oracle-pair/README.md
- docs/src/token-lending.md
- docs/src/token-swap.md
- docs/src/token-upgrade.md
- examples/c/README.md
- examples/rust/README.md
- farms/docs/intro.md
- governance/README.md
- instruction-padding/program/README.md
- libraries/math/README.md
- managed-token/README.md
- memo/README.md
- name-service/README.md
- name-service/js/src/utils.ts
- record/program/README.md
- shared-memory/README.md
- stake-pool/README.md
- stateless-asks/README.md
- token-lending/README.md
- token-lending/program/src/pyth.rs
- token-swap/README.md
- token-swap/proposals/DynamicMarketMaking.md
- token-upgrade/README.md
- token/README.md
Although the information is in the security policy, it's hard to find out which programs have been audited.  Also, we still use the S word in a few places in the docs.
* Add disclaimers to all unaudited program READMEs and docs
* Replace / remove the S-word with openbook / coral
* Add the list of actively maintained programs to the top-level README
Sorry that this is a bit of a kitchen-sink PR, but I'm hoping it won't be too annoying to read through since it's all docs changes.
> docs: Clarify audit status of all programs, no S word

- account-compression/Cargo.lock
- libraries/concurrent-merkle-tree/src/concurrent_merkle_tree.rs
This pr adds a getSeq method to the zero copy CMT struct needed for indexing.
> Add GetSeq to CMT

- libraries/concurrent-merkle-tree/Cargo.toml
Expose `get_seq` method on ConcurrentMerkleTree
> Concurrent Merkle Tree Release 0.1.3

- patch.crates-io.sh
as it stands, if you run `./patch.crates-io.sh /path/to/solana`, it updates you to the monorepo crates, but leaves you on the spl version of rust. this causes breakage when monorepo uses features that are stable on their version but unstable on ours
monorepo uses `rust-toolchain.toml` now so the fix is simple! and correct, since we always track the monorepo rust version when we formally update
> track rust version when using local monorepo

- .github/workflows/pull-request-token.yml
- token/twoxtx-setup.sh
The cargo-test-sbf-twoxtx CI job seems broken since the monorepo landed workspace inheritance.
SPL is on v1.60, and workspace inheritance was added in v1.64. So the twotx job probably needs to inherit the monorepo's rust toolchain and use the monorepo's `cargo-test-sbf`
Also, the SPL workspace needs to exclude the nested twoxtx-solana monorepo.
Needs rebase on #4064
> Fix twoxtx setup vis-a-vis workspace inheritance

- patch.crates-io.sh
The patch crates io script tries to use the version of Rust from the monorepo by copying the rust-toolchain.toml file, but this file doesn't exist for releases prior to 1.15.
Only copy the toolchain file if it exists. Since this is blocking the monorepo on 1.14 currently, I'll merge this right away.
> ci: Only copy monorepo toolchain file if it exists

- token/cli/src/output.rs
Due to circular dependencies with the token-cli, adding new extensions to the account-decoder in the mono repo causes ci tests to fail. `UiExtension` in the account decoder must cover all extension types, the `display_ui_extension` function in the token-cli requires all `UiExtension` types to be supported, and the ci tests require both crates to compile for any changes.
Replace `UiExtension::UnparseableExtension` with a catch-all pattern so that any new extensions that are added to the account-decoder are caught and processed by the token-cli.
> token-cli: add a catch-all pattern to cover all UiExtension instances when displaying token-22 extensions

- Cargo.lock
The account compression crate version was bumped in #4061, but the Cargo.lock file still has 0.1.2
Update the lockfile version too
cc @ngundotra
> ci: Update Cargo.lock for account compression version bump

- docs/src/associated-token-account.md
**Problem**
The async `findProgramAddress` function is deprecated in favor of `findProgramAddressSync`, and the docs don't currently reflect that.
**Changes**
Update docs to show newcomer developers that this is the method that should be used when deriving ATAs and PDAs in general.
> docs: Update ATA derivation example to use `findProgramAddressSync`

- Cargo.lock
- token/cli/Cargo.toml
New security advisory: https://rustsec.org/advisories/RUSTSEC-2023-0018
bump `tempfile` to v3.4.0
> update tempfile to 3.4

- Cargo.lock
- associated-token-account/program/Cargo.toml
- stake-pool/cli/Cargo.toml
Bump ATA to v1.1.3 that uses token-2022 0.6.
> Bump ATA to v1.1.3

- token/client/Cargo.toml
- token/client/src/token.rs
- token/program-2022-test/Cargo.toml
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
There is a PR in progress https://github.com/solana-labs/solana/pull/29996 that updates the proof verification program so that it break token-2022 confidential transfer. This results in downstream CI tests to fail.
Temporarily create a `proof-program` feature in the token-2022 program to disable the components that uses the proof program. Once https://github.com/solana-labs/solana/pull/29996 is merged and solana-program is updated, either make the `proof-program` feature as default or remove the feature altogether.
> [token-2022] Create proof-program feature

- token/client/Cargo.toml
- token/program-2022/Cargo.toml
There is a breaking update to the zk proof program (https://github.com/solana-labs/solana/pull/29996) in the monorepo that breaks downstream builds. https://github.com/solana-labs/solana-program-library/pull/4040 temporarily disables token-2022 components that rely on the proof program. A new patch of the token-2022 program should be released.
Bumping the token-2022 program and client to prepare for the patch release. Once the monorepo updates to this patch release, the downstream ci failure should be fixed.
> token-2022: bump program and client for a patch release

- Cargo.lock
- token/program-2022/src/extension/confidential_transfer/instruction.rs
https://github.com/solana-labs/solana-program-library/pull/4040 disables the proof components in the token-2022 program, but it missed the `transfer_with_fee` instruction constructor.
Temporarily disable `transfer_with_fee` constructor by including it in the `proof-program` feature.
> token-2022: disable transfer_with_fee instruction constructor

- docs/src/account-compression/concepts.md
> remove extra `can use` on account-compression docs

- account-compression/sdk/package.json
- account-compression/sdk/src/merkle-tree/index.ts
- account-compression/sdk/tests/merkleTree.test.ts
Additions:
- Easier to use constructor method `sparseMerkleTreeFromLeaves` which by default creates sparse MerkleTree leaves for you
- Easier to use `verify` & `hashProof` methods (now static)
Fix:
- Move `js-sha3` to dependencies, instead of `devDependencies`
> Account Compression TS SDK: add `MerkleTree` static functions

- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
This fixes a compilation error if spl-token-client is compiled with the proof-program feature, as it previously did not compile spl-token-2022 with the corresponding feature.
> spl-token-client: Depend on spl-token-2022/proof-program

- .github/label-actions.yml
- .github/workflows/label-actions.yml
The monorepo has a way to add an automated message and close an issue with the "question" label, as seen here https://github.com/solana-labs/solana/issues/30685#issuecomment-1482051342, but SPL does not.
It's useful for SPL too, so add it in!
> CI: Add GitHub action to post message and close on "question" label

- .github/workflows/spl_action.yml
- docs/publish-docs.sh
The scope for docs has changed, but SPL didn't get the update.
`VERCEL_SCOPE` is defined on the repo, so consume it in the action / script!
> docs: Add scope from secrets

- docs/publish-docs.sh
#4110 tried to fix the docs build, but messed up because of a dangling comma, which made the config file invalid JSON.
Remove the dangling comma
> docs: Remove dangling comma in JSON config

- token/program-2022/src/processor.rs
- token/program/src/processor.rs
- Previous test seems to use owner but large amount, wrong code path?
- assertion that trying to use more than delegated amount with sufficient amount fails
- assertion that using someone else than delegate or owner after approving delegate fails
- trailing OwnerMismatch test for delegate being wiped when all delegated amount has been used remains, but unrelated to above necessary tests
> More direct delegate test

- Cargo.lock
- Cargo.toml
- stake-pool/single-pool/Cargo.toml
- stake-pool/single-pool/program-id.md
- stake-pool/single-pool/src/entrypoint.rs
- stake-pool/single-pool/src/error.rs
- stake-pool/single-pool/src/instruction.rs
- stake-pool/single-pool/src/lib.rs
- stake-pool/single-pool/src/processor.rs
this is obviously a very rough sketch, but just to give an idea of what i had in mind re: "what if the 1lamp minimum stays and we did a new single-validator stake pool program instead of an automated manager on top of the existing one"
welcome to the stake birdbath
```
hana@laptop:stake-pool$ wc program/src/*
366   1222  12000 program/src/big_vec.rs
26     59    711 program/src/entrypoint.rs
154    530   5592 program/src/error.rs
1736   5652  64508 program/src/instruction.rs
175    552   5369 program/src/lib.rs
3950   9342 167792 program/src/processor.rs
1329   4483  49937 program/src/state.rs
7736  21840 305909 total
hana@laptop:stake-pool$ wc birdbath/src/*
26    59   711 birdbath/src/entrypoint.rs
154   530  5592 birdbath/src/error.rs
261   648  8991 birdbath/src/instruction.rs
45 …
```
> single-validator stake pool program

- token/js/src/actions/createAssociatedTokenAccount.ts
- token/js/src/actions/createAssociatedTokenAccountIdempotent.ts
- token/js/src/actions/createWrappedNativeAccount.ts
- token/js/src/actions/getOrCreateAssociatedTokenAccount.ts
Replace asynchronous `getAssociatedTokenAddress` calls with synchronous `getAssociatedTokenAddressSync`.
> [token-js] Switch to associated token address sync.

- Cargo.lock
- governance/program/src/error.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/vote_record.rs
- governance/program/tests/use_proposals_with_multiple_options.rs
Implementation of `Weighted` multi choice vote type. The implementation makes the `MultiChoice` `VoteType` to be of either `Approval` type (existing behaviour) or `Weighted` that makes possible to vote with percentage of the full vote weight.
The change is not backward compatible for multi choice proposals. However the option has never been exposed in the UI and hence hasn't been used. In case there is an unknown instance of spl-gov which uses it it would only affect historical proposals which couldn't be loaded
> Governance: MultiChoice type Weighted

- Cargo.lock
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token/cli/Cargo.toml
- token/cli/src/config.rs
- token/cli/src/main.rs
- token/client/Cargo.toml
- token/client/src/token.rs
- token/program-2022-test/Cargo.toml
The supplied `--blockhash` arg is ignored when online and finally sending the transaction, making it impossible to work with nonces.
Plumb the nonce blockhash down and use it.
> token-cli: Always use supplied blockhash for nonce txs

- account-compression/Cargo.lock
- account-compression/programs/account-compression/Cargo.toml
- account-compression/programs/account-compression/src/macros.rs
bumps crate version to 0.1.9
Previously exported macros were unusable bc inner macros were private. Now fixed.
> [compression] expose macros for invoking getter/setters on const generic CMT

- docs/sidebars.js
- docs/src/token-2022.md
- docs/src/token-2022/status.md
Although the GitHub project information lives at https://github.com/orgs/solana-labs/projects/34/views/1, that's not really consumable by a general audience.
Add a token-2022 one-pager. While I was at it, I added the NCC audit, hope that's ok!
> docs: Add token-2022 one-pager

- token/cli/src/config.rs
In several places in the cli `Result`s are unwrapped without error handling.
Check `Result`s for `Err`.
> token-cli: error handling fixes

- Cargo.toml
- patch.crates-io.sh
- token/twoxtx-setup.sh
The token twoxtx build is failing because of workspace dependencies in the monorepo.
Exclude the local solana directory when patching crates to avoid two conflicting workspaces. This is a much better version of #4121 thanks to @yihau
> ci: Exclude solana dir during patch to avoid workspace issues

- account-compression/programs/account-compression/src/lib.rs
Without these 2 exports using exported macros from macros.rs is not possible.
```
error[E0603]: enum `AccountCompressionError` is private
--> programs/tcomp/src/shared.rs:9:5
|
9  |     AccountCompressionError, ChangeLogEvent, ConcurrentMerkleTree,
|     ^^^^^^^^^^^^^^^^^^^^^^^ private enum
|
note: the enum `AccountCompressionError` is defined here
error[E0603]: enum `ChangeLogEvent` is private
--> programs/tcomp/src/shared.rs:9:30
|
9  |     AccountCompressionError, ChangeLogEvent, ConcurrentMerkleTree,
|                              ^^^^^^^^^^^^^^ private enum
|
note: the enum `ChangeLogEvent` is defined here
```
> make exported compression macros usable

- patch.crates-io.sh
I forgot we also use `patch.crates-io.sh` in downstream project test. We should add the exclude rule only when the solana root is under spl root I think 😢
> fix: only add exclude rule when solana root is under spl root

- Cargo.lock
- Cargo.toml
- libraries/type-length-value/Cargo.toml
- libraries/type-length-value/README.md
- libraries/type-length-value/src/discriminator.rs
- libraries/type-length-value/src/error.rs
- libraries/type-length-value/src/length.rs
- libraries/type-length-value/src/lib.rs
- libraries/type-length-value/src/pod.rs
- libraries/type-length-value/src/state.rs
Part of breaking up #4105 into real digestible parts, in order to work with TLV structures, we need a library!
Add it. There's more interesting information in the README, along with some examples in the tests in state.rs. Features to look out for:
* bytemuck / pod support
* optional borsh support
* alloc and realloc support
cc @austbot and @buffalojoec since I apparently can't just add you as reviewers
> tlv: Add library for using type-length-value structures

- token-swap/js/package.json
When importing @solana/spl-token-swap as an ESM module, the typescript compiler is unable to resolve the types, we need to export them from package.json.
> Fix ESM type exports in spl-token-swap

- account-compression/sdk/package.json
- memo/js/package.json
- token-swap/js/package.json
- token/js/package.json
I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
⚠️ this PR focuses solely on fixing "🐛 Used fallback condition" problem but the "👺 Masquerading as ESM" and "⚠️ ESM (dynamic import only)" remain here. You can check the reported errors …
> js: move `types` condition to the front

- .github/dependabot.yml
There aren't a lot of open dependabot PRs for cargo, and some of the JS packages are missing in the dependabot config.
Increase the number of cargo PRs to 6, and add stake-pool-js, memo-js, and name-service-js
> ci: Add more dependabot PRs for cargo and JS packages

- Cargo.lock
- governance/addin-mock/program/Cargo.toml
- governance/chat/program/Cargo.toml
- governance/program/Cargo.toml
- governance/program/src/state/proposal_transaction.rs
- token-lending/program/Cargo.toml
- token-lending/program/tests/helpers/genesis.rs
#4163 is trying to upgrade the base64 crate, which has a new API. While fixing this, I noticed that a bunch of governance crates declare base64 as a dev dependency but never use it.
Upgrade base64 to 0.21, use the new API, remove it where it isn't used
> deps: Upgrade base64 to 0.21.0, remove where it's not used

- associated-token-account/program-test/tests/extended_mint.rs
- associated-token-account/program-test/tests/recover_nested.rs
The ATA tests have been flaky, potentially because there's not enough blockhash refreshing going on.#4214 
I can't reproduce locally, but refreshing the blockhash more often has helped the stake pool tests in the past, so do it more often in the ATA tests too.
I've also removed some unnecessary keypair generations, which have been a problem in the past too.
> associated-token-account: Refresh blockhash more on flakey tests

- .github/workflows/pull-request.yml
The audit job is failing because the newest version of cargo-audit requires Rust version 1.63.
Until SPL moves to Solana 1.16, we're stuck with Rust 1.60, so temporarily pin the version of cargo-audit
> ci: Pin cargo-audit to earlier version

- Cargo.lock
- managed-token/program/Cargo.toml
- managed-token/program/tests/test.rs
While looking at #4251, it became clear that there are some unnecessary dependencies in the managed-token program.
Rather than upgrading unneeded deps, just remove them!
> managed-token: Cleanup unnecessary dependencies

- stake-pool/js/package-lock.json
- stake-pool/js/package.json
- stake-pool/js/rollup.config.js
- stake-pool/js/src/layouts.ts
- stake-pool/js/test/instructions.test.ts
- stake-pool/js/tsconfig.json
The stake pool bindings are on much older versions of web3.js and borsh, but the attempts at #4282 and  #4241 require more fixing.
Bump the packages, add a polyfill for `getRandomValues` in testing since the newer web3.js needs it, and add `skipLibCheck` to the tsconfig since the borsh dependency requires it from buffer-layout.
> stake-pool-js: Bump web3.js and borsh

- Cargo.lock
- token/cli/Cargo.toml
#4291 is trying to bump the "indicatif" dependency in the token-cli, but it's totally unused!
Remove the dependency
> token-cli: Remove unused indicatif dep

- docs/src/token.mdx
- name-service/js/README.md
https://github.com/solana-labs/token-list has been archived for awhile, but our docs still recommend to use it.
Change to a link to Metaplex docs. Also, why was it referenced in the name service JS bindings? The world may never know
> docs: Scrub all references to token-list

- docs/src/token-2022/wallet.md
There's an empty wallet guide for token-2022, and wallets need to know how to integrate token-2022.
From the experience on https://github.com/coral-xyz/backpack/pull/3976, add a guide!
> docs: Add basic token-2022 wallet guide

- SECURITY.md
- docs/src/token-2022.md
- token/program-2022/README.md
- token/program/README.md
Only the token-2022 status page is very clear that the program is still under audit, but people may miss that information.
Add the information to the top-level token-2022 docs page, the program's README, and the repo SECURITY page.
> docs: Be really clear that token-2022 is still under audit

- token/cli/src/output.rs
`spl-token display CKfatsPMUf8SkiURsDXs7eK6GWb4Jsd6UDbs7twMCWxo -um`
with the master branch
```
SPL Token Mint
Address: CKfatsPMUf8SkiURsDXs7eK6GWb4Jsd6UDbs7twMCWxo
Program: TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
Supply: 100000000000000
Decimals: 5
Mint authority: 7MyTjmRygJoCuDBUtAuSugiYZFULD2SWaoUTmtjtRDzD
Freeze authority: 7MyTjmRygJoCuDBUtAuSugiYZFULD2SWaoUTmtjtRDzD
Extensions
Transfer fees:
Current fee: 690bps
Current maximum: 3906250000000000000
Config authority: 7MyTjmRygJoCuDBUtAuSugiYZFULD2SWaoUTmtjtRDzD
Withdrawal authority: 7MyTjmRygJoCuDBUtAuSugiYZFULD2SWaoUTmtjtRDzD
Withheld fees: 0
```
It gives with this commit
```
SPL Token Mint
Address: CKfatsPMUf8SkiURsDXs7eK6GWb4Jsd6UDbs7twMCWxo
Program: TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
Supply: 100000000000000
Decimals: 5 …
```
> fix: upcoming fees should show if we are not yet over the epoch

- token/js/package-lock.json
- token/js/package.json
#4149 fixed Typescript resolution, but it hasn't been published to npm.
Bump the version before relase
> token-js: Bump version to 0.3.8 for publish

- token-swap/js/package-lock.json
- token-swap/js/package.json
#4149 fixed up how types are resolved in the token-swap js package, but we haven't deployed it yet.
Bump the version for release. This is a new minor version since there's been a lot of version bumps since 0.3.0, which changed the code a lot.
> token-swap-js: Bump to 0.4.0 for release

- token/cli/src/main.rs
Currently, it is not possible to update transfer fees in the token-cli. Furthermore, on `--mint-decimals` argument, the `set-transfer-fee` panics (issue #4098).
Add the ability to create `UpdateTransferFee` instruction offline. This should also close #4098.
> [token-cli] Enable offline `set-transfer-fee`

- token/program/src/instruction.rs
`InitializeMint` contains important note(s), so it's better to facilitate peeking into it from `InitializeMint2`
> Add link to doc: instruction.rs

- .github/workflows/pull-request-token.yml
- associated-token-account/program-test/tests/program_test.rs
The token CI job is failing due to no space left on device, ie https://github.com/solana-labs/solana-program-library/actions/runs/5164629307/jobs/9303653512?pr=4450
Move the ATA and transfer hook example builds to separate steps. The transfer hook tests have no other dependencies, so it's easy. The ATA tests currently use the BPF version of token-2022, but the tests are fine with the fake native version too. Finally, the JS tests require the ATA program, so it's uploaded / downloaded separately.
> ci: Split up token job to avoid using all disk space

- Cargo.lock
- Cargo.toml
the solana monorepo's tarballs bundle `spl-token-cli` for convenience. and that fancy repo uses still shiny rust v1.69 (im eyeing for 1.70 soon). and `ntapi` (one of monorepo dep hell) is pulled into this spl repo. and it isn't buildable anymore with the rust when targeted to the Windows os.
it's currently worked around with this yet another sinful hack...: https://github.com/solana-labs/solana/pull/31970#discussion_r1218039494 
~so, this pr needs to be shipped rather promptly after merge to be included in spl-token-cli v2.4.1....~ (EDIT: the monorepo-side cli-arg based patch for cargo install spl-token-cli seem to a better approach.)
links:
- https://github.com/solana-labs/solana/pull/31961
- https://github.com/solana-labs/solana/pull/31970
- …
> Patch ntapi for windows build with rust 1.69+

- docs/src/token-2022/wallet.md
While the token-2022 wallet docs cover deriving ATAs, they don't talk about creating ATAs. And we had a self-own happen with backpack, fixed in https://github.com/coral-xyz/backpack/pull/4102
Address creating ATAs too
> docs: Add create ATA instruction to token-2022 wallet guide

- Cargo.lock
- libraries/program-error/derive/Cargo.toml
- libraries/program-error/derive/src/macro_impl.rs
While trying to publish or build the program-error-derive subcrate, you'll get:
```
error[E0432]: unresolved import `syn::ItemEnum`
--> libraries/program-error/derive/src/macro_impl.rs:3:56
|
3 | use syn::{punctuated::Punctuated, token::Comma, Ident, ItemEnum, LitStr, Variant};
|                                                        ^^^^^^^^ no `ItemEnum` in the root
error[E0432]: unresolved import `syn::ItemEnum`
--> libraries/program-error/derive/src/lib.rs:20:30
|
20 | use syn::{parse_macro_input, ItemEnum};
|                              ^^^^^^^^ no `ItemEnum` in the root
For more information about this error, try `rustc --explain E0432`.
error: could not compile `spl-program-error-derive` due to 2 previous errors
```
According to https://docs.rs/syn/latest/syn/struct.ItemEnum.html, …
> program-error: Use "full" feature to get `ItemEnum`

- Cargo.lock
- Cargo.toml
- token-metadata/interface/Cargo.toml
- token-metadata/interface/README.md
- token-metadata/interface/src/error.rs
- token-metadata/interface/src/instruction.rs
- token-metadata/interface/src/lib.rs
- token-metadata/interface/src/state.rs
For the motivations given in https://forum.solana.com/t/srfc-00017-token-metadata-interface/283, we need a token-metadata interface
Add the interface first, and after that, an example program implementing all the instructions.
There are a couple of main differences to the proposal:
* the metadata struct is more flexible, providing room for any additional fields
* the state is marked as optional, but there's an "emit" instruction for indexers
Note: the strings used to determine the instruction discriminators may look wacky, but they ensured byte sequences that started with high bytes. Token-2022 will implement this, and it only uses 1 byte for instructions, and I wanted to ensure that there would never be any collision between existing or future token-2022 instructions and these.
cc …
> token-metadata: Add interface describing the program

- libraries/type-length-value/src/discriminator.rs
- token/transfer-hook-interface/src/instruction.rs
As noted in #4544, there's some ugliness around matching discriminators, since you can only match on const slices.
Thanks to the const `as_slice()` function on arrays at https://doc.rust-lang.org/std/primitive.array.html#method.as_slice -- we can make this way neater!
> TLV: Add const `as_slice()` function for easier matching

- memo/js/package.json
- token/js/package.json
As pointed out in #4552, the JS docs were no longer appearing.
Fixup the deploy step to use the correct source and destination directories.  Now https://solana-labs.github.io/solana-program-library/token/js/ is all good!
> typedocs: Fixup deployment

- Cargo.lock
- libraries/program-error/Cargo.toml
- libraries/program-error/derive/src/macro_impl.rs
- libraries/program-error/src/lib.rs
- token-metadata/interface/Cargo.toml
This PR fixes the requirement for crates that wish to use `spl-program-error` to have to import `thiserror`, `num-derive`, and `num-traits`.
Note: This will NOT require these crates to be present in the Cargo.toml file to use the **procedural macro attribute** `#[spl_program_error]`, however, if you decide to use any of the **derive macros** you'll need to import these crates.
> Fix downstream dependencies for `spl-program-error`

- Cargo.lock
- stake-pool/program/Cargo.toml
- stake-pool/program/src/inline_mpl_token_metadata.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/create_pool_token_metadata.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/update_pool_token_metadata.rs
Because of circular dependencies between SPL and Metaplex Token Metadata, the SPL can't upgrade to Solana 1.16.
After trying many different options, nothing can be done directly at the source level, except for splitting out stake pools into their own repo.
This goes one of the lazy routes, and directly inlines the bits needed for metadata support in the stake pool program. If this looks ok, I'll do the same for single pools.
While implementing this, I first did just the program to make sure that everything worked exactly the same from the outside, and then I removed the mpl dependency from the tests.
> stake-pool: Remove mpl crate dependency for 1.16 upgrade

- Cargo.lock
- stateless-asks/program/Cargo.toml
- stateless-asks/program/src/processor.rs
As mentioned in #4588, upgrading to 1.16 is essentially impossible due to metaplex dependencies in SPL.
We may just want to remove this at some point, but for now, we inline some stuff.
> stateless-asks: Remove metaplex dependency

- Cargo.lock
- token/program-2022-test/Cargo.toml
- token/program-2022-test/tests/reallocate.rs
- token/program-2022/src/extension/reallocate.rs
As kindly pointed out by @ryoqun, when reallocating a native account, we don't update the rent amount stored in `is_native`, meaning that the rent exempt reserve falls out of sync.
During realloc, also update the rent-exempt reserve in native accounts.
> token-2022: Sync native balance during realloc

- token/cli/src/main.rs
- token/client/src/token.rs
- token/program-2022-test/tests/metadata_pointer.rs
- token/program-2022/src/extension/metadata_pointer/instruction.rs
- token/program-2022/src/extension/metadata_pointer/mod.rs
- token/program-2022/src/extension/metadata_pointer/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
As the world of token-metadata potentially fractures between many different programs, it will be impossible to know which metadata address is correct.
Store the correct metadata address directly in a mint extension. A wallet just needs to fetch the mint, read out the metadata address, and then fetch that address.
Note that there is *NO* functionality with this address, and it's just storing two addresses -- the update authority, and the metadata account address.
Most of this is copy-pasted from the transfer hook program id management, and it's meant to be extremely simple.
cc @austbot and @jnwng
> token-2022: Add metadata pointer extension

- token-metadata/example/Cargo.toml
Even though the rest of the repo is explicitly using 1.16.1, the token-metadata example program missed the boat during a rebase.
Bump up the crates explicitly to bring them in line with the rest of the repo
> token-metadata: Update program crates to Solana 1.16.1

- Cargo.lock
- libraries/discriminator/Cargo.toml
- libraries/discriminator/src/discriminator.rs
- libraries/discriminator/src/lib.rs
- libraries/discriminator/syn/src/lib.rs
This PR adds `borsh` AND generic support for the `#[derive(SplDiscriminate)]` macro.
You can now apply this macro to structs/enums with:
- One lifetime specifier: `MyItem<'a>`
- Multiple lifetime specifiers: `MyItem<'a, 'b>`
- Generic type arguments: `MyItem<T>`
- Multiple generic type arguments: `MyItem<U, V>`
- Generic types with trait constraints (where clauses): `MyItem<T> where T: Copy`
- *Any combination of the above
I've also implemented `BorshDeserialize` and `BorshSerialize` for the `ArrayDiscriminator` struct, so one can now use this array of 8 bytes in any types that use `BorshDeserialize` or `BorshSerialize`.
Lastly, added a couple conversions for `ArrayDiscriminator` to go _into_ a `[u8; 8]` and _into_ a `u64`
> `spl-discriminator` generic arg support

- Cargo.lock
- libraries/tlv-account-resolution/Cargo.toml
- libraries/tlv-account-resolution/src/error.rs
- libraries/tlv-account-resolution/src/pod.rs
- libraries/tlv-account-resolution/src/state.rs
- libraries/type-length-value/Cargo.toml
- libraries/type-length-value/src/error.rs
- libraries/type-length-value/src/pod.rs
- token-metadata/example/Cargo.toml
This PR seeks to make progress toward building out the TLV library (`type-length-value`) to be more robust and cover a wider range of generic use cases for TLV.
- Moves `PodSlice` and associated types/functions into `type-length-value`, rather than `tlv-account-resolution`
- Cuts unnecessary dependencies and trait impls in favor of `spl-program-error`
The `PodSlice` types I felt are extremely useful and might be useful to other TLV use cases - beyond just account resolution. It's my belief that they should be included in the standard library. Open to feedback!
> Expanding TLV lib

- .github/workflows/pull-request-docs.yml
- docs/package-lock.json
- docs/package.json
The docs are pretty far behind, which is why dependabot bumped a bunch of stuff in #4598. Unfortunately, even though that all succeeded locally, it failed deployment to vercel because it was still using node 14 over there.
Redo the bumps, but also force Node 18 here. Vercel is already using the new version
> docs: Update node version and docusaurus

- associated-token-account/program-test/tests/create_idempotent.rs
- associated-token-account/program-test/tests/extended_mint.rs
- associated-token-account/program-test/tests/process_create_associated_token_account.rs
- associated-token-account/program-test/tests/recover_nested.rs
- docs/src/token-2022/onchain.md
- stake-pool/program/tests/helpers/mod.rs
- token-swap/program/src/processor.rs
- token/cli/src/main.rs
- token/client/src/token.rs
- token/program-2022-test/tests/initialize_account.rs
- token/program-2022-test/tests/initialize_mint.rs
- token/program-2022-test/tests/reallocate.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/reallocate.rs
- token/program-2022/src/processor.rs
- token/transfer-hook-example/tests/functional.rs
We want to add metadata support directly in token-2022, but token-2022's extensions only support extensions whose sizes are known at compile-time.
This is going to be done in a few steps for ease of review. This step just makes `ExtensionType::get_account_len` fallible, so that if you put in `ExtensionType::Metadata`, you get an error.
Thoughts on renaming the function to make that clearer? I went the lazy route and kept it the same name, but I thought about `get_static_account_len` or `get_account_len_with_sized`, but the added words didn't seem worth it.
> token-2022: Make `Extension::get_account_len` fallible

- token/cli/src/main.rs
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/initialize_mint.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/confidential_transfer_fee/instruction.rs
- token/program-2022/src/extension/confidential_transfer_fee/mod.rs
- token/program-2022/src/extension/confidential_transfer_fee/processor.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/pod.rs
- token/program-2022/src/proof.rs
There are a number of changes to be made to the confidential transfer with the Solana 1.16 upgrade. Instead of making all the changes in a single PR, it would be nice to break up the changes in smaller PRs for each instruction. Each PR could make changes to the program, token client, and tests related to a particular instruction in the confidential transfer extension.
This PR is a precursor to the individual PR changes for each instruction.
- [99429af](https://github.com/solana-labs/solana-program-library/pull/4650/commits/99429af1d002cf1ff40d42367a0ec7d1e5ba25db): Currently, the entire confidential transfer test is featurized out with `#![cfg(feature = "proof-program")]` under `proof-program`. This commit assigns `#[cfg(feature = "proof-program")]` to each components in the tests. …
> [token-2022] Update confidential transfer for Solana 1.16.1

- Cargo.lock
- Cargo.toml
- token-wrap/program/Cargo.toml
- token-wrap/program/src/entrypoint.rs
- token-wrap/program/src/instruction.rs
- token-wrap/program/src/lib.rs
- token-wrap/program/src/processor.rs
- token-wrap/program/src/state.rs
Token-2022 adoption will take a long time since many different systems need to make invasive changes.
Add an SPL token wrapping program which allows for easy interoperability of tokens, in case some systems never upgrade.  It's possible to wrap tokens in either direction, token -> token-2022 or token-2022 -> token, and then use them with any existing ecosystem.
The only piece of state required is a backpointer to the unwrapped mint address, which allows clients to figure out if their token is wrapped, and then how to unwrap it.
The functionality for unwrap will look very similar to the token-upgrade program #3436, since you're burning on one side and transferring from another.  `Wrap` will be the opposite: transfer then mint.
Note that since the wrapped mint also uses the wrapped token …
> token-wrap: Add interface description for wrapping program between two mints and/or token programs

- token/program-2022/src/error.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/pod.rs
This is a more complete and well-separated (I hope) version of #4647.
We want to add metadata support directly in token-2022, but token-2022's extensions only support extensions whose sizes are known at compile-time.
Step by step, it roughly goes:
* expose the raw extension bytes (the refactor part)
* add a new trait for unsized extensions
* add new alloc and realloc functions for the unsized extensions
Everthing from ba1d352b4873a6b86c0f3323600505be82f2bffe to 57e93d13274388a0c064453c257e3d903131e4aa is refactoring, and after that you'll see the new functionality.
I can separate this into multiple PRs if needed, but I hope the progression makes more sense here!
> token-2022: Allow alloc and realloc of unsized extensions

- Cargo.lock
- token/client/Cargo.toml
- token/client/src/client.rs
People who want to use the `spl-token-client` crate must use the exact same version of the solana tools, which limits downstream usage.
Relax the dependencies. I noticed that it's always been pinned, but I can't see why we can't relax them for the client library.
And while I was at it, I noticed that we could downgrade the `solana-client` dependency to `solana-rpc-client`.
> token-client: Unpin solana deps, and use `solana-rpc-client`

- update-solana-dependencies.sh
`update-solana-dependencies.sh` misses some of the new crates, like `solana-rpc-client`, like during the upgrade to 1.16.2 https://github.com/solana-labs/solana-program-library/pull/4679/files#diff-a160be2082921ef5bd4bc4ee704c95cf79cb248ad2acf9e1d0b2bfc53206e469R15
Update the update script with all of the crates in the patch script.
> ci: Add all Solana crates to update-solana-dependencies.sh

- docs/sidebars.js
- docs/src/token-2022.md
- docs/src/token-2022/presentation.md
I've been giving a presentation about token-2022, ie https://youtu.be/Gr0cSdqIjD4, but it's not available online anywhere.
The presentation is written in markdown, so just add it as markdown to the docs!
> docs: Add token-2022 presentation as markdown

- stake-pool/single-pool/src/instruction.rs
- stake-pool/single-pool/tests/deposit.rs
this fixes the default deposit address helper once and for all, discovered while testing the cli. the issue here was a) we want the address seeded from the pool for regularity, b) the stake program needs the vote account to delegate to, not the address used in the seed, and c) i was accidentally passing in the vote account in tests so this mistake in the interface went undetected 
this should be the final 1.0 commit to the program. note this doesnt affect anything except an instruction helper
> single-pool: fix default deposit helper

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Confidential transfer configure account instruction is not updated for the new Solana 1.16 changes.
- [b9a5682](https://github.com/solana-labs/solana-program-library/pull/4663/commits/b9a56828ecdad6625f1d62a28081ce63aa6fe04d): The `UpdateMint` instruction constructor and toiken client functions have not been touched for some time and they currently do not support multisig signers. I updated functions to support multisig signers. This should have been a part of the previous PR https://github.com/solana-labs/solana-program-library/pull/4650, which was missed.
- [3cc330b](https://github.com/solana-labs/solana-program-library/pull/4663/commits/3cc330b5b59aa51553c1042e0eb198887e454ffe):
- Updated `ConfigureAccount` instruction constructor and processor and brought them out of `proof-program` …
> [token-2022] Update confidential transfer configure account for 1.16

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Confidential transfer {enable,disable} confidential credits and empty account instructions are not updated for the new Solana 1.16 changes.
The changes in this PR are pretty straightforward.
- [6bc7e1b](https://github.com/solana-labs/solana-program-library/pull/4664/commits/6bc7e1b5ab75c5b7b9f7ef27980fae26f8913ccd): Updated the client code for the {enable, disable} confidential credits instructions. Previously, they did not support multisig. The functions are updated to be in-line with the rest of the client functions.
- [12d888c](https://github.com/solana-labs/solana-program-library/pull/4664/commits/12d888ca0efe4141694d45802179de67c26e0b7c): Updated the test code for {enable, disable} confidential credits instructions.
- [7f4b1cb](https://github.com/solana-labs/solana-program-library/pul …
> [token-2022] Update confidential transfer {enable,disable} confidential credits and empty account for Solana 1.16

- Cargo.lock
- libraries/type-length-value/Cargo.toml
- libraries/type-length-value/README.md
- libraries/type-length-value/src/lib.rs
- libraries/type-length-value/src/state.rs
- libraries/type-length-value/src/unsized_pack.rs
- libraries/type-length-value/src/variable_len_pack.rs
- token-metadata/example/Cargo.toml
- token-metadata/example/src/processor.rs
- token-metadata/example/tests/initialize.rs
- token-metadata/example/tests/remove_key.rs
- token-metadata/example/tests/update_authority.rs
- token-metadata/example/tests/update_field.rs
- token-metadata/interface/Cargo.toml
- token-metadata/interface/src/state.rs
As mentioned in #4719 and https://github.com/solana-labs/solana-program-library/pull/4661#discussion_r1254769560, the approach of using borsh directly has some issues, and it'll be better to go through another trait.
Implement the `UnsizedPack` trait, remove borsh, and use it in the token-metadata interface / example. The first commit is entirely in the TLV library, and the second is just how it's used in the token-metadata program.
I have to say, this felt very good. This removes the borsh dependency *and* the feature, which makes the TLV library much neater. 
Fixes #4719
> TLV: Add `VariableLenPack` trait to remove borsh dependency

- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/token_metadata/mod.rs
- token/program-2022/src/extension/token_metadata/processor.rs
- token/program-2022/src/processor.rs
We want to implement the token-metadata interface in token-2022, but we've only laid the groundwork for handling variable-length extensions, and none of the actual implementation.
This one's pretty simple, just putting in the scaffolding for handling a token-metadata instruction, no real functional bits yet:
* adds `ExtensionType::TokenMetadata` and marks it as variable-length
* parses incoming instructions as `TokenMetadataInstruction` *after* the token-2022 instructions -- this is the bulk of the change, and it's all white-space
* forwards `TokenMetadataInstruction` to specific processors, which are all empty
> token-2022: Add scaffolding to implement token-metadata interface

- stake-pool/cli/src/main.rs
found while testing single pool ledger support, these args dont show up in any subcommand
```
cargo run -- --help
Finished dev [unoptimized + debuginfo] target(s) in 0.19s
Running `/home/hana/work/solana/spl/target/debug/spl-stake-pool --help`
spl-stake-pool-cli 0.7.0
SPL-Stake-Pool Command-line Utility
USAGE:
spl-stake-pool [FLAGS] [OPTIONS] <SUBCOMMAND>
FLAGS:  
--dry-run      Simulate transaction instead of executing
-h, --help         Prints help information
--no-update    Do not automatically update the stake pool if needed
-V, --version      Prints version information
-v, --verbose      Show additional information
OPTIONS:
-C, --config <PATH>                  Configuration file to use [default: /home/hana/.config/solana/cli/config.yml]
--fee-payer <KEYPAIR>            Transaction …
```
> stake-pool-cli: mark args as global

- Cargo.lock
- associated-token-account/program-test/tests/create_idempotent.rs
- associated-token-account/program-test/tests/extended_mint.rs
- associated-token-account/program-test/tests/process_create_associated_token_account.rs
- associated-token-account/program-test/tests/recover_nested.rs
- docs/src/token-2022/onchain.md
- stake-pool/program/tests/helpers/mod.rs
- token-swap/program/src/processor.rs
- token/cli/src/main.rs
- token/client/src/token.rs
- token/program-2022-test/tests/initialize_account.rs
- token/program-2022-test/tests/initialize_mint.rs
- token/program-2022-test/tests/reallocate.rs
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/reallocate.rs
- token/program-2022/src/processor.rs
- token/transfer-hook-example/tests/functional.rs
We have many helpers now for allocating and reallocating individual entries in the TLV buffer, but we still can't realloc the underlying `AccountInfo` whenever we add or update an unsized extension.
In the token-metadata interface, the metadata is written after the mint is initialized. During mint initialization, we check to make sure that there's no extra allocated space, to be safe.
This means that during token-metadata initialization, we have to realloc the underlying account in order to write the new data. During updates, we have to realloc the extension to fit the new data size.
Add a few sets of functions and helpers to get this done:
* get the current number of bytes used in the account
* get the future number of bytes used in the account
* for init: realloc the account, alloc the …
> token-2022: Add account-level alloc and realloc

- Cargo.lock
- token/client/Cargo.toml
- token/client/src/token.rs
- token/program-2022-test/Cargo.toml
- token/program-2022-test/tests/token_metadata_initialize.rs
- token/program-2022/src/extension/token_metadata/processor.rs
As one of the steps in #4648, Token-2022 needs to implement the token-metadata interface to be a token-metadata program, but there's only the bare scaffolding for it.
Start with the basic instruction: initialization! This also adds support in the token-client and some tests, in separate commits, so you can go through them piece by piece.
> token-2022: Implement `TokenMetadataInstruction::Initialize`

- stake-pool/program/src/state.rs
There's been loads of work into supporting token-metadata in token-2022, but currently, a stake pool token cannot have the `MetadataPointer` or `TokenMetadata` extensions.
Add the `MetadataPointer` and `TokenMetadata` extension types in the "allow list" for stake pool token mints.
> stake-pool: Allow pool token mint to include metadata

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Confidential transfer withdraw instruction is not u9pdated for the new Solana 1.16 changes.
Updated the processor, client, and tests relating to the withdraw instruction. These are relatively simpler changes with just two commits. The withdraw instruction does fit into a single transaction, so I did not divide up the proof.
Some notable change is in the error. In the client, I changed the error variant `Proof(ProofError)` to `ProofGeneration`. Previously, `Proof(ProofError)` held the specific proof error from the zk-token-sdk. Now, I simplified it to just `ProofGeneration` because that is technically the only type of proof related error in the client and since the proof generation logic for the withdraw proof is now shoved into token-2022, propagating the error further could be a little …
> [token-2022] Update confidential transfer withdraw for Solana 1.16

- token/client/src/token.rs
- token/program-2022-test/tests/token_metadata_update_field.rs
- token/program-2022/src/extension/token_metadata/processor.rs
As one of the steps in #4648, Token-2022 needs to implement the token-metadata interface's `UpdateField` to be a token-metadata program.
This builds directly on #4744, so you just need to look at the last three commits. This has the same structure as the `Initialize` PR:
* processor implementation
* token client support
* tests
> token-2022: Implement `TokenMetadataInterface::UpdateField`

- token/program-2022-test/tests/token_metadata_emit.rs
- token/program-2022/src/extension/token_metadata/processor.rs
As part of #4648, token-2022 needs to implement `TokenMetadataInstruction::Emit` to be a token-metadata program.
Very similar to the example implementation https://github.com/solana-labs/solana-program-library/blob/142708116b57ae11bcfc33758962059c7ddf11c6/token-metadata/example/src/processor.rs#L175-L192
And tests (https://github.com/solana-labs/solana-program-library/blob/master/token-metadata/example/tests/emit.rs
Implement them!
> token-2022: Implement `TokenMetadataInstruction::Emit`

- token/client/src/token.rs
- token/program-2022-test/tests/token_metadata_update_authority.rs
- token/program-2022/src/extension/token_metadata/processor.rs
As part of #4648, token-2022 needs to implement `TokenMetadataInstruction::UpdateAuthority` to be a token-metadata program.
Very similar to the example implementation https://github.com/solana-labs/solana-program-library/blob/142708116b57ae11bcfc33758962059c7ddf11c6/token-metadata/example/src/processor.rs#L149-L172
And tests (https://github.com/solana-labs/solana-program-library/blob/master/token-metadata/example/tests/update_authority.rs
Implement them!
> token-2022: Implement `TokenMetadataInstruction::UpdateAuthority`

- .github/workflows/pull-request-token.yml
The 2xTx has recently started erroring due to running out of disk space: https://github.com/solana-labs/solana-program-library/actions/runs/5537335983/jobs/10106051181
Just use the solution built during #4505
> ci: Blast directories in 2xTx build

- token/client/src/token.rs
- token/program-2022-test/tests/token_metadata_remove_key.rs
- token/program-2022/src/extension/token_metadata/processor.rs
As part of #4648, token-2022 needs to implement `TokenMetadataInstruction::RemoveKey` to be a token-metadata program.
Very similar to the example implementation https://github.com/solana-labs/solana-program-library/blob/142708116b57ae11bcfc33758962059c7ddf11c6/token-metadata/example/src/processor.rs#L122-L146
And tests (https://github.com/solana-labs/solana-program-library/blob/master/token-metadata/example/tests/remove_key.rs
Implement them!
> token-2022: Implement `TokenMetadataInstruction::RemoveKey`

- token/client/src/token.rs
- token/program-2022-test/tests/token_metadata_emit.rs
- token/program-2022-test/tests/token_metadata_initialize.rs
- token/program-2022-test/tests/token_metadata_remove_key.rs
- token/program-2022-test/tests/token_metadata_update_authority.rs
- token/program-2022-test/tests/token_metadata_update_field.rs
The function names for the token-metadata processors in the token client are kinda goofy, see https://github.com/solana-labs/solana-program-library/pull/4774#discussion_r1261811662
Rename the functions as `token_metadata_instruction` rather than `instruction_in_token_metadata`.
I'll rebase the open PRs onto this after it lands.
> token-client: Rename metadata functions

- account-compression/sdk/src/events/index.ts
Added a helper function named `getAllChangeLogEventV1FromTransaction` to locate and return an array of ChangeLogEventV1 from a [TransactionResponse](https://solana-labs.github.io/solana-web3.js/types/TransactionResponse.html) or [VersionedTransactionResponse](https://solana-labs.github.io/solana-web3.js/types/VersionedTransactionResponse.html) 
Among other things, this will enable people to more easily locate the leaf index that was utilized during an interaction with the tree.
> [compression] added function to locate ChangeLogEvent from transaction

- Cargo.lock
- Cargo.toml
- libraries/type-length-value-derive-test/Cargo.toml
- libraries/type-length-value-derive-test/src/lib.rs
- libraries/type-length-value/Cargo.toml
- libraries/type-length-value/derive/Cargo.toml
- libraries/type-length-value/derive/src/builder.rs
- libraries/type-length-value/derive/src/lib.rs
- libraries/type-length-value/src/lib.rs
- libraries/type-length-value/src/pod.rs
- libraries/type-length-value/src/state.rs
- libraries/type-length-value/src/variable_len_pack.rs
Broken off of #4768 (1/3)
---
This PR adds a derive macro to `spl-type-length-value` for simply adding the `VariableLenPack` trait with borsh methods for those who do not wish to implement a custom implementation of the tratit.
It simply mimics the `TokenMetadata` state implementation of `VariableLenPack`:
```rust
impl VariableLenPack for TokenMetadata {
fn pack_into_slice(&self, dst: &mut [u8]) -> Result<(), ProgramError> {
borsh::to_writer(&mut dst[..], self).map_err(Into::into)
}
fn unpack_from_slice(src: &[u8]) -> Result<Self, ProgramError> {
try_from_slice_unchecked(src).map_err(Into::into)
}
fn get_packed_len(&self) -> Result<usize, ProgramError> {
get_instance_packed_len(self).map_err(Into::into)
}
}
```
---
I've also taken special care to set up a separate crate for testing the …
> TLV Derive Macro for Borsh Variable Length

- stake-pool/cli/src/main.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/single-pool-cli/src/quarantine.rs
- stake-pool/single-pool/src/processor.rs
- stake-pool/single-pool/tests/helpers/stake.rs
Update StakeState unpack with additional deactivation flag.
> Update Stake with the additional deactivation flag

- stake-pool/cli/src/main.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/single-pool-cli/src/quarantine.rs
- stake-pool/single-pool/src/processor.rs
- stake-pool/single-pool/tests/helpers/stake.rs
This reverts commit 19645b6cea1752bd1725e2170f3578950b0eda3a.
#4504 was merged before the upstream changes landed. We might want to keep it in draft to make it clear that it's not ready. Master currently doesn't build.
Revert the commit.
> Revert "Update Stake with the additional deactivation flag (#4504)"

- Cargo.lock
- token-metadata/example/tests/program_test.rs
- token-upgrade/cli/src/main.rs
- token-upgrade/program/tests/functional.rs
- token/cli/src/main.rs
- token/client/Cargo.toml
- token/client/src/client.rs
- token/client/src/output.rs
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
While working on the token-metadata `emit` instruction, which writes the token-metadata bytes into return data, I realized that we can't simulate transactions using the token-client.
Support transaction simulation! I went with a separate set of traits rather than adding simulation to the `SendTransaction` trait, in the case that we want to add tpu-client support. In that case, it would be a new client that *does not* support simulation, so it wouldn't implement those traits.
Since the RPC simulation results don't have any normal formatters, I just went with the default `Debug` one. Where would be the best place to implement that?
I'm not sure if either of you was already thinking about this, but I hope it lines up with your expectations! If not, I'm happy to drop it and go another route.
> token-client: Add simulation support to ProgramClient

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/account_info.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
Confidential transfer `Transfer` and `TransferWithFee` instructions are not updated for the new Solana 1.16 changes.
- [bdaf1fe](https://github.com/solana-labs/solana-program-library/pull/4779/commits/bdaf1fe9baf70944146f556bc3c98663898ee97b): The logic for the account info types needed for instructions was getting long, so I refactored these from `state.rs` into a separate module
- [e88c9e4](https://github.com/solana-labs/solana-program-library/pull/4779/commits/e88c9e4031e1bd912c3c934a7231f7ae322e0b26): I updated the processor and client logic for the `Transfer` instruction. This should be pretty standard except that I added helper functions that extract the relevant bits from the transfer amount and fee ciphertexts. The transfer amount and fee are encrypted under the source, …
> [token-2022] Update confidential transfer `Transfer` and `TransferWithFee` for Solana 1.16

- docs/src/token-2022/status.md
Updating the project status page on token-2022:
- Added a link to the ZK Token proof program feature gate issue
- Replaced a link to the previously merged PR on ZK Token proof program with the issue on the remaining tasks for token-2022 https://github.com/solana-labs/solana-program-library/issues/4817
> [docs] Update token-2022 project status on proof split

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/account_info.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/proof.rs
The token-2022 confidential transfer extension instructions that require zero-knowledge proofs do not yet support context states.
Added support for context state accounts. All the confidential transfer instructions that require zkp's have an `i8` proof instruction offset field that represents the position of the zkp instruction relative to the token-2022 instruction. Since the offset cannot be zero, I updated the program so that it if the offset is zero, it checks for a context state account.
- [8bb4d2a](https://github.com/solana-labs/solana-program-library/pull/4816/commits/8bb4d2aec8841a7689e1ca2980491fad6a5c1844): The previous PR that updated the`EmptyAccount` instruction for 1.16 did not add account info for it, so I added it in line with the rest of the zkp requiring instructions and …
> [token-2022] Add support for context state accounts

- token/cli/src/main.rs
- token/client/src/token.rs
There's no support for the transfer hook extension in the token CLI.
Add basic support for setting a transfer hook at mint creation, updating the program, and specifying transfer-hook-accounts for offline signing.
Fixes #4548
> token-cli: Support transfer hook extension

- stake-pool/program/src/big_vec.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/deposit_edge_cases.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/redelegate.rs
- stake-pool/program/tests/set_epoch_fee.rs
- stake-pool/program/tests/set_withdrawal_fee.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/update_validator_list_balance_hijack.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw_edge_cases.rs
- stake-pool/single-pool/tests/accounts.rs
- stake-pool/single-pool/tests/deposit.rs
- stake-pool/single-pool/tests/helpers/mod.rs
The SPL downstream tests were disabled in https://github.com/solana-labs/solana/pull/32524, but we need to re-enable the downstream tests to avoid breaking people in the future, per https://github.com/solana-labs/solana/pull/32655.
After doing the work to reinstate the old `StakeState` and re-enabling the downstream tests, there were errors in the stake pools tests.
The biggest change relates to the async rewards payout being implemented for https://github.com/solana-foundation/solana-improvement-documents/pull/15 -- we have to warp to `slot + 1` in order to get out of the rewards payout time.
After that, there was one issue where we weren't serializing 200 bytes for stake accounts in a test.
And a little extra thing, I noticed that `retain` in the stake pool program was using a function …
> stake-pool: Update tests for 1.17

- .github/workflows/manage-stale-issues-and-prs.yml
There's loads of old issues and PRs in SPL which mostly aren't applicable anymore.
Copying the monorepo, add a workflow for marking issues / PRs as stale, and then closing them
> ci: Add auto-closing stale issues and PRs

- docs/src/token-2022/extensions.mdx
- libraries/tlv-account-resolution/README.md
- libraries/tlv-account-resolution/src/account.rs
- libraries/tlv-account-resolution/src/lib.rs
- libraries/tlv-account-resolution/src/seeds.rs
- libraries/tlv-account-resolution/src/state.rs
- token/transfer-hook-example/src/processor.rs
- token/transfer-hook-example/src/state.rs
- token/transfer-hook-example/tests/functional.rs
- token/transfer-hook-interface/README.md
- token/transfer-hook-interface/src/instruction.rs
- token/transfer-hook-interface/src/offchain.rs
- token/transfer-hook-interface/src/onchain.rs
This PR renames a few things!
- `PodAccountMeta` to `ExtraAccountMeta`
- `ExtraAccountMetas` to `ExtraAccountMetaState`
- `pod.rs` to `account.rs`
> rename PodAccountMeta to ExtraAccountMeta

- libraries/tlv-account-resolution/src/account.rs
- libraries/tlv-account-resolution/src/seeds.rs
- libraries/tlv-account-resolution/src/state.rs
This PR swaps methods from `ExtraAccountMetaList` to `ExtraAccountMeta` and tightens up implementation.
This sets the stage for:
- Removal of `AccountInfo` helpers
- Updated integration with `spl-transfer-hook-example`
Summary:
- Moved `de_escalate_account_meta` and `resolve_pda` into `account.rs` as private helpers
- Added `resolve` to `ExtraAccountMeta`
- Trimmed implementation of `add_to_instruction` for `ExtraAccountMetaList`
Note: As it relates to #4963:
- An `is_pda()` or enum is no longer required
- An `AccountKeyable` trait is no longer required
> Tighten Up Account Resolution Methods

- libraries/tlv-account-resolution/README.md
- libraries/tlv-account-resolution/src/account.rs
- libraries/tlv-account-resolution/src/error.rs
- libraries/tlv-account-resolution/src/state.rs
- token/program-2022-test/tests/transfer_hook.rs
- token/transfer-hook-example/src/processor.rs
- token/transfer-hook-example/src/state.rs
This PR sets the stage for modifying the Transfer Hook Interface `InitializeExtraAccountMetas` instruction.
Here I'm condensing the act of initializing `ExtraAccountMetaList` state into one `init` function, rather than 3
> condense TLV AR state to one init

- stake-pool/single-pool/src/instruction.rs
- stake-pool/single-pool/src/processor.rs
- stake-pool/single-pool/tests/deposit.rs
the TODO was a note to myself to add the first parameter to that function (which I did) but the comment survived a merge. the owner check was already done by the stake program but since both audits commented on it i made it explicit in the svsp program
> single-pool: remove stray TODO, add explicit owner check in deposit

- Cargo.lock
- token/client/Cargo.toml
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/confidential_transfer_fee.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer_fee/account_info.rs
- token/program-2022/src/extension/confidential_transfer_fee/instruction.rs
- token/program-2022/src/extension/confidential_transfer_fee/mod.rs
- token/program-2022/src/extension/confidential_transfer_fee/processor.rs
The confidential transfer fee extension is not updated for solana 1.16
The most importants changes in the first, second, and last commits.
[b96f57a](https://github.com/solana-labs/solana-program-library/pull/4896/commits/b96f57a632187bc21c28418bb4df8d84dbbac1fb): Updated the `WithdrawWithheldTokensFromMint` instruction for Solana 1.16 and for it to support context states. This is pretty straightforward except for the part about adding the withheld feeds directly into a destination available balance.
The original plan (https://github.com/solana-labs/solana-program-library/issues/4817) was to divide the withheld amount into low and high parts. Transfer amounts and fees in the instruction are divided into low and high bits so that they are easier to decrypt. When the transfer amount is …
> [token-2022] Update confidential transfer fee extension for solana 1.16

- token/client/src/token.rs
- token/program-2022/src/extension/confidential_transfer/account_info.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
This is a follow-up to https://github.com/solana-labs/solana-program-library/pull/4896#discussion_r1289197648.
Added the constructors for the account info types in the confidential transfer instructions. Previously, the account information types had to be constructed using the associated function of `ConfidentialTransferAccount` type, which was quite unnatural.
> [token-2022] Add constructors for confidential transfer account info types

- libraries/type-length-value/src/pod.rs
- token/transfer-hook-example/src/processor.rs
- token/transfer-hook-example/tests/functional.rs
- token/transfer-hook-interface/src/instruction.rs
This PR modifies the Transfer Hook Interface to take configurations for extra required account metas as instruction data rather than in the list of account infos.
> Transfer Hook: Provide extra metas as instruction data

- ci/do-audit.sh
CI is failing because of the Rust security advisory on ed25519-dalek.
Since the fix requires a major version bump on ed25519-dalek, and SPL picks up these crates from the Solana SDK, we can't just fix it.
Instead, ignore the vulnerability until SPL updates to 1.17.
While I was at it, I noticed the openssl vulernability no longer applied, so I removed it from the list
> ci: Add dalek advisory to ignore list

- README.md
- docs/sidebars.js
- docs/src/single-pool.md
urls are correct after #5010 and https://github.com/solana-labs/security-audits/pull/13 land. also opening an issue for todos which can only be done after crates.io/npm releases
incidentally i dont know how to ensure this deploys after the pr is merged
> add single pool to spl.solana.com

- .github/workflows/pull-request-stake-pool.yml
- ci/warning/purge-ubuntu-runner.sh
https://github.com/solana-labs/solana/pull/32677 is failing due to lack of disk space, but there's definitely more stuff to blast in the ubuntu runner.
Remove more packages to get another 7GB
> ci: Test purging more packages

- docs/src/token-2022/extensions.mdx
- libraries/tlv-account-resolution/README.md
- token/transfer-hook-example/src/processor.rs
- token/transfer-hook-interface/README.md
This PR updates the documentation for the Transfer Hook Interface and the TLV Account Resolution library
Closes #4942
> Transfer Hook Docs

- stake-pool/js/src/index.ts
- stake-pool/js/src/utils/stake.ts
- stake-pool/program/src/lib.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/withdraw_edge_cases.rs
- stake-pool/py/stake_pool/constants.py
The `MINIMUM_RESERVE_BALANCE` in the stake pool program is `1`, which is no longer the case after https://github.com/solana-labs/solana/issues/24669 was enabled on mainnet.
Update `MINIMUM_RESERVE_BALANCE` to `0`. There was one check during increase that needed to be changed too from `<=` to `<`, and then a few places in the testing where we added an additional lamport to make stake accounts "valid".
> stake-pool: Update minimum reserve balance to 0

- docs/src/stake-pool/overview.md
In the "roles" section of the stake pool docs, it doesn't specify that the staker can update the staker.
Specify it!
> docs: Specify that the stake pool staker can update the staker

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/confidential_transfer_fee.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_transfer/account_info.rs
- token/program-2022/src/extension/confidential_transfer/ciphertext_extraction.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/mod.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/confidential_transfer/split_proof_generation.rs
- token/program-2022/src/extension/confidential_transfer/verify_proof.rs
- token/program-2022/src/extension/confidential_transfer_fee/instruction.rs
- token/program-2022/src/proof.rs
- token/program-2022/src/serialization.rs
- [779eaba](https://github.com/solana-labs/solana-program-library/pull/5001/commits/779eaba30d3cecb91ba2b890eca389555f8667f1): The verify proof helper function for `Transfer` is going to be a bit more involved, so I created a `verify_proof` submodule and refactored the existing `verify_..._proof`()` helper functions into this submodule.
- [7ee73cb](https://github.com/solana-labs/solana-program-library/pull/5001/commits/7ee73cb34e210440541ff63c04f82cc9e0059fea): Modified `instruction.rs` modules to support split proof context states. The most notable change here is the addition of `SplitContextStateAccounts` variant of `ProofLocation` argument type.
- [c26ec15](https://github.com/solana-labs/solana-program-library/pull/5001/commits/c26ec15c93e4c6288e934c427e2c9caf42f1ad75): I updated the …
> [token-2022] Update confidential transfer instruction to support split proof contexts

- token/cli/src/main.rs
This is finishing up #3356 -- thanks to @SUMEETRM !
Copying that pull request text:
Pull request for issue https://github.com/solana-labs/solana-program-library/issues/1805
Retained --recipient-is-ata-owner as a hidden flag and, if passed, warn the user that the behavior is now default, the flag is deprecated and can be removed.
New flag called --no-recipient-is-ata-owner to match convention of other CLI tools. Reverse the logic for the flag.
>  token-cli: reverse logic for --recipient-is-ata-owner

- libraries/math/src/instruction.rs
- libraries/math/src/processor.rs
- libraries/math/tests/instruction_count.rs
`powf` finally works in bpf!
To make sure it keeps working, here's a test calling `powi` and `powf` on floats
> math: Add f64 powf and powi

- ci/do-audit.sh
There's a RUSTEC advisory on webpki, which is used by upstream dependenices like tokio, but there's no upgrade path.
We'll have to ignore it for now unfortunately.
> ci: Ignore webpki RUSTSEC issue

- .github/workflows/pull-request-token-metadata.yml
- Cargo.lock
- token-metadata/interface/Cargo.toml
- token-metadata/interface/src/instruction.rs
- token-metadata/interface/src/state.rs
Issue #3325
Adds serde support for instructions from `token-metadata`. Continuation of #4772
Notes:
* Added `serde-traits` feature flag to `token-metadata`, all serde code is behind this flag
* Noticed `OptionalNonZeroPubkey` is virtually identical to the type with the same name from `token-2022` so I basically copy/pasted the de/serialization logic from there. Let me know if a different approach is preferred.
@joncinque @buffalojoec
> [token-metadata] Add serde support for token metadata instructions

- token/program-2022/src/extension/confidential_transfer/ciphertext_extraction.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer_fee/instruction.rs
- token/program-2022/src/extension/cpi_guard/instruction.rs
- token/program-2022/src/extension/default_account_state/instruction.rs
- token/program-2022/src/extension/interest_bearing_mint/instruction.rs
- token/program-2022/src/extension/memo_transfer/instruction.rs
- token/program-2022/src/extension/metadata_pointer/instruction.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/extension/transfer_hook/instruction.rs
- token/program-2022/src/instruction.rs
- token/program-2022/tests/serialization.rs
Issue #3325
Addresses this comment: https://github.com/solana-labs/solana-program-library/pull/5050#discussion_r1300031644
I still plan on implementing a macro to replace a lot of these serde attributes, but until that is done it feels like the camelCase should not be postponed too much so I added it in this PR.
@joncinque @buffalojoec
> token-2022: enable camelCase for serde

- docs/src/token-2022/extensions.mdx
- token/js/examples/transferHook.ts
- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/index.ts
- token/js/src/extensions/transferHook/actions.ts
- token/js/src/extensions/transferHook/index.ts
- token/js/src/extensions/transferHook/instructions.ts
- token/js/src/extensions/transferHook/state.ts
- token/js/src/instructions/types.ts
- token/js/test/e2e-2022/transferHook.test.ts
- token/js/test/unit/programId.test.ts
> token-js: Added support for transfer hook instructions

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/main.rs
The metadata extension in token-2022 is great, but currently unusable except in the token client.
Support initializing and updating metadata!
Unfortunately, we can't also initialize the metadata during that first call to `create-token` because the mint authority doesn't sign that command, and it's more confusing than anything else to have it take a maybe-keypair and then maybe-do-it. The solution there was to explain the next steps.
Otherwise, the rest should be straightforward!
> token-cli: Integrate token-metadata in the mint

- libraries/tlv-account-resolution/src/account.rs
- libraries/tlv-account-resolution/src/error.rs
- libraries/tlv-account-resolution/src/state.rs
This PR adds a check to the seed resolution step for the provided instruction data, to ensure the instruction data buffer is at least long enough for the end index of the proposed slice.
> TLV Account Resolution: Add instruction data length check

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/confidential_transfer_fee.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/confidential_transfer/verify_proof.rs
- token/program-2022/src/extension/confidential_transfer_fee/instruction.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/proof.rs
- [838e6be](https://github.com/solana-labs/solana-program-library/pull/5054/commits/838e6becd52a67634233420804774ed8950f167b): I removed the split proofs from the `Transfer` instruction and added a separate `TransferWithSplitProofs` that support transfer with split proof contexts.
- [cda6078](https://github.com/solana-labs/solana-program-library/pull/5054/commits/cda6078fd81e8db5d5331efa196650868e1b6137): Updated the main program logic for split proof contexts to support no-op if the account is not initialized and also auto close on full transfer execution. Since CPI into the proof program is not currently supported, I currently disabled auto close on transfer execution with an invalid instruction data error. The notable change in this PR is to the result type of `verify_transfer_proof` …
> [token-2022] Confidential transfer parallel split proofs

- token/client/src/token.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
The `destination` and `mint` account pubkeys in instructions and function parameters are different for the transfer and confidential transfer instructions.
Swapped the order of these pubkeys in the confidential transfer instructions.
This is a follow up to https://github.com/solana-labs/solana-program-library/pull/5054#discussion_r1305994718.
> [token-2022] Switch `destination` and `mint` account pubkeys in confidential transfer extension

- token/program-2022/src/extension/confidential_transfer/ciphertext_extraction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/confidential_transfer/verify_proof.rs
It isn't possible to build token-2022 with `--no-default-features`, since some parts depend on the `zk-ops` feature being enabled.
Add the feature check wherever needed to get `cargo build-sbf --no-default-features` to work.
> token-2022: Featurize `zk-ops` to build without it

- libraries/pod/src/bytemuck.rs
`pod_slice_from_bytes()` return type isn't mutable, so let's fix the doc that suggests it will be.
Also, I find the docs in this file a little hard to read, because the word `slice` is used so many times. Do you think it is worth saying `slice of bytes` or `byte slice` or something to distinguish those slices from the slices of `Pod`?
> Fix incorrect code doc

- token/js/examples/transferHook.ts
- token/js/src/errors.ts
- token/js/src/extensions/transferHook/actions.ts
- token/js/src/extensions/transferHook/index.ts
- token/js/src/extensions/transferHook/instructions.ts
- token/js/src/extensions/transferHook/seeds.ts
- token/js/src/extensions/transferHook/state.ts
- token/js/test/unit/transferHook.test.ts
resolves #5108
Couple notes:
* Not sure exactly how multisigners is implemented for extra account resolution in the program since it changes the ordering of the account keys. Does it mean that if a user wants multisigners to work they explicitly need to code this into their transfer hook program?
* What is done by `tlv-account-resolution` in rust is now baked into `@solana/spl-token` for js. Might be a nice improvement to separate that into its own package?
* I have written a few tests to the best of my understanding of what exactly the data structure of the extra accounts data account is. Might be worth for @joncinque or @buffalojoec to check if my implementation actually matches that of the rust client.
* The way `transferCheckedWithHook` and `addExtraAccountsToInstruction` are …
> token-js: added extra account resolution for transfer hook extension

- libraries/pod/src/bytemuck.rs
This PR updates code docs in bytemuck.rs to specify what each slice is a slice of, as discussed [here](https://github.com/solana-labs/solana-program-library/pull/5177#pullrequestreview-1603204939)
I also threw in a couple other changes that I thought made the docs more clear, and for consistency.
> spl-pod: make code docs more explicit

- Cargo.lock
- libraries/pod/src/primitives.rs
- stake-pool/cli/src/main.rs
- stake-pool/cli/src/output.rs
- stake-pool/program/Cargo.toml
- stake-pool/program/src/big_vec.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/force_destake.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/redelegate.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
Under Rust 1.72, the cast done by the stake pool program from raw bytes into a `ValidatorStakeInfo` panics because the underlying pointer might not be aligned to an address with a multiple of 8. See the offending line: https://github.com/solana-labs/solana-program-library/blob/c79c727f88710e565cd47bde0049f1b449aef0eb/stake-pool/program/src/big_vec.rs#L163C1-L163C80
And see https://github.com/solana-labs/solana/actions/runs/6029425589/job/16358927677?pr=32961 for a failing run.
It causes loads of churn, but do the right thing: use the alignment-safe `PodU64` and `PodU32` instead of `u64` and `u32`, respectively.
Note: this is blocking the upgrade of the monorepo to 1.72 because of downstream build errors
> stake-pool: Use unaligned types for safe pointer cast

- libraries/pod/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/program-2022/Cargo.toml
When declaring an optional dependency in `Cargo.toml` like so: `serde_with = { version = "3.3.0", optional = true }`, it will automatically define a new feature, in this case `serde_with`.  Adding the `dep:` prefix prevents this.
This is why some spl crates have extra feature flags, for example `spl-token-2022` has `serde` and `serde_with` features, https://docs.rs/crate/spl-token-2022/0.7.0/features
This PR should fix it.
@buffalojoec @joncinque
> Serde optional dependencies clean-up

- token/js/src/extensions/transferHook/instructions.ts
- token/js/src/extensions/transferHook/state.ts
- token/js/test/e2e-2022/transferHook.test.ts
The method is not actually getting any account. Rather it is computing the address for the account. Alongside that I have flipped the parameters around to be consistent with other address getter functions.
> token-js: renamed `getExtraAccountMetaAccount` to `getExtraAccountMetaAddress`

- account-compression/sdk/package.json
As found out through an extensive game of telephone, the account compression JS docs have not been properly deployed.
Following the same changes made to the memo and token JS packages, update the deployment script to specify the destination. Now you'll see all of the docs pages:
* account-compression https://solana-labs.github.io/solana-program-library/account-compression/sdk/
* memo https://solana-labs.github.io/solana-program-library/memo/js/
* token https://solana-labs.github.io/solana-program-library/token/js/
> account-compression: Fixup sdk doc deployment

- stake-pool/program/src/error.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/initialize.rs
It's possible to create a stake pool with some number of decimals that isn't equal to 9. This has absolutely no impact on the functioning of the program, but if a stake pool mint has 2 decimals, when you deposit 1 SOL, you would get ~10,000,000.00 tokens. It's the same number underneath, but it would look wildly different.
Although the tooling already uses 9 in most places to avoid this exact issue, let's just enforce it on-chain to avoid any confusion.
> stake-pool: Enforce that pool mint uses 9 decimal places (HAL-03)

- stake-pool/program/src/processor.rs
There are unnecessary ownership checks in `Initialize` in the stake pool program since the runtime will do the check.
Since security folks typically want to see every parameter checked, even if it's redundant, keep the checks, but add a comment about them
> stake-pool: Add comments about unnecessary ownership checks (HAL-01)

- Cargo.lock
- libraries/program-error/derive/Cargo.toml
- libraries/program-error/derive/src/lib.rs
- libraries/program-error/derive/src/macro_impl.rs
- libraries/program-error/derive/src/parser.rs
- libraries/program-error/src/lib.rs
- libraries/program-error/tests/decode.rs
- libraries/program-error/tests/into.rs
- libraries/program-error/tests/mod.rs
- libraries/program-error/tests/print.rs
- libraries/program-error/tests/spl.rs
- libraries/tlv-account-resolution/src/error.rs
- libraries/type-length-value/src/error.rs
- token-metadata/interface/src/error.rs
- token/transfer-hook-example/tests/functional.rs
- token/transfer-hook-interface/Cargo.toml
- token/transfer-hook-interface/src/error.rs
This PR adds unique, custom error codes to every error in SPL libraries - including the two interfaces `transfer-hook` and `token-metadata`.
The ability to derive unique `u32` error codes from hash inputs is powered by these changes to the `spl-program-error` crate, which simply hashes the following combination of inputs and takes bytes 13 through 16 as the little-endian `u32`:
```text
"spl_program_error:" + <enum name> + ":" + <variant name>
```
This creates unique error codes for each error, as requested in [this comment](https://github.com/solana-labs/solana-program-library/pull/5168#issuecomment-1697853488)
Closes #5042 
Solves discussions in #5168
> SPL errors from hashes

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- libraries/pod/Cargo.toml
- libraries/program-error/Cargo.toml
- libraries/program-error/derive/Cargo.toml
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value-derive-test/Cargo.toml
- libraries/type-length-value/Cargo.toml
- single-pool/cli/Cargo.toml
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- token-metadata/example/Cargo.toml
- token-metadata/interface/Cargo.toml
- token-swap/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook-example/Cargo.toml
- token/transfer-hook-interface/Cargo.toml
In order to release a new token-2022, we need to bump its version and every local crate that it depends on. That means the following:
* spl-token-2022
* spl-program-error
* spl-tlv-account-resolution
* spl-type-length-value
* spl-token-metadata-interface
* spl-token-metadata-example
* spl-transfer-hook-interface
* spl-transfer-hook-example
* spl-token-client (this one's not needed, but it's cleaner)
> release: Bump token-2022 and all dependencies

- .github/workflows/pull-request-token.yml
The monorepo is running 1.72 and the setup steps involved in the `twoxtx` CI job are pulling in the latest Solana version, which causes some non-compatibility between crates.
This repairs failing CI job for `twoxtx`
https://github.com/solana-labs/solana-program-library/actions/runs/6111174177/job/16592442873#step:8:756
> bump twoxtx ci rust version to 1.72.0

- token/cli/src/main.rs
I am in the process of upgrading the token-cli to use clap-v3 (https://github.com/solana-labs/solana-program-library/pull/4506). Since this upgrade necessarily needs a big change, I am trying to divide some smaller parts into individual PRs.
The deprecated `account-info` command uses the helper function `owner_address_arg()` to specify a positional argument.
```
pub fn owner_address_arg<'a, 'b>() -> Arg<'a, 'b> {
Arg::with_name(OWNER_ADDRESS_ARG.name)
.long(OWNER_ADDRESS_ARG.long)
.takes_value(true)
.value_name("OWNER_ADDRESS")
.validator(is_valid_pubkey)
.help(OWNER_ADDRESS_ARG.help)
}
```
The long name does not really make sense for positional arguments, but this is ignored in clap-v2. However, in clap-v3, this becomes an error.
I just hardcoded `owner_address_arg()` into the argument …
> [token-cli] Make owner address argument in `account-info` command to be non-positional

- token/cli/src/main.rs
Although token-metadata operations are supported in the CLI, the metadata update-authority missed the boat because I thought it was handled by `authorize`, when it wasn't. It uses a separate instruction on the token-metadata interface.
Since the token metadata authority isn't a normal `AuthorityType`, and exists on a separate interface, I preferred to keep a cleaner separation of interfaces and avoid mixing the two by adding `AuthorityType::Metadata`.
To do that, add a new `CliAuthorityType`, which also contains the metadata authority, and will do a better job of supporting new authority types going forward. From there, call the token-metadata `update_authority` function properly.
We had a bunch of missing types in the "possible values" part of the authorize command, which is natural …
> token-cli: Support updating metadata authority

- Cargo.lock
- name-service/js/package.json
- name-service/program/Cargo.toml
closes #5211 
Will need to publish new versions after this goes in, as well as cut tags.
For context, the `realloc` instruction was added to the program and SDK after the most recent release for both.
> [name-service]: cut new release for name-service

- token/cli/src/main.rs
```
cargo run -- initialize-metadata 27vKc6xe74j79vwmaUYd18mgjDNLHWXTv49BWKTBktBW lol hi
Finished dev [unoptimized + debuginfo] target(s) in 0.21s   
Running `/home/hana/work/solana/spl/target/debug/spl-token initialize-metadata 27vKc6xe74j79vwmaUYd18mgjDNLHWXTv49BWKTBktBW lol hi`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', token/cli/src/main.rs:4404:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> token-cli: initialize-metadata args are required

- .github/workflows/pull-request-token.yml
- ci/warning/purge-ubuntu-runner.sh
As noted in #5231, CI keeps breaking because of a lack of disk space.
Use the `purge-ubuntu-runner.sh` script in token's `cargo-test-sbf` step.
I added `/imagegeneration` to the script, which I wasn't aware of.
> ci: Make space in token test-sbf run

- associated-token-account/program-test/tests/program_test.rs
The recover_nested tests in ATA have been flakey for sometimes using too much compute budget.
Increase the compute budget limit.
> associated-token-account: Increase compute budget number

- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/deposit_authority.rs
- stake-pool/program/tests/deposit_edge_cases.rs
- stake-pool/program/tests/deposit_sol.rs
- stake-pool/program/tests/force_destake.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/redelegate.rs
- stake-pool/program/tests/set_preferred.rs
- stake-pool/program/tests/set_withdrawal_fee.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/update_validator_list_balance_hijack.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
- stake-pool/program/tests/withdraw_edge_cases.rs
- stake-pool/program/tests/withdraw_sol.rs
- stake-pool/program/tests/withdraw_with_fee.rs
There are still some flaky tests in the stake pool program, but there's no indication about what's going on since we're just doing `assert!(error.is_none())`.
This doesn't fix the flaky tests, but will log the error during failures for future investigation.
> stake-pool: Add error logging during test failures

- Cargo.lock
- stake-pool/cli/src/output.rs
- stake-pool/program/Cargo.toml
- stake-pool/program/src/big_vec.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/src/state.rs
- stake-pool/program/tests/force_destake.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/vsa_add.rs
- stake-pool/program/tests/vsa_remove.rs
https://github.com/solana-labs/solana-program-library/pull/5179 was a quick fix to properly deserialize the stake pool types in-place, updating all contained types to align to 1. This works, but any other type aligned to an address greater than 1 can still expose undefined behavior.
Rather than parametrizing everything in `BigVec` to the `Pack` trait, change `BigVec` to use the bytemuck `Pod` trait, which is designed for this exact situation.
While going through this, I noticed that the custom iterator over `BigVec` was not very performant, and that it was much better to just deserialize the whole slice in-place. With this PR, we can once again support the big pool size from #5179.
> stake-pool: Remove unsafe pointer casts via `Pod` types

- Cargo.lock
- token/cli/Cargo.toml
There have been a couple of fixes since 3.1.0, but they're not accessible to people using `cargo install` or the solana releases.
Bump the version to publish a new release!
> token-cli: Bump to 3.1.1 for release

- stake-pool/js/src/index.ts
- stake-pool/js/src/instructions.ts
- stake-pool/program/src/error.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/redelegate.rs
During redelegate, the first split account should have the rent-exempt reserve populated. This makes it clearer how many lamports are actually moving to the new validator.
Include the stake pool reserve in redelegate, and withdraw the required rent during redelegate.
> stake-pool: Prefund split account during redelegate

- stake-pool/js/src/index.ts
- stake-pool/js/src/instructions.ts
- stake-pool/program/src/error.rs
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/helpers/mod.rs
We should fund the rent-exempt reserve for the transient stake account from the stake pool reserve during decrease.
To start with, require the reserve during `decrease_additional_validator_stake`, and then withdraw the rent-exemption from the reserve during processing.
The next step after this is to create a new instruction for a normal decrease without an ephemeral stake account. Or we could deprecate the old one and force people to always use this one.
> stake-pool: Fund rent-exemption from reserve in `decrease_additional`

- Cargo.lock
Per the failed CI run at https://github.com/solana-labs/solana-program-library/actions/runs/6262299761/job/17004155266?pr=5326, quinn-proto 0.9.4 has a security advisory out.
Bump to quinn-proto 0.9.5
> ci: Update quinn-proto to 0.9.5 for rustsec

- token/cli/src/main.rs
Update-metadata doesn't support offline signing in the token CLI.
Thankfully it's pretty simple -- just add the offline args!
Fixes #5291
> token-cli: Support offline signing for update-metadata

- Cargo.lock
- stake-pool/program/Cargo.toml
- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/redelegate.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/update_validator_list_balance_hijack.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw.rs
- stake-pool/program/tests/withdraw_edge_cases.rs
- stake-pool/program/tests/withdraw_with_fee.rs
Note: this PR builds on #5288, starting with [b482537](https://github.com/solana-labs/solana-program-library/pull/5322/commits/b482537949e1dfcf03e2a0f17587fdb3f77a7a42)
To adapt stake pools to the upcoming changes in https://github.com/solana-labs/solana/pull/33295, stake pools need to pre-fund the rent-exempt reserve during splits in `DecreaseValidatorStake`.
The first commit [b482537](https://github.com/solana-labs/solana-program-library/pull/5322/commits/b482537949e1dfcf03e2a0f17587fdb3f77a7a42) is the meat of the change which adds a new instruction to use the reserve, deprecates the old one. And the rest of the commits fix the tests.
I tested this with #5285 against the monorepo master, and everything passes!
> stake-pool: add new version of `DecreaseValidatorStake` to use reserve, add compatibility with master

- Cargo.lock
- libraries/tlv-account-resolution/Cargo.toml
- libraries/tlv-account-resolution/README.md
- libraries/tlv-account-resolution/src/account.rs
- libraries/tlv-account-resolution/src/error.rs
- libraries/tlv-account-resolution/src/seeds.rs
- libraries/tlv-account-resolution/src/state.rs
- token/program-2022-test/tests/transfer_hook.rs
- token/program-2022/src/offchain.rs
- token/transfer-hook-interface/src/offchain.rs
This PR adds support for account data as a seed configuration for a PDA stored
within validation data.
A dynamic program-derived address may depend on one or more seeds that are
actually taken from the inner data of some account in the list of accounts
provided to the program.
- Commit 1: Changes made to account resolution
- Commit 2: Re-working tests and docs
- Commit 3: Fixing the closure provided to a transfer hook test to return `None` for accounts that don't exist
> Support Account Data for Seeds in Account Resolution

- Cargo.lock
- token/program-2022/Cargo.toml
We need to update the monorepo to a newer version of token-2022, but the 0.8.0 release is missing some required features from the monorepo, as it's still on 1.16.3.
Cut a release for 0.8.1
cc @samkim-crypto
> token-2022: Bump to 0.8.1 for release

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- libraries/tlv-account-resolution/Cargo.toml
- single-pool/cli/Cargo.toml
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- token-metadata/example/Cargo.toml
- token-swap/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook-example/Cargo.toml
- token/transfer-hook-interface/Cargo.toml
We want to use a new version of spl-token-2022, but its version on master depends on spl-tlv-account-resolution, which made a breaking change to support deriving PDAs from account data.
Bump tlv-account-resolution and everything that depends on it to a new minor version. The idea was to do a minor version bump on things that we want to release, and things that would break because of the change.
> release: Bump tlv-account-resolution and dependents

- stake-pool/py/stake_pool/actions.py
- stake-pool/py/stake_pool/instructions.py
- stake-pool/py/tests/test_a_time_sensitive.py
- stake-pool/py/tests/test_bot_rebalance.py
This builds on https://github.com/solana-labs/solana-program-library/pull/5322, so only the last commit matters.
https://github.com/solana-labs/solana-program-library/pull/5322 introduces a new version of `DecreaseValidatorStake`, but it doesn't add it to the python bindings.
Add the instruction and use it properly in tests
> stake-pool-py: Add and use new decrease instruction

- stake-pool/js/src/index.ts
- stake-pool/js/src/instructions.ts
- stake-pool/js/test/instructions.test.ts
This builds on  #5322, so only the last commit matters.
#5322 introduces a new version of `DecreaseValidatorStake`, but it doesn't add it to the JS bindings.
Add the instruction
> stake-pool-js: Add new decrease instruction 

- Cargo.lock
- token/cli/Cargo.toml
- token/cli/src/encryption_keypair.rs
- token/cli/src/main.rs
- token/cli/src/output.rs
There are no cli support for confidential transfers yet.
Updated/added cli commands regarding the mint. The `create-token` with `--enable-confidential-transfers` flag should already be supported.
[f616231](https://github.com/solana-labs/solana-program-library/pull/5335/commits/f616231da8b821759220b30072a01de9ba7605fc): Updated the `display` command to support the confidential transfer mint extension. Unfortunately, the `solana-account-decoder` is still using the older version of token-2022 before the confidential transfer and confidential transfer fee extensions were split, which means we can't use the `UiConfidentialTransferMint` type from `solana-account-decoder`. I hard-coded a temporary `UiConfidentialTransferMint` type in `output.rs` to account for this. This part can be removed in …
> [token-cli] Add confidential transfer mint commands

- Cargo.lock
- libraries/discriminator/derive/Cargo.toml
- libraries/discriminator/syn/Cargo.toml
- libraries/discriminator/syn/src/lib.rs
- libraries/program-error/derive/Cargo.toml
- libraries/program-error/derive/src/macro_impl.rs
While updating the monorepo to use the new spl crates, like token-2022, I got a really strange build error:
```
warning: output filename collision.
The lib target `solana-program` in package `solana-program v1.17.0 (/home/jon/src/solana/solana/sdk/program)` has the same output filename as the lib target `solana-program` in package `solana-program v1.17.0 (/home/jon/src/solana/solana/sdk/program)`.
Colliding filename is: /home/jon/src/solana/solana/target/debug/deps/libsolana_program.so
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```
After the warning, it complained that `solana_sdk` didn't exist.
I dug around for a bit, and …
> macro: Remove dependency on solana-program

- Cargo.lock
- libraries/program-error/Cargo.toml
- libraries/program-error/derive/Cargo.toml
While making the change in #5375 to remove the solana-program dependency, I forgot to bump the version on spl-program-error-derive
Bump the version!
> release: Bump spl-program-error-derive for release

- ci/do-audit.sh
There's a RUSTSEC advisory on tungstenite https://rustsec.org/advisories/RUSTSEC-2023-0065 causing CI failures
Same as 1.16, ignore the advisory: https://github.com/solana-labs/solana/pull/33457
> ci: Ignore tungstenite security advisory

- token/program-2022-test/tests/confidential_transfer.rs
There was a spurious failure during CI in a confidential transfer test: https://github.com/solana-labs/solana-program-library/actions/runs/6383061276/job/17322950719
Essentially, we're doing the same thing twice in a row without refreshing the blockhash, so there's a chance that the program-test will return the same old response.
Refresh the blockhash
> token-2022: Refresh blockhash in flaky test

- account-compression/Cargo.lock
- account-compression/programs/account-compression/Cargo.toml
- account-compression/sdk/package.json
- rust sdk 0.2.0 -> 0.3.0 
- ts sdk 0.1.10 -> 0.2.0
Minor versioning because new buffer/depth options have tiny potential to break systems that hard-coded the previous list.
> [account compression] bump sdk versions

- stake-pool/program/src/instruction.rs
- stake-pool/program/src/processor.rs
- stake-pool/program/tests/force_destake.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/py/stake_pool/instructions.py
As mentioned in a Discord discussion https://discord.com/channels/428295358100013066/859540542608900127/1157393252119478332, stake pools cannot properly handle a validator that has been force-destaked through the new `DeactivateDelinquent` instruction on the stake program.
It's pretty simple -- don't try to deactivate a stake account again during removal. This way, the manager simply needs to remove the validator and then re-run an update to reabsorb the account.
While going through this, I also relaxed the check on an activating / active transient stake account, so that it'll just deactivate it. This way, we prevent a potential malfunction during this edge case:
* someone deactivates-delinquent the main stake account, but *not* an activating transient stake account
* the delinquent …
> stake-pool: Allow removal of force-destaked validator

- stake-pool/program/tests/force_destake.rs
As pointed out at https://github.com/solana-labs/solana-program-library/pull/5439#issuecomment-1758777522, the new test for removing a force destaked validator is failing the monorepo downstream job.
Not really a solution, but ignore the test for now to unblock the monorepo.
> stake-pool: Ignore test that fails in downstream

- token/cli/src/main.rs
- token/cli/src/output.rs
There are many extensions that aren't displayed by the token CLI, because it's using the older parsers.
The parsers were updated in https://github.com/solana-labs/solana/pull/33453 though, so use all of those!
Before, a devnet mint with metadata showed no extensions, and now it'll show:
```
SPL Token Mint
Address: 25HxeJ6NKj8akSKLZmnxzLtxKnSK1wZEwjuCEJjsijqJ
Program: TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
Supply: 3000000
Decimals: 6
Mint authority: DtkFBodq67HK9tzFgkjnWw2ZS4LZZgAVqeerukxp6rZs
Freeze authority: GkatiJtcJWVToqYgqQKRx6qUbcTAzMm5fLVgzZCeS3xH
Extensions
Permanent delegate: GkatiJtcJWVToqYgqQKRx6qUbcTAzMm5fLVgzZCeS3xH
Metadata Pointer:
Authority: G8ENSYKVGPbRTbcN1BxXuRMYeCq13271UjCUrrpZTJ4X
Metadata address: 25HxeJ6NKj8akSKLZmnxzLtxKnSK1wZEwjuCEJjsijqJ
Metadata:
Update …
```
> token-cli: Display all mint and account extensions

- stake-pool/program/tests/force_destake.rs
As noted in https://github.com/solana-labs/solana-program-library/pull/5439#issuecomment-1758777522, the new force-destake test was failing in the downstream job from the monorepo.
This is happening because the test is serializing 196 bytes for the stake account, rather than the expected 200 bytes. This works fine in 1.16, where we don't use the extra 4 bytes. In 1.17 and 1.18, however, those extra 4 bytes matter for the stake flags.
Overallocate the vector used when serializing a `StakeState`.
> stake-pool: Fix test for monorepo downstream job

- single-pool/cli/src/cli.rs
- single-pool/cli/src/main.rs
- single-pool/cli/tests/test.rs
- single-pool/js/src/internal.ts
- single-pool/program/src/instruction.rs
- single-pool/program/src/processor.rs
- single-pool/program/tests/accounts.rs
- single-pool/program/tests/reactivate.rs
handles the issue described in #5439. the first commit is the important one (changes the program itself), the others just add to the cli. also i moved half the commands into a subcommand, 99% of users are only ever going to need `deposit` and `withdraw` so im trying to minimize visual clutter
> single-pool: add `ReactivatePool` instruction

- token/cli/src/main.rs
- token/client/src/token.rs
- token/program-2022-test/tests/token_metadata_remove_key.rs
- token/program-2022-test/tests/token_metadata_update_field.rs
Even though #5326 attempted to add offline signing support for `update-metadata`, it did not cover the case of updating metadata and transferring lamports to cover the new rent-exempt amount of the account.
Add a new `--transfer-lamports` parameter which is required for offline signing. With this PR, you can do:
```
$ spl-token update-metadata 5K8RVdjpY3CHujyKjQ7RkyiCJqTG8Kba9krNfpZnmvpS new-field new-value --sign-only --blockhash 5K8RVdjpY3CHujyKjQ7RkyiCJqTG8Kba9krNfpZnmvpS --transfer-lamports 10
Blockhash: 5K8RVdjpY3CHujyKjQ7RkyiCJqTG8Kba9krNfpZnmvpS
Signers (Pubkey=Signature):
4SnSuUtJGKvk2GYpBwmEsWG53zTurVM8yXGsoiZQyMJn=3oMKkcJPxceeKByiqawu39LttYkpSUFBC3oLDsjkogBGvCiZ8SLpPFMaSt5pGWfT9fg6H8R8MXXzbRNX2Sx12RBa
```
> token-cli: Fix updating metadata with offline signer

- Cargo.lock
- token/cli/Cargo.toml
There have been some fixes and updates to the token-cli, to display new extensions, and to correctly update metadata with offline signers, but it's not released yet.
Bump the version to release!
> token-cli: Bump to 3.2.0 for release

- Cargo.lock
- token/client/Cargo.toml
We bumped token-cli in #5531, but we also need the token-client on a new version because of a changed function.
Bump the version!
> token-client: Bump to 0.7.1 for release

- token/program-2022/src/extension/cpi_guard/mod.rs
- token/program-2022/src/extension/default_account_state/mod.rs
- token/program-2022/src/extension/immutable_owner.rs
- token/program-2022/src/extension/interest_bearing_mint/mod.rs
- token/program-2022/src/extension/memo_transfer/mod.rs
- token/program-2022/src/extension/metadata_pointer/mod.rs
- token/program-2022/src/extension/mint_close_authority.rs
- token/program-2022/src/extension/non_transferable.rs
- token/program-2022/src/extension/permanent_delegate.rs
- token/program-2022/src/extension/transfer_fee/mod.rs
- token/program-2022/src/extension/transfer_hook/mod.rs
Fixes #5431 
Note that for extension `confidentional_transfer` and `confidential_transfer_fee`,  some the fields are in a separate sdk which doesn't  have the serialisation enabled. We would have to change there first before setting it here 
Tested by turning on the compile time flags `serde-trait` by default and using it in our codebase.
> token-2022(feat): add serialisation option for the extensions

- Cargo.lock
- single-pool/cli/Cargo.toml
- single-pool/cli/src/cli.rs
- single-pool/cli/src/main.rs
- single-pool/cli/src/output.rs
- single-pool/cli/tests/test.rs
- single-pool/js/packages/classic/tests/fixtures/spl_single_pool.so
- single-pool/js/packages/classic/tests/fixtures/spl_single_validator_pool.so
- single-pool/js/packages/classic/tests/transactions.test.ts
- single-pool/program/Cargo.toml
- single-pool/program/src/instruction.rs
- single-pool/program/tests/accounts.rs
- single-pool/program/tests/create_pool_token_metadata.rs
- single-pool/program/tests/deposit.rs
- single-pool/program/tests/helpers/mod.rs
- single-pool/program/tests/helpers/token.rs
- single-pool/program/tests/initialize.rs
- single-pool/program/tests/reactivate.rs
- single-pool/program/tests/update_pool_token_metadata.rs
- single-pool/program/tests/withdraw.rs
- stake-pool/program/src/inline_mpl_token_metadata.rs
actually for real final pr before i tag my 1.0 versions and release... this is so we can be `spl-single-pool` and `spl-single-pool-cli` on crates.io. ive removed all uses of "single-validator pool," officially we are "single-pool" or "svsp" for short and "single-validator stake pool" in full
once this is in i will:
* make three tags and three releases for program, cli, js (js-classic depends on js-modern so these should advance in lockstep, hence no fourth release)
* cargo and npm publish
* update docs with npm url and reactivate example and merge #5414 
* program on devnet!!!
ill hold the devnet upgrade authority for now, we need to figure out who will ultimately be the uprgrader for mainnet before we deploy there. but the finish line is in sight
> single-pool: rename program to spl_single_pool

- Cargo.lock
- Cargo.toml
- token-group/interface/Cargo.toml
- token-group/interface/src/error.rs
- token-group/interface/src/instruction.rs
- token-group/interface/src/lib.rs
- token-group/interface/src/state.rs
This PR initializes a newer, slimmed down version of the SPL Token Group interface.
Previous PR: #5190
> token group: init interface

- single-pool/js/packages/classic/package.json
The single-pool js tests are failing in CI, e..g https://github.com/solana-labs/solana-program-library/actions/runs/6560481835/job/17818975411
It was fiddly, but I needed to make two changes -- one to use the `import` flag instead of `loader`, and then to use the common js loader instead of esm. Who knows why this works? Not me! :upside_down_face:
> single-pool-js: Fix ci

- token/cli/src/main.rs
The token-cli does not yet support initializing confidential transfer account
Added configuring cli commands for confidential transfer accounts. I think each commits should be pretty straightforward and independent with the following note:
- For `configure-confidential-transfer-account`, I made it so that the elgamal and aes keys are derived from the signer by default. This can be updated so that users have the option to initialize the account with custom keys once we upgrade to clap-v3-utils.
> [token-cli] Enable configuring confidential transfer account

- token-group/interface/src/state.rs
I realized I didn't add the mint as a required field in the state of a `TokenGroup` or `TokenGroupMember`.
This PR adds the mint!
> token group: add mint to interface

- token/program-2022/src/extension/cpi_guard/mod.rs
- token/program-2022/src/extension/default_account_state/mod.rs
- token/program-2022/src/extension/immutable_owner.rs
- token/program-2022/src/extension/interest_bearing_mint/mod.rs
- token/program-2022/src/extension/memo_transfer/mod.rs
- token/program-2022/src/extension/metadata_pointer/mod.rs
- token/program-2022/src/extension/mint_close_authority.rs
- token/program-2022/src/extension/non_transferable.rs
- token/program-2022/src/extension/permanent_delegate.rs
- token/program-2022/src/extension/transfer_fee/mod.rs
- token/program-2022/src/extension/transfer_hook/mod.rs
#5437 did some great work with deriving the serde traits, but we forgot to specify `rename_all = "camelCase"` as a separate attribute, which means that we'd get some inconsistency in the serialization.
Just add the attribute config. There were also a couple of transfer-fee structs that didn't have it, so I added those.
> token-2022: Use serde with `rename_all = "camelCase"`

- token/client/src/token.rs
- token/program-2022-test/tests/group_pointer.rs
- token/program-2022/src/extension/group_pointer/instruction.rs
- token/program-2022/src/extension/group_pointer/mod.rs
- token/program-2022/src/extension/group_pointer/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
This PR adds the `GroupPointer` extension to Token2022.
This extension behaves exactly like the existing `MetadataPointer` extension, serving to denote the corresponding account containing a mint's group configurations and prevent any unauthorized configurations.
> token 2022: add `GroupPointer` extension

- token-metadata/js/package-lock.json
- token-metadata/js/package.json
Bumps the version of the new SPL Token Metadata JS library to `0.1.0` for release.
> token metadata js: bump version to 0.1.0

- .github/workflows/pull-request-token-collection.yml
- Cargo.lock
- Cargo.toml
- token-collection/README.md
- token-collection/program/Cargo.toml
- token-collection/program/src/entrypoint.rs
- token-collection/program/src/lib.rs
- token-collection/program/src/processor.rs
- token-collection/program/tests/setup.rs
- token-collection/program/tests/token_collection.rs
Ok, I threw this together to see what we think of it. A reference example of using SPL Token Group to make a Collections program.
> token collection: create spec program

- .github/workflows/pull-request-token.yml
- Cargo.lock
- Cargo.toml
- ci/cargo-build-test.sh
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/cli/src/main.rs
I want to demo transfer hooks at breakpoint, but there's no easy way to create / manage the extra account metas required for transfer hooks.
Create a simple CLI that can do exactly that. It even comes with a test and everything! The parsing of extra account metas was lifted directly from the token-cli, with some small modifications for clap v3. The tests were mostly lifted from the token-upgrade-cli.
> transfer-hook-cli: Add a tool for creating account metas

- token/cli/src/main.rs
The token-cli does not yet support confidential transfer instructions to deposit and withdraw confidential transfer tokens, apply pending balance to available balance, and make a confidential transfer.
Add the four commands for the four instructions listed above. For confidential transfers, the functionality is added into the existing `transfer` command instead of creating a dedicated command for confidential transfers.
> [token-cli] Add confidential transfer deposit, withdraw, apply pending balance, and confidential transfer

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
A lot of the confidential transfer functions in the token client parametrize on `Signer` and accept multiple keypairs for the required signatures (account authority, context state accounts, etc). This does not work with the token CLI, which uses a huge `bulk_signers` everywhere.
Change all of the functions to take in `Signers` instead! This works very nicely for the most part, but the split-proofs-in-parallel functions get a little tricky since you need to craft the correct `Signers` arrays for each transaction.
Let me know how it looks! You should be able to track each commit pretty easily, since each one actually works on its own.
> token-client: Use `Signers` instead of `Signer` for confidential transfer functions

- token/cli/src/main.rs
- token/client/src/token.rs
We can't do confidential token withdrawal through the cli due to the transaction size limit
Divide up the process of creating proof context states and the actual token withdraw.
> [token-cli] sequentially process confidential transfer withdraw in token-cli

- token/cli/src/main.rs
- token/cli/src/output.rs
The `conflicts_with` on confidential token `deposit` and `withdraw` makes it unusable with `--address`.
Also, colons `:` appear twice while displaying confidential transfer mint info.
In separate commits:
* remove `conflicts_with("address")` for deposit and withdraw
* remove the extra colon
> token-cli: Cleanup `conflicts_with` and output colons

- Cargo.lock
- single-pool/cli/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-metadata/example/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
The token-cli supports confidential operations, but it hasn't been released yet!
Bump it (and spl-token-client` to new minor versions for the next release.
Note: this should land after #5688
> token-cli{,ent}: Bump version for release

- .github/workflows/pull-request-token.yml
The token JS tests have been flaky in CI, sometimes failing to download the transfer hook example program. This is because the JS step incorrectly doesn't require the transfer hook example to be built.
Require that the transfer hook example program be built too!
> ci: Fix flakiness on token js tests

- docs/src/token-2022/extensions.mdx
- docs/src/token-2022/presentation.md
- docs/src/token-2022/status.md
- token/cli/src/main.rs
We've added a lot of functionality for using extensions in the CLI, but it isn't exposed in the docs.
This is a bit of a kitchen sink of changes, but it should update everything roughly to where we are.
Someone also pointed out that the command were incorrect for transfer-hooks, so I decided to make those consistent
> docs: Update token-2022 extensions

- docs/src/confidential-token/quickstart.md
The confidential transfer quickstart doc is empty, but we can use confidential transfers!
Add some simple examples of how to use confidential transfers in the CLI
> docs: Add quickstart guide for confidential tokens

- .github/dependabot.yml
The dependabot PRs don't properly update the lockfile, probably because we have a job for each JS library, where it doesn't look for the pnpm lockfile.
Update the npm directory to the root of the repo and remove all of the copied jobs. While I was at it, I updated to UTC to make it clearer when it runs.
> dependabot: Update npm to root to properly update dependencies

- stake-pool/program/src/state.rs
Token-2022 version 0.9.0 split out the confidential transfer fee extension from the confidential transfer extension, but stake pools are not aware of that.
Also allow `ConfidentialTransferFeeConfig` as an extension for stake pool mints.
> stake-pool: Allow mints with confidential transfer fee

- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/index.ts
- token/js/src/extensions/metadataPointer/index.ts
- token/js/src/extensions/metadataPointer/instructions.ts
- token/js/src/extensions/metadataPointer/state.ts
- token/js/src/instructions/types.ts
- token/js/test/e2e-2022/metadataPointer.test.ts
- token/js/test/unit/metadataPointer.test.ts
Adding support for the metadata pointer extension
Split out of wider task to add metadata support for ease of review
https://github.com/solana-labs/solana-program-library/pull/5667
> token 2022: add metadata pointer extension to js @solana/spl-token client

- token/cli/src/main.rs
As noted in #5804, it's currently not possible to update the approve policy and the auditor pubkey during `update-confidential-transfer-mint` because only one `update_field` is allowed at once.
Allow both to be set by setting `multiple(true)` on the `"update_field"` parameter.
cc @samkim-crypto
> token-cli: Make update confidential accept multiple args

- token/js/src/errors.ts
- token/js/src/extensions/transferHook/instructions.ts
- token/js/src/extensions/transferHook/seeds.ts
- token/js/src/extensions/transferHook/state.ts
- token/js/test/common.ts
- token/js/test/unit/transferHook.test.ts
This PR adds support for the `AccountData` seed from the
`spl-tlv-account-resolution` library and Token2022.
This addresses point number 2 in #5685.
> [token js]: transfer-hook: add support for account data seeds

- token/js/src/extensions/transferHook/instructions.ts
This PR adds the `deEscalateAccountMeta` function in JavaScript, which was
previously missing.
The new function operates exactly the same as its Rust counterpart in
`spl-tlv-account-resolution`.
Addresses point number 1 in #5686.
> [token js]: transfer-hook: add account meta de-escalation

- token/js/src/extensions/transferHook/instructions.ts
This PR modifes the ordering of pushing account metas to an instruction to align
exactly with the Rust interface's `offchain` helper.
Closes #5686
> [token js]: transfer-hook: align key pushing flow with Rust helpers

- .github/dependabot.yml
The dependabot tab in the dependency graph is giving an error:
```
The property '#/updates/0/schedule/time' value "9:00" did not match the regex '^\d\d:\d\d$'
```
Because the time is specified "9:00".
Update it to "09:00"
> dependabot: Fix time format to add leading 0

- token-metadata/js/package.json
- token-metadata/js/src/state.ts
- token-metadata/js/test/state.test.ts
Token2022 doesn't using 8-byte discriminators, and can't use the unpack function current in @solana/spl-token-metadata which assumes 8-byte discriminators.
This PR exposes a function that just decodes to the data, so it can be used in Token2022.
Discussion where the need arose:
https://github.com/solana-labs/solana-program-library/pull/5667#discussion_r1390234922
> token 2022: Expose token-metadata state decoder in @solana/token-metata

- .github/workflows/fuzz-nightly.yml
- .github/workflows/pull-request-account-compression.yml
- .github/workflows/pull-request-binary-oracle-pair.yml
- .github/workflows/pull-request-docs.yml
- .github/workflows/pull-request-examples.yml
- .github/workflows/pull-request-feature-gate.yml
- .github/workflows/pull-request-feature-proposal.yml
- .github/workflows/pull-request-governance.yml
- .github/workflows/pull-request-instruction-padding.yml
- .github/workflows/pull-request-js.yml
- .github/workflows/pull-request-libraries.yml
- .github/workflows/pull-request-memo.yml
- .github/workflows/pull-request-name-service.yml
- .github/workflows/pull-request-record.yml
- .github/workflows/pull-request-shared-memory.yml
- .github/workflows/pull-request-single-pool.yml
- .github/workflows/pull-request-stake-pool.yml
- .github/workflows/pull-request-token-collection.yml
- .github/workflows/pull-request-token-group.yml
- .github/workflows/pull-request-token-lending.yml
- .github/workflows/pull-request-token-metadata.yml
- .github/workflows/pull-request-token-swap.yml
- .github/workflows/pull-request-token-upgrade.yml
- .github/workflows/pull-request-token.yml
- .github/workflows/pull-request.yml
- .github/workflows/spl_action.yml
Our GitHub Actions runs produce loads of warnings because we're using old versions of actions or deprecated actions.
Update them all! Everything was done in separate commits, but here's the list:
* actions/checkout -> v4
* actions/cache -> v3
* actions/upload-artifact -> v3
* actions/download-artifact -> v3
* actions/setup-node -> v4
* actions-rs/toolchain -> [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) which seems to be the next version used by everyone, maintained by a Rust OG
* actions-rs/cargo -> just call `cargo`
* actions-rs/install -> just call `cargo install`
> CI: Update GitHub actions to modern versions

- token/client/src/token.rs
- token/program-2022-test/tests/token_group_update_max_size.rs
- token/program-2022/src/extension/token_group/processor.rs
This PR adds the `UpdateGroupMaxSize` instruction to Token2022 - from the SPL Token Group interface.
> token 2022: add `UpdateGroupMaxSize` instruction from SPL Token Group interface

- .github/workflows/pull-request-stake-pool.yml
As a final follow-up to #5844, actions/setup-python is also outdated.
To keep this PR slim, just update the stake pool job to use actions/setup-python v4
> ci: Update actions/setup-python to v4

- token/client/src/token.rs
- token/program-2022-test/tests/token_group_update_authority.rs
- token/program-2022/src/extension/token_group/processor.rs
This PR adds the `UpdateGroupAuthority` instruction to Token2022 - from the SPL Token Group interface.
> token 2022: add `UpdateGroupAuthority` instruction from SPL Token Group interface

- .github/workflows/pull-request-binary-oracle-pair.yml
- .github/workflows/pull-request-feature-proposal.yml
- .github/workflows/pull-request-governance.yml
- .github/workflows/pull-request-single-pool.yml
- .github/workflows/pull-request-stake-pool.yml
- .github/workflows/pull-request-token-collection.yml
- .github/workflows/pull-request-token-lending.yml
- .github/workflows/pull-request-token-swap.yml
- .github/workflows/pull-request-token-upgrade.yml
CI is still running too many jobs when `token/js` changes because many downstream workflows run if `token/**` is changed.
Update the downstream workflows to also exclude `token/js/**`
> ci: Don't run downstream workflows if token/js is changed

- .github/workflows/pull-request-libraries.yml
The js-test-tlv step in the libraries CI run is failing because it's still trying to use the old script of `js-test-tlv.sh`, which was renamed to `js-test-libraries.sh`: https://github.com/solana-labs/solana-program-library/actions/runs/6934539549/job/18862851015
Update the script name in the CI job
> ci: Update script name for libraries JS run

- docs/src/token.mdx
As evidenced by the comment at https://github.com/solana-labs/solana-program-library/issues/2742#issuecomment-1822038083, people don't know the status of the token program.
Add a couple of lines in the docs to essentially say that the token program isn't changing.
> docs: Add status of the token program

- .github/workflows/spl_action.yml
The docs publish job is still using node 16, whereas the deployment now requires 18, and the vercel build is already configured to 18.
Update the publish job to 18 too.
> ci: Update node version to 18 on docs

- .github/workflows/spl_action.yml
Even though the CI docs workflow was just updated, the publish step didn't run because it needs a change to `docs/**`.
Also have the job run when the workflow file is changed.
> ci: Run docs publish when CI job is updated too

- docs/docusaurus.config.js
This will open the editor on `master` and then prompt the user to commit directly to `master` or create a PR, and they _shouldn't_ have perms to do the former.
> [docs]: add edit page button to GitHub PRs

- token/program-2022/src/extension/confidential_transfer_fee/instruction.rs
The instruction creators for some of the confidential-transfer-with-fee instructions add the multisig signers as non-signers. An instruction created in this way will not work, since all of the multisig signers must sign the transaction.
Have the multisig signers declared as signing.
> token-2022: [OS-SPL-ADV-02] Fix instruction creator

- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
During confidential transfer approval, there's no check to make sure that the token account corresponds to the provided mint. This makes it possible to approve accounts on other mints.
Add a check that the provided token account belongs to the provided mint.
> token-2022: [OS-SPL-ADV-03] Check account mint in approve

- token/cli/src/clap_app.rs
This PR adds the validation for a valid pubkey on the `--metadata-address <ADDRESS>` arg for `spl-token create-token`.
> [token cli]: add validation to metadata address

- token/client/src/token.rs
- token/program-2022-test/tests/token_group_initialize_member.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/token_group/mod.rs
- token/program-2022/src/extension/token_group/processor.rs
This PR adds the `InitializeMember` instruction to Token2022 - from the SPL Token Group interface.
> token 2022: add `InitializeMember` instruction from SPL Token Group interface

- token/program-2022-test/tests/group_member_pointer.rs
This PR adds a test to ensure a mint can successfully be initialized with _both_
a `GroupPointer` and a `GroupMemberPointer`.
A mint may be both a member of a group, but also a group itself (or sub-group).
> token 2022: add a test for mint with group and member pointer

- Cargo.lock
- token/program-2022/Cargo.toml
- token/program-2022/src/entrypoint.rs
There is support for showing the Neodyme security.txt in the explorer, but none of our programs support it.
Following the directions at https://github.com/neodyme-labs/solana-security-txt, add it to token-2022. Note that this will need to get updated on every release along with versions.
> token-2022: Add security.txt

- Cargo.lock
- stake-pool/program/Cargo.toml
- stake-pool/program/src/entrypoint.rs
There is support for showing the Neodyme security.txt in the explorer, but none of our programs support it.
Following the directions at https://github.com/neodyme-labs/solana-security-txt, add it to stake pool. Note that this will need to get updated on every release along with versions.
> stake-pool: Add security.txt

- token/program-2022/src/entrypoint.rs
As pointed out at https://github.com/solana-labs/solana-program-library/pull/5929#discussion_r1409700660, the current discord link might expire.
Use the solana.com version
> token-2022: Update discord link in security.txt

- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022/src/entrypoint.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/confidential_transfer/verify_proof.rs
The accounts that are required for a confidential transfer with split proof are as follows:
```
///   1. `[writable]` The source SPL Token account.
///   2. `[]` The token mint.
///   3. `[writable]` The destination SPL Token account.
///   4. `[]` Context state account for
///      `VerifyCiphertextCommitmentEqualityProof`.
///   5. `[]` Context state account for
///      `VerifyBatchedGroupedCiphertext2HandlesValidityProof`.
///   6. `[]` Context state account for `VerifyBatchedRangeProofU128`.
///   7. `[signer]` The source account owner.
///   If `close_split_context_state_on_execution` is set, all context state
///     accounts must be `writable` and the following sequence
///     of accounts are needed:
///   8. `[]` The destination account for lamports from the context state
/// …
```
> token-2022: [OS-SPL-ADV-00] Enable and fix account ordering on confidential transfer with split proofs

- Anchor.toml
`anchor_version` and `solana_version` in [`Anchor.toml`](https://github.com/solana-labs/solana-program-library/blob/5da184aed56cda46b0006ebf3ea5d617ef0501a8/Anchor.toml#L1-L2) is obsolete after `anchor-cli 0.29.0`.
Define the versions under `[toolchain]`.
**Note:** This change also makes Anchor use the versions specified in `Anchor.toml` in all commands, not just verifiable builds. See the [release notes](https://github.com/coral-xyz/anchor/blob/dfee9589fd56f9aa1a52aa949507b70035482857/docs/src/pages/docs/release-notes.md#override-toolchain-for-the-workspace) for more info.
> repo: Add `[toolchain]` to `Anchor.toml`

- token/cli/src/command.rs
- token/cli/tests/command.rs
As reported at https://solana.stackexchange.com/questions/8106/is-it-possible-yet-to-use-mint-tokens-supporting-both-transfer-fees-and-confiden, the token-cli currently fails when creating a mint with a transfer fee and confidential transfers, even though we have tests that work for creating the mint.
It's a bit tricky since we're not receiving the ElGamal keypair, but this little bandaid solution uses the default signer's derived ElGamal keypair. This will unblock people who want to create a mint with both.
If you think this is a bad idea, however, I'll relent and we can just say it's unsupported until 1.18.
> token-cli: Support creating mint with fee and conf transfer

- governance/program/src/instruction.rs
Improved version of this PR: https://github.com/solana-labs/solana-program-library/pull/5723
Remove the `rent` account from the doc since it is no longer used in these 4 ixs:
[CreateGovernance](https://github.com/solana-labs/solana-program-library/blob/eeb1ca9601afb3675011063cc20d87fbb3b693aa/governance/program/src/processor/process_create_governance.rs#L31-L42)
[CreateProgramGovernance](https://github.com/solana-labs/solana-program-library/blob/eeb1ca9601afb3675011063cc20d87fbb3b693aa/governance/program/src/processor/process_create_program_governance.rs#L37-L53)
[CreateMintGovernance](https://github.com/solana-labs/solana-program-library/blob/eeb1ca9601afb3675011063cc20d87fbb3b693aa/governance/program/src/processor/process_create_mint_governance.rs#L39-L54) …
> Governance: remove `rent` from the docs

- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/token_group/processor.rs
Token-2022 has undergone the final audit for 1.17, but the audit did not include the implementation of the token-group interface.
For safety, featurize the token-group instruction processor. This way, we can still build a version of the program for mainnet, while still keeping and testing its code. Also, this will let us implement the type decoders in the monorepo without going through another round of releases.
While I was at it, I noticed that the `proof-program` feature wasn't used anywhere, so I removed it
> token-2022: Featurize the token-group processor

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- stake-pool/program/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-metadata/example/Cargo.toml
- token-swap/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/program-2022/src/entrypoint.rs
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
Token-2022 is ready for 1.0, but it's still on version 0.9.
Bump it! We'll also need to bump all of its downstream users in SPL, but I wanted to keep this PR separate so we can tag a release from it more cleanly.
> token-2022: Bump to 1.0.0 for prod release

- SECURITY.md
- account-compression/sdk/README.md
- binary-option/README.md
- docs/src/name-service.md
- governance/NOTES.md
- governance/program/src/instruction.rs
- libraries/program-error/README.md
- libraries/tlv-account-resolution/README.md
- libraries/type-length-value/README.md
I spotted a few typos and issues in the Solana docs and I thought I'd help out with some quick fixes:
1. *Name Service Doc:* Fixed a grammar issue for better clarity.
2. *Tutorial Code Mix-up:* Corrected a variable name error (other_value1 to other_value2) in the type-length-value tutorial.
3. *Various Typo Corrections:*
- 'Motivation' section: 'intepret' to 'interpret'.
- tlv-account-resolution README: 'challeneges' to 'challenges'.
- program-error README: 'procedureal' to 'procedural'.
- account-compression SDK link typo fixed.
4. *Binary Option README Updates:* Grammar fixes and corrected 'Milwaulkee' to 'Milwaukee', 'combanatorics' to 'combinatorics'.
5. *Governance Instruction and Notes:* Updated 'singer' to 'signer' and fixed a date format issue.
6. *Security Doc:* Added a missing …
> Documentation Tweaks

- pnpm-lock.yaml
- token-metadata/js/package.json
This PR bumps the version for SPL Token Metadata JS.
Note the previous patch version was published with `npm publish`, not `pnpm publish`, so the dependency link to the TLV library does not resolve on install:
```json
"@solana/spl-type-length-value": "workspace:*",
```
In order to avoid this issue in the future, and allow installing of `@solana/spl-token-metadata` with any package manager, I've also removed the `workspace:*` path in exchange for the real version.
> token metadata js: bump version

- pnpm-lock.yaml
- single-pool/js/packages/classic/package.json
- stake-pool/js/package.json
- token-lending/js/package.json
- token-metadata/js/package.json
- token-swap/js/package.json
- token/js/package.json
This PR removes the `workspace:*` path from all JS libraries, while we wait for `npm` to incorporate workspace resolution.
In the meantime, this will ensure any downstream developers can install these packages with any package manager.
> js: remove workspace paths

- Cargo.lock
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
After #5894 we need to bump the versions for Transfer Hook interface & example, then push some new cratez!
> transfer hook: bump

- Cargo.lock
- libraries/tlv-account-resolution/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
In step with #5970 we need to bump the TLV Account Resolution library.
Note: I think I semi-bungled this a bit. I published `spl-transfer-hook-interface`, which was using the previous version of TLV Account Resolution, however it does not use any of the new version `0.5.0` code.
The example, however, does use the new code, so it requires version `0.5.0`.
If both are used together, Cargo should resolve to `0.5.0` all the time, right?
> tlv account resolution: bump

- Cargo.lock
- token/transfer-hook/interface/Cargo.toml
This bump to `spl-transfer-hook-interface` adds the newer version of `spl-tlv-account-resolution` (`0.5`).
> transfer hook: bump interface to 0.4.1

- Cargo.lock
- associated-token-account/program/Cargo.toml
- stake-pool/cli/Cargo.toml
We need to use token-2022 v1 in the monorepo. Associated-token-account uses it too, but there's no published crate version that uses it.
Bump the ATA crate for a new publish.
> associated-token-account: Bump to use token-2022 v1

- docs/src/token-2022/extensions.mdx
CPI Guard has been around for some time, but there aren't any docs about it.
Using the great proposal at #3694 for inspiration (and copy-pasta), add the docs!
Fixes #3771
> docs: Add CPI Guard extension info

- governance/program/tests/process_execute_transaction.rs
According to https://github.com/solana-labs/solana/pull/34407, a governance test currently fails because of how solana-program-test manages forks.
To unblock that PR, ignore the test for now. Once solana-program-test does things correctly, we can re-enable it.
> governance: Ignore test for changes in monorepo

- pnpm-lock.yaml
- token/js/package.json
- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/index.ts
- token/js/src/extensions/tokenMetadata/actions.ts
- token/js/src/extensions/tokenMetadata/index.ts
- token/js/src/extensions/tokenMetadata/state.ts
- token/js/src/instructions/index.ts
- token/js/test/e2e-2022/tokenMetadata.test.ts
- token/js/test/unit/tokenMetadata.test.ts
Addresses #5229 
> With the addition of token metadata to Token2022 and the SPL Token Metadata interface itself to the SPL library, we need to support this cool feature & interface in JavaScript!
> 
> The goal here is to lay down a JavaScript library for SPL Token Metadata and then import it into @solana/spl-token for Token2022 metadata support.
> 
> This issue is importing and implementing @solana/spl-token-metadata.
> Adding Token Metadata Support to @solana/spl-token 

- token-metadata/js/test/instruction.test.ts
- token-metadata/js/test/state.test.ts
This PR updates the tests for Token Metadata JS to check its pack-unpack accuracy against hand-rolled code in JavaScript, like its Rust counterpart does.
This eliminates hard-coded bytes extracted from the Rust library's test runs.
> token metadata js: update test suites

- docs/src/token.mdx
Token docs reference obsolete wallet `sollet`. Remove the parenthetical entirely. Also tighten language, removing meaningless clauses.
Fixes #6031
> Remove sollet reference from token docs

- pnpm-lock.yaml
- stake-pool/js/package.json
- token-lending/js/package.json
- token-swap/js/package.json
- token/js/package.json
After #5667 we need to bump Token JS so we can cut a new release and folks can start using the Token Metadata tooling!
> token js: bump to 0.3.10

- Cargo.lock
- record/program/Cargo.toml
- record/program/src/instruction.rs
- record/program/src/processor.rs
- record/program/src/state.rs
- record/program/tests/functional.rs
Currently, the zero-knowledge proofs that are required for the token-2022 program barely fits in a single transaction. The spl-record program provides a convenient way to break up the proofs into byte chunks to be submitted on chain. However, the record program depends on borsh serialization, which creates issues when combined with the zk-token-proof program.
Remove the borsh dependency from the record program and use bytemuck for the serialization of data.
> [spl-record] Remove borsh dependency from spl-record program

- Cargo.lock
- single-pool/program/Cargo.toml
- single-pool/program/src/entrypoint.rs
The other new SPL programs that we deploy to the chain have a security.txt, ie #5929 and #5928, but the single pool program doesn't.
Add it in! Since the final audit just completed, you can fill in the information for the hash and release name.
> single-pool: Add security.txt

- record/program/src/instruction.rs
- record/program/src/processor.rs
- record/program/src/state.rs
- record/program/tests/functional.rs
The record program uses the struct `RecordData` to represent record data in accounts.
```
pub struct RecordData {
pub version: u8,
pub authority: Pubkey,
pub data: Data,
}
```
The `Data` type is an array of fixed size 8. It seems like this struct was added just for initial testing. The logic to support arbitrary length record data already exists in the processor logic.
By removing `Data` from the `RecordData` type and using it just as a header for data, we should be able to support arbitrary length record data.
Removed the `Data` struct from state and updated the record program to support arbitrary length data.
This is a follow-up to https://github.com/solana-labs/solana-program-library/pull/6054#discussion_r1441021286.
> [spl-record] Remove `Data` type from `RecordData` type

- docs/src/token-2022/extensions.mdx
- token-group/interface/README.md
Adds some documentation for `GroupPointer`, `TokenGroup`, `MemberPointer` and `TokenGroupMember` extensions!
As well as a README with documentation on the SPL Token Group interface.
> docs: add token group docs

- Cargo.lock
- libraries/tlv-account-resolution/Cargo.toml
- libraries/tlv-account-resolution/src/seeds.rs
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/cli/src/main.rs
- token/transfer-hook/cli/src/meta.rs
This PR adds support to the Transfer Hook CLI to add extra account meta configurations that involve seed configs!
This feature supports JSON or YAML file types, with a flexible layout to represent the extra metas.
Closes #5661.
> transfer hook cli: add support for PDAs as extra metas

- Cargo.lock
- token/transfer-hook/cli/Cargo.toml
So, we've made some minor enhancements to the Transfer Hook CLI over the last few months, and we've never actually published a crate beyond the `0.0.1` placeholder.
This PR reverts the crate version for Transfer Hook CLI back to `0.1.0` in preparation for it's first release.
After this PR goes in, I'll cut a tag and release for `0.1.0` with the significant enhancements mentioned.
> psuedo-bump transfer hook CLI to 0.1.0

- Cargo.lock
- libraries/tlv-account-resolution/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
Bumps TLC Account Resolution's patch version to include the new `serde-traits` feature. Backwards compatible without the feature, so we shouldn't need a minor release (?).
> tlv account resolution: bump to include serde

- record/program/src/instruction.rs
- record/program/src/processor.rs
- record/program/tests/functional.rs
The record program is useful when storing arbitrary length data on accounts. However, if the data is too long to fit inside an account, it is not possible to record the data without creating a new account with enough space. It would be nice to be able to reallocate more space to the existing account to store longer record data.
Add a reallocate instruction. I followed the main logic of the reallocate instruction in the token-2022 program.
This PR builds on top of https://github.com/solana-labs/solana-program-library/pull/6062. Once https://github.com/solana-labs/solana-program-library/pull/6062 is merged, I will rebase to master to remove the first few commits.
> [spl-record] Add `Reallocate` instruction

- SECURITY.md
- docs/src/token-2022.md
- docs/src/token-2022/status.md
Token-2022 has finished its audits for version 1.0.0, making it eligible for bug bounties, but the documentation is out of date.
Say that token-2022 is ready!
> docs: Specify that token-2022 is ready and eligible for bounties

- pnpm-lock.yaml
- stake-pool/js/package.json
- token-lending/js/package.json
- token-swap/js/package.json
- token/js/package.json
Bumps Token JS to `0.3.11` for release.
> token-js: bump to 0.3.11

- .github/workflows/pull-request-account-compression.yml
- .github/workflows/pull-request-binary-oracle-pair.yml
- .github/workflows/pull-request-docs.yml
- .github/workflows/pull-request-examples.yml
- .github/workflows/pull-request-feature-gate.yml
- .github/workflows/pull-request-feature-proposal.yml
- .github/workflows/pull-request-governance.yml
- .github/workflows/pull-request-instruction-padding.yml
- .github/workflows/pull-request-js.yml
- .github/workflows/pull-request-libraries.yml
- .github/workflows/pull-request-memo.yml
- .github/workflows/pull-request-name-service.yml
- .github/workflows/pull-request-record.yml
- .github/workflows/pull-request-shared-memory.yml
- .github/workflows/pull-request-single-pool.yml
- .github/workflows/pull-request-stake-pool.yml
- .github/workflows/pull-request-token-collection.yml
- .github/workflows/pull-request-token-group.yml
- .github/workflows/pull-request-token-lending.yml
- .github/workflows/pull-request-token-metadata.yml
- .github/workflows/pull-request-token-swap.yml
- .github/workflows/pull-request-token-upgrade.yml
- .github/workflows/pull-request-token.yml
- .github/workflows/pull-request.yml
- .github/workflows/spl_action.yml
It's easy for our CI machines to get bogged down if many PRs go in quickly, which often happens when we have multiple dependabot PRs in at once. This happens because CI is run at the same time for every single commit.
Following https://github.com/solana-labs/solana/pull/34733, limit the concurrency on PRs and branches to one per workflow type.
> ci: Only run one of each workflow at once for a branch / PR

- Cargo.lock
- token/program-2022/src/offchain.rs
- token/transfer-hook/interface/Cargo.toml
- token/transfer-hook/interface/src/offchain.rs
This PR adds a new offchain helper for adding the necessary account metas for an 
`ExecuteInstruction` to the SPL Transfer Hook interface, deprecating the old 
one.
As described in #6064, the offchain helper in Token2022 was using the original 
offchain helper from the SPL Transfer Hook interface incorrectly when resolving 
extra account metas for a transfer.
In order to provide a safer, more robust helper, this new function takes the 
instruction, fetch account data function, as well as the individual arguments 
for `instruction::execute(..)`. This will help to ensure Token2022 as well as 
anyone else using the helpers from the SPL Transfer Hook interface are properly 
resolving the necessary additional accounts.
Note: Although deprecated, the original helper in the SPL Transfer Hook …
> transfer hook: add new offchain helper

- Cargo.lock
- token/client/src/token.rs
- token/program-2022-test/tests/transfer_hook.rs
- token/program-2022/Cargo.toml
- token/program-2022/src/offchain.rs
This PR adds a new offchain helper for creating a `TransferChecked` instruction 
with the necessary accounts metas for a transfer hook `ExecuteInstruction` to 
Token2022, deprecating the old one.
As described in #6064, the original offchain helper in Token2022 was being used 
incorrectly to resolve extra account metas. Rather than providing the SPL 
Transfer Hook interface helper with a valid `ExecuteInstruction`, the original 
Token2022 helper was actually providing it with a transfer instruction, causing 
erroneous account resolution.
Taking advantage of the more secure SPL Transfer Hook interface offchain helper 
provided in #6099, this new offchain helper creates a `TransferChecked` 
instruction and calls `add_extra_account_metas_for_execute(..)`, providing the 
keys used to build the …
> token 2022: add new offchain helper

- token/client/src/token.rs
This PR continues the necessary repairs for addressing #6064 by refactoring the
Token Client's `transfer(..)` function to use the new offchain transfer hook
helpers.
If transfer hook accounts are provided, in either case they're appended to the
instruction like before.
If no transfer hook accounts are provided:
- If decimals are provided, Token2022's offchain helper
`create_transfer_checked_instruction_with_extra_metas(..)` is used.
- If decimals are not provided, SPL Transfer Hook interface's
`add_extra_account_metas_for_execute(..)` is used.
In either case where no transfer hook accounts are provided, the new,
non-deprecated helpers are used.
> token client: refactor transfer to use new offchain helper

- token/program-2022-test/tests/transfer_hook.rs
Following up from the new helpers added in #6099 and #6100, there's a transfer
hook test in `program-2022-test` that's using the now-deprecated helper to build
a swap instruction for the test program.
This PR replaces that bit of code to use the new helper from
`spl_transfer_hook_interface`.
Note: The test in question is designed to test Token2022's
`invoke_transfer_checked(..)` on-chain helper, *not* the offchain helpers. So,
it's appropriate to use the offchain helper directly from the interface crate
for this step.
> token 2022 test: refactor transfer hook test to use new offchain helper

- token/program-2022/src/onchain.rs
- token/transfer-hook/interface/src/onchain.rs
As another step for solving #6064, the onchain helpers now need to be
replaced. This PR makes that change in the SPL Transfer Hook interface.
Specifically, this commit adds a new `add_extra_accounts_for_execute_cpi(..)`
helper and deprecates the old one.
Like its offchain counterpart, this new helper requires the arguments for
`instruction::execute(..)` in order to validate that a proper
`ExecuteInstruction` is being resolved, thus ensuring proper account resolution.
This function, like its now-deprecated sibling, is designed specifically to add
extra accounts to an `ExecuteInstruction` CPI instruction. It's expected that
the instruction being provided is a CPI instruction for another program, and
that program will CPI to the transfer hook program in question. Details about
this have been …
> transfer hook: add new onchain helper

- Cargo.lock
- token/program-2022-test/Cargo.toml
- token/program-2022-test/tests/transfer_hook.rs
- token/program-2022/src/onchain.rs
Continuing on from the new helper introduced in #6111.
Here the onchain helper in Token2022 is updated to use the non-deprecated new
onchain helper from SPL Transfer Hook interface.
PDAs as extra meta configs are also added to the transfer hook test in
`program-2022-test` for additional assurance.
> token 2022: repair onchain helper

- token/js/src/extensions/transferHook/instructions.ts
- token/js/test/unit/transferHook.test.ts
This is the final PR to round off the changes required to fix #6064.
Previously, the offchain helpers for adding extra metas to instructions have
been replaced with new ones in the SPL Transfer Hook interface and Token2022.
This PR follows suit and adds a new helper to SPL Token JS.
The new helper, `addExtraAccountMetasForExecute(..)`, mirrors the Rust helper in
SPL Transfer Hook interface, requiring the parameters for an
`ExecuteInstruction` to be passed into the function directly.
This change also adds a public function for creating an `ExecuteInstruction`, in
case developers wish to create such an instruction for directly sending
instructions to their transfer hook program.
These existing functions have been updated to use the new helper:
- …
> token js: create new offchain helper

- token/client/src/token.rs
Added the necessary extra metas resolution to  `create_recipient_associated_account_and_transfer` with the same pattern as `transfer` in the Token CLI as per #6118.
> [token-client] Added transfer-hook compatibility to `create_recipient_associated_account_and_transfer`

- token/client/src/token.rs
With the new activation of the feature `8pgXCMNXC8qyEFypuwpXyRxLXZdpM4Qo72gJ6k87A6wL - Native program should consume compute units` activated, the token-2022 tests seem to break downstream ci in the monorepo due to the token-2022 confidential transfer with fee instruction taking too many compute units.
- Update the token-client by adding `process_ixs_with_additional_compute_budget`, which adds an extra compute budget instruction to the transaction
- Use the new function to allocate additional compute budget for transfer with fee
> [token-client] Add interface to add additional compute budget for transactions

- token/cli/src/clap_app.rs
While trying to create a "megatoken", AKA a token with every extension enabled, I noticed that a mint wasn't allowed to be both a group and a member.
From our earlier discussions, I'm pretty sure we wanted to allow this exact case, but the CLI prevents it.
Remove those extra conflicts! If this is the wrong approach and I've missed something, please let me know
> token-cli: Allow a token to be a group and a member

- token/cli/src/command.rs
While testing a "megatoken", AKA a mint with all extensions enabled, I wasn't able to create an account with confidential transfers enabled. This is because there's also the confidential transfer fee, but the CLI only allocates enough for the confidential transfer extension.
Pretty similar to #5862, but for token accounts instead of mints.
> token-cli: Reallocate account for confidential transfer fee

- Cargo.lock
The `h2` crate has a security advisory out:
```
Crate:     h2
Version:   0.3.18
Title:     Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)
Date:      2024-01-17
ID:        RUSTSEC-2024-0003
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0003
Solution:  Upgrade to ^0.3.24 OR >=0.4.2
Dependency tree:
h2 0.3.18
```
Just like in https://github.com/solana-labs/solana/pull/34816, update the dependency. Since `h2` is not used by on-chain programs, it should be mostly safe to update. It is used by CLIs though.
> audit: Bump h2 to 0.3.24

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/program_test.rs
- token/program-2022-test/tests/transfer_hook.rs
- token/program-2022/Cargo.toml
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/offchain.rs
If a mint is configured with a transfer hook, the program is meant to be called during all transfers. This doesn't happen during confidential transfers though.
The program changes are pretty simple: just execute the transfer hook, as in a normal transfer. This comes with a few other changes:
* b834e962f4919acd0c5c892166bb444289324b60 refactor some confidential transfer test helpers to be used in the transfer hook test
* 55f51c84e7cc44fc3eba8389a94fd8f37500181a call the incorrect #6064 account resolver in token-client for all confidential transfer functions
* dc28301b featurize the processor changes, to avoid deploying them accidentally
* rename `destination_token_account_info` -> `destination_account_info` for consistency
The biggest issue is that we don't know the amount transferred when …
> token-2022: Execute transfer hook during confidential transfer

- token/js/src/extensions/transferHook/instructions.ts
- token/program-2022/src/offchain.rs
- token/transfer-hook/interface/src/offchain.rs
- token/transfer-hook/interface/src/onchain.rs
Ahead of #6119, if we're going to do releases, we can drop the deprecated helpers altogether.
This PR removes the deprecated `offchain` and `onchain` helpers from SPL Transfer Hook interface, as well as the deprecated `offchain` helper from Token2022.
> token 2022 & transfer hook: drop deprecated helpers

- stake-pool/program/src/instruction.rs
- stake-pool/program/tests/decrease.rs
- stake-pool/program/tests/deposit.rs
- stake-pool/program/tests/deposit_edge_cases.rs
- stake-pool/program/tests/force_destake.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/huge_pool.rs
- stake-pool/program/tests/increase.rs
- stake-pool/program/tests/redelegate.rs
- stake-pool/program/tests/set_epoch_fee.rs
- stake-pool/program/tests/set_withdrawal_fee.rs
- stake-pool/program/tests/update_stake_pool_balance.rs
- stake-pool/program/tests/update_validator_list_balance.rs
- stake-pool/program/tests/update_validator_list_balance_hijack.rs
- stake-pool/program/tests/vsa_remove.rs
- stake-pool/program/tests/withdraw_edge_cases.rs
`spl_stake_pool::instruction::update_validator_list_balance()`'s API has a redundant param in `validator_vote_accounts` since this data is already present in the `validator_list: &ValidatorList` param. This also makes usage of the function more prone to error because the actual instruction processor only works on contiguous chunks of the list but this API allows users to pass in any slice of vote accounts.
The function also does several unnecessary `Vec` allocations that can be omitted if an iterator is used instead.
Update `update_validator_list_balance()` to just take a `len` parameter that specifies the number of validators on the `ValidatorList` starting from `start_index` to include into the instruction.
Update `update_validator_list_balance()` to remove the unnecessary `Vec` …
> stake-pool: make `update_validator_list_balance()` more ergonomic

- Cargo.lock
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
This PR bumps the versions of the transfer hook interface and CLI. Commits:
1. `interface`: 0.4.1 -> 0.5.0
2. `cli`: 0.1.0 -> 0.1.1 (The CLI doesn't use the helpers)
> Transfer hook: bump versions

- Cargo.lock
- token/program-2022-test/Cargo.toml
- token/transfer-hook/example/Cargo.toml
Marking this as a draft for now. I want to make sure this one is timed right.
Technically, since this depends on Token2022, we should really publish Token2022 first and then update this crate's version. Although I wanted to at least check out the bump since nowhere in the example or tests are we using the helpers from Token2022, only the interface.
`cargo publish --dry-run` checks out.
Lmk.
> bump transfer hook example

- Cargo.lock
Audit jobs are failing due to https://rustsec.org/advisories/RUSTSEC-2024-0006
Bump the dependency to 1.3 as suggested
> audit: Update shlex to 1.3 due to advisory

- Cargo.lock
- token/cli/src/clap_app.rs
- token/cli/src/command.rs
- token/cli/tests/command.rs
As per #5937, added command_update_group_max_size to the token CLI. This allows one to update the max_size of a token group given the update_authority.
> token-cli: Add command_update_group_max_size to token CLI

- token/cli/src/clap_app.rs
- token/cli/src/command.rs
- token/cli/tests/command.rs
Token-2022 and token-client support initializing token group members, but we can't do it in the CLI.
Following the excellent work in #6135, pretty much do the same thing, but for initializing members
> token-cli: Add initialize-member command

- stake-pool/program/tests/update_validator_list_balance.rs
The `success_with_burned_tokens` stake pool test is still flaky: https://github.com/solana-labs/solana-program-library/actions/runs/7625706514/job/20770570815?pr=6165
Force refresh the blockhash to be sure that the pool update happens, and fix the blockhash provided by the test setup.
> stake-pool-test: Fix updating blockhash, force a new one

- token/js/src/extensions/transferFee/instructions.ts
- token/js/src/serialization.ts
- token/js/test/e2e-2022/transferFee.test.ts
- token/js/test/unit/transferfee.test.ts
The `InitializeTransferFeeConfig` instruction in Token2022's Rust crate expects a `COption<Pubkey>`, which denotes `None` with a single `0` and `Some(Pubkey)` with a `1` followed by the public key bytes.
The layout for this instruction in Token JS - `initializeTransferFeeConfigInstructionData` - was incorrectly using 32 all-zero bytes for `None`, as one might do with an `OptionalNonZeroPubkey`. This was causing incorrect instruction data when one of the two authorities was set to `null`.
Here I've introduced a `COptionPublicKeyLayout` serialization layout to use for this kind of case. It will handle the proper `COption<Pubkey>`. encoding and decoding, so we encode and decode instructions properly!
Closes #6113
> token-js: add `COption<Pubkey>` support to `InitializeTransferFeeConfig` instruction

- stake-pool/program/src/state.rs
- stake-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/withdraw_sol.rs
- stake-pool/program/tests/withdraw_with_fee.rs
During deposit and withdrawal functions, if the SOL or pool token amount is small, it is possible the fee calculations floor to zero due to loss of precision, preventing fee collection.
This scenario is not economically viable, and the cost of fee avoidance would outweigh the benefit of depositing such a small amount to the stake pool, but it's better to fix things up.
The change takes the ceiling of all fee calculations by adding `denominator - 1` to the numerator.
> stake-pool: Ceiling all fee calculations (HAL-01)

- docs/src/token-2022.md
There's a disconnect between the "Token Extensions" and "Token-2022" names in the docs.
Call out that it's also called "Token Extensions"
> docs: Add "Token Extensions" in the top-level doc

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- stake-pool/program/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-metadata/example/Cargo.toml
- token-swap/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
There's a breaking change in the master version of token-2022, but we need to publish new crates for the solana v2 bump in #6182
Bump token-2022 to a new major version so that the new crates can be used.
cc @willhickey
> token-2022: Bump to v2

- stake-pool/py/stake_pool/state.py
The ValidatorList.decode method has a debug print command in it that clutters the output whenever I use that function. Assume it is there for debugging purposes so should be safe to remove.
> reduce cluttering by removing debug print command

- account-compression/Cargo.lock
- account-compression/programs/account-compression/Cargo.toml
CI is failing on the account-compression build because it's trying to pull in v1.18 of `solana-program`.
Not sure if this will work, but try setting `solana-program` explicitly in the Cargo.toml and update the lockfile
> account-compression: Specify solana-program version

- token/program-2022/src/extension/confidential_transfer/instruction.rs
The confidential transfer instruction constructors do not work directly with cryptographic functions (create proofs, call the encrypt function, etc.). However, the compilation target for these functions forbid them from being used on chain.
Remove the restriction on the compilation target for these constructor functions.
> [token-2022] Remove build target restriction on confidential transfer instruction constructors

- token/program-2022/src/state.rs
We can change `>=` to `>` because already checked `==` on the previous step
> [token-2022] improve condition in Account::valid_account_data

- token/js/examples/transferHook.ts
Correcting `transferCheckedWithHook` to `transferCheckedWithTransferHook` in `/examples/transferHook.ts`
> fix: correcting import in transfer hook js example

- Cargo.lock
- associated-token-account/program/Cargo.toml
- feature-gate/program/Cargo.toml
- instruction-padding/program/Cargo.toml
- libraries/discriminator/Cargo.toml
- libraries/discriminator/derive/Cargo.toml
- libraries/discriminator/syn/Cargo.toml
- libraries/pod/Cargo.toml
- libraries/program-error/Cargo.toml
- libraries/program-error/derive/Cargo.toml
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value-derive-test/Cargo.toml
- libraries/type-length-value/Cargo.toml
- memo/program/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/example/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/program/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
Bump crate versions in preparation for tagging new releases so the monorepo dependencies can be updated to SPL versions that will use 2.0.0 for transitive dependencies.  [Discord discussion](https://discord.com/channels/428295358100013066/910937142182682656/1200210293112979626)
> Bump SPL crate versions

- stake-pool/js/src/utils/program-address.ts
BN.toBuffer is not available in the browser. Replaced with .toArrayLike which provides the same functionality and works consistently both in nodejs and browser.
> Replace BN.toBuffer with BN.toArrayLike

- .github/workflows/pull-request-token-collection.yml
During PR #6233, the token-collection CI job was run because there was a change in `token-group/js`, but that's unnecessary.
Don't run token-collection CI if `token-group/js` was changed.
> ci: Don't run token-collection for js changes

- Cargo.lock
- token/program-2022/Cargo.toml
In preparation for bumping the monorepo version to 2.0.0, relax some of the internal dependencies.
> Update token dependencies

- update-solana-dependencies.sh
the regex in `update-solana-dependencies.sh` doesnt match the range dependency we current have, so running the `patch-crates.io` appears to succeed but when you build a project it doesnt use the local dependency
this changes it from "match maybe an equals sign then a single old version number, replace with the new version number preceded by whatever preceded the old one" to "match maybe eq/gt/lt/gte/lte then an old version number then whatever other nonsense comes until the end quote, replace with equals the new version number"
this still assumes if `Cargo.toml` has a version `>=1.2.3,<4.5.6` then `solana-version.sh` contains `1.2.3`
> fix dependency update for new version

- token/program-2022-test/tests/non_transferable.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/processor.rs
This PR improves the token-2022 account initialisation addressed by issue (#5884).
when trying to initialize an account on a non-transferable mint,  Now It will check whether the account has immutable ownership:
1. if yes, pass the check.
2. if no, return NonTransferableNeedsImmutableOwnership error.
> token-2022: initialize an account on a non-transferable mint without immutable ownership

- stake-pool/js/package.json
#6226 fixed using BNs as seeds in browser, but it hasn't been released yet.
Release 1.0.1 with the fix
Fixes #6269
> stake-pool-js: Bump to 1.0.1 for release

- stake-pool/py/stake_pool/actions.py
- stake-pool/py/stake_pool/constants.py
- stake-pool/py/stake_pool/instructions.py
- stake-pool/py/tests/test_a_time_sensitive.py
- Updated the Python stake pool client library methods increase_validator_stake and decrease_validator_stake to support the increase/decrease additional validator stake instructions using the same logic as in the corresponding methods in the JS library.
- A bugfix in the JS stake pool client code, increaseValidatorStake function
> Added support for the increase/decrease additional stake instructions in the Python client library

- libraries/type-length-value/js/package.json
- libraries/type-length-value/js/typedoc.json
- pnpm-lock.yaml
Simply adds typedoc configs to Type Length Value, adds the necessary `devDependencies`, and sorts the scripts alphabetically.
> type-length-value-js: add docs configs

- token/js/test/unit/metadataPointer.test.ts
The `MetadataPointer` tests are a little bit difficult to follow, so this change
refactors them to be a bit more legible, so onlookers can see what's going on
and learn how to use the `MetadataPointer` instructions & state from observing
the tests.
> token-js: refactor metadata pointer tests

- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/groupPointer/index.ts
- token/js/src/extensions/groupPointer/instructions.ts
- token/js/src/extensions/groupPointer/state.ts
- token/js/src/extensions/index.ts
- token/js/src/instructions/types.ts
- token/js/test/e2e-2022/groupPointer.test.ts
- token/js/test/unit/groupPointer.test.ts
As mentioned in #6175, the `GroupPointer` extension is live on Token-2022
mainnet-beta, but it's not currently supported in the `@solana/spl-token`.
This change adds that support!
> token-js: add `GroupPointer` extension

- token/js/src/extensions/extensionType.ts
- token/js/src/extensions/groupMemberPointer/index.ts
- token/js/src/extensions/groupMemberPointer/instructions.ts
- token/js/src/extensions/groupMemberPointer/state.ts
- token/js/src/extensions/index.ts
- token/js/src/instructions/types.ts
- token/js/test/e2e-2022/groupMemberPointer.test.ts
- token/js/test/unit/groupMemberPointer.test.ts
As mentioned in #6175, and building on the previous PR, the `GroupMemberPointer`
extension is live on Token-2022 mainnet-beta.
This change adds support for `GroupMemberPointer` in `@solana/spl-token`!
> token-js: add `GroupMemberPointer` extension

- token/js/src/instructions/setAuthority.ts
- token/js/test/e2e-2022/groupMemberPointer.test.ts
- token/js/test/e2e-2022/groupPointer.test.ts
Add the newly added `GroupPointer` and `GroupMemberPointer` to the
`setAuthority` instruction.
> token-js: add `GroupPointer` and `GroupMemberPointer` to `setAuthority`

- pnpm-lock.yaml
- token/js/package.json
Simply bumping the version for `@solana/spl-token` to publish the new extension
support.
> token-js: bump version

- token/js/README.md
The build instructions for the token js library in the readme file is outdated:
- it suggests to use `npm` instead of `pnpm`
- it suggests to build in `solana-program-library/token/js`, but the build only works at the root of the repository
Updated the instructions to use `pnpm` and to also build at the root of the repository.
> [token-js] Update build instructions for token js

- token/cli/src/clap_app.rs
- token/cli/src/command.rs
- token/cli/tests/command.rs
Several of the token commands, such as `transfer`, support using the `ALL` keyword for the `amount` argument in order to automatically choose all of the tokens in the account.
This PR adds support for the `ALL` keyword to the `burn` command as well.
~~TODO: haven't tested this, should probably do so before this PR is considered for submission~~
UPDATE: I have since tested this, and confirmed that running with the keyword `ALL` worked as expected and selected all available tokens in an account. Please let me know if any other level of testing is desired; it doesn't look like the CLI has unit testing but I'll also admit that I haven't spent much time looking in / contributing in this repo
> token-cli: Allow burn command to accept ALL keyword for amount

- Cargo.lock
Fixes the audit vulnerability finding for `mio`, a dependency of `tokio`.
> lockfile: update `mio` to `0.8.11`

- Cargo.lock
This change bumps `ahash` in the `Cargo.lock` to the newer patch `0.7.8`, which fixes the nightly build error causing Token-2022's `docsrs` build to fail.
Fixes #6287 
More details can be found in the linked issue.
> lockfile: update `ahash` to `0.7.8`

- libraries/pod/src/primitives.rs
While working on converting token-2022 to `Pod` types in #6316, I need to create `Pod` types in a const context, but that wasn't possible because `From` cannot be used in `const` contexts.
Add a `from_primitive` function on the numbers and `from_bool` for `PodBool`.
Along with that, expose the underlying data stored, so that you can initialize a `PodU64` with `PodU64([0,0,0,0,0,0,0,0])`
> pod: Add const-compatible creators for primitives

- Cargo.lock
- token/program-2022/Cargo.toml
Bumps the patch version of Token-2022 to include the new lockfile changes from #6325 and #6324.
> token-2022: bump patch version

- token/program-2022/tests/action.rs
- token/program-2022/tests/assert_instruction_count.rs
As part of moving token-2022 to Pod-style deserializers in https://github.com/solana-labs/solana-program-library/pull/6316, we need good baseline CU usage numbers to see the impact of the Pod work, but we don't have any tests that exercise `transfer_checked`.
Add an instruction count test that uses `transfer_checked` as a baseline.
> token-2022: Add instruction count test for `transfer_checked`

- token/program-2022/tests/assert_instruction_count.rs
As part of moving token-2022 to `Pod`-style deserializers in #6316, we need good baseline CU usage numbers to see the impact of the Pod work.
Update the numbers based on the compiler that comes with 1.18.2.
> token-2022: Update compute unit numbers to get baseline CU usage

- token/program-2022/src/extension/mod.rs
- token/program-2022/src/state.rs
As part of #6316, in order to create a `Pod`-compatible version of `StateWithExtensions`, we need to relax the requirement for `BaseState` to implement `Pack`, since it will implement `Pod` instead for the pod version of `StateWithExtensions`.
On the flip-side, we do need to know the size of the underlying type to move through the underlying buffer.
Introduce a new trait, `PackedSizeOf`, which only gives the packed length of a type. This is just a more limited version of the `LEN` on the `Pack` trait.
Relax the trait bound on `BaseState` so that it requires `PackedSizeOf` instead of `Pack`.
> token-2022: Introduce `PackedSizeOf` and relax `BaseState` trait

- token/program-2022/src/extension/mod.rs
Towards zero-copy deserialization in token-2022 in #6316, we need a `Pod`-compatible version of `StateWithExtensions`, where the underlying `BaseState` implements `Pod`. That way, we can `unpack` something in zero-copy.
Add the new types. I tried to do as much dedupe as possible by introducing `unpack_tlv_data`, but it's tough to reduce too much more than that.
Also, the `unpack` functions on the new types are extremely similar to their non-`Pod` versions, and the only difference is calling `pod_from_bytes` instead of `unpack`.
We could do this with a macro, but macros always feel a little more brittle / hacky. I don't feel too strongly though, so I'm happy to do whatever you think is best!
Also, `unpack_tlv_data` is just an immutable version of the previous `unpack_type_and_tlv_data`, …
> token-2022: Add `Pod`-compatible versions of `StateWithExtensions`

- Cargo.lock
Duplicate version of `spl-tlv-account-resolution` (which doesn't accept the range of solana-program versions) is breaking agave downstream CI builds when we attempt to bump to v2: https://github.com/anza-xyz/agave/pull/121
I am guessing this fix should have been part of #6221, but I am not sure why cargo did not resolve it automatically. I hope we're not going to have to make manual lock fixes all the time.
> Update old spl-tlv-account-resolution in Cargo.lock

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/process_create_governance.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/legacy.rs
- governance/program/tests/program_test/legacy.rs
- governance/program/tests/program_test/mod.rs
Rename `governed_account` to `governance_seed` for `Governance` account to reflect its actual meaning. The asset specific `Governance` accounts were removed in https://github.com/solana-labs/solana-program-library/pull/6335 and the concept of `governed_account` doesn't exist any longer. 
`governance_seed` was made mandatory for `create_governance` instruction creator
> Governance: Rename governed_account to governance_seed

- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/token_group/processor.rs
- token/program-2022/src/extension/token_metadata/processor.rs
As part of the transition to using `Pod` types with #6316, the `alloc_and_serialize` extension helpers need to use `Pod` types to avoid more expensive deserialization.
Use `PodStateWithExtensions*` in the `alloc_and_serialize*` functions.
I spent a long time trying to do this by adding an `unpack` function to the `BaseStateWithExtensions` traits, but because `unpack` takes in a `&[u8]`, and `StateWithExtensions` holds onto a reference, the lifetimes were an absolute nightmare. Because of that, I decided to just transition the whole function to use only `Pod` types.
I don't know why the alloc functions were `pub` to begin with, so I've also made them `pub(crate)`. This will require a major version bump.
> token-2022: Update alloc_and_serialize to use Pod types

- governance/program/src/error.rs
- governance/program/src/state/enums.rs
- governance/program/src/state/proposal.rs
The function `assert_can_flag_transaction_error` is not used any longer and cna be removed
> Governance: Remove assert_can_flag_transaction_error

- governance/chat/program/tests/program_test/mod.rs
- governance/program/src/error.rs
- governance/program/src/instruction.rs
- governance/program/src/processor/mod.rs
- governance/program/src/processor/process_execute_transaction.rs
- governance/program/src/processor/process_insert_transaction.rs
- governance/program/src/state/governance.rs
- governance/program/src/state/legacy.rs
- governance/program/src/state/proposal.rs
- governance/program/src/state/proposal_transaction.rs
- governance/program/tests/process_add_required_signatory.rs
- governance/program/tests/process_add_signatory.rs
- governance/program/tests/process_create_native_treasury.rs
- governance/program/tests/process_execute_transaction.rs
- governance/program/tests/process_insert_transaction.rs
- governance/program/tests/process_remove_required_signatory.rs
- governance/program/tests/process_set_governance_config.rs
- governance/program/tests/process_sign_off_proposal.rs
- governance/program/tests/program_test/legacy.rs
- governance/program/tests/program_test/mod.rs
- governance/program/tests/use_proposals_with_multiple_options.rs
Remove `hold_up_time` for individual `ProposalTransactions` and use a single `Governance` level `hold_up_time` for all transactions within a `Proposal` instead.
The individual hold up times for transactions haven't been used and if the delay logic, in addition to the `Governance` defined time lock,  is required then it can be implemented by other means like inserting instructions with a delay guard  or a wrapping instructions with a configured delay.
> Governance: Remove ProposalTransaction hold_up_time

- pnpm-lock.yaml
- token-group/js/package.json
- token-group/js/src/instruction.ts
- token-group/js/src/state/tokenGroup.ts
- token-group/js/src/state/tokenGroupMember.ts
- token-group/js/test/instruction.test.ts
- token-metadata/js/package.json
- token-metadata/js/src/field.ts
- token-metadata/js/src/instruction.ts
- token-metadata/js/src/state.ts
- token-metadata/js/test/instruction.test.ts
As pointed out in the comments in https://github.com/solana-labs/solana-program-library/pull/6358, the token group and metadata JS libraries do some slightly non-idiomatic things with the new web3.js.
Implement those suggestions:
* update to using just `@solana/codecs`
* change version to just `2.0.0-preview.1`
* eliminate `packInstruction` for more idiomatic encoder creator
* use a real `PublicKey` encoder rather than a buffer
Unfortunately, we can't totally get rid of `Buffer` because it's required in the `data` part of the `TransactionInstruction` in old web3.js, but now its use is more isolated.
> js: Update token-group / token-metadata to use more idiomatic encoders

- token/program-2022/src/pod.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/assert_instruction_count.rs
All of the pod types are ready to be used in the instruction processors, but they're not being used anywhere.
Use them in `initialize_mint`, which brings CUs down from 2196 to 1742
> token-2022: Update initialize_mint to use Pod types

- pnpm-lock.yaml
- token-group/js/package.json
- token-metadata/js/package.json
- token-metadata/js/src/instruction.ts
- token-metadata/js/test/instruction.test.ts
Per https://github.com/solana-labs/solana-program-library/pull/6388#discussion_r1519883981, we're using `@solana/options` by name, which is also included in `@solana/codecs`
Use everything from `@solana/codecs` directly, and remove the dependency on `@solana/options`
> js: Remove direct usage of `@solana/options`

- token/program-2022/src/extension/memo_transfer/mod.rs
- token/program-2022/src/extension/transfer_hook/mod.rs
- token/program-2022/src/pod.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/assert_instruction_count.rs
All of the pod types are ready to be used in the instruction processors, but they're not being used anywhere.
Use pod types in `transfer`, which brings CUs down from 2988 to 1642 for unchecked transfers, and from 3839 to 1960 for checked transfers! This is probably the biggest win from our efforts.
> token-2022: Update transfer to use Pod types (uses half the CUs!)

- token/program-2022/src/processor.rs
- token/program-2022/tests/assert_instruction_count.rs
All of the pod types are ready to be used in the instruction processors, but they're not being used anywhere.
Use them in `initialize_account`, which brings CUs down from 3229 to 2016
> token-2022: Update initialize_account to use Pod types

- token/program-2022/src/processor.rs
- token/program-2022/tests/assert_instruction_count.rs
The Pod types exist in token-2022, but mint_to doesn't use them
Use Pod types in mint_to in token-2022
> token-2022: Update mint_to to use Pod types

- token/program-2022/src/pod.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/assert_instruction_count.rs
The Pod types exist in token-2022, but close_account doesn't use them
Use Pod types in close_account in token-2022
> token-2022: Update close_account to use Pod types

- token/program-2022/src/processor.rs
The Pod types exist in token-2022, but toggle_freeze doesn't use them
Use Pod types in toggle_freeze in token-2022
> token-2022: Update toggle_freeze to use Pod types

- token/program-2022/src/processor.rs
The Pod types exist in token-2022, but sync_native doesn't use them
Use Pod types in sync_native in token-2022
> token-2022: Update sync_native to use Pod types

- token/program-2022/src/processor.rs
The Pod types exist in token-2022, but initialize_immutable_owner doesn't use them
Use Pod types in initialize_immutable_owner in token-2022
Side note: I thought it was very cool that this only takes one line
> token-2022: Update initialize_immutable_owner to use Pod types

- token/program-2022/src/processor.rs
The Pod types exist in token-2022, but initialize_mint_close_authority doesn't use them
Use Pod types in initialize_mint_close_authority in token-2022
Side note: another one-liner!
> token-2022: Update initialize_mint_close_authority to use Pod type

- token/program-2022/src/processor.rs
The Pod types exist in token-2022, but amount_to_ui_amount doesn't use them
Use Pod types in amount_to_ui_amount in token-2022
Side note: more one-liners!
> token-2022: Update amount_to_ui_amount to use Pod types

- token/program-2022/src/processor.rs
The Pod types exist in token-2022, but ui_amount_to_amount doesn't use them
Use Pod types in ui_amount_to_amount in token-2022
Side note: even more one-liners!
> token-2022: Update ui_amount_to_amount to use Pod types

- token/program-2022/src/processor.rs
There are still a few base instruction processors using the non-Pod types.
Update the last few: `withdraw_excess_lamports`, `initialize_non_transferable_mint`, and `initialize_permanent_delegate`.
With this, we can close #6316 !
> token-2022: Finish updating base processors to Pod types

- token/program-2022/src/extension/memo_transfer/processor.rs
As part of #6418, the memo transfer extension does not use Pod types.
Use them
> token-2022: Update memo_transfer to Pod types

- token/program-2022/src/extension/cpi_guard/processor.rs
As part of #6418, the cpi guard extension does not use Pod types.
Use them
> token-2022: Update cpi guard to Pod

- token/program-2022/src/extension/transfer_hook/processor.rs
As part of #6418, the transfer hook extension does not use Pod types.
Use them
> token-2022: Update transfer_hook to use Pod types

- token/program-2022/src/extension/interest_bearing_mint/processor.rs
As part of #6418, the interest-bearing mint extension does not use Pod types.
Use them
> token-2022: Update interest_bearing_mint to Pod types

- token/program-2022/src/extension/metadata_pointer/processor.rs
As part of #6418, the metadata pointer extension does not use Pod types.
Use them
> token-2022: Update metadata_pointer to use Pod types

- token/program-2022/src/pod.rs
- token/program-2022/src/processor.rs
While porting all of the instruction processors over to use Pod types, I missed porting `set-authority`.
Port it over to the pod types!
Note: it's not clear where the new `ok_or` function is used. It's at lines 708 and 724 in `processor.rs`
> token-2022: Update SetAuthority to use Pod types

- token/cli/src/command.rs
While looking at this SSE question https://solana.stackexchange.com/questions/11725/correct-usage-of-spl-token-transfer-with-offline-signing, I noticed there's a bug in the `transfer-hook-account`s passed in to the token CLI. During `--sign-only`, we create an offline client that will fail if trying to fetch an account, but during token-client's `transfer`, we fetch the mint account if there are no transfer-hook accounts specified. Because of that, we fail during `--sign-only`, which is incorrect.
The current workaround is to just specify an empty `--transfer-hook-account` arg on the command line, but that's annoying.
If we're in `--sign-only` mode and no transfer accounts have been specified, default them to an empty vector.
> token-cli: Pass empty transfer-hook-accounts for sign-only transfer

- stake-pool/js/src/index.ts
- stake-pool/js/src/instructions.ts
- stake-pool/js/src/utils/program-address.ts
- stake-pool/js/src/utils/stake.ts
- stake-pool/js/test/instructions.test.ts
This PR adds support for the `AddValidatorToPool` instruction for the stake pool program in the javascript library. Removing a validator has not been implemented in the spirit of keeping the PR as small as possible. If accepted, I can also implement support for that instruction as well.
My guess is that this instruction was never prioritized in the javascript library due to the `spl-stake-pool` package mostly being used in frontend applications. This instruction is helpful to have though for users who are using nodejs, hence why I added support for it.
The code was successfully run on mainnet with tx hash `4QnuyTWTYYTPX1pr8sw5haFUp96PnNXCe4VWbWZVzN9PcRvhDkTaGpxKvpRC2wETC23VrgoSBdDC1UhZ7s3vfoM6` targetting Edgevana's stake pool.
> stake-pool: supporting AddValidatorToPool in js library

- libraries/pod/src/optional_keys.rs
- token/program-2022/src/pod.rs
- token/program-2022/src/processor.rs
There's still one more way to reduce CU usage in token-2022, and that's through Pod-style deserialization of the instruction, similar to how all of the extensions deserialize their instructions. 
To prepare the switch over to Pod instructions, start with some refactoring. This PR moves all of the `process_*` functions to accept `Pod` types and references, which will come out of the instruction deserialization.
Note: Once this is all done, Pod instructions reduce usage by around 150 CUs, and since it isn't too complicated, it seems like a good option.
> token-2022: Prepare processors for Pod instructions by taking references and pod types

- token/program-2022/src/extension/transfer_fee/instruction.rs
- token/program-2022/src/extension/transfer_fee/processor.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/processor.rs
As part of moving token-2022 to deserializing instructions as Pod-style types, we can't have enums with data, ie as:
```
enum Instruction {
Variant(Data),
}
```
Thankfully, most of the token-2022 instructions have pretty simple data, as a pubkey or a u64. The transfer fee extension is a bit special, however, in that we include the whole type in the base `TokenInstruction` enum as `TransferFeeExtension(TransferFeeInstruction)`. This is inconsistent with how other extensions deserialize their instructions, where we only provide the first byte in `TokenInstruction`, and then deserialize the extension-specific instruction in its processor.
No matter what, we'll need to change the transfer fee extension to deserialize as the other extensions do, because we can't include data in the Pod …
> token-2022: Deserialize transfer fee instruction in its processor

- token/program-2022/src/instruction.rs
As part of transitioning the instructions to pod, it's useful to test unpacking the new pod instruction types, which makes the one instruction packing test much larger.
No functional changes, but break up all the tests to make the future changes easier to parse.
> token-2022: Split up instruction pack tests

- stake-pool/js/src/index.ts
- stake-pool/js/src/instructions.ts
- stake-pool/js/test/instructions.test.ts
This PR adds the `RemoveValidatorFromPool` instruction to the stake-pool JS bindings. Like the recent addition of `AddValidatorToPool`, this instruction is useful for pool operators using Node.js bots to maintain their pools.
The code was successfully run against the mainnet-beta instance of the BlazeStake pool at transaction hash `RjEP2XBmA6nyVM2Ej23Xct67JZJEAQdb777DkUPJvatkqGWRdzphtGyDKpWMDGmmuHxMjZvBsYBCZiLtWNVpdTR`
> stake-pool: Add RemoveValidatorFromPool instruction in JS bindings

- token/program-2022/src/instruction.rs
- token/program-2022/src/lib.rs
- token/program-2022/src/pod_instruction.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/assert_instruction_count.rs
Token-2022 is still deserializing instructions on the stack, which uses up more CUs than in-place deserialization.
Define a new enum `PodTokenInstruction`, which is just the discriminant from `TokenInstructions`, along with `Pod` types for the instruction data. And then use these types to deserialize instruction data in the processor.
`COption` is an outlier here because it can't be represented as a `Pod` type, so there's a helper to deserialize it when included with a `Pod` type.
The final savings are about another 150 CUs per instruction, which is pretty good! And this should be the last PR for awhile on token-2022.
Most of the changes are tests, so I hope this won't be too tough to review.
> token-2022: Deserialize instructions as `Pod` types

- token/js/src/actions/approveChecked.ts
The documentation on the `approveChecked` function in `token/js/src/actions/approveChecked.ts` is missing the mint param.
> token js: add missing "mint" param to docs for approveChecked

- stake-pool/js/package.json
There have been some additions to the stake pool JS library, but we haven't released them.
Bump the JS package to release it!
> stake-pool-js: Bump to 1.1.0 for release

- token/js/package.json
Thanks to @qiweiii, the `TokenGroup` and `TokenGroupMember` extensions are now available in `@solana/spl-token`, but we need to publish a release with the new features!
Ship it!
> token-js: bump to 0.4.2 for release

- stake-pool/js/src/index.ts
- stake-pool/js/src/layouts.ts
- stake-pool/js/src/utils/stake.ts
- stake-pool/js/test/calculation.test.ts
According to reports, `divideBnToNumber` is causing some issues for big numbers that fall outside of the safe js `number:
```
Error: Number can only safely store up to 53 bits
at assert (bn.js:7:21)
at BN.toNumber (bn.js:548:7)
at divideBnToNumber (index.browser.esm.js:774:70)
at calcPoolTokensForDeposit (index.browser.esm.js:754:23)
at prepareWithdrawAccounts (index.browser.esm.js:722:42)
at async Module.withdrawStake (index.browser.esm.js:1757:35)
```
Just kick out `divideBnToNumber` and use correct floor and ceiling divisions as needed.
> stake-pool-js: Remove `divideBnToNumber`, use BNs more

- token/js/src/extensions/extensionType.ts
The confidential transfer extension in token-js has not been updated for a while. Currently, the wrong lengths for the confidential transfer mint and accounts are hard-coded in. Although confidential transfers are not yet supported in token-js, this could be quite confusing (e.g. https://github.com/solana-labs/solana-program-library/issues/6338).
Hard-code the mint and account lengths with the correct number. These should be replaced with the `confidentialTransferMint.span` and `confidentialTransferAccount.span` as soon as wasm support for zk-token-sdk lands.
> [token-js] Fix confidential transfer extensions account length

- token/client/src/token.rs
Currently, the token client uses `Message::new_with_nonce` for nonce transactions, which means that we need to do some copy-pasta on the `instructions` before simulating to find the compute unit limit.
Extract the part from `Message::new_with_nonce` that adds an instruction to the transaction.
This actually fixes a bug where `Message::new_with_nonce` was taking `token_instructions` instead of `instructions`.
> token-client: Refactor `Message` creation to use the same `instructions` everywhere

- token/client/src/client.rs
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/confidential_transfer_fee.rs
As part of #6492, the token-cli doesn't support priority fees. Currently, the token-client allows for setting a compute unit price and limit, but that requires users to know the compute units used by their transaction.
Transaction simulation gives the compute units used by a transaction, so instead of asking users to provide a number, we can be a bit smarter and use simulation results to set the compute unit limit used by a transaction.
We also need to support offline signing, which cannot simulate transactions. In this PR, the token client fails to extract the compute units used by the transaction after the offline "simulation", and thus uses the default limit of 200k * num_top_level_instructions.
A user-provided value for `compute_unit_limit` always takes precedence, so offline signing …
> token-client: Use transaction simulation results for the compute unit limit

- token/cli/src/clap_app.rs
- token/cli/src/command.rs
- token/cli/src/config.rs
- token/cli/tests/command.rs
As the last part of #6492, the token-cli isn't using the new fields for setting the compute unit price and limit.
Pipe them down into the token client, and that's pretty much it!
There's also a refactor for the `transfer` test so that the `compute_budget` test can use it directly, without any change in behavior.
Note that this copies `COMPUTE_UNIT_PRICE_ARG` from clap-utils rather than importing. I made this choice because #6376 updates to clap-v3, which doesn't have any compute budget helpers. I've put in a PR to add them to clap-v3 at https://github.com/anza-xyz/agave/pull/440
> token-cli: Add priority fee args

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- libraries/pod/Cargo.toml
- managed-token/program/Cargo.toml
- single-pool/cli/Cargo.toml
- single-pool/program/Cargo.toml
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- stateless-asks/program/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-metadata/example/Cargo.toml
- token-swap/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
We need to get a new token cli release out to go with the next 1.18 release, since it includes priority fees.
Bump everything needed for token-cli:
* token-cli
* token-client
* token-2022 (major because of breaking changes)
* associated-token-account (major because of new borsh version)
* pod (needed for new constructors)
I was worried that the major version bump on token-2022 would be an absolute horror, but it was pretty ok!
> bump: Bump everything up for new token cli

- Cargo.lock
- libraries/pod/Cargo.toml
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value-derive-test/Cargo.toml
- libraries/type-length-value/Cargo.toml
- record/program/Cargo.toml
- single-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/example/Cargo.toml
- token-metadata/interface/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
We need to release a new token-cli crate to get the priority fees out to people, but the crates aren't at the proper version to be released.
Bump all the required crates to do this in a semver-compatible way, since we've bumped to borsh v1 in SPL:
* pod
* tlv
* tlv-account-resolution
* token-group (interface and example)
* token-metadata (interface and example)
* token-2022 (already done)
* token-cli (already done)
* token-client
* transfer-hook (interface, example, and CLI)
* associated-token-account (already done)
To make tagging releases simpler, this PR won't be squashed
> various: Bump crates required to get a semver-compatible token-cli release

- token/cli/Cargo.toml
- token/client/Cargo.toml
The token client and CLI declare a requirement of spl-memo 4.0.1, which restricts it from being used with some older crates.
Relax the dependency to 4.0, same as with token.
> token-cli{,ent}: Relax spl-memo dependency

- Cargo.lock
- libraries/discriminator/Cargo.toml
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value-derive-test/Cargo.toml
- libraries/type-length-value/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
The discriminator library is still using borsh 0.10, which is causing very strange failures when trying to publish.
Bump to borsh 1 and its version to 0.2.0
> discriminator: Bump to 0.2.0

- token/client/tests/program-test.rs
There are some tests in the token-client that were ignored until token-2022 was included by default in solana-program-test. token-2022 is included in program-test, but the tests are still ignored.
Unignore them! There was a bug in one of the tests that tried to set an owner on an associated token account, which naturally failed, so I changed that to use an auxiliary token account instead.
> token-client: Unignore tests

- libraries/math/src/precise_number.rs
- libraries/tlv-account-resolution/src/seeds.rs
> chore: fix typos

- token/transfer-hook/cli/src/main.rs
Removed the deprecated functions from the transfer-hook cli as per #6307
> [transfer-hook] Remove deprecated functions from cli

- token/js/src/constants.ts
- token/js/src/extensions/transferHook/instructions.ts
Although strict equality checking _usually_ works for comparing two `PublicKey` instances, it can cause problems across different bundle types - for example when a CJS `PublicKey` meets an ESM `PublicKey`.
Opt for the provided byte-wise `PublicKey.equals` comparator over strict equality (`===`).
Closes #6536
> token-js: opt for `PublicKey.equals`

- Cargo.lock
There's an audit warning on h2, so CI is failing.
Bump it to 0.3.26
> audit: Bump h2 to 0.3.26

- single-pool/program/tests/accounts.rs
This reverts commit b32ab740bf536e3867186ec11700c1be355f16f9.
The fix in #6543 doesn't actually work for the future changes, as https://github.com/anza-xyz/agave/pull/470#issuecomment-2035749009 explains.
Revert the test change.
> Revert "single-pool: Allow stake config to be anything in tests (#6543)"

- single-pool/cli/tests/test.rs
- single-pool/program/tests/helpers/mod.rs
- stake-pool/program/tests/helpers/mod.rs
The feature flag `vote_state_add_vote_latency` has been activated on all clusters, so the old vote state version is no longer supported. 
As such, consumers should use `VoteState::size_of()` instead of `VoteStateVersions::vote_state_size_of(true)`.
Unblocks the cleanup of this feature flag https://github.com/anza-xyz/agave/pull/468
> Remove usage of VoteStateVersions::vote_state_size_of

- docs/src/confidential-token/quickstart.md
- token/cli/examples/confidential-transfer.sh
People want to test with confidential transfers, but it's annoying to piece together an end-to-end working example from the docs.
Upload the test script into an "examples" folder and mention it in the confidential docs.
> docs: Add confidential transfer test script

- pnpm-lock.yaml
- single-pool/js/packages/classic/package.json
Reverts solana-labs/solana-program-library#6503
Yeah, weird. Seems like the newest bankrun has some memory mapping issues. Tests seem to sporadically fail with segmentation faults or memory allocation violations. Perhaps the JS-Rust binding is unsafe in some bits?
> Revert "build(deps-dev): bump solana-bankrun from 0.2.0 to 0.3.0"

- libraries/program-error/derive/src/macro_impl.rs
When annotating an error enum with `[spl_program_error]`, the generated
trait implementations are using `solana_program` directly, which might cause
conflicts with the `program_error` crate's version of `solana_program` and
the program's version.
```
error[E0659]: `solana_program` is ambiguous
--> /Users/joesol/.cargo/git/checkouts/address-lookup-table-b4ff4f65bda84997/11a0b41/program/src/error.rs:5:1
|
5 | #[spl_program_error]
| ^^^^^^^^^^^^^^^^^^^^ ambiguous name
|
= note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
= note: `solana_program` could refer to a crate passed with `--extern`
= help: use `::solana_program` to refer to this crate unambiguously
```
Use unambiguous imports to let the Rust compiler decide …
> program error: use unambigious globs

- Cargo.lock
- libraries/program-error/Cargo.toml
- libraries/program-error/derive/Cargo.toml
Bumps the patch version of program error after #6590.
> program error: bump patch version

- single-pool/cli/src/main.rs
- single-pool/program/tests/helpers/mod.rs
- token/cli/src/command.rs
Add the missing single quota mark in words
> Add the missing single quota mark in words

- name-service/js/.eslintignore
- name-service/js/.prettierignore
When linting against `name-service-js`, the build target directory, `lib`, can get
included in linting, since there's no ignore rules set for prettier.
Add some ignore rules!
> name-service-js: add `.prettierignore` and `.eslintignore`

- account-compression/sdk/src/constants/index.ts
- account-compression/sdk/src/generated/instructions/append.ts
- account-compression/sdk/src/generated/instructions/closeEmptyTree.ts
- account-compression/sdk/src/generated/instructions/initEmptyMerkleTree.ts
- account-compression/sdk/src/generated/instructions/insertOrAppend.ts
- account-compression/sdk/src/generated/instructions/replaceLeaf.ts
- account-compression/sdk/src/generated/instructions/transferAuthority.ts
- account-compression/sdk/src/generated/instructions/verifyLeaf.ts
- account-compression/sdk/src/generated/types/AccountCompressionEvent.ts
- account-compression/sdk/src/generated/types/ChangeLogEventV1.ts
- account-compression/sdk/src/generated/types/ConcurrentMerkleTreeHeaderDataV1.ts
- account-compression/sdk/src/generated/types/PathNode.ts
- account-compression/sdk/src/instructions/index.ts
- account-compression/sdk/src/merkle-tree/index.ts
- account-compression/sdk/src/types/ConcurrentMerkleTree.ts
- account-compression/sdk/src/types/Path.ts
- account-compression/sdk/src/types/index.ts
- account-compression/sdk/tests/accounts/concurrentMerkleTreeAccount.test.ts
- account-compression/sdk/tests/events/applicationData.test.ts
- account-compression/sdk/tsconfig.json
- ci/js-test-account-compression.sh
The SPL Account Compression SDK has long been unchecked by `prettier` or
`eslint` rules. This means changes to the SDK are never checked by CI for
formatting or linting violations.
Additionally, as we migrate the workspace to use ESLint 9.0, it makes things 
difficult to test.
Lint `--fix` everything in the Account Compression SDK, and enable linting in 
CI!
> Account Compression SDK: Add back linting

- token/transfer-hook/cli/src/main.rs
The `pubkey_of_signer` function from `solana-clap-v3-utils` expects arguments to be parsed as `String`. However, if when using the more up-to-date way of declaring arguments using `SignerSourceParserBuilder`, clap expects arguments to be parsed directly as `SignerSource` rather than `String` and hence returns a downcast error when `pubkey_of_signer` is invoked.
Replace `pubkey_of_signer` with `pubkey_from_source`.
Unfortunately, this way of parsing is a bit more verbose than the original code, but it should do the job. Perhaps an analogous function to `pubkey_of_signer`, which parses arguments directly as `SignerSource` can be added to `solana-clap-v3-utils` later on to make the code less verbose.
Closes https://github.com/solana-labs/solana-program-library/issues/6623.
> [transfer-hook-cli] Replace `pubkey_of_signer` with `pubkey_from_source`

- token/cli/src/clap_app.rs
- token/cli/src/command.rs
- token/cli/src/config.rs
- token/cli/tests/command.rs
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/program_test.rs
https://github.com/solana-labs/solana-program-library/pull/6501 broke offline signing -- by default, the token client sets the compute unit limit based on simulation. If it's using offline signing, it'll silently swallow the error and pop the compute unit limit instruction.
So when we offline-sign a transaction, it won't have the compute unit limit instruction, and when we broadcast it, we'll simulate and add the compute unit limit instruction, causing a pre-signer error.
This was the classic overly-clever-but-brittle solution. I discovered it while applying the token-cli changes to the Solana CLI.
Be more explicit:
* don't simulate by default
* allow users to specify `--with-compute-unit-limit SIMULATED` if they want that
* error if someone sets `--with-compute-unit-price` *without* …
> token-cli: Fix offline signing by making simulated compute unit limit explicit

- stake-pool/cli/src/client.rs
- stake-pool/cli/src/main.rs
Due to network congestion mainnet and the lack of priority fee support, stake pool users can't interact with their pool on mainnet.
A few things to provide a full solution:
* Add `--with-compute-unit-price` flag to set micro-lamports per CU for all transactions in a command
* Add `--with-compute-unit-limit` flag to set the number of CUs for all transactions in a command
* If `--with-compute-unit-limit` is not set, simulate the transaction and use the number of compute units reported
As part of this, the idea is to funnel all transaction creation through `checked_transaction_with_signer` or `checked_transaction_with_signers_and_additional_fee`, which will do the simulation work and add the compute budget instructions.
Since there is some refactor, it might be easier to go through this …
> stake-pool-cli: Add support for priority fees

- Cargo.lock
- token/cli/Cargo.toml
There have been a couple of bug fixes on the token CLI, but they haven't been released yet.
Bump the crate for a new release.
> token-cli: Bump to 3.4.1 for release

- Cargo.lock
- single-pool/cli/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-metadata/example/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
We want to publish a new token-cli, but token-client had a breaking change with the new `ComputeUnitLimit` enum.
Bump to 0.10.0 for the next release.
> token-client: Bump for token-cli release

- token/transfer-hook/cli/src/main.rs
The arg for the token mint address in the Transfer Hook CLI's `create-extra-metas`
and `update-extra-metas` commands was searching for `program_id`. This causes
the program ID to be passed to the transfer hook program, when instead it should
be the mint address!
Fix the parameter parsers!
> transfer-hook-cli: patch token arg

- pnpm-lock.yaml
- stake-pool/js/package.json
- token-lending/js/package.json
- token-swap/js/package.json
These were missed, and the versions were behind npm to begin with.
Closes #6629.
> Bump version of `@solana/spl-token` to 0.4.6 and bump dependent packages

- stake-pool/cli/src/main.rs
#6550 fixed the token-cli for offline signing, but still defaults to using simulated compute units, while #6499 in the stake-pool-cli forces people to specify that they want to use `SIMULATED` compute units, and otherwise adds nothing. This is inconsistent.
Make the stake pool CLI consistent with the token CLI by defaulting to simulated compute units. On the other hand, this PR allows people to specify that they want `DEFAULT` compute units.
Let me know what you think!
> stake-pool-cli: Default to simulated compute units

- pnpm-lock.yaml
- token/js/package.json
Web3.js TP3 is out, but token-js is still on TP2.
Upgrade to TP3. This one has no other changes required, so it can go in first
> token-js: Upgrade to tp3

- pnpm-lock.yaml
- token-metadata/js/package.json
- token-metadata/js/src/field.ts
- token-metadata/js/src/instruction.ts
- token-metadata/js/src/state.ts
- token-metadata/js/test/instruction.test.ts
token-metadata-js is still on TP2, even though TP3 is out.
Upgrade to TP3! This one is very similar to #6665, but the biggest change that I have a question about is whether the `additionalMetadata` in the metadata struct should be `readonly`.
> token-metadata-js: Upgrade to tp3

- pnpm-lock.yaml
- token-group/js/package.json
- token-group/js/src/instruction.ts
- token-group/js/src/state/tokenGroup.ts
- token-group/js/src/state/tokenGroupMember.ts
- token-group/js/test/instruction.test.ts
web3.js TP3 is out, but the token-group JS library isn't using it.
Upgrade to the new lib and use it. Let me know if I'm following the right conventions! I looked at example usage from the repo directly for inspiration.
> token-group-js: Update to tp3

- token/js/src/extensions/transferFee/actions.ts
- token/js/src/extensions/transferFee/instructions.ts
- token/js/test/e2e-2022/transferFee.test.ts
Problem
As pointed out at https://github.com/solana-labs/solana-program-library/issues/5451
Solution
Add SetTransferFee endpoint
Fixes https://github.com/solana-labs/solana-program-library/issues/5451
> [spl-token-2022-js]: Add SetTransferFee instruction

- token/cli/src/clap_app.rs
The two arguments for `initialize-member` on the Token CLI are `token` and `group_token`.
However, when you print the help you'll see `<TOKEN_MINT_ADDRESS> <TOKEN_MINT_ADDRESS>`.
These should be a bit more clear.
Change the group token address help print-out to `<GROUP_TOKEN_ADDRESS>`.
> token-cli: update member `GROUP_TOKEN_ADDRESS` arg

- docs/src/token-2022/extensions.mdx
- token/js/examples/memoTransfer.ts
As pointed out at https://github.com/solana-labs/solana-program-library/issues/6655#issuecomment-2085980581, we're missing some documentation about how to actually perform a transfer with a memo.
Add a CLI and JS example.
Closes #6655 closes #6656
> token-2022: Add memo-transfer examples

- libraries/math/src/instruction.rs
- libraries/math/src/processor.rs
- libraries/math/tests/instruction_count.rs
Running the following command has been helpful determining which types to use for various math operations:
```sh
cargo test-sbf -- --nocapture --test-threads=1
```
In considering how to perform math in our programs (whether to create methods to replicate performing floating-point arithmetic or to use floats directly), we needed to benchmark some arithmetic with u128 vs f64.
This PR adds multiplication and division for each of these types.
> math: more type tests

- token/program-2022-test/tests/cpi_guard.rs
- token/program-2022/src/processor.rs
If someone has CPI guard enabled, and their token account is delegated to the owner, then it's still possible to sign with the owner's key to transfer. This goes against the spirit of the CPI guard, which does not allow transfers in CPI if they were signed by the owner.
Prohibit a transfer if:
* CPI guard is enabled
* the call is in a CPI
* the delegate is the owner
> token-2022: Prohibit self-delegated transfers with CPI Guard

- .github/workflows/fuzz-nightly.yml
- .github/workflows/pull-request-account-compression.yml
- .github/workflows/pull-request-binary-oracle-pair.yml
- .github/workflows/pull-request-examples.yml
- .github/workflows/pull-request-feature-proposal.yml
- .github/workflows/pull-request-governance.yml
- .github/workflows/pull-request-instruction-padding.yml
- .github/workflows/pull-request-js.yml
- .github/workflows/pull-request-libraries.yml
- .github/workflows/pull-request-memo.yml
- .github/workflows/pull-request-name-service.yml
- .github/workflows/pull-request-record.yml
- .github/workflows/pull-request-shared-memory.yml
- .github/workflows/pull-request-single-pool.yml
- .github/workflows/pull-request-stake-pool.yml
- .github/workflows/pull-request-token-collection.yml
- .github/workflows/pull-request-token-group.yml
- .github/workflows/pull-request-token-lending.yml
- .github/workflows/pull-request-token-metadata.yml
- .github/workflows/pull-request-token-swap.yml
- .github/workflows/pull-request-token-upgrade.yml
- .github/workflows/pull-request-token.yml
- .github/workflows/pull-request.yml
Node16 is deprecated and Actions using it will stop being used 3rd of June
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Remove warnings like this https://github.com/solana-labs/solana-program-library/actions/runs/9073098915
> ci: upgrade cache action to version with node20

- pnpm-lock.yaml
- stake-pool/js/package.json
- stake-pool/js/src/index.ts
- stake-pool/js/src/layouts.ts
- stake-pool/js/src/types/buffer-layout.d.ts
As outlined in #6677, the JS deserializer for the stake pool doesn't work because it doesn't handle the `FutureEpoch` type, which was introduced on the Rust side to force at least one epoch of notice for a change in withdrawal or epoch fees.
It's a bit gross, but this mainly copies the code from https://github.com/coral-xyz/anchor/blob/4540c8253acc2708ffd1085918e5f82f0e6c71e2/ts/packages/borsh/src/index.ts#L132, but also allows the discriminator to be 2.
This will at least allow people to deserialize pools properly until we get a real code-gen client library.
Fixes #6677
> stake-pool-js: Add deserializer for `FutureEpoch`

- stake-pool/js/package.json
There have been some fixes to the stake pool JS lib, but it's not available.
Bump the package to release.
> stake-pool-js: Bump version to 1.1.4 for release

- token/cli/tests/command.rs
The compute budget test is failing CI: https://github.com/solana-labs/solana-program-library/actions/runs/9408429916/job/25916391900
The static compute unit budget is too low.
Since this test isn't checking that compute units are below a certain amount, just bump it from 30k to 40k
> token-cli: Update CU number on tests

- Cargo.lock
- token/js/package.json
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/cli/src/main.rs
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/example/src/lib.rs
- token/transfer-hook/example/src/processor.rs
- token/transfer-hook/example/tests/functional.rs
The transfer hook example program allows any mint to initialize extra account metas. If there are other accounts managed by the transfer hook program, it might be possible for an attacker to create their own extra account metas account using accounts from another mint.
For example, mint A uses the extra accounts metas account B, which declares usage of an account C, owned by the transfer hook program. An attacker creates a mint D with extra account metas E, and also declares usage of account C. Now two mints might be modifying the same account.
While this attack is hypothetical and not possible given the simple transfer hook program here, let's model good default behavior and limit the transfer hook example to only allow account metas for one mint.
> transfer-hook-example: Only allow one mint to initialize

- stake-pool/cli/src/main.rs
Adding the following commands to the `spl-stake-pool` rust cli:
- `create_token_metadata`
- `update_token_metadata`
All arguments have been catered for with friendly descriptions.
> Add Create & Update Token Commands to Stake-Pool CLI

- stake-pool/cli/scripts/setup-stake-pool.sh
- stake-pool/cli/scripts/setup-test-validator.sh
Some of the stake pool setup scripts are out of date -- they don't use token-metadata, and they don't clone programs properly.
Update the script to add token metadata and to clone the MPL token metadata program.
> stake-pool-cli: Add metaplex program to setup script

- token/program-2022-test/tests/confidential_transfer_fee.rs
fix downstream project tests for: https://github.com/anza-xyz/agave/pull/1693
> test: ensure confidential_transfer using the latest blockhash

- token/program-2022-test/tests/confidential_transfer.rs
I missed this file in https://github.com/solana-labs/solana-program-library/pull/6836 🫠 
---
https://github.com/anza-xyz/agave/pull/1693
> test: ensure confidential_transfer using the latest blockhash 

- libraries/tlv-account-resolution/src/account.rs
- libraries/tlv-account-resolution/src/error.rs
- libraries/tlv-account-resolution/src/key_data.rs
- libraries/tlv-account-resolution/src/lib.rs
- libraries/tlv-account-resolution/src/pubkey_data.rs
- libraries/tlv-account-resolution/src/state.rs
Currently, TLV Account Resolution (and Transfer Hook) doesn't support extracting
account keys from data - including instruction or account data.
Introduce the `PubkeyData` configuration for doing exactly that, then add support for
it to `ExtraAccountMeta` and `ExtraAccountMetaList`.
cc @jychab
Closes #6845
> TLV Account Resolution: Add support for keys in data

- token/program-2022/src/extension/confidential_transfer/processor.rs
According to the Certora audit findings:
> Description: Regular instructions (Transfer, TransferChecked, and TransferCheckedWithFee) determine that an account is non-transferable by checking for presence of NonTransferableAccount extension in the source account. ConfidentialTransferInstruction::Transfer, instead, checks that the mint has the NonTransferable mint extension.
> Recommendation: This is not an issue at the moment because every account of NonTransferable mint has a NonTransferableAccount extension. We recommend that all instructions use NonTransferableAccount to make the code more uniform and to prevent any deviation in the future should the invariant no longer be maintained.
We have to use the account check for the extension in non-confidential transfers, since the mint might …
> token-2022: [L-02] Check for non-transferable extension consistently

- ci/do-audit.sh
Just like https://github.com/anza-xyz/agave/pull/1786, SPL is failing the audit check in CI.
Until we can upgrade to curve25519-dalek v4, ignore it
> audit: Add curve25519-dalek RUSTSEC to ignore list

- token/program-2022/src/extension/transfer_fee/instruction.rs
According to the Certora audit:
> A TransferCheckedWithFee succeeds even if the mint account is not extended with TransferFeeConfig if the instruction argument expected_fees is zero. This makes TransferChecked redundant since it can always be replaced by TransferCheckedWithFee.
> Recommendation: 
> Either not allow TransferCheckedWithFee to succeed when fees are not enabled, or document that this is an expected and allowed behavior. 
Comment that it is intended for TransferCheckedWithFee to work with any mint.
> token-2022: [L-04] Comment that TransferCheckedWithFee works for all mints

- token/program-2022/src/processor.rs
According to the Certora audit findings:
> Description: The function process_transfer in token-2022/src/processor.rs is used to implement Transfer, TransferChecked, and TransferCheckedWithFee. However, it also succeeds when called with a fee and no mint. 
> Recommendation: Return an error if the function is called with the last two arguments being None and Some.
It's really a programmer error if we call `process_transfer` with an expected fee, but no mint decimals, so be more bold and assert that there's never an expected fee if there's no mint decimals.
> token-2022: [I-01] Assert that a transfer fee always includes mint decimals

- token/program-2022/src/lib.rs
- token/program-2022/src/processor.rs
- token/program-2022/tests/assert_instruction_count.rs
From the Certora audit report, there's mixed use of `==` and `sol_memcmp` for public keys. This was done because the syscall was cheaper for a time, but is no longer the case.
The first commit updates the instruction counts for current master, and then the second commit makes the change and updates with the new instruction counts -- everything is reduced!
> token-2022: [L-05] Use Pubkey's `==` instead of `sol_memcmp`

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- binary-option/program/Cargo.toml
- binary-oracle-pair/program/Cargo.toml
- examples/rust/transfer-tokens/Cargo.toml
- feature-proposal/program/Cargo.toml
- governance/addin-mock/program/Cargo.toml
- governance/chat/program/Cargo.toml
- governance/program/Cargo.toml
- governance/test-sdk/Cargo.toml
- governance/tools/Cargo.toml
- managed-token/program/Cargo.toml
- single-pool/cli/Cargo.toml
- single-pool/program/Cargo.toml
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- stateless-asks/program/Cargo.toml
- token-lending/cli/Cargo.toml
- token-lending/flash_loan_receiver/Cargo.toml
- token-lending/program/Cargo.toml
- token-swap/program/Cargo.toml
- token-swap/program/fuzz/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022/Cargo.toml
- token/program/Cargo.toml
As mentioned in #6897, updating to allow for version <= 2.0 of the solana crates can appear as a breaking change for new projects, since cargo pulls in the latest version of all dependencies, and once there's an attempt to mix v1 and v2, downstream users will see errors.
This is made worse that the patch versions will quietly pick up the v2 dependency, so if someone doesn't know how to manipulate a cargo lockfile, they will get build errors and won't know how to resolve them.
All other SPL crates contain a new breaking version (new major for crates on v1 or more, new minor for crates on v0.X), except for spl-token.
Bump spl-token to v5.
> token: Update to v5 for solana-program 2.0 compatibility

- token/program-2022-test/tests/memo_transfer.rs
- token/program-2022/src/processor.rs
According to the Certora audit report:
> Description: In regular instructions (Transfer, TransferChecked, and TransferCheckedWithFee)  a self-transfer does not require a memo even if the destination is extended with MemoTransfer while in ConfidentialTransferInstruction::Transfer, self-transfer always does. 
> Recommendation: Make regular and confidential instructions behave uniformly with respect to MemoTransfer.
The opposite of #6861: require a memo for non-confidential self-transfers
> token-2022: [L-03] Require memo on self-transfer with memo-transfer

- Cargo.lock
- account-compression/programs/account-compression/Cargo.toml
- account-compression/programs/account-compression/src/concurrent_tree_wrapper.rs
- account-compression/programs/account-compression/src/lib.rs
- account-compression/programs/account-compression/src/macros.rs
- libraries/concurrent-merkle-tree/Cargo.toml
- libraries/concurrent-merkle-tree/src/concurrent_merkle_tree.rs
- libraries/concurrent-merkle-tree/tests/tests.rs
Building the current version of account-compressions on the master branch gives the following error. 
```
Error: Function _ZN23spl_account_compression23spl_account_compression12replace_leaf17hdc3dd750827dcd7bE Stack offset of 4976 exceeded max offset of 4096 by 880 bytes, please minimize large stack variables
Error: Function _ZN23spl_account_compression23spl_account_compression11verify_leaf17h04e381cb5ac1c2baE Stack offset of 4912 exceeded max offset of 4096 by 816 bytes, please minimize large stack variables
Error: Function _ZN23spl_account_compression23spl_account_compression16insert_or_append17hf55fb617fa2a0f55E Stack offset of 4952 exceeded max offset of 4096 by 856 bytes, please minimize large stack variables
```
This indicates a potential stack overflow issue. The underlying issue …
> account-compression: fix for a stack overflow issue on macro usage

- token/js/package.json
We haven't released token-js since `setTransferFee` was added, among other things.
Bump and release
> token-js: Bump to 0.4.7 for release

- Cargo.lock
- instruction-padding/program/Cargo.toml
- token/program-2022-test/Cargo.toml
Bump spl-instruction-padding for the next release
> instruction-padding: Bump to 0.2.0 for Solana v2 support

- Cargo.lock
- libraries/discriminator/Cargo.toml
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value-derive-test/Cargo.toml
- libraries/type-length-value/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
Bump spl-discriminator for the next release
> discriminator: Bump to 0.3.0 for Solana v2

- Cargo.lock
- libraries/pod/Cargo.toml
- libraries/program-error/Cargo.toml
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
Bump spl-program-error for the next release
> program-error: Bump to 0.5.0 for Solana v2 compatibility

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- binary-option/program/Cargo.toml
- binary-oracle-pair/program/Cargo.toml
- examples/rust/transfer-tokens/Cargo.toml
- feature-proposal/program/Cargo.toml
- governance/addin-mock/program/Cargo.toml
- governance/chat/program/Cargo.toml
- governance/program/Cargo.toml
- governance/test-sdk/Cargo.toml
- governance/tools/Cargo.toml
- managed-token/program/Cargo.toml
- single-pool/cli/Cargo.toml
- single-pool/program/Cargo.toml
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
- stateless-asks/program/Cargo.toml
- token-lending/cli/Cargo.toml
- token-lending/flash_loan_receiver/Cargo.toml
- token-lending/program/Cargo.toml
- token-swap/program/Cargo.toml
- token-swap/program/fuzz/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022/Cargo.toml
- token/program/Cargo.toml
Bump spl-token for the next release
> token: Bump to v6 for Solana v2 compatibility

- Cargo.lock
- libraries/pod/Cargo.toml
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value/Cargo.toml
- record/program/Cargo.toml
- stake-pool/program/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/example/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
Bump spl-pod for the next release
> pod: Bump to 0.3.0 for Solana v2 compat

- Cargo.lock
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value-derive-test/Cargo.toml
- libraries/type-length-value/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/example/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
Bump spl-type-length-value for the next release
> tlv: Bump to 0.5.0 for Solana v2 compatibility

- Cargo.lock
- libraries/pod/Cargo.toml
- libraries/pod/src/optional_keys.rs
- libraries/pod/src/primitives.rs
- libraries/pod/src/slice.rs
We can't publish spl-pod because it runs into issues with trying to derive `Pod` and `Zeroable`, likely because all of our tests activate the `derive` feature on bytemuck, but the solo crate does not.
Use `bytemuck_derive` explicitly
> pod: Use `bytemuck_derive` explicitly

- Cargo.lock
- libraries/tlv-account-resolution/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
Bump spl-tlv-account-resolution for the next release
> tlv-account-resolution: Bump to 0.7.0 for Solana v2

- Cargo.lock
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/example/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
Bump spl-token-metadata-interface, spl-token-group-interface, and spl-transfer-hook-interface for the next release
> token-{metadata,group,transfer-hook}-interface: Bump for Solana v2 compatibility

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- stake-pool/program/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-metadata/example/Cargo.toml
- token-swap/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/example/Cargo.toml
Bump spl-token-2022 for the next release
> token-2022: Bump to v4 for Solana v2 compatibility

- Cargo.lock
- associated-token-account/program-test/Cargo.toml
- associated-token-account/program/Cargo.toml
- managed-token/program/Cargo.toml
- single-pool/cli/Cargo.toml
- single-pool/program/Cargo.toml
- stake-pool/cli/Cargo.toml
- stateless-asks/program/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-wrap/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
Bump spl-associated-token-account for the next release
> associated-token-account: Bump to v4 for Solana v2

- Cargo.lock
- single-pool/cli/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-metadata/example/Cargo.toml
- token-upgrade/cli/Cargo.toml
- token-upgrade/program/Cargo.toml
- token/cli/Cargo.toml
- token/client/Cargo.toml
- token/program-2022-test/Cargo.toml
- token/transfer-hook/cli/Cargo.toml
Bump spl-token-client for the next release
> token-client: Bump to v0.11 for Solana v2 compatibility

- Cargo.lock
- token/cli/Cargo.toml
Bump spl-token-cli for the next release
> token-cli: Bump to v4 for Solana v2 compatibility

- Cargo.lock
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
The stake-pool-cli v1 is failing to build due to multiple solana-program versions, same issue that we've been seeing in #6897.
Bump and release the v2 compatible crate
> stake-pool: Bump to v2 for Solana v2 compatibility

- Cargo.lock
- stake-pool/cli/Cargo.toml
All of the SPL crates have been bumped up to using the Solana v2 crates, but there hasn't been a new release of the stake pool CLI.
Bump to v2 for the next release
> stake-pool-cli: Bump to v2 for Solana v2 compatibility

- token/program-2022/src/extension/mod.rs
- token/program-2022/src/pod.rs
The method to determine if a particular `PodAccount` is initialized simply checks
whether or not the `state` field (`AccountState`) is _not_ equal to zero.
However, this means that any number besides `0` is considered to be an initialized
`PodAccount`. This allows arbitrary data with size 165 to be considered a valid token
account. For example, `&[5; 165]` registers as an initialized token account.
Adjust the `is_initialized` method to explicitly check the two initialized `AccountState`
variants, rather than `!= 0 `.
> token-2022: adjust `PodAccount` initialized check

- token/transfer-hook/cli/Cargo.toml
- token/transfer-hook/cli/src/main.rs
The transfer hook cli tool still uses some deprecated functions from clap-v2.
Updated the deprecated functions from clap-v2. Most of the changes should be straightforward:
- Replaced `Arg::with_name` to `Arg::new`, which is functionally identical
- Replaced `Arg::multiple` with `ArgAction::Append`, which should be functionally identical
- Replaced `is_present` with `try_contains_id`. The old `is_present` panics if the arg is not previously known/defined while `try_contains_id` gives an error. Otherwise, the two functions are identical.
The only non-trivial change would be replacing `value_of`. This should technically be updated to `try_get_one::<T>(...)` or `get_one::<T>(...)`, but I replaced it with a convenience function `try_get_signer`, which was added with `solana-clap-v3-utils 2.0`. …
> [transfer-hook] Remove clap deprecated functions

- .github/workflows/pull-request-account-compression.yml
- .github/workflows/pull-request-js.yml
- .github/workflows/pull-request-libraries.yml
- .github/workflows/pull-request-memo.yml
- .github/workflows/pull-request-name-service.yml
- .github/workflows/pull-request-single-pool.yml
- .github/workflows/pull-request-stake-pool.yml
- .github/workflows/pull-request-token-group.yml
- .github/workflows/pull-request-token-lending.yml
- .github/workflows/pull-request-token-metadata.yml
- .github/workflows/pull-request-token-swap.yml
- .github/workflows/pull-request-token.yml
Upgrading the `pnpm/action-setup` to v4 can prevent encountering these failed situations:
- https://github.com/element-plus/element-plus/actions/runs/9788077597/job/27027285287
- https://github.com/yazi-rs/yazi-rs.github.io/actions/runs/9786469651/job/27021395652
Upstream: https://github.com/pnpm/action-setup/issues/135#issuecomment-2206861174
> ci: update pnpm setup

- .npmrc
- pnpm-lock.yaml
- token-group/js/package.json
- token/js/package.json
Bump & publish `@solana/spl-token-group` version `0.0.5` to include any recent changes to dependencies.
Then bump & publish `@solana/spl-token` version `0.4.8` to include the newer Token Group JS, eliminating the dependency on the deprecated version.
Closes #6958 
In our repository, we build and publish packages using `pnpm` version `8.14.3` (see workspace package.json). There are a few ways you can configure a matching `pnpm` version locally, but I use the following command, since my global version is 9.5.0.
```shell
npx pnpm@8.14.3 <command>
```
When using the proper version of `pnpm` and - after installing all packages - running the build step from the **workspace root** (ie., `npx pnpm@8.14.3 run build`), the postbuild step that configures the CJS output is successfully run by Turbo. …
> bump token-group and token-js

- libraries/pod/src/primitives.rs
Currently there is no equivalent `Pod*` type for `u128`, so it is not possible to use `u128` fields when the alignment does not match.
Add a `PodU128` type, which provides a flexible `Pod` type based on a byte array.
> [libraries/pod]: add `PodU128` type

- token-upgrade/cli/Cargo.toml
- token-upgrade/cli/src/main.rs
The token-upgrade cli tool still uses some deprecated functions from clap-v2.
Updated the deprecated functions from clap-v2. Most of the changes should be straightforward:
- Replaced `Arg::multiple` with `ArgAction::Append`, which should be functionally identical
- Replaced `is_present` with `try_contains_id`. The old `is_present` panics if the arg is not previously known/defined while `try_contains_id` gives an error. Otherwise, the two functions are identical.
- Replaced `try_pubkey_of` with `SignerSource::try_get_pubkey`. The `try_pubkey_of` internally tries to parse `Pubkey` from `SignerSource`, which unfortunately, solana-clap-v3-utils does not yet support. The `SignerSource::try_get_pubkey` parses `SignerSource` correctly and then extracts `Pubkey` from it.
The only non-trivial …
> [token-upgrade] Remove clap deprecated functions

- Cargo.lock
- patch.crates-io.sh
- token/confidential-transfer/proof-extraction/Cargo.toml
- token/confidential-transfer/proof-extraction/src/encryption.rs
- token/confidential-transfer/proof-extraction/src/errors.rs
- token/confidential-transfer/proof-extraction/src/lib.rs
- token/confidential-transfer/proof-extraction/src/transfer_with_fee.rs
- token/confidential-transfer/proof-generation/src/encryption.rs
- token/confidential-transfer/proof-generation/src/errors.rs
- token/confidential-transfer/proof-generation/src/lib.rs
- token/confidential-transfer/proof-generation/src/transfer_with_fee.rs
- token/confidential-transfer/proof-tests/tests/proof_test.rs
The logic to generate proof data for transfer with fee have not been added to the repo yet.
Add the logic to generate the proof data. This proof is quite technical, but it essentially follows the existing logic in [token client](https://github.com/solana-labs/solana-program-library/blob/master/token/client/src/proof_generation.rs).
> [confidential-transfer] Add transfer with fee proof generation and extraction

- token/program-2022/Cargo.toml
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/token_group/processor.rs
The `token-group` and `confidential-hook` crate features were added to deploy a version of token-2022 without the token-group extension and without calling the transfer hook in confidential transfers.
Since then, token-2022 has been audited multiple times with these features, but they're still in the code.
In preparation of the next deployment, remove the features since they aren't needed anymore
> token-2022: Remove `token-group` and `confidential-hook` features

- token/confidential-transfer/proof-extraction/src/lib.rs
- token/confidential-transfer/proof-extraction/src/withdraw.rs
- token/confidential-transfer/proof-generation/src/lib.rs
- token/confidential-transfer/proof-generation/src/withdraw.rs
- token/confidential-transfer/proof-tests/tests/proof_test.rs
The withdraw proof logic has not yet been added to the `proof-generation` and `proof-extraction` modules.
Add the withdraw proof logic. The logic should essentially be the same as the one in `split_proof_generation` module in `program-2022`.
> [confidential-transfer] Add withdraw proof generation and extraction

- token/confidential-transfer/proof-generation/src/transfer.rs
- token/confidential-transfer/proof-generation/src/transfer_with_fee.rs
- token/confidential-transfer/proof-tests/tests/proof_test.rs
The constructor functions for proof data required for confidential transfer and transfer with fee returns a tuple of proof data structs. It would be cleaner and more readable to organize the return type using structs instead.
Re-organize the proof data using structs.
> [confidential-transfer] Organize transfer proof data using structs

- Cargo.lock
- Cargo.toml
- token/confidential-transfer/ciphertext-arithmetic/Cargo.toml
- token/confidential-transfer/ciphertext-arithmetic/src/lib.rs
The syscall ElGamal ciphertext arithmetic functions (the logic in `solana_zk_token_sdk::zk_elgamal::ops`) have been removed in `solana-zk-sdk` as they are related specifically to the token program with plans to be moved into the spl repo.
Added the confidential transfer `ciphertext-arithmetic` crate that implements the syscall ElGamal ciphertext arithmetic functions. 
This is essentially a copy of the logic from `solana_zk_token_sdk::zk_elgamal::ops` except for the following functions:
- `elgamal_ciphertext_to_ristretto(...)`: In the `zk-token-sdk`, `(`PodPedersenCommitment, PodDecryptHandle)` implemented `TryFrom` for `PodElGamalCiphertext`. However, this was removed in `zk-sdk` for simplicity. The `elgamal_ciphertext_to_ristretto(...)` was added as a function to directly convert from …
> [confidential-transfer] Add confidential transfer ciphertext arithmetic crate

- Cargo.lock
- token/program-2022/Cargo.toml
1.18 is out on mainnet, and token-2022 has had a few more audits since the last deployment, so it's time to deploy!
Bump the crate to 4.0.1 to include recent fixes
> token-2022: Bump to 4.0.1 for next release

- token/program-2022/src/entrypoint.rs
We're about to deploy the new token-2022, but the security.txt info is out of date.
Update the security.txt fields
> token-2022: Update security.txt info

- Cargo.lock
The audit job is failing due to https://rustsec.org/advisories/RUSTSEC-2024-0357.html, e.g. see https://github.com/solana-labs/solana-program-library/actions/runs/10038554596/job/27740708684?pr=7034 for a failure
Just like https://github.com/anza-xyz/agave/pull/2228, bump openssl to 0.10.66
> deps: Update openssl to 0.10.66 for rustsec

- account-compression/programs/account-compression/src/concurrent_tree_wrapper.rs
- account-compression/programs/account-compression/src/lib.rs
Fixes stack frame violation found when deployed on devnet ([here](https://explorer.solana.com/tx/vqdom3dquBA3zzkbkBc7XNaF9oC3h5HFmKHu7V4vASXMfX1EiwU7KyN58bWXFFYjq4WaBVW2wXsmcSdxwTmVeGA)).
> Fix init empty stack frame violation

- stake-pool/cli/src/main.rs
When creating a stake-pool using the CLI, if at any point an instruction fails subsequent commands will also fail. This behavior creates a problem when initializing a stake pool in the CLI with vanity keypairs. This solution aims to break up the `command_create_pool` into iterative steps with checks along the way.
I had changed the deprecated ` use spl_associated_token_account::create_associated_token_account` but am happy to change it back.
> stake-pool: CLI QOL improvements

- libraries/pod/src/option.rs
The `PodOption` type currently has 2 limitations:
1. It does not handle correctly the conversion of `Option::Some(T::default())` to `PodOption` since `T::default()` corresponds to the `None` value. As a result, it will convert a `Some` to a `None` value.
2. It always assume that `T:default()` is the `None` value, which might not be true in all cases and could be a limitation.
To address (1), replace the `From` implementation for a `TryFrom`, where the conversion will fail when trying to convert a `Option::Some(T::default())` value to `PodOption`.
To address (2), add a new associated constant `NONE` to the `Nullable` trait instead of relying on the `default` value. Types implementing the trait can then specify the value that represents `None`.
> [libraries/pod]: improve `PodOption` type

- Cargo.lock
- libraries/pod/Cargo.toml
We added two new types to `spl-pod`:
* A generic `PodOption<T>` that can be used as a `Pod` for types that can have a designated `None` value.
* `PodU128` to represent primitive `u128`
Bump `spl-pod` for the next patch version.
> pod: Bump to 0.3.1

- libraries/pod/src/option.rs
It's a bit annoying that `PodOption` doesn't implement `Default`.
Just like `Option`, have it return `Nullable::NONE`
> pod: Implement `Default` for `PodOption`

- Cargo.lock
- token/cli/Cargo.toml
The current spl-token-cli fails to build, and it looks like it's because some of the SPL crates lost their ability to support 2.0 during the re-publish.
The 2.0.3 Solana crates use only 2.0 crates, and SPL already supports this version, so we just need to bump the token cli version and publish.
Fixes #7043
> token-cli: Bump to 4.0.1 for new release

- token/cli/src/command.rs
**Problem**
Currently the `spl-token wrap` and `spl-token unwrap` commands ignore the `--compute-budget-limit` and price arguments. With the current congestion on Solana, this makes it difficult to land transactions.
**Solution**
Do not ignore these values with native mints and instead replicate the `config_token_client` within `native_token_client_from_config` to properly check for priority fees and limits.
> spl-token-cli: support compute price + limit with native tokens

- token/program-2022-test/tests/transfer_hook.rs
- token/transfer-hook/interface/src/instruction.rs
- token/transfer-hook/interface/src/offchain.rs
- token/transfer-hook/interface/src/onchain.rs
It's possible to write a perfectly good transfer hook without the extra account metas, and just the transfer hook program. For example, if you add a field to the metadata portion of the mint, a transfer hook program can check only that, so it has no need for anything else.
Relax the requirement that the extra account metas account is provided. This was surprisingly straightforward, but maybe a little brittle, so let me know what you think.
> transfer-hook: Relax requirement of validation account

- ci/do-audit.sh
There are many old audit ignores in the cargo audit script.
Remove the security advisories that we don't need to ignore.
> CI: Remove unneeded ignores in audit

- libraries/type-length-value/README.md
Building on https://github.com/solana-labs/solana-program-library/pull/7106, use the repetition numbers returned by `init_value` to re-fetch the entries, to demonstrate their use.
> TLV: README: use repetition numbers

- token/cli/README.md
- token/cli/src/clap_app.rs
- token/cli/src/config.rs
- token/cli/tests/command.rs
Instead of copying the token program id of the token22 program one can now just write: 
```
create-token --token-program-2022
or
create-token -2
```
> token-2022: add token 2022 argument to token cli for easy use

- Cargo.lock
The binary built with `cargo install --locked spl-token-cli` has a segfault, likely due to https://github.com/RustCrypto/hashes/issues/344. The normal build with `cargo install spl-token-cli` does work, however. It's not clear why this issue has only started now, but the spl-token-cli build is not working on the Solana 2.0.4 and 2.0.5 releases.
Bump sha2 to 0.9.9.
> deps: Bump sha2 to 0.9.9

- pnpm-lock.yaml
- single-pool/js/packages/classic/package.json
- single-pool/js/packages/classic/src/addresses.ts
- single-pool/js/packages/classic/src/instructions.ts
- single-pool/js/packages/classic/src/transactions.ts
- single-pool/js/packages/classic/tests/transactions.test.ts
- single-pool/js/packages/modern/package.json
- single-pool/js/packages/modern/src/addresses.ts
- single-pool/js/packages/modern/src/index.ts
- single-pool/js/packages/modern/src/instructions.ts
- single-pool/js/packages/modern/src/internal.ts
- single-pool/js/packages/modern/src/quarantine.ts
- single-pool/js/packages/modern/src/transactions.ts
The single pool js package has been fixed to a certain version of the new web3.js library. Now that the RC has been tagged, let's update it!
Update to rc.0 and make all other required changes. As part of this, I updated to using the individual packages (ie. address + transaction-messages over the omnibus), which will confuse dependabot less in the future.
> single-pool-js: Update to web3.js v2 rc

- libraries/program-error/derive/src/macro_impl.rs
- libraries/program-error/derive/src/parser.rs
- libraries/program-error/tests/spl.rs
- libraries/type-length-value/src/error.rs
There are going to be a lot of issues with people seeing errors on
spl_program_error derivation. When a build pulls in two version of
solana_program, the macro uses `::solana_program`, which now becomes
ambiguous.
I'm not sure if this is a good idea, but this PR gives the ability
to specify which version of `solana_program` to use when deriving the
various traits on your error type.
Borsh has this same functionality, and it's saved us when pulling in
multiple versions of borsh in the SDK.
Note: this PR defaults to `solana_program` instead of
`::solana_program`, which might cause downstream issues.
> program-error: Add option to specify solana_program crate

- stake-pool/program/src/instruction.rs
Created a new variant of these creators, `decrease_additional_validator_stake_with_list` and `increase_additional_validator_stake_with_list`, which takes in the pool's ValidatorList.
Fixes #6279
> stake-pool: Add instruction creators that re-use existing seeds

- token/js/src/actions/createAssociatedTokenAccount.ts
In certain scenarios, such as with a DEX, it may be necessary to create an associated token account for a PDA (Program Derived Address). However, the current implementation of `createAssociatedTokenAccount` in the `@solana/spl-token` library has the `allowOffCurve` option set to false by default while `getAssociatedTokenAddressSync`.
(Reference: [GitHub link](https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/actions/createAssociatedTokenAccount.ts#L29))
To create an ATA for a PDA, a custom implementation is required.
This PR aims to enhance code reusability by allowing users to set the `allowOffCurve` option when using `createAssociatedTokenAccount`.
> Adding Curve Option When Creating ATA

- token/cli/src/clap_app.rs
Just check both conditions and return error. Clap doesn't have the method for check that, so I do check in command logic.
Fixes #7042
> Add check withdraw-withheld-tokens has sources or include mint

- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer_fee/instruction.rs
- token/program-2022/src/proof.rs
The token program upgraded to use the new `solana-zk-sdk`, but some of the docs still use references to `solana-zk-token-sdk`.
- Updated `ZeroBalanceProof` to `ZeroCiphertextProof`
- Updated `zk-token-proof` to `zk-elgamal-proof`
- Removed the `Proof` suffix in some of the zk elgamal proof instruction names (e.g. `VerifyZeroCiphertextProof` to `VerifyZeroCiphertext`)
Note: This PR only touches the comments/docs, not the actual code.
> [token-2022] Update docs to use `zk_elgamal_proof` program

- token/program-2022/src/lib.rs
- token/program-2022/src/proof.rs
The ZK Token Proof program has been updated to ZK ElGamal Proof program. However, the program consistency function in the token program still refers to this function as `check_zk_token_proof_program_account`.
Update `check_zk_token_proof_program_account` to `check_zk_elgamal_proof_program_account`.
> [token-2022] Update to `check_zk_elgamal_proof_program_account`

- token/client/src/token.rs
Currently, the token-client handles to create confidential transfer instructions that require split zkp's always generate the proof data. However, this is wasteful in that if all of the proofs are pre-verified using a context-state account or already generated and stored in a record account, then there is no need to generate the split proofs.
Update the client logic so that for the special case of when the proof accounts are all `Some(...)`, we skip proof generation.
> [token-2022] Remove unnecessary split proof generation logic

- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/confidential_transfer_fee.rs
- token/program-2022-test/tests/program_test.rs
In the token22 tests, there are a bit of repeated logic to test instructions that require zkps in the form of instruction data, record account, and context state account. In the recent PRs (https://github.com/solana-labs/solana-program-library/pull/7127, https://github.com/solana-labs/solana-program-library/pull/7148) the tests for transfer and withdraw instructions have been refactored to tests the three variants of tests in a module way. The test logic for the other instructions could also benefit from this style of refactoring.
Made the refactoring changes for the empty account, configure account, and withdraw withheld fees instructions.
> [token-2022] Refactor tests to use `ConfidentialTransferOption`

- token/cli/src/command.rs
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/confidential_transfer_fee.rs
Some confidential transfer related functions in the token-client take in `Signer` instead of `Signers` as is done in other token-client functions.
I updated these functions to take in `Signers` to be in-line with the rest of the functions. The only exception is `confidential_transfer_create_record_account`. This function creates multiple transactions and they might require differing list of signers. Therefore, for this function, I ended up updating the parameters so that the different signers could be of differing type (previously, they had to be the same type, e.g. both signers have to be keypairs).
> [token-client] use `Signers`instead of `Signer` for confidential transfer client functions

- token/cli/src/command.rs
- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/confidential_transfer_fee.rs
There is an inconsistency in the parameter orders between the `confidential_transfer_close_context_state` and `confidential_transfer_close_record_account` functions.
- In `confidential_transfer_close_context_state`, the lamport destination account is before the context state authority
- In `confidential_transfer_close_record_account`, the lamport destination comes after the context state authority
I updated `confidential_transfer_close_record_account` function to follow the `confidential_transfer_close_context_state` function. I also updated the `confidential_transfer_close_context_state` function name to `confidential_transfer_close_context_state_account` to be more consistent with the other functions.
> [token-client] Make `close_context_state_account` and `close_record_account` variable order consistent

- token/js/src/instructions/associatedTokenAccount.ts
- token/js/test/common.ts
- token/js/test/unit/index.test.ts
> add derivation of createAssociatedTokenAccountIdempotentInstruction

- .github/workflows/publish-rust.yml
- ci/publish-rust.sh
There are a lot of crates in SPL, and in the future SDK monorepo, so it would be extremely useful to have a manual GitHub Actions workflow to test a package, bump its version everywhere, publish it, and create a release on GitHub.
Following the excellent scripts at the
[counter-shank repo](https://github.com/solana-program/counter-shank/blob/main/.github/workflows/publish-rust-client.yml), port the zx bits to bash, and do mostly the same thing, except allowing for multiple packages to be published. Thanks @lorisleiva!
The tests before publish are just the steps from `pull-request.yml`.
You can also see my testing around with this at https://github.com/joncinque/counter-shank
> CI: Add manual workflow to publish crates

- token/confidential-transfer/ciphertext-arithmetic/Cargo.toml
- token/confidential-transfer/proof-extraction/Cargo.toml
- update-solana-dependencies.sh
The solana-curve25519 dependency is marked at 2.0.0, where all of the other crates are at 2.0.3.
Update the dependency to 2.0.3 for consistency. At the same time, add that crate along with a few others to `update-solana-dependencies.sh`
> deps: Bump solana-curve25519 to 2.0.3 for consistency

- .github/workflows/publish-rust.yml
The "Publish Rust Crate" job fails in the last step because the cargo toolchain hasn't been set properly.
Set the environment variable before installing the rust toolchain.
> ci: Fix publish step by setting env vars

- ci/publish-rust.sh
The tag is incorrect in the publish step, using an `@` instead of a `-`, ie `token-2022@v1.0.0` instead of `token-2022-v1.0.0`.
Change the `@` to a `-`
> ci: Fix tag in publish-rust step

- pnpm-lock.yaml
- token-group/js/package.json
- token-metadata/js/package.json
- token/js/package.json
As pointed out in #7202, `@solana/spl-token-metadata` depends on a newer version of `@solana/codecs`, which some developers would like to use. Additionally, `@solana/spl-token-group` also depends on this new codecs API, so it makes sense to bump them both together!
We can wait to publish a new patch for `@solana/spl-token` until that's been requested as well, if so desired.
Bump the patch versions of both `@solana/spl-token-metadata` and `@solana/spl-token-group`.
At one point some of the JS packages fell out of sync with their published versions, so token-metadata skips one here. We rectified a few of these with https://github.com/solana-labs/solana-program-library/pull/7000, but looks like metadata didn't get a release during that one.
Closes #7202
> Bump token-metadata-js and token-group-js

- libraries/type-length-value/src/error.rs
While trying to publish type-length-value, there's an issue because its error definition requires new changes to spl_program_error.
There are a lot of packages to publish for the new token-2022, so to keep things simple, revert the usage of the new macro.
> type-length-value: Revert specifying solana program crate path

- .github/workflows/publish-rust.yml
The publish step can fail because the protobuf compiler is missing: https://github.com/solana-labs/solana-program-library/actions/runs/10596818547/job/29366085606
Install build deps during publish step
> CI: Install build deps before publish

- Cargo.toml
The curve25519-dalek crate could be quite slow on development mode relative to release mode. This could result in some tests failing (e.g. https://github.com/anza-xyz/agave/pull/2252).
Bump up the opt-level for the crate in Cargo.
> Increase dev mode opt-level for curve25519-dalek crate

- docs/src/token-2022/status.md
The status of token-2022 has changed due to the refactor of the ZK ElGamal proof program.
Make that clearer.
> docs: Update the status of token-2022

- .github/workflows/publish-rust.yml
Sometimes, while the publish workflow is running, we merge a different PR, which means that the workflow is running against an older commit. This makes the step to push the tag commit fail sometimes, but this happens *after* the new crate has already been published. This means that we end up publishing crates that don't have any commits attached to them.
Add a step to rebase before publishing.
cc @lorisleiva in case you want to do something similar for the template repos
> ci: Rebase during publish step

- Cargo.lock
- libraries/tlv-account-resolution/Cargo.toml
- libraries/type-length-value-derive-test/Cargo.toml
- libraries/type-length-value/Cargo.toml
- token-collection/program/Cargo.toml
- token-group/example/Cargo.toml
- token-group/interface/Cargo.toml
- token-metadata/example/Cargo.toml
- token-metadata/interface/Cargo.toml
- token/program-2022/Cargo.toml
- token/transfer-hook/example/Cargo.toml
- token/transfer-hook/interface/Cargo.toml
There was an issue in the publish for TLV 0.6.0, which means that the crate was published, but the version bump didn't go through: https://github.com/solana-labs/solana-program-library/actions/runs/10595201490/job/29360836916
Do the version bump.
> Publish type-length-value v0.6.0

- .github/workflows/publish-rust.yml
- Cargo.toml
- ci/publish-rust.sh
The publish workflow is great, but it does some work by hand, namely creating the git commit and tag. `cargo release` can do this, but we currently don't use it because we aren't customizing it.
Add configuration options to the top-level Cargo.toml and let cargo release do everything for us.
Side note: this *does not* resolve the issue of publishing a crate and then failing to push the git commit. `cargo release` is just doing the steps in series, so if `git push` fails after `cargo publish`, you're in the same situation as now. This just makes the scripts and workflow a bit simpler
> ci: Add git tag / commit message with cargo release

- .github/workflows/pull-request-account-compression.yml
- .github/workflows/pull-request-name-service.yml
- .github/workflows/pull-request-single-pool.yml
- .github/workflows/pull-request-stake-pool.yml
- .github/workflows/pull-request-token-lending.yml
- .github/workflows/pull-request-token-swap.yml
- .github/workflows/pull-request-token.yml
CI is still on the older v3 of upload-artifact / download-artifact.
We were needlessly uploading programs before, so remove those instances, and otherwise, use v4 everywhere.
> ci: Update to upload / download artifact v4

- token/cli/tests/command.rs
- token/client/src/token.rs
- token/program-2022-test/tests/transfer_hook.rs
- token/program-2022/src/offchain.rs
- token/program-2022/src/onchain.rs
Per #7059 
Adds a new offchain helper `offchain::create_transfer_checked_with_fee_instruction_with_extra_metas`.
Adds a new onchain helper `onchain::invoke_transfer_checked_with_fee`
Adds logic to `transfer_with_fee` in token/client/src/token.rs to add the extra-account-metas using the offchain helper if the token uses the transfer-hook extension.
> [token-cli] Add support for transfer-hook account resolution for transfers with the transfer-fee extension.

- account-compression/sdk/package.json
- libraries/type-length-value/js/package.json
- memo/js/package.json
- name-service/js/package.json
- pnpm-lock.yaml
- single-pool/js/packages/classic/package.json
- single-pool/js/packages/modern/package.json
- stake-pool/js/package.json
- token-group/js/package.json
- token-lending/js/package.json
- token-metadata/js/package.json
- token-swap/js/package.json
- token/js/package.json
The latest ESLint plugin bump from dependabot broke CI for JavaScript jobs.
Revert it.
Closes #7259
> Revert ESLint plugin bump

- .github/workflows/pull-request-js.yml
As outlined in #7259, we aren't testing JavaScript PRs against all versions of Node.js that the packages are documented to support. 
Add relevant Node.js versions to the `pull-request-js.yml` matrix.
> CI: add matrix for node versions to JS PRs

- token/confidential-transfer/proof-extraction/src/burn.rs
- token/confidential-transfer/proof-extraction/src/encryption.rs
- token/confidential-transfer/proof-extraction/src/lib.rs
- token/confidential-transfer/proof-extraction/src/mint.rs
- token/confidential-transfer/proof-generation/src/burn.rs
- token/confidential-transfer/proof-generation/src/encryption.rs
- token/confidential-transfer/proof-generation/src/lib.rs
- token/confidential-transfer/proof-generation/src/mint.rs
- token/confidential-transfer/proof-tests/tests/proof_test.rs
There are no proof generation and verification logic for the new confidential mint and burn extension (https://github.com/solana-labs/solana-program-library/issues/6879).
Added the proof generation and verification (context extraction) logic for the confidential mint and burn logic. There is already a community PR (https://github.com/solana-labs/solana-program-library/pull/6881) that adds the extension on the program side. This PR just adds the confidential mint and burn zkp logic in the new confidential transfer submodules.
The description of the zkp can be found in https://github.com/solana-labs/solana-program-library/issues/6879, but we basically need the following components:
- The confidential burn zkp is essentially the same as that of a confidential transfer. We need the following …
> [confidential-transfer] Add confidential burn proof generation and extraction

- ci/do-audit.sh
Similar to https://github.com/anza-xyz/agave/pull/3052, we need to ignore the RUSTSEC advisory on tonic until it's resolved upstream.
Ignore the tonic advisory.
> ci: Add tonic to audit ignore

- stake-pool/js/src/index.ts
Necessary to load individual StakePools by their pubkey (possibly across different stake pool program deployments) and decode.
> [@solana/spl-stake-pool] export the StakePoolLayout

- stake-pool/js/package.json
The 1.1.6 publish didn't work for some reason.
Bump to 1.1.7 and do it again
> stake-pool-js: Bump to 1.1.7

- ci/cliff.toml
git-cliff has deprecated the `commit.github` field available during parsing, opting for `commit.remote` instead.
Use `commit.remote` instead of `commit.github`.
> CI: Use `commit.remote` in git-cliff

- Cargo.lock
- libraries/concurrent-merkle-tree/Cargo.toml
- libraries/merkle-tree-reference/Cargo.toml
Reverts solana-labs/solana-program-library#7356 so that CI still passes for https://github.com/anza-xyz/agave/actions/runs/11372664282/job/31637497171
> Revert "Set patch version to only use solana-program <2"

- .github/workflows/pull-request-js.yml
- libraries/type-length-value/js/README.md
- libraries/type-length-value/js/package.json
- libraries/type-length-value/js/src/splDiscriminate.ts
- libraries/type-length-value/js/test/splDiscriminate.test.ts
- pnpm-lock.yaml
This is a breaking change which _removes_ the need for browsers to introduce a polyfill for `createHash`. Engines now have a built-in `SubtleCrypto#digest` which serves this purpose, polyfill-free, with [good support](https://caniuse.com/mdn-api_subtlecrypto_digest).
The reason this is a breaking change is that `createHash` is synchronous and `SubtleCrypto#digest` is async.
Related to #7351.
> Use the SHA-256 implementation built into JavaScript engines

- .github/workflows/pull-request-js.yml
- pnpm-lock.yaml
- stake-pool/js/package.json
- token-group/js/package.json
- token-group/js/src/instruction.ts
- token-group/js/test/instruction.test.ts
- token-lending/js/package.json
- token-metadata/js/package.json
- token-metadata/js/src/instruction.ts
- token-metadata/js/test/instruction.test.ts
- token-swap/js/package.json
- token/js/package.json
1. There is no need to compute these well-known values at runtime
2. Adding insult to injury, computing them requires a SHA-256 _polyfill_ for browsers
Resolves #7351.
> Hardcode the discriminators so that you don't have to compute them at runtime

- .github/workflows/pull-request-libraries.yml
- .github/workflows/pull-request-token-group.yml
- .github/workflows/pull-request-token-metadata.yml
The token-group and token-metadata JS packages now require at least Node v19, but the specific workflows only use v16.
Update the CI job to v20.
> CI: Update token-group and token-metadata JS jobs to Node 20

- account-compression/programs/account-compression/Cargo.toml
- Expose `idl-build` feature to work properly with other anchor crates
> Release v0.4.2 with idl-build feature

- docs/src/token.mdx
It's unclear that SPL Token's multisigs allow for duplicate signers.
Call out the behavior of duplicate signers in a multisig.
> docs: Specify behavior for dupes in token multisig

- .github/workflows/publish-rust.yml
The release step in CI is failing because the latest cargo-release requires Rust 1.79, but this repo is still at 1.78.
Pin cargo-release to 0.25.11, which is compatible with 1.78, as noted in the failing run: https://github.com/solana-labs/solana-program-library/actions/runs/11523644623/job/32082450563
> CI: Pin version of cargo-release

- .github/workflows/publish-rust.yml
- .github/workflows/pull-request.yml
- libraries/discriminator/src/lib.rs
- libraries/pod/src/optional_keys.rs
- token-swap/program/src/constraints.rs
- token-swap/program/src/processor.rs
- token/program-2022/src/serialization.rs
- token/program-2022/tests/serialization.rs
Clippy isn't run with `--all-features`, and there are some pieces that are broken with all features enabled.
Add `--all-features` to clippy steps, and fix existing issues.
> CI: Update clippy to use `--all-features`, fix issues

- token/program-2022/src/extension/confidential_mint_burn/instruction.rs
The PR for the upgrade for v2.1 and confidential mint/burn went in at the same time, but there were some improper doc comments in the confidential mint/burn, which breaks the new clippy version used with v2.1.
Update the doc comments to unbreak master.
> CI: Fix clippy for confidential mint/burn

- .github/workflows/pull-request-js.yml
- libraries/type-length-value/js/package.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- single-pool/js/packages/classic/package.json
- single-pool/js/packages/modern/package.json
- token-group/js/package.json
- token-metadata/js/package.json
- token/js/package.json
`@solana/web3.js@2` has released rc.2, but the SPL JS libs don't use it.
Use it!
> js: Update libs from rc.1 to rc.2

- Cargo.lock
- libraries/pod/Cargo.toml
- libraries/pod/src/bytemuck.rs
- libraries/pod/src/error.rs
- libraries/pod/src/lib.rs
- libraries/pod/src/option.rs
- libraries/pod/src/optional_keys.rs
- libraries/pod/src/slice.rs
This required replacing `#[spl_program_error]` with inline impls. I think it is hard or perhaps impossible to decouple `spl-program-error` from `solana_program` without breaking changes.
For now there will still be an indirect solana-program dep via solana-zk-sdk
> remove solana-program from spl-pod

- Cargo.lock
- libraries/discriminator/Cargo.toml
- libraries/discriminator/src/discriminator.rs
- libraries/discriminator/src/lib.rs
This one's pretty simple, just had to update a few imports
> remove solana-program from spl-discriminator

- Cargo.lock
- token-metadata/interface/Cargo.toml
- token-metadata/interface/src/error.rs
- token-metadata/interface/src/instruction.rs
- token-metadata/interface/src/lib.rs
- token-metadata/interface/src/state.rs
Updated some imports and replaced spl-program-error with inlining
> remove solana-program from token-metadata-interface

- .github/workflows/pull-request.yml
It looks like the clippy CI step is running out of space on the build machine.
Use the purge script for the clippy step.
> CI: Purge ubuntu runner for clippy step

- Cargo.lock
- libraries/pod/Cargo.toml
- libraries/pod/src/option.rs
There's still a dev-dependency on solana-program in spl-pod, but it's only used for a hardcoded pubkey.
Use another hardcoded pubkey and remove the dev-dependency
> pod: remove solana-program from dev-dependencies

- .github/workflows/publish-rust.yml
The clippy step is running out space during the publish workflow.
Same as #7432, but for the publish workflow.
> CI: Purge runner during clippy step for publish

- Cargo.lock
- instruction-padding/program/Cargo.toml
- instruction-padding/program/src/entrypoint.rs
- instruction-padding/program/src/instruction.rs
- instruction-padding/program/src/lib.rs
- instruction-padding/program/src/processor.rs
The instruction-padding program still has an explicit dependency on solana-program, but it isn't needed.
Use the component crates instead. Some of the syscall consts aren't available yet outside of solana-program, but it was easy to add a static assertion for those.
The program build is _lightning fast_ with this!
> instruction-padding: Remove solana-program dependency

- token/cli/src/output.rs
The downstream job in https://github.com/anza-xyz/agave/pull/3431 is failing because of the new addition to the `UiExtension` enum.
We've done this before: temporarily add a wildcard pattern so that the downstream job passes.
> token-cli: Add unreachable pattern for future change

- token/cli/src/config.rs
It seems that we define `compute_unit_limit` argument in the clap app, but try to parse it as `compute_unit_price`.
Parse `compute_unit_limit` properly.
> [token-cli] Parse compute unit limit with the proper name

- .github/workflows/pull-request-account-compression.yml
- .github/workflows/pull-request-js.yml
- account-compression/Cargo.lock
- ci/js-test-account-compression.sh
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
CI is failing because the account-compression sdk was removed from the pnpm workspace, but the rest of the repo uses pnpm.
Add `account-compression/sdk` back into the workspace, and fix the CI job to install the correct version of the Solana tools.
> CI: Re-add account-compression sdk to build

- token/cli/src/bench.rs
- token/cli/src/clap_app.rs
- token/cli/src/command.rs
- token/cli/src/config.rs
The token-cli now uses clap-v3, but there are still some deprecated functions that should be removed (we ultimately want to remove `#![allow(deprecated)]` at the top of `clap_app.rs`). In particular, with clap-v3, input validation has been deprecated in favor of just parsing the inputs.
All of the occurrences of `Arg::validator` in the token-cli should be replaced with `Arg::value_parser`. Since there are many of these occurrences, I think these can be removed in a sequence of smaller PRs.
In this PR, I started removing validator functions related to numbers and amounts. I think the changes should be pretty straightforward:
[318244b](https://github.com/solana-labs/solana-program-library/pull/7448/commits/318244b40ac51450caaec6f227707757dde8e6c7): I started with removing validator …
> [token-cli] Remove `is_amount_or_all`, `is_amount`, and `is_parsable` validators

- token/cli/src/config.rs
As noticed with #7456, a transaction with a nonced blockhash fails to confirm even though it works.
This might be because of the confirmation logic in the RPC client, which looks for the provided blockhash:
https://github.com/anza-xyz/agave/blob/b46c87ea538a1508ed4ae36f8dbf6c75dd57c883/rpc-client/src/nonblocking/rpc_client.rs#L1090
Specify a default transaction confirmation timeout.
> token-cli: Add confirm-tx timeout to RPC client

- token/program-2022/src/extension/confidential_mint_burn/instruction.rs
In the confidential mint and burn extension, the vector of proof instructions are appended to the token instruction using the `extend_from_slice` method, which requires the underlying element type of the slice to implement the `Clone` trait. Though minimal, it is better to use the `extend` function that subsumes the input vector since `extend` does not require the underlying element type to be implement any trait.
This is relevant when building the token22 program for wasm target. The `Instruction` type implements `Clone` for non-wasm targets, but does not seem to implement it for wasm targets (https://github.com/anza-xyz/agave/blob/master/sdk/instruction/src/lib.rs#L108). 
Replace `extend_from_slice` with `extend`.
> [token22] Avoid the use of `extend_from_slice` when appending instructions

- stake-pool/program/Cargo.toml
The current spl-stake-pool crate doesn't always work due to its dependency on spl-math which still uses the v1 Solana crates.
Since the spl-math dependency wasn't actually needed, it was removed in #7421. So just to get a new patch release out, downgrade the local dependencies.
This will fail CI, but after it lands we can tag the release, and revert this PR.
cc @billythedummy
> stake-pool: Downgrade dependencies for fixed release

- Cargo.lock
- stake-pool/cli/Cargo.toml
- stake-pool/program/Cargo.toml
This reverts commit d4c250f34ab2b3ce9717c587da80fe20366ca605.
See #7509 for more info.
Reverts the commit, but still keeps the crate version at 2.0.1
> Revert "stake-pool: Downgrade dependencies for fixed release (#7509)"

- token/client/src/token.rs
- token/program-2022-test/tests/scaled_ui_amount.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/scaled_ui_amount/instruction.rs
- token/program-2022/src/extension/scaled_ui_amount/mod.rs
- token/program-2022/src/extension/scaled_ui_amount/processor.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/pod_instruction.rs
- token/program-2022/src/processor.rs
The interest-bearing extension is useful for tokens that accrue in value constantly, but many "rebasing" tokens on other blockchains employ a different method of updating the number of tokens in accounts.
Rather than setting a rate and allowing the number to change automatically over time, they set a scaling factor for the tokens by hand.
Add a new `ScaledUiAmount` extension to token-2022 for doing just that. This is essentially a simplified version of the interest-bearing extension, where someone just sets a scaling value into the mint directly. The scale has no impact on the operation of the token, just on the output of `amount_to_ui_amount` and `ui_amount_to_amount`.
cc @jnwng
> token-2022: Add scaled amount extension

- Cargo.lock
There's a security advisory on rustls 0.23.16, and it advises to update to 0.23.18.
Bump the dependency to 0.23.18
> deps: Bump rustls to 0.23.18

- token/cli/src/config.rs
In clap v2, the `ArgMatches::is_present(ARG_NAME)` function returns `None` when `ARG_NAME` is not defined in the clap app. In clap v3, `ArgMatches::is_present(ARG_NAME)` panics of `ARG_NAME` is not defined in the clap app.
I thought I fixed all occurrences of `is_present` that could panic in the token-cli, but it seems that I missed one place when we parse for `Config`.
```
`sign_only` is not an id of an argument or a group.
Make sure you're using the name of the argument itself and not the name of short or long flags.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Replace `is_present` with `try_contains_id` that does not panic.
> [token-cli] Fix panicking behavior from `sign_only`

- token/js/src/actions/createAssociatedTokenAccountIdempotent.ts
This add `allowOwnerOffCurve` parameter to `createAssociatedTokenAccountIdempotent`.  
The `createAssociatedTokenAccount` action has an option to allow off curve owner, but not in `createAssociatedTokenAccountIdempotent`.
> add allowOwnerOffCurve parameter to createAssociatedTokenAccountIdempotent

- Cargo.lock
Hashbrown has a security advisory on v0.15.0:
https://rustsec.org/advisories/RUSTSEC-2024-0402
Bump to 0.15.1
> deps: Update hashbrown to 0.15.1

- token/program-2022/src/extension/interest_bearing_mint/mod.rs
- token/program-2022/src/extension/scaled_ui_amount/mod.rs
- token/program-2022/src/lib.rs
The interest-bearing and scaled UI amount extensions don't take into account the mint decimals when printing the number, and they don't properly trim afterwards. This can be confusing.
Update the UI amount conversion to take into account the decimals of precision, and then actually trim. Note that a lot of calculations become more precise because of this change!
> token-2022: Take decimals into account for UI amount

- token/client/src/token.rs
- token/program-2022-test/tests/confidential_transfer.rs
- token/program-2022-test/tests/pausable.rs
- token/program-2022/src/error.rs
- token/program-2022/src/extension/confidential_mint_burn/processor.rs
- token/program-2022/src/extension/confidential_transfer/instruction.rs
- token/program-2022/src/extension/confidential_transfer/processor.rs
- token/program-2022/src/extension/mod.rs
- token/program-2022/src/extension/pausable/instruction.rs
- token/program-2022/src/extension/pausable/mod.rs
- token/program-2022/src/extension/pausable/processor.rs
- token/program-2022/src/instruction.rs
- token/program-2022/src/pod_instruction.rs
- token/program-2022/src/processor.rs
Users want a more Ethereum-style token experience by being able to "pause" their token, similar to the "Pausable" interface. When a mint is paused, tokens cannot be minted, burned, or transferred.
Add the extension and some tests. It covers the following interactions:
* mint / mint-checked
* burn / burn-checked
* transfer / transfer-checked / transfer-with-fee
* confidential transfer / confidential transfer with fee
* confidential mint / confidential burn
* confidential deposit / confidential withdraw
Unfortunately, the confidential mint / burn extension doesn't have testing, so I couldn't get a full end-to-end test for it.
Also note that it's still possible to:
* move withheld tokens
* initialize token accounts
* close token accounts
* set authority
* freeze / thaw
* approve / revoke
* …
> token-2022: Add Pausable extension

- token/confidential-transfer/proof-generation/src/mint.rs
- token/confidential-transfer/proof-tests/tests/proof_test.rs
- token/program-2022/src/extension/confidential_mint_burn/account_info.rs
The confidential mint/burn extension and the confidential transfer extension have some inconsistent ways of generating proofs from account data.
[6b073ce](https://github.com/solana-labs/solana-program-library/pull/7575/commits/6b073ce08bdf6b6bd00e6d0ac4ec041aeca13969): All proof data types (`TransferProofData`, `TransferWithFeeProofData`, `BurnProofData`, ...) just contains the proof components while the `MintProofData` contains the new decryptable supply component. The decryptable supply ciphertext could be generated together with the proofs, but I think it is slightly more natural to generate it separately from account data like in the other confidential transfer instructions. In this commit, I removed the decryptable supply component from `MintProofData`. Sorry I should have noticed …
> [program-2022] Add functions to generate mint/burn proofs from account info

- token/cli/src/config.rs
`spl-token` CLI doesn't respect the `commitment` field of Solana config when creating the RPC client.
See https://github.com/solana-labs/solana-program-library/issues/7590 for more details.
Use the `confirmation` field from the Solana config when creating the RPC client.
**Note:** This won't affect any users (unless they've overridden the `commitment` field) because [`confirmed` is already the default commitment of Solana config](https://github.com/anza-xyz/agave/blob/9e59baae79570628163d95a169e40f11b1db5109/cli-config/src/config.rs#L88).
Resolves https://github.com/solana-labs/solana-program-library/issues/7590
> token-cli: Use the `commitment` field from Solana config
