solana-labs/solana-program-library

README.md

Add reference to Sealevel

---

token/src/cli/main.js
token/src/cli/token-test.js
token/src/client/token.js
token/src/program/Cargo.lock
token/src/program/src/state.rs

Added a `Burn` instruction
fixes: #11

Add incinerator

---

.gitignore
.travis.yml
ci/memo.sh
ci/token.sh
do.sh
memo/src/lib.rs
memo/src/processor.rs
package-lock.json
token/Cargo.lock
token/js/package.json
token/src/error.rs
token/src/instruction.rs
token/src/lib.rs
token/src/processor.rs
token/src/state.rs

- Documents
- Move Token's `Instruction` into its own file

Add rustdocs

---

bpf-sdk-install.sh
token/Cargo.lock
token/js/cli/token-test.js
token/js/client/token.js
token/js/client/util/new-account-with-lamports.js
token/js/client/util/send-and-confirm-transaction.js
token/js/package-lock.json
token/js/package.json

Fixes: https://github.com/solana-labs/solana-program-library/issues/21

Bump to Solana v1.2.3 and Solana-web3.js v0.60.0

---

token/src/instruction.rs
token/src/state.rs

Add helpers to create token instructions

Add instruction helpers

---

token-swap/inc/token-swap.h
token-swap/src/lib.rs

No reason fee members should be private.

Make fee members public

---

.gitignore
token-swap/.gitignore
token/.gitignore

Consolidate .gitignore

---

memo/Cargo.lock
memo/Cargo.toml
memo/src/processor.rs
token-swap/Cargo.lock
token-swap/Cargo.toml
token-swap/src/error.rs
token-swap/src/state.rs
token/Cargo.lock
token/Cargo.toml
token/inc/token.h
token/src/error.rs
token/src/state.rs

This allows https://github.com/solana-labs/solana/pull/11015 to build

Bump solana-sdk to 1.2.10

---

token/js/cli/main.js
token/js/cli/token-test.js

Fix CloseAccount js test

---

memo/Cargo.lock
memo/Cargo.toml
token-swap/Cargo.lock
token/Cargo.lock
token/Cargo.toml
token/inc/token.h

This is just a bump to be able to use memo and token as dependencies in https://github.com/solana-labs/solana/pull/11136

Bump patch versions

---

.gitignore
docs/package-lock.json

Missing package-lock.json for docs build environment

Add package-lock.json

---

docs/siteConfig.js
docs/static/css/code-block-buttons.css
docs/static/js/code-block-buttons.js

Add copy code block buttons to docs
Sourced from here: https://gist.github.com/yangshun/55db997ed0f8f4e6527571fc3bee4675

Add copy code block button support to docs

---

token/src/lib.rs
token/src/native_mint.rs

@CriesofCarrots - you _might_ find these useful in RPC

spl-token: Add ui amount conversion helpers

---

docs/src/token.md
token/cli/README.md

First pass of basic info and example usage

Add spl-token command-line documentation

---

token/program/src/instruction.rs

SPL Token's instruction data fields are padded out to the largest, aligned variant (24bytes).  This results in superfluous wire bytes and implementation signing ambiguities
Truncate instructions to their `pack()`'d size
Add packing test

Truncate SPL Token instruction data field

---

do.sh

I want to do from the `token/program2/` directory

Allow `../../do.sh build .`

---

token/program/src/error.rs
token/program/src/instruction.rs
token/program/src/processor.rs

Fixes https://github.com/solana-labs/solana-program-library/issues/333

token: InitializeMint's mint authority is no longer optional

---

token/program/inc/token.h
token/program/src/error.rs
token/program/src/instruction.rs
token/program/src/processor.rs
token/program/src/state.rs

Toward #328 
Separately: restore total_supply to Mint, and adjust on burns
Toward #303 
Separately: require valid Mint exist on InitializeAccount

token: Require that Account, Mint, and Multisig be rent exempt

---

token/program/src/processor.rs

The wrapped-SOL lamport credits/debits should be covered by the runtime, but I updated them to follow the checked-match commandment anyway.
Fixes #344

Use checked math everywhere

---

Cargo.lock
token-swap/program/src/processor.rs
token/cli/src/main.rs
token/program/Cargo.toml
token/program/src/instruction.rs
token/program/src/lib.rs
token/program/src/option.rs
token/program/src/pack.rs
token/program/src/processor.rs
token/program/src/state.rs

Get rid of the scary-looking unsafe code.  This new code at least triples the number of instructions required but will make auditors a lot more happy

Safer pack/unpack

---

token-swap/program/src/processor.rs
token/program/src/pack.rs
token/program/src/processor.rs

There are cases where the token program only needed to unpack to read data but is instead also repacking that unchanged data
- Don't repack if we don't need to
- Ensure that pack function check initialization
- Cleanup the pack trait by encapsulating stray functions
- Fix some token-swap rot

Don't repack if not needed

---

token/js/client/token.js

isInitialized is set to false when the account is frozen

[token-js] Fix isInitialized when account is frozen

---

token/cli/src/main.rs

Token CLI only support keypair file signers.  I want to on-chain-test the Ledger app.
Support arbitrary signers like Solana CLI

Token CLI: Support arbitrary signers

---

bpf-sdk-install.sh
ci/script.sh
do.sh
token-swap/js/cli/token-swap-test.js
token-swap/js/client/token-swap.js
token-swap/js/package-lock.json
token-swap/js/package.json
token-swap/program/src/entrypoint.rs
token-swap/program/src/instruction.rs
token-swap/program/src/processor.rs
token-swap/program/src/state.rs

* Change generation of program address to use a nonce
* Accept nonce properly in initialization
* Include nonce in TokenSwap structure
* Fixup serialization with new parameter (padding used for now)
* Update dependencies

Fix token-swap tests

---

token-swap/js/cli/token-swap-test.js
token-swap/js/client/token-swap.js
token-swap/program/src/instruction.rs
token-swap/program/src/processor.rs

* Refactor tests for easier composibility
* Add deposit instruction and test
* Deposit JS test works again

Fix deposit instruction

---

token/js/client/token.js

Rebase on solana-web3 bump

---

token/cli/src/main.rs

Sometimes you just want to BYO address

token-cli: create-token/create-account now accept an optional keypair

---

token/cli/src/main.rs

SingleGossip has stronger guarantees than Single.
cc: @carllin

token-cli: Use SingleGossip commitment

---

token/cli/src/main.rs
token/program/src/instruction.rs
token/program/src/processor.rs

Rename x2 instructions to xChecked

---

Cargo.lock
token/cli/Cargo.toml
token/cli/src/main.rs

Accommodate solana_sdk::fee_calculator change
Fixes #520

Bump spl-token-cli, and solana versions

---

token/cli/src/main.rs

Add approve, revoke subcommands

---

token/cli/src/main.rs

Add close subcommand

---

do.sh

Fixes `npm run build:program` scripts

Allow ../../do.sh build <program>

---

.travis/install-program-deps.sh
ci/script.sh
do.sh

- Program dumping has been neglected, fix it
- Depends on `gread`, depend on `readelf` instead
- CI does not check `dump`, add it

Fix program dump

---

Cargo.lock
token-swap/js/cli/token-swap-test.js
token-swap/js/client/token-swap.js
token-swap/js/client/util/account.js
token-swap/js/module.d.ts
token-swap/js/module.flow.js
token-swap/program/src/processor.rs
token-swap/program/src/state.rs

Pass TokenSwap state into the constructor to simplify function calls

---

do.sh

Also:
1. `../../do.sh dump .` now works
2. Fixed indent issues 
3. Removed duplicate so name derivation code
4. Renamed `${so_name}_debug` to  `${so_name}_unstripped`

./do.sh dump now helps the user when they don't have the right tools installed

---

docs/src/token.md

Fixes https://github.com/solana-labs/solana-program-library/issues/628

token docs: Add JSON RPC methods section

---

token/js/client/token.js
token/js/module.d.ts
token/js/module.flow.js

Hard to discover what the currently deployed SPL Token program id is in the JS SDK

Export token program id in JS sdk

---

.travis.yml
.travis/install-program-deps.sh

Preparing for https://github.com/solana-labs/solana-program-library/pull/698

Install solana cli tools in CI

---

token/program-v3/src/instruction.rs
token/program/src/instruction.rs

reformat token instruction comments

---

token/cli/src/main.rs

Review tip: One commit at a time

token-cli: Support offline signing and durable nonces

---

docs/src/token.md

Related to: https://github.com/solana-labs/solana-program-library/issues/722

Document self-transfer behavior

---

docs/src/token.md

Document another known issue.
sibling: #743

Document about the known fake rent issue

---

token-swap/program/src/instruction.rs
token-swap/program/src/state.rs
token/cli/src/main.rs
token/program-v3/src/instruction.rs
token/program/src/instruction.rs

Quick fix for the lints in #764

Clippy suggestions

---

.github/workflows/pull-request.yml
.mergify.yml

Let's see if this gets merged in automatically once all of the CI is passed!

Add more checks to mergify due to GitHub Actions migration

---

associated-token-account/program/program-id.md
associated-token-account/program/src/lib.rs
associated-token-account/program/src/processor.rs
associated-token-account/program/tests/functional.rs

* improve code comments
* add better program logging
* add program-id.md

associated-token-account refinements

---

stake-pool/program/src/instruction.rs
stake-pool/program/src/processor.rs

Positive tests for:
- withdraw
- claim
- set staking authority
- set owner
Fixed bugs when forming claim and set owner instructions.

Added positive tests in stake pool and fixed several bugs in instructions

---

docs/src/token.md

Docs contain no examples demonstrating SPL Token multisig usage
Add some

Docs: Add Token multisig examples

---

token-swap/js/module.d.ts
token-swap/js/module.flow.js

This changeset fixes some inconsistencies between the type definitions and the actual class.

Fix type definitions for TokenSwap class

---

ci/cargo-build-test.sh
examples/c/makefile
examples/c/src/cross-program-invocation/cross-program-invocation.c
examples/c/src/custom-heap/custom-heap.c
examples/c/src/custom-heap/test_custom-heap.c
examples/c/src/logging/logging.c
examples/c/src/logging/test_logging.c
examples/c/src/transfer-lamports/test_transfer-lamports.c
examples/c/src/transfer-lamports/transfer-lamports.c

Add C examples
Testing is limited to none due to lack of any meaningful full framework

Add c examples

---

Cargo.lock
shared-memory/program/Cargo.toml
themis/client_ristretto/Cargo.toml
token/perf-monitor/Cargo.toml

Pulls in overflow/underflow fixes

Bump rbpf to v0.1.33, use semver

---

.github/workflows/pull-request.yml
token/cli/src/main.rs

cc: https://github.com/solana-labs/solana/pull/13699
Fixes #872

spl-token-cli: Avoid RpcClient::get_account() in some cases

---

shared-memory/program/tests/shared-memory.rs
themis/client_ristretto/tests/assert_instruction_count.rs
token/perf-monitor/tests/assert_instruction_count.rs

Apply new clippy suggestion in shared-memory test

Clippy cleanup

---

feature-proposal/cli/src/main.rs

`spl-feature-proposal-cli` generates a csv for token distribution. `solana-tokens` expects the recipients in that csv to be unique. However, currently validator addresses associated with multiple vote accounts will create duplicate lines (one for each vote account).
Combine vote account duplicates into one record.

Combine vote account duplicates associated with the same validator id

---

stake-pool/cli/src/main.rs
stake-pool/program/src/lib.rs
stake-pool/program/src/processor.rs

Now if there is not enough funds on the single stake account CLI will withdraw from several and then join them into one single account.

Multi-account withdraw added the stake-pool CLI

---

token-swap/program/src/curve/stable.rs

The stable swap test to go through all numbers and compare to the Python impl doesn't cover the space as effectively as a proptest does, so this converts the math test to be a proptest instead.

token-swap: Add proptest for stable swap intead of all numbers

---

ci/solana-version.sh

Bump CI solana CLI version to v1.4.16

---

token-lending/program/src/processor.rs
token-lending/program/tests/borrow.rs

Fees are subtracted from `collateral_deposit_amount` before depositing the collateral into the reserve. Later, fees are paid from the reserve which causes the actual collateral deposited to be slightly less than it should.
- Perform collateral deposit and fee payment from the user account
- Add test

lending: Fix fee collection for borrows

---

examples/rust/sysvar/src/processor.rs
examples/rust/sysvar/tests/functional.rs

Developer requested that `Rent` be added to the sysvar example

Add rent to sysvar example

---

token-lending/program/src/processor.rs
token-lending/program/src/state/obligation.rs
token-lending/program/src/state/reserve.rs

When loans default (collateral is fully withdrawn with an outstanding balance), the remaining borrow amount is not taken into account in the reserve collateral calculations. When loans default, collateral tokens should lose value, but currently, the end result is a situation where the reserve thinks there's still liquidity that will be paid back and so will not allow full redemption of outstanding collateral tokens.
- After an obligation is liquidated and defaults, subtract the default amount from the repay reserve

lending: Handle the lost funds from defaulted loans

---

docs/src/associated-token-account.md
docs/src/token.md

Fixes a couple typos in spl docs; also hard-wraps some lines.

Fix doc typos

---

token/program/src/instruction.rs
token/program/src/processor.rs

Token's `InitializeAccount` instruction takes its `owner` value in the accounts list, even though only the `Pubkey` is required.  This puts a burden on instructions that call it via CPI to do the same.
Adds an `InitializeAccount2` instruction that takes the `owner`'s `Pubkey` as transaction data
fixes #843

token: Add InitializeAccount2 instruction

---

Cargo.lock
Cargo.toml
themis/client_ristretto/Cargo.toml
themis/program_ristretto/Cargo.toml

I rewrote history in a dependency. Update to the latest.
cc: @t-nelson

Unbreak build

---

token/cli/src/main.rs

`spl-token transfer` rejects a transfer to an unfunded system account by default for the sender's safety.  Adding `--allow-empty-recipient` will now override this check.

spl-token cli: Add --allow-empty-recipient to `transfer` command

---

token-lending/program/src/processor.rs
token-lending/program/tests/init_lending_market.rs

- Bump seed is not set in market init
- Incorrect owner is set for reserve creator's collateral token

lending: fix market and reserve initialization

---

stake-pool/cli/src/main.rs
stake-pool/program/src/processor.rs

* Stake split was passing the wrong accounts: fix that.
* Withdraw tokens were passing lamports instead of pool tokens: fix that.

stake-pool: Fix stake split and withdraw token calculation

---

token/cli/src/main.rs

Upstream solana is slated to deprecate the TokenAmount::ui_amount `f64`. In the short term, this field will become an `Option<f64>`, which breaks several spots in the spl-token cli that call this field directly.
Replace these usages with forward-compatible ones to prepare for the change.

spl-token-cli: Use forward-compatible apis

---

Cargo.lock
token/cli/Cargo.toml

Bump token-cli in preparation for publication

Bump token-cli to v2.0.7

---

docs/src/token.md

Revert outdated part of https://github.com/solana-labs/solana-program-library/pull/753

Remove outdated comment

---

token-swap/proposals/DynamicMarketMaking.md
token-swap/proposals/ProactiveMarketMaking.md

* Dynamic market making curve that leverages serum dex v3
* Proactive Market Making

Future proposals for token-swap program

---

stake-pool/cli/src/main.rs

Per feedback on the stake pool docs `burn` is a bit of a scary word for withdrawals, so change the name of the param.

stake-pool-cli: Rename burn -> withdraw

---

token/cli/src/main.rs

Supports the short `-u` url arg, as well as adds parsing for public-cluster monikers

Token cli: Enable short arg, monikers

---

docs/src/stake-pool.md

People need to know how to use stake pools!
Add a guide to the different instructions and examples of how to use them in the CLI.  The program is currently deployed on testnet at `poo1B9L9nR3CrcaziKVYVpRX6A9Y1LAXYasjjfCbApj`, so people can start playing with stake pools.

stake-pool: Add usage docs

---

token/cli/src/main.rs

The `create-account` always signs with the `owner` argument when present but this should not be done when creating associated token accounts.
```
cargo run -- create-account 2Sb43Jm4akvYK3S1EdFCqu31vcZN71tDFQWUwdV33xPh \
--fee-payer ~/.config/solana/2nr1bHFT86W9tGnyvmYW4vcHKsQB3sVQfnddasz4kExM.json \
--owner ~/.config/solana/9ufAiSyboCZmmEsoStgLYQfnx9KfqP1ZtDK8Wr1j8SJV.json
```
Error (with logging)
```
Creating account DUuwmeM5JZaTfTP97pWTnJZAcu1rHm1VFjgGQMz5xgBP
fee payer: Some(2nr1bHFT86W9tGnyvmYW4vcHKsQB3sVQfnddasz4kExM)
signer: 9ufAiSyboCZmmEsoStgLYQfnx9KfqP1ZtDK8Wr1j8SJV
signer: 2nr1bHFT86W9tGnyvmYW4vcHKsQB3sVQfnddasz4kExM
keypair-pubkey mismatch
```

token-cli: Don't sign with owner when creating an associated token account

---

token/cli/src/main.rs

Align `spl-token` with https://github.com/solana-labs/solana/pull/16060
`--allow-empty-recipient` is retained as a hidden arg for backwards compatibility.

token/cli: Rename --allow-empty-recipient to --allow-unfunded-recipient

---

token/cli/src/main.rs

No functional change. Just re-ordering to make it easier to verify updates across App, arg-parsing, and command method.

spl-token cli: Reorder App subcommands

---

token/cli/src/main.rs

Users offering solana/wallet support need a way quickly determine the associated token address for a given account and mint for debugging. This PR adds the `spl-token address` command to meet this need.
In accordance with the ATA model, which encourages wallets to hide the token holding address from the end user, this command returns the main wallet address (`--owner`), unless the `--token` and `-v` args are provided.
If these args are provided, the cli confirms the `--token` is a valid mint, and provides the owner's associated token address as well. Examples below.
Fixes  #1430
Using config owner:
```
$ spl-token address
Wallet address: Bbqg1M4YVVfbhEzwA9SpC9FhsaG83YMTYoR4a8oTDLX
```
Cluster connection required to verify mint validity:
```
$ spl-token address --token …
```

Add spl-token address command

---

token/cli/src/main.rs

If a user submits the command `spl-token accounts <ADDRESS>` using a non-mint address, they receive this error:
`RPC request error: Failed to deserialize RPC error response: {"code":-32602,"message":"Invalid param: could not find mint"} [missing field `data`]`
This is confusing, especially if you are under the mistaken assumption that address arg should specify a specific token owner.
Instead, check the mint before calling `get_token_accounts_by_owner` and use a more helpful error message.
Fixes #762

spl-token cli: accounts, check mint if provided

---

token/cli/src/main.rs

Currently, `spl transfer` lacks `--no-wait` while `solana transfer` has it. This lack of feature-parity is causing some trouble for partners.
Implement it. The code is shamelessly copied from the `solana` code for the strict same behavior, implementation and documentation.

Add spl-token transfer --no-wait

---

stake-pool/cli/src/main.rs

Using a stake pool with `solana-test-validator --slots-per-epoch 32` is super annoying because you need to run `spl-stake-pool update` every 15 seconds.  Instead detect and automatically update the pool by default

Automatically update the stake pool if needed, use the `--no-update` flag to disable

---

stake-pool/cli/src/main.rs

Don't use `Config` when `RpcClient` will do

stake-pool-cli: Minor config -> rpc_client refactor

---

token/js/README.md

Add basic release docs

---

stake-pool/cli/src/main.rs
stake-pool/program/src/processor.rs
stake-pool/program/src/state.rs
stake-pool/program/tests/vsa_add.rs

Remove obnoxious comments.  `validator_account` is not a thing, it's a `vote_account`

stake-pool: Code cleanup v2

---

token-swap/program/src/constraints.rs

Token swap currently allows only for a fixed set of fee constraints. For some pools, 25bps is too high.
Production constraints are considered minimum fees charged. Specifically `trade_fee_numerator` is now set to `0` to allow protocol users to customize how high fees for the given pool should be. Note: minimum owner fee remains at 5bps of that host can claim up to 1bps

token-swap: Adjust fee constraints

---

stake-pool/cli/src/main.rs
stake-pool/program/src/instruction.rs
stake-pool/program/tests/decrease.rs
stake-pool/program/tests/helpers/mod.rs
stake-pool/program/tests/increase.rs

The new instructions to increase / decrease validator stakes in the pool aren't in the CLI.
Add them in!

stake-pool-cli: Add increase / decrease validator stake

---

token/cli/src/main.rs

`spl-token transfer` is overconstrained in offline mode, disallowing ATA creation
Trust the args

token-cli: Fix ATA creation in offline mode

---

stake-pool/program/src/processor.rs
stake-pool/program/tests/withdraw.rs

With the reserve stake account, stakers get flexibility to move stake between validators.  Since stake pool users can only withdraw from active validator stakes up to a certain amount, if a malicious and / or delinquent staker decreases the stake from all of the validators, there's no way for people to get their SOL back.
Allow users to withdraw from the reserve stake account, but *only* if there are no other options available, meaning that all of the validator stake accounts have no withdrawable lamports left.  The error message will specify a possible valid option if someone tries to withdraw from the reserve, but there's still some possible lamports.
Fixes #1500

stake-pool: Add ability to withdraw from reserve if no stake available

---

docs/src/token.md

Fixes https://github.com/solana-labs/solana/issues/16839

docs: specify mint in spl-token balance examples

---

name-service/program/program-id.md
name-service/program/src/entrypoint.rs
name-service/program/src/error.rs
name-service/program/src/instruction.rs
name-service/program/src/lib.rs
name-service/program/src/processor.rs
name-service/program/src/state.rs

Also sneak in some minor code clean up.
cc: @Lcchy

Add name-service program id: `namesLPneVptA9Z5rqUDD9tMTWEJwofgaYwp8cawRkX`

---

docs/src/stake-pool.md

The stake pool program changed a lot, but the docs did not.  Bring them up to speed!
The updated output here is all based on the changes in #1650.

stake-pool: Update docs for all new features

---

docs/src/token.md

Add a section about the SPL token vesting contract

docs: add token vesting section

---

token/cli/Cargo.toml
token/cli/src/main.rs

Opening to fix rebasing/squashing issue from last PR https://github.com/solana-labs/solana-program-library/pull/1708

implement the ability to leave a memo on token creation

---

name-service/README.md
name-service/js/.eslintrc.json
name-service/js/README.md
name-service/js/package-lock.json
name-service/js/package.json
name-service/js/src/bindings.ts
name-service/js/src/index.ts
name-service/js/src/instructions.ts
name-service/js/src/state.ts
name-service/js/src/test.ts
name-service/js/src/twitter.ts
name-service/js/src/utils.ts
name-service/js/yarn.lock

* Update ID
* Update web3.js
* Switch to borsh from @bonfida/borsh-js
* Lint
* Spelling

Name Service JavaScript cleanup

---

stake-pool/cli/src/client.rs

cc: #https://github.com/solana-labs/solana/pull/17399

Add forward compatibility with solana-client 1.6.10

---

token-swap/program/Cargo.toml
token-swap/program/fuzz/src/instructions.rs
token-swap/program/src/curve/stable.rs

Only the constant product curve is fuzzed at the moment
Fuzz every curve instead!

token-swap: Fuzz all curves

---

examples/rust/sysvar/src/processor.rs

Show how to use the new sysvar `::get()` methods

Update sysvar example

---

docs/src/token.md

Someone was asking about a token registry, and the docs don't mention the token-list.
Mention it!

token-docs: add token registry

---

stake-pool/program/src/instruction.rs

Writability of the validator list during update stake pool balance was not documented.
Document it!
Fixes #1863

stake-pool: Document writability of validator list

---

stake-pool/program/src/processor.rs

Ownership checks for the stake pool accounts are performed implicitly through mutability of owned accounts.
Add explicit ownership checks in case we change something in the future.
Fixes #1864

stake-pool: Add explicit ownership checks

---

docs/src/stake-pool.md

This is needed for the program to work

Also clone program data for stake pool test-validator

---

stake-pool/cli/README.md
stake-pool/cli/scripts/deposit-withdraw.sh
stake-pool/cli/scripts/setup-local.sh
stake-pool/cli/scripts/setup-stake-pool.sh

Stake pools are complicated to setup.
Add some helper scripts to make it easier, and some extra documentation for how to use them.

stake-pool: Add helper scripts for setting up a pool

---

docs/src/token.md

spl-token docs: Create NFT token with 0 decimal place

---

Cargo.lock
stake-pool/cli/Cargo.toml
stake-pool/cli/src/main.rs

* Fix signer parameters (staker, manager, depositor, fee-payer, and
token-owner)
* On deposit / withdraw / add / remove validator, show the validator
stake account and where the stake is going to

stake-pool-cli: Address feedback

---

token/js/.eslintignore
token/js/examples/create_mint_and_transfer_tokens.js

created examples directory and example of how to mint and transfer spl tokens

chore: examples directory with mint transfer example

---

token/program/src/processor.rs

When setting a new account owner, the close authority is not cleared for native accounts.
Clear it.

token: Clear close authority for native accounts

---

Cargo.lock
associated-token-account/program/Cargo.toml
binary-oracle-pair/program/Cargo.toml
feature-proposal/program/Cargo.toml
governance/program/Cargo.toml
stake-pool/cli/Cargo.toml
stake-pool/program/Cargo.toml
token-swap/program/Cargo.toml
token-swap/program/fuzz/Cargo.toml
token/cli/Cargo.toml
token/program/Cargo.toml

Bump spl-token version to 3.2.0 in preparation for the release.

token: Bump version to 3.2.0 everywhere

---

token/cli/src/config.rs

`spl-token-cli` can't handle authorities being specified as an address rather than a signer path.  This is required for specifying multisig authorities.
Allow `NullSigner`s to be returned if there are instances of `--multisig-signer` on the commandline

token-cli: fix resolving multisig authorities

---

token-swap/js/package.json

token-swap-js: Bump version for release

---

token-swap/js/package-lock.json
token-swap/js/package.json

The tokens-wap package.json isn't referencing the correct files
Reference those files!
cc @Arrowana

token-swap-js: Update package.json to use real files

---

docs/src/stake-pool.md

@c3pko How does this look? regarding your comment https://github.com/solana-labs/solana-program-library/pull/2125#pullrequestreview-714375264

stake-pool docs: Clarify withdrawal

---

Cargo.lock
governance/program/Cargo.toml
governance/program/src/error.rs
governance/program/src/processor/process_create_account_governance.rs
governance/program/src/processor/process_create_mint_governance.rs
governance/program/src/processor/process_create_program_governance.rs
governance/program/src/processor/process_create_token_governance.rs
governance/program/src/state/token_owner_record.rs
governance/program/tests/process_create_account_governance.rs
governance/program/tests/process_create_proposal.rs

Implements asserts for token amount required to crate governances within a realm

Governance: Assert tokens to create governance

---

token/js/module.d.ts
token/js/module.flow.js

Fix typescript definitions for https://github.com/solana-labs/solana-program-library/pull/1802

token: fix ts for @solana/spl-token

---

Cargo.lock
stake-pool/program/Cargo.toml
stake-pool/program/src/error.rs
stake-pool/program/src/processor.rs
stake-pool/program/src/state.rs
stake-pool/program/tests/withdraw.rs

Because of rounding, it may be possible in the future, as stake pool tokens become very valuable, to leech value from the pool through deposit / withdrawal.
Fixup fee calculation, and also correct a divide by 0 error.
Closes #2103

stake-pool: Make it impossible to leech value

---

stake-pool/program/src/state.rs

Fixes #2237
When the withdraw calculation was updated to use `checked_ceil_div`, it wasn't updated for proper bounds checking, especially for withdrawals that result in 0 pool tokens.  It was returning `None` instead of `0`, tripping up the proptests on some inputs.
Properly check for 0 results beforehand, and add a test

stake-pool: Fix zero withdraw calculation

---

.gitignore
Cargo.lock
governance/program/Cargo.toml
governance/program/src/error.rs
governance/program/src/instruction.rs
governance/program/src/processor/process_cancel_proposal.rs
governance/program/src/processor/process_cast_vote.rs
governance/program/src/processor/process_create_proposal.rs
governance/program/src/processor/process_deposit_governing_tokens.rs
governance/program/src/processor/process_finalize_vote.rs
governance/program/src/processor/process_withdraw_governing_tokens.rs
governance/program/src/state/proposal.rs
governance/program/src/state/token_owner_record.rs
governance/program/tests/process_cancel_proposal.rs
governance/program/tests/process_cast_vote.rs
governance/program/tests/process_create_proposal.rs
governance/program/tests/process_execute_instruction.rs
governance/program/tests/process_finalize_vote.rs
governance/program/tests/process_remove_instruction.rs
governance/program/tests/process_withdraw_governing_tokens.rs
governance/program/tests/program_test/mod.rs

Limit the number of outstanding proposal per token owner

Governance: Constrain active proposals

---

governance/README.md
governance/program/src/instruction.rs
governance/program/src/processor/process_create_program_governance.rs
governance/program/src/state/proposal.rs
governance/program/src/state/realm.rs

- Readme has been updated to de-emphasise program updates as the primary function of the `governance` program and creation of DAOs has been emphasised instead. 
- nit updates from retrospective reviews of past PRs.

Governance:  Readme DAO update

---

stake-pool/program/src/processor.rs
stake-pool/program/tests/set_withdrawal_fee.rs

Fixes: https://github.com/solana-labs/solana-program-library/issues/2263

stake-pool: Update fee changes only once per epoch

---

stake-pool/cli/src/main.rs
stake-pool/program/src/instruction.rs
stake-pool/program/src/processor.rs
stake-pool/program/tests/set_manager.rs

Closes #2265 
~~Pending confirmation on whether to do the same for `SetStaker`~~
@jon-chuang

fix: stake-pool require signature in SetManager

---

stake-pool/program/src/processor.rs

Fixes: https://github.com/solana-labs/solana-program-library/issues/2267

stake-pool: Check that initialized accounts are distinct

---

token/js/module.d.ts

chore(token): expose transfer checked instruction

---

stake-pool/cli/src/client.rs
stake-pool/cli/src/main.rs

No way to fetch all stake pools.
Add it in!

stake-pool-cli: Add `list-all` instruction

---

binary-oracle-pair/program/src/processor.rs

Added a mint check to the Withdraw function (#2061)

---

stake-pool/cli/src/main.rs
stake-pool/program/src/error.rs
stake-pool/program/src/instruction.rs
stake-pool/program/src/lib.rs
stake-pool/program/src/processor.rs
stake-pool/program/src/state.rs
stake-pool/program/tests/decrease.rs
stake-pool/program/tests/deposit.rs
stake-pool/program/tests/helpers/mod.rs
stake-pool/program/tests/huge_pool.rs
stake-pool/program/tests/increase.rs
stake-pool/program/tests/set_preferred.rs
stake-pool/program/tests/update_validator_list_balance.rs
stake-pool/program/tests/vsa_add.rs
stake-pool/program/tests/vsa_remove.rs
stake-pool/program/tests/withdraw.rs

Stake pools don't use a configurable seed for transient stake accounts.
Use a configurable seed!
cc @jon-chuang

stake-pool: Add seed for transient stake account

---

Cargo.lock
token/cli/Cargo.toml
token/cli/src/bench.rs
token/cli/src/main.rs
token/cli/src/rpc_client_utils.rs

Improve user output and transaction retry logic

spl-token-cli: Groom send_and_confirm_messages_with_spinner

---

token/cli/src/rpc_client_utils.rs

Since `TpuClient` fans out transactions to the leaders of the next 12 slots it's not really necessary to re-transmit transactions every 500ms

spl-token-cli bench: Slow down retransmission of transactions

---

token/js/examples/create_mint_and_transfer_tokens.js

Use const instead of let / var without any readon

Fix example codestyle

---

token/cli/src/rpc_client_utils.rs

1. Slow down RPC requests slightly
2. Indicate to the user when TPU or RPC is being used as the transmission method
3. Hide current block height during times when it's not being updated to avoid user (me) confusion

spl-token-cli bench: Adjust send_and_confirm_messages_with_spinner() to work better with public mainnet RPC

---

token/cli/src/rpc_client_utils.rs

Thanks @jon, this is way better

token-cli: Use status.satisfies_commitment

---

token/cli/src/rpc_client_utils.rs

Bring https://github.com/solana-labs/stake-o-matic/pull/171 over

spl-token-cli: Always check transaction statuses before resending

---

Anchor.toml
Cargo.lock
governance/program/Cargo.toml
governance/program/src/state/token_owner_record.rs

increase outstanding proposals per user to 10
made a verifiable build using anchor 16.1
```
sha256sum target/verifiable/spl_governance.so
a88382feaeb56a95157dbbe6e5677d21ae8e5d9cd83df7ffc1c4778f9f497a2f  target/verifiable/spl_governance.so
```

spl_governance v1.1.1

---

docs/src/stake-pool.md
stake-pool/cli/src/main.rs

Stake pool docs are out of date.
Update them!  This mainly adds sections about:
* fees
* liquid staking
* 0.001 SOL minimum for validator accounts
* Rust docs
* easy-add validator

stake-pool: Update docs and help messages

---

token/cli/src/config.rs
token/cli/src/main.rs

BEFORE:
```
$ spl-token -ul transfer --owner 7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j --allow-unfunded-recipient So11111111111111111111111111111111111111112 0 Bu2JLKrt83azq5hUAVouT4RsxgrN2ocYrbfx3fL2vrbg --sign-only --blockhash $(head -c 32 /dev/urandom | base58) --mint-decimals 9 --dump-transaction-message
Blockhash: 4KoUVKPhR8kBma6cQP9i17kSoJWDr1Mvm96QHbzgbLcT
Absent Signers (Pubkey):
7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j
```
AFTER:
```
$ spl-token -ul transfer --owner 7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j --allow-unfunded-recipient So11111111111111111111111111111111111111112 0 Bu2JLKrt83azq5hUAVouT4RsxgrN2ocYrbfx3fL2vrbg --sign-only --blockhash $(head -c 32 /dev/urandom | base58) --mint-decimals 9 --dump-transaction-message
Blockhash: …
```

Really plumb dump_transaction_message

---

Cargo.lock
stake-pool/cli/Cargo.toml
stake-pool/program/Cargo.toml

It's time to release the new stake pool program + crates, so let's bump the version!

stake-pool: Bump version for 0.6.0 release

---

governance/chat/program/tests/program_test/mod.rs
governance/program/src/instruction.rs
governance/program/src/processor/mod.rs
governance/program/src/processor/process_deposit_governing_tokens.rs
governance/program/src/tools/spl_token.rs
governance/program/tests/process_deposit_governing_tokens.rs
governance/program/tests/program_test/mod.rs

Make amount explicit on `Deposit` instruction to support smaller governance tokens deposits

Governance: Add deposit amount

---

examples/rust/transfer-lamports/src/processor.rs

fix: typo in comments

---

Cargo.lock
stake-pool/cli/Cargo.toml
stake-pool/program/Cargo.toml

In preparation for crate + program release

stake-pool: Bump CLI and program version to 0.6.3

---

token-swap/program/src/curve/stable.rs

`A` in the stable curve is actually `A * n ** (n-1)`, but it's not documented anywhere.
Refactor the calculation to add a comment.

token-swap: Add comment for stable curve A calculation

---

token/cli/src/main.rs

Fix typo in main.rs

---

token-swap/program/src/processor.rs

Certain curves forbid deposits otherwise it creates a potential rug pull opportunity.  Unfortunately, a single token deposit can still go through.
Forbid single token deposit if the curve doesn't support deposits.

token-swap: Prevent single deposits for curves that don't allow it

---

token/cli/src/bench.rs
token/cli/src/main.rs
token/cli/src/output.rs

spl-token: provide more useful output when using create-token with the output option and small redesign of token cli architecture

---

token/program/src/state.rs

I was confused when reading this comment and had to read the code to realize that the comment isn't a typo. 
(Btw, let me know if this kind of small changes are helpful or not 👍.)

Update comment on state.rs regarding is_native

---

docs/src/token.md

Added another solution for SPL token vesting, with additional customizations, after the review by @joncinque. :)

docs: token: Added timelock program

---

token-swap/js/package-lock.json
token-swap/js/package.json
token-swap/js/src/buffer-layout.d.ts
token-swap/js/src/index.ts
token-swap/js/src/layout.ts

token-swap: Migrate to `@solana/buffer-layout`

---

stake-pool/cli/src/client.rs
stake-pool/cli/src/main.rs
stake-pool/py/tests/conftest.py
stake-pool/py/tests/test_deposit_withdraw_stake.py

Certain clients may need to automate depositing a lot of stake accounts into a stake pool.
Add `deposit-all-stake`, which takes in a stake pool and a stake authority pubkey.  It fetches all stake accounts for which that pubkey is the stake authority, and then attempts to deposit each of those into the stake pool.  This follows how stake-o-matic fetches all of the stake accounts under consideration.
Currently, the command will fail if a stake account is delegated to a validator not present in the stake pool.  We can relax this if needed.
Sample usage + output:
```
$ spl-stake-pool --funding-authority usb://ledger deposit-all-stake Zg5YBPAk8RqBR9kaLLSoN5C8Uv7nErBz1WC63HTsCPR GiSf1rz49mUzfg9t2f6YHapkiWgxE3UvxRdLe1uZLYfz --withdraw-authority usb://ledger
Signature: …
```

stake-pool-cli: Add `deposit-all-stake` command

---

farms/farm-sdk/src/program/account.rs

Fix typo in account.rs

---

docs/src/stake-pool/quickstart.md
stake-pool/cli/scripts/setup-stake-pool.sh
stake-pool/program/tests/huge_pool.rs
stake-pool/py/stake_pool/actions.py

Certain memory operations will become more expensive, which affects the maximum possible stake pool.
Lower the maximum from 3950 to 3825.
cc @jackcmay

stake-pool: Reduce maximum pool size

---

memo/program/src/lib.rs

Hi,
I want to add some tests to have a better code coverage.
Best regards,
Michal

add test for memo

---

token-swap/program/sim/Cargo.toml
token-swap/program/sim/src/lib.rs

[token-swap] Upgrade PyO3 from 0.12.3 to 0.15.1

---

token/program/src/state.rs

Hi,
This PR adds some tests for token program.
Best regards,
Michal

token tests p1

---

coverage.sh
libraries/math/src/error.rs
libraries/math/src/instruction.rs

Hi,
This PR adds more libraries tests.
Best regards,
Michal

libraries tests p2

---

coverage.sh
libraries/math/src/precise_number.rs
libraries/math/src/processor.rs

Hi,
This PR adds some tests for libraries.
Best regards,
Michal

libraries tests p1

---

docs/src/token.md

for Streamflow Timelock. :)
@joncinque

docs: token: Added missing information about security audit

---

binary-option/client/binary_option.py

fix: typo in binary_option.py

---

token/program-2022/src/processor.rs

`validate_owner` borrows the owner account info for processing multisigs, which can lead to a double-borrow if the owner account info is the same as the underlying account info, and the underlying account's data is mutably borrowed.
Add a self-ownership check.  Note that `validate_owner` is only ever used to validate the ownership of a `Mint` or `Account`, since `Multisig`s don't have an owner.
When working with extensions, we will often need to validate the owner after deserialization of the base, and if it's self-owned, we will blow up every time.

token: Check self-ownership in `validate_owner`

---

token-lending/program/src/instruction.rs

Hi,
This PR adds some tests to token lending.
Best regards,
Michal

token lending tests p1

---

Cargo.lock
binary-oracle-pair/program/Cargo.toml
feature-proposal/program/Cargo.toml
governance/chat/program/Cargo.toml
governance/program/Cargo.toml
governance/test-sdk/Cargo.toml
governance/tools/Cargo.toml
governance/voter-weight-addin/program/Cargo.toml
stake-pool/cli/Cargo.toml
stake-pool/program/Cargo.toml
stateless-asks/program/Cargo.toml
token-lending/flash_loan_receiver/Cargo.toml
token-swap/program/Cargo.toml
token-swap/program/fuzz/Cargo.toml
token/cli/Cargo.toml
token/program/Cargo.toml

New token program was released, but not the corresponding creates.
Bump the version number to release the crates.

token: Bump version to 3.3.0

---

Cargo.lock
associated-token-account/program/Cargo.toml
associated-token-account/program/src/lib.rs

Restore rent sysvar to create_associated_token_account

---

token/program-2022/src/error.rs
token/program-2022/src/extension/transfer_fee/processor.rs
token/program-2022/src/processor.rs
token/program-2022/tests/initialize_mint.rs
token/program-2022/tests/mint_close_authority.rs
token/program-2022/tests/program_test.rs
token/program-2022/tests/transfer_fee.rs
token/rust/src/token.rs

The transfer fee config authority needs to be able to set the transfer fee.
Add the implementation and tests for it

token-2022: Implement set transfer fee instruction

---

token/program-2022/src/entrypoint.rs
token/program-2022/src/error.rs
token/program-2022/src/instruction.rs
token/program-2022/src/native_mint.rs
token/program-2022/src/processor.rs
token/program-2022/src/state.rs

Nothing to see here. Purely stylistic changes to legacy token files for consistency.

token-2022: fixup use-statement style

---

Cargo.lock
associated-token-account/program/Cargo.toml

This reverts commit 533f76756319ef945fd137f1bb560769c45a9893.
To be merged after ATA v1.0.5 is published
cc @joncinque

Revert "Revert ATA to spl-token v3.3 (#2796)"

---

associated-token-account/program/src/lib.rs
associated-token-account/program/src/processor.rs
associated-token-account/program/src/tools/account.rs
associated-token-account/program/tests/extended_mint.rs
associated-token-account/program/tests/program_test.rs

Handle extended token Accounts in ATA program

---

token/program-2022/src/extension/mod.rs

In working on the MemoTransfer extension, I found I needed an api to determine if reallocation was needed. Might be useful for confidental transfers as well.
Thoughts?

token-2022: add extension realloc helper

---

governance/chat/program/tests/program_test/mod.rs

Are tests being run differently on monorepo downstream build or are y'all merging on red?

fix monorepo downstream build tests

---

associated-token-account/program/src/instruction.rs
associated-token-account/program/src/processor.rs
associated-token-account/program/tests/process_create_associated_token_account.rs
associated-token-account/program/tests/program_test.rs

Nothing to see here, just formatting changes in ATA

ATA: single use statements

---

token/program-2022/src/extension/transfer_fee/processor.rs
token/program-2022/tests/transfer_fee.rs

Fees need to be collected from the mint as they're harvested.
Add the capability.
Note: this builds on #2848, only the second commit is needed.
Also note: there are a few TODO tests in the transfer fee, and I'll add those with `withdraw_withheld_tokens_from_accounts`

token-2022: Add transfer fee withdrawal from mint

---

Cargo.lock
governance/chat/program/Cargo.toml
governance/chat/program/src/state.rs
governance/program/src/instruction.rs
governance/program/src/state/governance.rs
governance/program/src/state/legacy.rs
governance/program/src/state/realm.rs
governance/tools/src/account.rs

- Use exhaustive account type checks
- Fix `RealmV1` deserialisation

Governance V2 cleanup

---

token-swap/program/fuzz/src/instructions.rs
token-swap/program/src/constraints.rs
token-swap/program/src/curve/base.rs
token-swap/program/src/instruction.rs
token-swap/program/src/processor.rs
token-swap/program/src/state.rs

token-swap: Changed Wrap SwapCurve's calculator field into Arc instead of Box

---

token/cli/src/main.rs

Fixes https://github.com/solana-labs/solana/issues/22933

spl-token-cli: Freezing -> Thawing

---

token/program-2022/tests/transfer.rs

Nothing to see here really, just copying the current program-tests for `transfer` to work also with extensions.
We need a set of basic transfer tests that also work with extensions, to make sure that the pack / unpacking bits are done correctly.
Refactor the transfer tests to add more tests with extensions.

token-2022: Add transfer tests with extension

---

token/program-2022/src/processor.rs
token/program-2022/tests/burn.rs
token/rust/src/token.rs

`burn` doesn't work with extensions
Support it, and add some tests

token-2022: Support extensions in burn

---

token/js/README.md

Fixing Readme of token

---

token/js/package.json

token/js: shifted dotenv to dev dependancies

---

governance/program/src/state/proposal_transaction.rs

Governance: fix typo in proposal_transaction.rs

---

Cargo.lock
token/program-2022/Cargo.toml
token/program-2022/src/error.rs
token/program-2022/src/extension/confidential_transfer/instruction.rs
token/program-2022/src/extension/confidential_transfer/mod.rs
token/program-2022/src/extension/confidential_transfer/processor.rs
token/program-2022/src/processor.rs

Adding fee for confidential transfers. Will need to update `WithdrawWithheld` instructions in a separate pr.

token-2022: add fee for confidential extension

---

stake-pool/cli/src/main.rs

`````rust
if lamports <= min_balance {
continue;
}
let available_for_withdrawal_wo_fee =
stake_pool.calc_pool_tokens_for_deposit(lamports).unwrap();
`````
available_for_withdrawal_wo_fee dont consider min_balance
@joncinque

stake_pool: fix wrong available_for_withdrawal_wo_fee calculation

---

token/program-2022/src/processor.rs
token/program/src/processor.rs

Initialized close_authority explicitly in both token/program and token/program-2022
Closes #707

Initialize Account close_authority explicitly

---

token/program-2022/src/extension/confidential_transfer/mod.rs
token/program-2022/src/extension/confidential_transfer/processor.rs

Minor renaming of pod variables with more descriptive type names.

token-2022: minor rename pod types with descriptive types

---

Cargo.lock
farms/farm-rpc/Cargo.lock
token-lending/flash_loan_receiver/Cargo.lock

Bump regex to v1.5.5

---

token-swap/program/src/curve/stable.rs

Fix typo remove_liquidty -> remove_liquidity

Fix typo in token-swap/program/src/curve/stable.rs

---

docs/src/token.mdx

docs: Fixed Token JS Bindings broken link

---

token/js/src/extensions/extensionType.ts
token/js/src/extensions/immutableOwner.ts
token/js/src/extensions/index.ts
token/js/src/instructions/index.ts
token/js/src/instructions/initializeImmutableOwner.ts
token/js/test/e2e-2022/immutableOwner.test.ts

Javascript extension for the Token 2022 InitializeImmutableOwner Instruction

InitializeImmutableOwner Instruction

---

governance/chat/program/tests/program_test/mod.rs
governance/program/src/processor/process_create_proposal.rs
governance/program/src/state/enums.rs
governance/program/src/state/governance.rs
governance/program/src/state/legacy.rs
governance/program/src/state/proposal.rs
governance/program/tests/process_cast_vote.rs
governance/program/tests/process_create_governance.rs
governance/program/tests/process_finalize_vote.rs
governance/program/tests/process_set_governance_config.rs
governance/program/tests/program_test/mod.rs
governance/program/tests/use_proposals_with_multiple_options.rs

Maintenance change for separating community and  council vote threshold

Rename vote_threshold_percentage to community_vote_threshold

---

token/client/src/token.rs

Extending token client to support withdrawing of confidential withheld tokens from fees.

token-2022: client for confidential withdraw withheld tokens

---

token-swap/js/package-lock.json
token-swap/js/package.json

People want updated dependencies in token-swap-js.
Update those dependencies!
cc @JamesMDunn

token-swap-js: Bump buffer-layout and web3.js

---

token-swap/js/package-lock.json
token-swap/js/package.json

@JamesMDunn wants a new version of token-swap-js.
Bump the version for the release!

token-swap-js: Bump package version for release

---

README.md

Fixes: #3219 
Added clearer build instructions and pre-requisites for setting up the development environment for this library. Also provided fixes or help links to common issues one might run into.

Documentation on environment setup

---

Cargo.lock
token/cli/Cargo.toml
token/cli/src/main.rs

Fixes #2598 
Added Enums for Command Names and replaced hard coded command names
@joncinque

spl-token: Enums for Cli command names

---

token/js/README.md
token/js/package.json

The token-js instructions for building / testing / running don't include anything about building the required programs.
Add a `test:build-programs` step and documentation about it.
cc @kunaljaydesai

token-js: Clarify how to run tests

---

token-swap/program/src/curve/stable.rs

As found during this proptest run: https://github.com/solana-labs/solana-program-library/runs/7289001263 -- it's possible to fail a valid stable swap because you'd *close* to draining one side.  This is due to `checked_ceil_div` being overly conservative for constant product divisions.
Stable swap divisions aren't exactly the same, and sometimes a result of `1` is valid, but not allowed by `checked_ceil_div`.  To get around this, Do some special casing during the approximation for the new destination amount.

token-swap: Allow for huge swaps that almost entirely drain one side

---

token-swap/js/package.json

[issues](https://github.com/solana-labs/solana-program-library/issues/3363)

token-swap-js: change .mjs to .js

---

Cargo.lock
token/cli/Cargo.toml
token/cli/src/main.rs

This PR resolves #367 by adding tests for transferring and burning tokens when delegated to another account.

Add delegation tests

---

token/program-2022/src/instruction.rs
token/program/src/instruction.rs

Needs version bump to v3.4.0 first

Prep for spl-token v3.5.0

---

governance/README.md
governance/program/src/state/legacy.rs

https://github.com/solana-labs/solana-program-library/blob/3d3b32dcf6b64bfe609600735d067ebe735ed36d/governance/program/src/state/proposal_transaction.rs#L100-L101

fix reference to the field hold_up_time in the governance README

---

docs/src/token.mdx

Rename e to tokenAccount / error as appropriate

---

token/js/FAQ.md
token/js/README.md
token/js/package.json

We've got loads of new functionality in the spl-token JS package, but it's not published!
Bump the version, and improve the README with some more info for people upgrading from 0.1.x and 0.2.0

token-js: Version bump to 0.3.0

---

token/js/src/state/account.ts
token/js/src/state/mint.ts

token-js: expose unpack methods

---

token/cli/src/config.rs
token/cli/src/main.rs

token-cli: dont push duplicates to bulk_signers

---

memo/js/package-lock.json
memo/js/package.json
token/js/package-lock.json
token/js/package.json

Fixes https://github.com/solana-labs/solana-program-library/issues/3522

spl-token: fix CJS imports

---

token/cli/src/main.rs

resolves #3406 
i used `handle_tx` for `command_set_interest_rate` because i was getting a trait bound error trying to pass an `Arc<dyn Signer>` into the token client's `update_interest_rate`
not super happy with how i handled the two params for `--interest-bearing <RATE_AUTHORITY> <RATE_BPS>` - i made the former optional by checking if it was "NONE" because i couldn't find a way to do this natively in clap

token-cli: Support the `InterestBearingMint` extension

---

docs/src/token-2022/onchain.md

Seems like this is a minor typo in the docs.

[docs] Token-2022 On-chain Program Guide minor typo 

---

token/cli/src/main.rs

remembered while working on something else that none of the `program_id` fetch logic does anything, because inference happens when `Config` is created and any mismatch will hard error anyway. ie, nothing in this pr changes any behavior
note that `get_mint_info` is a `Token` method rather than a `Config` method, and thus doesnt go through `get_account_checked`, but _does_ error on a `program_id` mismatch itself too

token-cli: remove unnecessary program_id logic

---

token/cli/src/main.rs
token/cli/src/output.rs
token/cli/src/sort.rs

token-cli: add `spl-token display`

---

account-compression/sdk/package.json
account-compression/sdk/src/index.ts
account-compression/sdk/src/instructions/index.ts
account-compression/sdk/src/utils/index.ts
account-compression/sdk/tests/accountCompression.test.ts
account-compression/sdk/tsconfig.base.json
account-compression/sdk/tsconfig.cjs.json
account-compression/sdk/tsconfig.json
account-compression/sdk/yarn.lock

Tested that this release of the SPL Account Compression package can be imported & used in a node js setting.
How do I test this package more generally (ie in the browser)?

SPL Account Compression JS Package

---

token/cli/src/main.rs

didnt wanna put this in the original pr in case it messed up the author getting full credit for the squash commit

token-cli: remove unnecessary fetch for memo transfers

---

governance/NOTES.md

just an .MD file with knowledge that can make it easier for new developers to contribute

Governance: add notes to ease collaboration

---

Cargo.lock
token/cli/src/main.rs
token/client/Cargo.toml
token/client/src/token.rs

token-cli: support immutable owner extension

---

governance/program/tests/program_test/mod.rs

Seems like I missed `with_upgrade_program_transaction()`, which is very similar to `with_governed_program()`, in #3637.

#3637 for `with_upgrade_program_transaction()`

---

token/program-2022/src/error.rs
token/program/src/error.rs

Fix a small typo for the uninitialized ...

chore: typos in error message

---

token/client/src/token.rs
token/client/tests/program-test.rs
token/program-2022-test/tests/burn.rs
token/program-2022-test/tests/confidential_transfer.rs
token/program-2022-test/tests/default_account_state.rs
token/program-2022-test/tests/delegate.rs
token/program-2022-test/tests/freeze.rs
token/program-2022-test/tests/interest_bearing_mint.rs
token/program-2022-test/tests/memo_transfer.rs
token/program-2022-test/tests/mint_close_authority.rs
token/program-2022-test/tests/non_transferable.rs
token/program-2022-test/tests/reallocate.rs
token/program-2022-test/tests/transfer.rs
token/program-2022-test/tests/transfer_fee.rs

sorry about this terrible review
~rebase after #3669 lands~

token-client: remove useless temp vecs

---

account-compression/programs/account-compression/Cargo.toml
account-compression/programs/account-compression/src/lib.rs
account-compression/programs/account-compression/src/noop/mod.rs

* Rename `Wrapper` -> `SplNoop`
* Rename Account pubkey from `log_wrapper` to `noop`

Account Compression: Rename Wrapper to Noop

---

token/js/examples/createMintAndTransferTokens.ts
token/js/examples/createMintCloseAuthority.ts
token/js/examples/defaultAccountState.ts
token/js/examples/immutableOwner.ts
token/js/examples/interestBearing.ts
token/js/examples/memoTransfer.ts
token/js/examples/nonTransferable.ts
token/js/examples/reallocate.ts
token/js/examples/transferFee.ts

[token-js]: new overload of confirm tx in examples

---

token/program-2022/src/extension/mod.rs

The `get_extension` function indexes the TLV data, which could potentially cause an index out-of-range error. This PR fixes this issue.
This PR addresses issue #3700.

[token-2022] Fix potential panic from short data length

---

token/program-2022/src/extension/mod.rs

If extension data is malformed, we can return some false positives in `get_extension_types`.
Check step by step if it's possible to deserialize the TLV data properly, and return an error if not.
Fixes #3695

token-2022: Return errors for malformed extension data

---

token/cli/src/main.rs

check if the user needs to provide a memo
dont let the user create ata accounts belonging to other token-owned accounts
closes #3711

token-cli: more better errors in command_transfer

---

token/program-2022/src/extension/confidential_transfer/processor.rs

For confidential transfers, the instruction processor must check whether a destination account is configured to receive funds:
- `allow_balancd_credits` is set to `true`
- `pending_balance_credit_counter` does not surpass the `maximum_pending_balance_credit_counter`
These conditions are not checked for`WithdrawWithheldTokensFromMint` and `WithdrawWithheldTokensFromAccounts` instructions.
Add these checks.

[token-2022] Add destination confidential account test for withdraw withheld instructions [ZELLIC-3.5]

---

account-compression/sdk/package.json

Bump Typescript SDK version before publish

Account Compression: Bump typescript SDK version to 0.1.3

---

token/cli/src/main.rs

part of #3771. will do js and docs in separate prs. displaying in the cli requires me to pr the solana account decoder
edit: aaand the solana account decoder pr would require a new token-2022 release, so thats not happening for a bit...
tentative plan is after permanent delegate is merged too, we figure out if/when the confidential stuff will be in a good state for a release, then we release token program/client/cli all together. and then i can update the account decoder for both extensions, then update the cli to display them and release that again just itself

token-cli: support cpi guard enable/disable

---

account-compression/sdk/README.md
account-compression/sdk/package.json

Add pointer to https://solana-labs.github.io/solana-program-library/account-compression/sdk/docs/

Account Compression: add docs link for account compression

---

token/client/src/token.rs
token/program-2022/src/extension/confidential_transfer/instruction.rs
token/program-2022/src/extension/confidential_transfer/processor.rs

Currently, when a confidential token account is initialized, the ElGamal pubkey is not fully checked to be valid. The pubkey is checked to be a valid curve25519 point, but it is not checked whether the owner knows a valid private key corresponding to the public key. Technically, this should be fine and the Fiat-Shamir heuristic should prevent rogue-key attacks. However, zk proof for pubkey validation is not too expensive and could be put in as an extra layer of security.
Add the pubkey validity check in the confidential extension `ConfigureAccount` instruction.

[token-2022] Require pubkey validity proof when initializing a confidential account [ZELLIC-3.7]

---

token/program-2022/Cargo.toml
token/program-2022/src/extension/confidential_transfer/processor.rs

Temporarily disabling fees to make breaking updates to the zk-token-sdk.

[confidential-extension] Temporarily disable fees

---

governance/program/src/processor/process_create_realm.rs
governance/program/src/processor/process_set_governance_config.rs
governance/program/src/processor/process_set_realm_config.rs
governance/program/src/processor/process_sign_off_proposal.rs
governance/program/src/state/realm.rs
governance/program/src/state/realm_config.rs
governance/program/src/state/token_owner_record.rs

Governance: Maintenance update

---

Cargo.lock
token-upgrade/cli/Cargo.toml
token-upgrade/program/Cargo.toml
token/cli/Cargo.toml
token/client/Cargo.toml
token/program-2022-test/Cargo.toml

i removed the patch version locking since really we shouldnt need it internal to the repo

bump token-cli to 2.2 and token-client to 0.3

---

token/js/src/extensions/extensionType.ts
token/js/src/extensions/index.ts
token/js/src/extensions/permanentDelegate.ts
token/js/src/instructions/index.ts
token/js/src/instructions/initializePermanentDelegate.ts
token/js/src/instructions/types.ts
token/js/test/e2e-2022/permanentDelegate.test.ts
token/js/test/unit/decode.test.ts
token/js/test/unit/index.test.ts
token/js/test/unit/programId.test.ts

fixes #3814  Js support for permanent delegate authority

token-js: Support for permanent delegate authority

---

token/cli/src/main.rs

token-cli: support for permanent delegate

---

stake-pool/program/tests/helpers/mod.rs
stake-pool/program/tests/huge_pool.rs

The current max pool size is capped at 3300 validators, but that's using the default 200k compute units. Using the compute budget instructions to request more compute units, we can support an even bigger maximum pool size!
No changes to the program, but add tests to the `huge_pool.rs` suite which sets the compute budget limit to 1.4M units and uses a much larger pool of 20k validators.
The test framework is pretty flaky on these even locally, maybe due to all of the required accounts, so in the interest of CI stability, this doesn't add the test-case to every test.
Individually though, these all pass with the 20k validator limit.

stake-pool: Test max pool size with max requested compute unit limit

---

stake-pool/program/tests/withdraw_edge_cases.rs

We're still getting failures in CI for stake pools.
Try to refresh the blockhash more often.

stake-pool: Keep trying to fix tests for CI

---

token/js/examples/cpiGuard.ts
token/js/src/extensions/cpiGuard/actions.ts
token/js/src/extensions/cpiGuard/index.ts
token/js/src/extensions/cpiGuard/instructions.ts
token/js/src/extensions/cpiGuard/state.ts
token/js/src/extensions/extensionType.ts
token/js/src/extensions/index.ts
token/js/src/extensions/memoTransfer/instructions.ts
token/js/src/extensions/memoTransfer/state.ts
token/js/src/instructions/types.ts
token/js/test/e2e-2022/cpiGuard.test.ts
token/js/test/unit/programId.test.ts

token-js: cpi guard

---

account-compression/programs/account-compression/Cargo.toml

Update dependency to anchor 0.26

Compression: bump version to 0.1.6 for release

---

token/program-2022/src/extension/confidential_transfer/processor.rs

When invoking syscall functions such as `ops::add(...)`, re-relabel `ops` to `syscall` for better readability and to emphasize that this is a syscall function.

[confidential-extension] Rename ops to syscall for better readability

---

token/js/src/extensions/extensionType.ts
token/js/test/e2e-2022/cpiGuard.test.ts
token/js/test/e2e-2022/tlv.test.ts
token/js/test/unit/index.test.ts

token-js: sanity check header space in tlv data

---

token/js/package-lock.json
token/js/package.json

It's been awhile since a token-js release, and we've had some nice changes, like #3967
Bump the version to prep for release

token-js: Bump version for release

---

account-compression/programs/account-compression/Cargo.toml
account-compression/sdk/package.json

Account Compression: bump versions

---

stake-pool/js/README.md
stake-pool/js/package.json
stake-pool/js/src/constants.ts
stake-pool/js/src/index.ts
stake-pool/js/src/instructions.ts
stake-pool/js/src/utils/program-address.ts
stake-pool/js/test/instructions.test.ts
stake-pool/js/test/mocks.ts

Hello here are the js-bindings for new stake-pool instructions
@joncinque

stake-pool: add redelegate js bindings

---

account-compression/Cargo.lock
account-compression/programs/account-compression/Cargo.toml

* New macros for applying functions to merkle trees
* Fixed issue with verifyLeaf instruction on merkle trees with canopy

Account Compression: bump rust version

---

docs/src/account-compression.md

Fix: typos

---

Anchor.toml

Add spl-governance-chat program to anchor config to support verifiable build

Governance: Add Chat to Anchor config

---

token/cli/src/main.rs

`Command::Authorize` in the token-cli does not yet support updating authorities associated with the transfer fee extension.
- Fill in the `umimplemented!()` parts to support updates to the transfer fee authorities (confidential extension authorities soon to follow!)
- Add tests for disabling transfer fee authorities for sanity

[token-2022, token-cli] Enable Command::Authorize to update transfer fee extension authorities

---

account-compression/sdk/package.json

Account Compression SDK: bump version

---

stake-pool/program/src/processor.rs

carrying over the love from #3974

stake pool: dont pass unnecessary program infos

---

account-compression/programs/account-compression/Cargo.toml

bump accoutn compression to 0.1.10

---

token-swap/js/package-lock.json
token-swap/js/package.json

#4148 kindly fixed the problem of importing types properly, but the fix is not available in npm.
Bump the package version to push to npm

token-swap: Bump JS package to pick up fix

---

docs/src/token-2022/status.md

The actual token-2022 program completion will likely take a couple more weeks.
Bump out the dates in the status page. Let me know if these dates look ok @samkim-crypto !

docs: Delay token-2022 status dates by one month as we finish

---

memo/js/package-lock.json
memo/js/package.json

#4149 fixed up type declarations, but hasn't been released
Bump version to 0.2.3 for release

memo-js: Bump version for release

---

.github/workflows/pull-request.yml

the audit task has a dependency resolution problem that i will now attempt to debug

fix cargo-audit task

---

stake-pool/single-pool/src/lib.rs
stake-pool/single-pool/src/processor.rs
stake-pool/single-pool/tests/accounts.rs
stake-pool/single-pool/tests/deposit.rs
stake-pool/single-pool/tests/helpers/mod.rs
stake-pool/single-pool/tests/update_pool_token_metadata.rs

ht to zellic. rebase after #4117 lands

single pool: authorized withdrawer fix

---

docs/src/token-2022/extensions.mdx

Minor grammatical issue in the first sentence of the "Non-Transferable Tokens" paragraph.

Fix grammar issue in the Non-Transferable Tokens section in extensions.mdx

---

.github/workflows/pull-request-stake-pool.yml
ci/warning/purge-ubuntu-runner.sh

The stake pool CI job is failing with "no space left on device".
Blast some unused directories and see if that helps!

ci: Clear unneeded runner dirs for stake pool job

---

token-metadata/interface/src/instruction.rs

https://github.com/solana-labs/solana-program-library/pull/4514/files#r1227330392 -- the comment for the `emit` instruction is incomplete.
Finish that comment!

token-metadata: Finish that comment!

---

token/cli/src/config.rs

`--config-file` -> `--config` and `--fee_payer` -> `--fee-payer`

token cli: correct signer/payer errors

---

ci/do-audit.sh

Suppress RUSTSEC-2023-0044 audit failure until SPL upgrades to Solana v1.16.2 or greater

---

.github/workflows/pull-request-token-metadata.yml
Cargo.lock
Cargo.toml
libraries/type-length-value/src/state.rs
token-metadata/example/Cargo.toml
token-metadata/example/src/entrypoint.rs
token-metadata/example/src/lib.rs
token-metadata/example/src/processor.rs
token-metadata/example/tests/emit.rs
token-metadata/example/tests/initialize.rs
token-metadata/example/tests/program_test.rs
token-metadata/example/tests/remove_key.rs
token-metadata/example/tests/update_authority.rs
token-metadata/example/tests/update_field.rs
token-metadata/interface/Cargo.toml
token-metadata/interface/src/error.rs
token-metadata/interface/src/instruction.rs
token-metadata/interface/src/lib.rs
token-metadata/interface/src/state.rs

#4514 introduced an interface for token-metadata programs, but there's no program that implements the interface.
Add that program! I ended up tweaking some bits of the interface while implementing this. Most of the PR is made up of tests, and I found the processor implementation to look quite neat with the right helpers. Fingers crossed that the token-2022 implementation will also go smoothly...
cc @austbot

token-metadata: Implement example program

---

stake-pool/single-pool/src/processor.rs

single-pool: support new 1.16 vote account

---

Cargo.lock
associated-token-account/program-test/Cargo.toml
associated-token-account/program/Cargo.toml
binary-option/program/Cargo.toml
binary-oracle-pair/program/Cargo.toml
examples/rust/transfer-tokens/Cargo.toml
feature-proposal/program/Cargo.toml
governance/addin-mock/program/Cargo.toml
governance/chat/program/Cargo.toml
governance/program/Cargo.toml
governance/test-sdk/Cargo.toml
governance/tools/Cargo.toml
stake-pool/cli/Cargo.toml
stake-pool/program/Cargo.toml
stake-pool/single-pool/Cargo.toml
stateless-asks/program/Cargo.toml
token-lending/cli/Cargo.toml
token-lending/flash_loan_receiver/Cargo.toml
token-lending/program/Cargo.toml
token-swap/program/Cargo.toml
token-swap/program/fuzz/Cargo.toml
token-upgrade/cli/Cargo.toml
token-upgrade/program/Cargo.toml
token/cli/Cargo.toml
token/client/Cargo.toml
token/program-2022/Cargo.toml
token/program/Cargo.toml

Bumped token & token CLI !
- `token` 4.0.0
- `token-cli` 3.0.0

bump token & co.

---

token/cli/src/main.rs

feat: cli subcommand for token metadata address extension

---

libraries/discriminator/README.md

Update README.md for `spl-discriminator`

---

account-compression/sdk/package.json

New feature added by @nickfrosty : #4658

Bump SPL Account Compression JS SDK version

---

token/js/test/e2e/create.test.ts

People are complaining that `getOrCreateAssociatedTokenAccount` doesn't work in #4718, but it seems to work.
Add a test to make sure that it does actually work!

token-js: Add test for `getOrCreateAssociatedTokenAccount`

---

docs/src/stake-pool/cli.md
docs/src/stake-pool/fees.md

There can still be some confusion about when stake pool fees are set and whether it's possible to rug people.
Make it clearer!

docs: Clarify stake pool fees more

---

libraries/tlv-account-resolution/src/account.rs
libraries/tlv-account-resolution/src/error.rs
libraries/tlv-account-resolution/src/state.rs
token/transfer-hook-example/src/processor.rs
token/transfer-hook-example/tests/functional.rs

This PR modifies the transfer hook example program to demonstrate use of PDAs as extra account configs
Ref #4942

Transfer Hook Example with PDAs

---

docs/src/token-2022.md
docs/src/token-2022/extensions.mdx

The metadata and metadata-pointer extensions have been in token-2022 for some time, but there's no way to know.
Add some text and examples about how to use them. This uses the flows from #5094.

docs: Explain the token-2022 metadata and pointer extensions

---

libraries/type-length-value/README.md

Updates the README for `spl-type-length-value` to reflect the addition of the "allow repetition" API.
Closes #5125

[type-length-value]: update README

---

account-compression/sdk/README.md

[Compression SDK]: Update docs link in README

---

token/program-2022-test/tests/transfer_fee.rs

Another fix for https://github.com/solana-labs/solana/pull/32767

Remove EpochSchedule Copy

---

.github/workflows/pull-request-feature-gate.yml

This PR adds the Feature Gate program to the SPL repository's CI.

feature gate: add to CI

---

account-compression/sdk/README.md
docs/src/feature-proposal.md
docs/src/single-pool.mdx
docs/src/stake-pool/overview.md
docs/src/stake-pool/quickstart.md

docs: Fix typos

---

token/program-2022-test/tests/token_metadata_remove_key.rs

The `success_remove` test for token metadata still fails randomly in CI, ie https://github.com/solana-labs/solana/actions/runs/6976357557/job/18984698009
Refresh the blockhash *twice* in the hope that it really takes effect this time. And use the token client rather than creating a transaction.

token-2022: Really get a new blockhash during test

---

token/cli/src/clap_app.rs
token/cli/src/command.rs
token/cli/tests/command.rs

This PR adds support for the group pointer in the Token CLI!

[token cli]: add support for group pointer

---

token/cli/src/clap_app.rs
token/cli/src/command.rs
token/cli/tests/command.rs

This PR adds support to the SPL Token CLI for Token Group Member Pointer!

[token cli]: add support for group member pointer

---

Cargo.lock
token/transfer-hook/cli/Cargo.toml

In step with #5970, bump the transfer hook CLI!

transfer hook cli: bump

---

account-compression/programs/noop/README.md
docs/README.md
docs/src/confidential-token/deep-dive/encryption.md
docs/src/token-2022/extensions.mdx
governance/NOTES.md
governance/README.md

I have made several typo corrections and improvements to the documentation in various sections of the Solana project. These changes aim to enhance clarity and readability. Here's a summary of the updates:
1. **Twisted ElGamal Encryption Section**: Corrected a typo to improve the sentence's clarity.
2. **Token-2022 Extensions**: Fixed a typo that involved a missing word, ensuring the sentence is complete and informative.
3. **SPL Noop Rust SDK Section**: Amended a grammatical issue to enhance the readability of the SDK documentation.
4. **Governance README**: Addressed several grammatical errors and a typo. These changes help in making the documentation more professional and easier to understand.
5. **Documentation's README and Governance UI**: Fixed typographical errors in the 'Governance …

Documentation Enhancements for Clarity and Accuracy in Solana Project

---

Cargo.lock
record/program/Cargo.toml

There have been some changes to the record program:
- https://github.com/solana-labs/solana-program-library/pull/6054
- https://github.com/solana-labs/solana-program-library/pull/6062
- https://github.com/solana-labs/solana-program-library/pull/6063
Bump to 0.2.0 for release

[spl-record] bump to 0.2.0

---

docs/src/single-pool.mdx
docs/src/theme/SearchBar/algolia.css
docs/src/token-2022/extensions.mdx
docs/src/token.mdx

Caught a few typos while reading the docs (one of them is in a comment in js file, put it together).
Have a nice week-end

chore(docs): proofreading the docs

---

record/program/src/lib.rs

Add a new address for the record program before publishing `0.2.0` and deploying the program.

[spl-record] add a new program address

---

token/transfer-hook/interface/README.md

Small correction to point to the correct file

Fix broken link in transfer-hook interface Readme.md

---

Cargo.lock
governance/CHANGELOG.md
governance/chat/program/Cargo.toml
governance/program/Cargo.toml

Bump `spl-governance` version to v4.0.0

Governance: bump spl-governance version to v4.0.0

---

token/js/src/instructions/initializeMint.ts
token/js/src/instructions/initializeMint2.ts
token/js/src/instructions/initializeMintCloseAuthority.ts
token/js/src/instructions/setAuthority.ts
token/js/test/e2e-2022/closeMint.test.ts
token/js/test/e2e/initialize.test.ts

fix: Use COptionPubkeyLayout for all COption fields

---

token/client/src/token.rs

with `spl-token` cli, when passing the same keypair as `--owner` and `--fee-payer` (and i suspect `--nonce-authority`), the transaction message will be signed multiple times. when the keypair is non-interactive, this behavior is unnoticeable. however if the keypair is interactive (ledger), each signing needs to be confirmed
deduplicate signings when constructing transactions.
---
ideally we'd only call `try_partial_sign()` once with a full, deduplicated signers list. unfortunately there are assumptions that fee-payer and nonce authority are held independently in multiple public interfaces and we are too generic at signing time to coalesce them.
---
easier to review with [whitespace ignored](https://github.com/solana-labs/solana-program-library/pull/6340/files?w=1)

token-client: avoid signing multiple times with the same keypair

---

token/program-2022/src/processor.rs

The Pod types all work great in token-2022, but revoke doesn't use them
Use Pod types in revoke in token-2022

token-2022: Update revoke to use Pod types

---

token/program-2022/src/pod.rs
token/program-2022/src/processor.rs
token/program-2022/tests/assert_instruction_count.rs

The Pod types exist in token-2022, but burn doesn't use them
Use Pod types in burn in token-2022

token-2022: Update burn to use Pod types

---

docs/src/token-2022/extensions.mdx
token/js/examples/metadata.ts

adding js examples for the metadata part of the token22 extension

Extensions doc metadata js example

---

token/program-2022/src/extension/default_account_state/processor.rs

As part of #6418, the default account state extension does not use Pod types.
Use them

token-2022: Update default_account_state to Pod types

---

token/program-2022/src/extension/confidential_transfer_fee/processor.rs

As part of #6418, the confidential transfer fee extension does not use Pod types.
Use them

token-2022: Update confidential_transfer_fee to Pod types

---

token/program-2022/src/extension/confidential_transfer/processor.rs

As part of #6418, the confidential transfer extension does not use Pod types.
Use them

token-2022: Update confidential transfers to Pod types

---

token/program-2022/src/extension/group_member_pointer/processor.rs

As part of #6418, the group member pointer extension does not use Pod types.
Use them

token-2022: Update group_member_pointer to Pod types

---

token/program-2022/src/extension/token_group/processor.rs

As part of #6418, the token group extension does not use Pod types.
Use them

token-2022: Update token_group to Pod types

---

token/program-2022/src/extension/token_metadata/processor.rs

As part of #6418, the token metadata extension does not use Pod types.
Use them

token-2022: Update token_metadata to use Pod types

---

token/program-2022/src/processor.rs

As part of #6418, the multisig instructions and validators do not use Pod types.
Use them.
This one had me slightly worried since it requires holding onto the mutable reference to the data, but I didn't find any potential double-borrow situations since we're only ever looking at the keys and signer status of other accounts.

token-2022: Update multisig usage to PodMultisig

---

token/cli/src/command.rs

The `set_interest_rate` test is failing because of time passing between simulation and execution and causing the call to use more compute units.
See https://github.com/solana-labs/solana-program-library/actions/runs/8468520195/job/23201746093?pr=6513 for a failing run
Do a little refactor, and force static compute unit limits during set_interest_rate (but still allow it to be overridden).

token-cli: Set a compute unit limit for set_interest_rate

---

token/program-2022/src/extension/transfer_fee/mod.rs

As mentioned in #6451, the pre fee amount calculation doesn't properly handle certain edge cases. If the fee is 100%, we return zero, which is flat-out wrong.
Return `maximum_fee + post_fee_amount` if fee is 100%. I changed this to use a match instead to make it easier to read, I hope it looks ok!
Fixes #6451

token-2022: Fix pre fee calculation edge cases

---

token/program-2022/src/extension/transfer_fee/mod.rs

According to the Certora audit report:
> Description: The function calculate_inverse_fee is not exactly an inverse operation of calculate_fee. That is, it is not the case that calculate_inverse_fee(x + calculate_fee(x)) == calculate_fee(x).
> Recommendation: Document that calculate_inverse_fee is not an exact inverse and instead that only the relationship calculate_fee(x) <= calculate_inverse_fee(x + calculate_fee(x)) holds in order to avoid confusion with the potential users of calculate_inverse_fee.
Do the recommended thing. I don't think the math in the comment is correct, so I've added a test to make sure the relationship is correct.

token-2022: [I-03] Clarify `calculate_inverse_fee` math

---

token/program-2022-test/tests/cpi_guard.rs
token/program-2022/src/processor.rs

Although #6724 fixed self-delegated transfers with CPI guard, it didn't fix all situations, including if the permanent delegate is the owner. And it also didn't cover burns. Per Certora's audit report:
> Description: Fund decreasing instructions (Transfer, TransferChecked, TransferCheckedWithFee, and Burn) when protected by CpiGuard should not be allowed if signed by the owner. The intention is that they are only allowed if signed by some other account delegate. This property is violated when
> * an account is delegated to itself
> * the account is a permanent delegate of the mint
> * the account is owned by system program or incinerator (in this case, signing authority is not checked and can be arbitrary) 
> Recommendation: Revert instruction when it is called in CPI, with enabled …

token-2022: [L-01] Check for all possible self-auth with CPI guard

---

Cargo.lock
memo/program/Cargo.toml
token/cli/Cargo.toml
token/client/Cargo.toml
token/program-2022-test/Cargo.toml
token/program-2022/Cargo.toml

Bump spl-memo for the next release

memo: Bump to 5.0.0 for Solana v2 support

---

docs/src/stake-pool.md

It's not clear that the devnet version of the stake pool program isn't usable.
Specify that it isn't usable.
Fixes #7208

docs: Update stake pool devnet info

---

account-compression/sdk/package.json
account-compression/sdk/src/instructions/index.ts

Adds helpers for batch init instructions added here: #6764

Account Compression v0.4.0 js release

---

docs/src/token-2022/presentation.md

What needs to change - 
Are you aware that it's 2023?
Reason - 
It's not 2023 anymore. 
Fix - 
Changed 2023 to 2024. 
PS. This was very fun to read. Good job!

Update a typo in presentation.md

---

account-compression/sdk/package.json

Keep JS versioning up to date with rust crate. Also force NPM cache to show new package version

Bump AC JS SDK version number

---

stake-pool/js/package.json

#7324 exposed some needed types, but it's not released yet.
Bump the patch version to release a new version.

stake-pool-js: Bump to release

---

Cargo.lock
libraries/concurrent-merkle-tree/Cargo.toml
libraries/merkle-tree-reference/Cargo.toml

Patching this to unblock MPLX development

Set patch version to only use solana-program <2

---

token/js/README.md

Mention the packages to use for web3.js version 2.

---

stake-pool/program/src/instruction.rs

chore: update instruction.rs

---

account-compression/sdk/README.md
docs/src/account-compression/usage.md
memo/js/README.md
token-group/js/README.md
token-lending/js/README.md
token-metadata/js/README.md
token/js/README.md

Read why, here: https://github.com/solana-labs/solana-web3.js/issues/3498

Lock to web3.js 1.x for compatibility

---

binary-option/client/binary_option.py
token-lending/program/src/state/reserve.rs
token/confidential-transfer/proof-extraction/src/burn.rs
token/confidential-transfer/proof-extraction/src/mint.rs

chore: fix some comments
